### ISSUE TITLE
Why the first step of Norne wells are under RESERVOIR_RATE controls?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1011]
The first record I can find from Norne schedule is 
```
 170 WCONHIST ^M
 171      'C-4H'      'OPEN'      'ORAT'      0.000      0.000      0.000  5* /^M
 172      'B-2H'      'OPEN'      'ORAT'      0.000      0.000      0.000  5* /^M
 173      'D-1H'      'OPEN'      'RESV'   4347.700      0.000 482594.703  5* /^M
 174 /
```

Output the available well controls in the simulator (both flow and flow_ebos)
```
106  well C-4H
107 RESERVOIR_RATE BHP 
108  well B-2H
109 RESERVOIR_RATE BHP 
110  well D-1H
111 RESERVOIR_RATE BHP 
```

The output code is the following. 
```
 195                 const int nw = wells().number_of_wells;
 196                 for (int w = 0; w < nw; ++w) {
 197                     std::cout << " well " << wells().name[w] << std::endl;
 198                     WellControls* wc = wells().ctrls[w];
 199                     const int nwc = well_controls_get_num(wc);
 200                     for (int c = 0; c < nwc; ++c) {
 201                         if (well_controls_iget_type(wc, c) == RESERVOIR_RATE) {
 202                             std::cout << "RESERVOIR_RATE ";
 203                         } else if (well_controls_iget_type(wc, c) == SURFACE_RATE) {
 204                             std::cout << "SURFACE_RATE ";
 205                         } else if (well_controls_iget_type(wc, c) == BHP) {
 206                             std::cout << "BHP ";
 207                         } else if (well_controls_iget_type(wc, c) == THP) {
 208                             std::cout << "THP ";
 209                         }
 210                     }
 211                     std::cout << std::endl;
 212                 }
```

**Comment by andlaus** [comment]
this might be caused by some schedule internalization issue in opm-parser. @joakim-hove, @jokva, @pgdr?

**Comment by totto82** [comment]
Check out # 608 in SimulatorBase_impl.hpp 

 ```
    well_controls_add_new(RESERVOIR_RATE, target,
                                                      invalid_alq, invalid_vfp,
                                                      & distr[0], ctrl);
```

For WCONHIST wells it seems like RESV is enforced. Maybe  @bska or @atgeirr can explain why?

**Comment by GitPaean** [comment]
This function is inside the if condition `if (! resv_wells.empty()) {`.  The first two wells should not enter this if condition in the first place?

**Comment by bska** [comment]
> For WCONHIST wells it seems like RESV is enforced.

You're right, that's a bug.

History matching wells **always** support `RESV` controls, so function [`is_resv(wmap, name, step)`](https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/SimulatorBase_impl.hpp#L378-L399) always returns `true` for history matching wells whence a history matching well will always be treated as a `WCONHIST/RESV` well in `SimulatorBase<>::computeRESV()`.  Would you mind testing if the following patch (compile-tested only) solves the problem?

```diff

@@ -590,7 +592,9 @@ namespace Opm
                         const WellProductionProperties& p =
                             wp->getProductionProperties(step);
 
-                        if (! p.predictionMode) {
+                        if ((! p.predictionMode) &&
+                            (p.controlMode == WellProducer::RESV))
+                        {
```

**Comment by GitPaean** [comment]
It partially fixed the problem that defines the first two wells as `RESEVOIR_RATE` control wells, however, the output becomes 
```
 well C-4H
SURFACE_RATE SURFACE_RATE SURFACE_RATE SURFACE_RATE RESERVOIR_RATE BHP 
 well B-2H
SURFACE_RATE SURFACE_RATE SURFACE_RATE SURFACE_RATE RESERVOIR_RATE BHP 
 well D-1H
RESERVOIR_RATE BHP
```

We need to provides more fixes from the opm-core and opm-parser side. 

And also, it is pretty interesting that it checks both the `well_controls` and `Well` from the EclipseState to decide whether a well is a resv_well.

**Comment by GitPaean** [comment]
More detailed looking at the related code shows possible cause behind the current way in handling the `WCONHIST` is that we need to find a way to transfer the historical phase rates from the parser to simulator. Since the implementation is relying on the `WellControls`, then the phase rates will enter the `WellControls` as limits (`WellControls` can only has limits to incorporate rate information at the moment).  As a result, one unified way to handle `WCONHIST` is to handle the `WCONHIST` well as `RESV` well.

**Comment by GitPaean** [comment]
The issue is understood well now. It was partially fixed through parser. More work will be done on both parser and simulators side. Closing the issue now.
