### ISSUE TITLE
Parallel output of flow_ebos broken

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1020]
It only outputs the grid and state of the master process.

The problem already starts when writing the initial state. The current code only has local views of the Geology available and uses a local grid. That local grid is also used to initialize the eclipse writer which prevents output from seeing the global state. Output might also need a global representation of the permeabilities for outputting the wells (but I might be wrong here).

Still thinking about the best way to fix this. Getting the global grid is easy, but computing/gathering TRAN{XYZ} will need some refactoring. Would be nice to know what direction #1019 goes.

Maybe moving the [transmissibility calculation for loadbalance](/OPM/ewoms/blob/deccd9937de6c00c9e4510d64185e2a03dded19c/ebos/eclcpgridmanager.hh#L147-L183) out of the grid manager and use that would be a good idea.

**Comment by blattms** [comment]
For those not so much into the code:

flow_legacy did set up a global grid, computed all global properties and material laws, wrote initial state, set up the output layer and then loadbalance and distributed the data.
flow_ebos seems to this differently, it setup a global grid and material law manager, then it computes the global transmissibilities to give them to the loadbalancer. Afterwards all the properties are set locally and the output layer is initialized. A non-advertised paradigm shift that seems to have produced some bugs in parallel.

**Comment by andlaus** [comment]
yes, ebos tries hard to avoid having to distribute any data outside of the linear solver. would it help to make the transmissibilities of the sequential grid available via the grid manager? (as you already have noticed, these are already calculated, so this is a pretty simple change.)

**Comment by blattms** [comment]
IMHO such data should never be stored in a grid manager. Please compute it outside. That is transparent. The current situation is opaque and and will force people to recode stuff several times.

**Comment by andlaus** [comment]
> IMHO such data should never be stored in a grid manager

I totally agree. that said, it should also never be used for load balancing ;)

**Comment by andlaus** [comment]
> The current situation is opaque and and will force people to recode stuff several times.

while I agree that the current situation is opaque, these values are only calculated in one place: https://github.com/OPM/ewoms/blob/master/ebos/ecltransmissibility.hh

calculating this once more for the equilGrid, would basically mean a bit of copy-and-pasted code (and a small performance penalty).

**Comment by blattms** [comment]
> I totally agree. that said, it should also never be used for load balancing ;)

I agree that [your values](https://github.com/OPM/ewoms/blob/deccd9937de6c00c9e4510d64185e2a03dded19c/ebos/eclcpgridmanager.hh#L147-L183) should *never* be used as they are the unprocessed eclipse values. What we used are those exported by Geology. These are computed [here](/OPM/opm-simulators/blob/af3049b5a64928310cc069685c93d404004e59f6/opm/autodiff/GeoProps.hpp#L122-L160). Note sure whether this is the same as in your ecltransmissibility.hh.

**Comment by atgeirr** [comment]
> I totally agree. that said, it should also never be used for load balancing ;)

I don't agree that the strength of a connection should never be used for load balancing, but perhaps I misunderstood you?

**Comment by andlaus** [comment]
> Not sure whether this is the same as in your ecltransmissibility.hh.

for the decks I've tested so far at least the first 8 decimal digits should be identical. not sure if that applies for all corner cases, though...

> I don't agree that the strength of a connection should never be used for load balancing, but perhaps I misunderstood you?

I guess you understood this correctly: `flow_legacy` and `flow_ebos` both use them as edge weights for load balancing. While this makes sense from a mathematical perspective, it constitutes a layering violation IMO :/

**Comment by atgeirr** [comment]
If sensible mathematics leads to bad code, it is the code design that is at fault, not the mathematics :-)

**Comment by andlaus** [comment]
yeah, that's what the mathematicians say ;)

As I see it, the problem is that the grid is seen as a layer below the "PDE solver/model". While this makes a lot of sense IMO, using transmissibilities as edge weights breaks that design.

**Comment by andlaus** [comment]
ok, I've figured that there already *is* a zoltan package in ubuntu (that makes me wonder why the zoltan people hide the download behind a registration form): `libtrilinos-zoltan-dev`. any idea what's the difference to the `libtrilinos-zoltan2-dev` package?

**Comment by notspiff** [comment]
There is no such package i  ubuntu rather it is provided in opm ppa. Zoltan2 is a complete reboot (c++ this time).

**Comment by andlaus** [comment]
> There is no such package i ubuntu rather it is provided in opm ppa. Zoltan2 is a complete reboot (c++ this time).

ah, okay. sorry that I deleted my comment, I moved it to OPM/ewoms#136 (where I intended it to be in the first place)

**Comment by blattms** [comment]
Solved with the merge of #1041

**Comment by akva2** [comment]
does that mean flow_ebos now runs and solves in parallel for you ? reason i ask is that it (still) fails utterly for me, though the crash is gone. it now suffer convergence errors starting from the very first solve. this was done by enabling some of the parallel regression tests for flow_ebos (compareECLFiles.cmake).

**Comment by blattms** [comment]
No. There are still lots of problems and they seem to have multiplied whenever I look into ewoms.
