### ISSUE TITLE
Segfault on parallel run

### ISSUE THREAD

**Issue by hnil** [OPM/opm-simulators#1030]
flow_mpi made segfault on parallel runs with more then 1 processor on a twophase case.
This happend while experimenting with OPM for a proposed benchmark case.

**Comment by blattms** [comment]
We are aware of the problem. Unfortunately, the master of OPM is
currently shifting to an ewoms based flow simulator and the parallel
implementation is lacking behind and we might not even have a working
one. Benchmarking the current master is comparing apples with oranges
as flow will use ewoms, but flow_mpi will use the old implementation.

My advise would be to asses the parallel implementation of the last
release. Hopefully we will be able to carry the increased speed of
flow_ebos compared to flow_legacy (was that 20%?) over to the new
parallel implementation.

**Comment by andlaus** [comment]
> Unfortunately, the master of OPM is currently shifting to an ewoms based flow simulator 

this doesn't/shouldn't affect `flow_legacy` and `flow_mpi` though?

@hnil: if you're using the master version, you can also try if the `flow_ebos` binary works for your case. Often, it tends to be significantly faster...

> (was that 20%)

for the Norne case, the speedup is more than 50% (if you like the inverse better: it only takes two thirds of the time) in sequential runs. the performance of other cases ("Model 2") was consistent with this.

**Comment by blattms** [comment]
> > Unfortunately, the master of OPM is currently shifting to an ewoms based flow simulator 
> 
> this doesn't/shouldn't affect `flow_legacy` and `flow_mpi` though?
>

It does as we do not invest resources to fix bugs introduced to
flow_mpi but concentrate on getting flow_ebos working in parallel.
We have bugs hanging around since at least midth of December.

> @hnil: if you're using the master version, you can also try if the `flow_ebos` binary works for your case. Often, it tends to be significantly faster...
>

Are you sure that flow_ebos works in parallel already? @hnil was trying to run
in parallel, was he not?

The last time I checked master flow_ebos was the default for sequential
runs. Hence he is using that for his sequential run and therfore my
statement about apples (flow -> flow_ebos) and oranges ( flow_mpi ->
flow_legacy).

**Comment by andlaus** [comment]
> Are you sure that flow_ebos works in parallel already? @hnil was trying to run
in parallel, was he not?

I'm sure it is not working in parallel. I just wanted to say that possibly `flow_ebos` in sequential mode is fast enough. (in my own experience for the Norne deck it was about as fast in sequential mode as `flow_mpi` with six processes. That's without ZOLTAN, though...)

> The last time I checked master flow_ebos was the default for sequential runs.

really? I'm not aware that we've changed this (not that I would mind). Also:

```
and@heuristix:~/src/opm-simulators|master > ls -l bin/flow
lrwxrwxrwx 1 and users 11 Jan 17 17:07 bin/flow -> flow_legacy
```

**Comment by blattms** [comment]
Then I have to apologize. Somehow I thought that this switch already happened. I am a bit paranoid these days.

So to sum this without further ranting for @hnil:
If you interested in how flow behaves in parallel then please use the lates [release](http://opm-project.org/?p=758).
If you want to know what is possible in the future you can use the git master version of flow_ebos (but not parallel).

**Comment by hnil** [comment]
For the case which will be the TNO benchmark .. ebos is the slower than flow her is results
flow_ebos... Not that twophase problem (This is from master 12. january... )
/timing/total_time=1233.97
/timing/pressure/total_time=0
/timing/transport/total_time=0
/timing/newton/iterations=195
/timing/linear/iterations=9495
--------------------
flow
/timing/total_time=746.566
/timing/pressure/total_time=0
/timing/transport/total_time=0
/timing/newton/iterations=200
/timing/linear/iterations=10065

**Comment by andlaus** [comment]
this contradicts my current experience; even for water-oil cases it should not be slower in sequential runs. (note that your results indicate that `flow_ebos` uses slightly fewer non-linear and linear iterations.) are you sure that you used the same compiler and the same flags to compile both simulators? Also, can you somehow make the deck available to me so that I can investigate this issue?

**Comment by hnil** [comment]
I am quite confident that this is the case, since I compile evrything from scratch..
I confirmed it by running on norne where the result is oposite like you indicate.
I will can of coarse rerun with better compile options....

**Comment by andlaus** [comment]
I think @totto82 once indicated that the `flow_ebos` performance was significantly better for a twophase case which he tested. maybe it regressed since then.

**Comment by GitPaean** [comment]
Without digging in for further information, for this specific example, it looks like `flow_ebos` is slower. 

The following is the iteration output (provided by @hnil ) for one time step. 

output for flow_ebos
```
---------------    Simulation step number 13    ---------------
      Current time (days)     4749
      Current stepsize (days) 365
      Total time (days)       7305



Time step   13 at day 4749/7305, date = 01-Jan-2029, size = 365 days
  Substep 0, stepsize 365 days.
Iter  W-FLUX(water)  W-FLUX(oil)
   0  8.939e-06  6.852e-05
Iter    MB(W)      MB(O)      CNV(W)     CNV(O)   W-FLUX(W)  W-FLUX(O)
   0  1.943e-03  1.929e-03  3.084e-01  3.085e-01  8.939e-06  6.852e-05
   1  3.003e-05  3.568e-05  1.009e+01  7.699e-01  4.718e-05  1.949e-05
   2  1.430e-05  9.353e-07  8.458e+00  3.288e+00  5.503e-06  2.636e-06
   3  3.844e-06  1.040e-05  3.891e+00  2.881e+00  1.992e-07  2.833e-07
   4  2.284e-06  4.651e-07  2.311e-01  3.486e-01  3.685e-08  4.179e-08
   5  1.165e-06  5.820e-08  7.817e-02  1.083e-01  1.219e-09  1.668e-10
   6  6.541e-07  1.123e-09  6.961e-03  7.381e-03  2.680e-12  8.630e-13
Overall linear iterations used: 235
    Substep summary: newton iterations = 6, linearizations = 7 (4.92509 sec), linear iterations = 235 (16.7937 sec)
```

output from flow
```
---------------    Simulation step number 13    ---------------
      Current time (days)     4749
      Current stepsize (days) 365
      Total time (days)       7305



Time step   13 at day 4749/7305, date = 01-Jan-2029
  Substep 0, stepsize 365 days.
Iter  W-FLUX(W)  W-FLUX(O)  WELL-CONT
   0  7.192e-06  5.728e-05  0.000e+00
well converged iter: 0
Iter   MB(Wat)    MB(Oil)     CNV(W)     CNV(O)   W-FLUX(W)  W-FLUX(O)  WELL-CONT
   0  1.949e-03  1.932e-03  2.839e-01  2.839e-01  9.088e-06  8.154e-05  0.000e+00
   1  3.321e-05  3.139e-05  5.391e+00  7.846e-01  3.222e-05  2.403e-05  0.000e+00
   2  1.244e-05  2.858e-06  3.610e+00  3.787e+00  6.385e-07  1.307e-06  0.000e+00
   3  4.054e-06  4.844e-06  3.984e+00  3.108e+00  3.668e-08  3.958e-08  0.000e+00
   4  3.100e-07  5.908e-07  1.777e-01  3.848e-01  1.238e-09  6.232e-10  0.000e+00
   5  1.796e-06  1.280e-07  5.329e-01  1.224e-01  7.966e-10  9.119e-11  0.000e+00
   6  1.816e-06  1.093e-07  9.064e-02  2.494e-02  4.526e-13  1.059e-12  0.000e+00
   7  4.195e-07  7.086e-09  6.614e-03  9.730e-03  8.783e-12  1.315e-11  0.000e+00
Overall linear iterations used: 239
    Substep summary: newton iterations = 7, linearizations = 8 (5.6298 sec), linear iterations = 239 (10.1996 sec)
```

I just have been working with flow_ebos from very recently. Not having much idea about what is going on here yet. 

I suggest we make a few more smaller tests (in the size of SPE9) to check this.

**Comment by GitPaean** [comment]
From the above output, it looks like the linearization takes similar time for this two phase case, while the linear solution takes obviously longer time for flow_ebos.

**Comment by totto82** [comment]
I have the same experience as @hnil.  For the Brugge case flow_ebos is slower than flow, but not much. 
The reason is that flow_ebos uses as pseudo phase in 2p simulations. 
For a linear solver time dominated case like Brugge, the speed up in the assembly does not compensate the overhead of solving a 3p problem (2p + a pseudo phase) in the linear solver. If you try to use amg instead of the default linear solver it may speed up your case. 
I have implemented a prototype in flow_ebos that removes the pseudo phase before passing it to the linear solver. It involves some extra copying that slowed down the real 3p calculations so I never submitted it. Maybe the code needs to be revived.

Maybe using amg instead of the default linear solver speeds up your case.

**Comment by blattms** [comment]
Maybe using AMG with flow_legacy improves the runtime, too and evens out the improvement you have seen?

**Comment by GitPaean** [comment]
> The reason is that flow_ebos uses as pseudo phase in 2p simulations.

I think this does not apply anymore. We should close this issue?
