### ISSUE TITLE
About block matrix system in Dune

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1048]
My question is about block matrix in Dune. 

Does Dune support a block matrix with different block size? Like some blocks are of size 3X3 and some blocks are of sizes of 4X4, 4X3 and 3X4. 

If not, I guess one option is to maintain the matrix to be a vector of sub-matrices, and we apply each sub-matrices one by one when eliminating the well related Jacobian from the mass balance equations.  Will there be some penalty in term of performance?  

Any comments or suggestions will be appreciated.

**Comment by GitPaean** [comment]
If I read correctly, it looks like the elimination of the well related Jacobian happens already based on perforation calculation already. The variable size block matrix representation is only needed for the well related operations.  Will come back to this question later.

**Comment by andlaus** [comment]
I do not know if there is are classes in dune that support multiple block sizes. a simple fix would be to use the same block size as the reservoir equations for the well equations and add "dummy" lines for the "superfluous" equations. performance-wise the impact is probably negligible.

**Comment by blattms** [comment]
> Does Dune support a block matrix with different block size? Like some blocks are of size 3X3 and some blocks are of sizes of 4X4, 4X3 and 3X4. 
>

Kind of. You can use
[MultiTypeBlockMatrix](https://www.dune-project.org/doxygen/2.5.0/classDune_1_1MultiTypeBlockMatrix.html#details)
and
[MultiTypeBlockVector](https://www.dune-project.org/doxygen/2.5.0/classDune_1_1\
MultiTypeBlockVector.html#details) as long as the sizes are known at
compile time. Then you basically have a dense Matrix of Sparse
Matrices.

From the top my head in your case
```
#include <dune/common/fmatrix.hh>
#include <dune/common/indices.hh>
#include <dune/istl/multitypeblockvector.hh>
#include <dune/istl/multitypeblockmatrix.hh>
#include <dune/istl/bcrsmatri.hh>
MultiTypeBlockMatrix<MultiTypeBlockVector<BCRSMatrix<FieldMatrix<double,3,3>>,
                                          BCRSMatrix<FieldMatrix<double,3,4>>,
                     MultiTypeBlockVector<BCRSMatrix<FieldMatrix<double,3,4>>,
	                                  BCRSMatrix<FieldMatrix<double,4,4>>>
    A;
    using namespace Dune::Indices;
    auto& 3by3block = A[_0][_0]
``

Might be handy to use if CPR is requested to prevent copying, too.

**Comment by GitPaean** [comment]
Thanks for the comments. It is good to know there is some support / solution. Will come back to this issue when I need to handle it soon later.

**Comment by andlaus** [comment]
@GitPaean: Should this issue be closed. IMO probably yes because we should probably come back to it when (if?) somebody works on that?

**Comment by GitPaean** [comment]
@andlaus , sorry I did not see your message.
