### ISSUE TITLE
use_TUNING=true not handled in flow_ebos

### ISSUE THREAD

**Issue by hnil** [OPM/opm-simulators#1050]
It seems like flow_ebos do not handle the use_TUNING variable?

**Comment by andlaus** [comment]
that's weird: https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/SimulatorFullyImplicitBlackoilEbos.hpp#L167

maybe it gets ignored anyway...

**Comment by atgeirr** [comment]
It seems to have been added a little less than a month ago, your version must be older than that. Seems to work, after some simple testing. Closing the issue.
