### ISSUE TITLE
FOPT do not use ministeps?

### ISSUE THREAD

**Issue by hnil** [OPM/opm-simulators#1051]
It seems like FOPT (or other totals) do not use the ministeps rates to calculate the totals. Thus it will seem lik OPM has large errors in FOPT, even if the outputs of the rates are accurate.

**Comment by joakim-hove** [comment]
We will look into this, there have been recent changes in mimistep handling
- so you might have identified a bug.

9. feb. 2017 12:57 skrev "hnil" <notifications@github.com>:

**Comment by joakim-hove** [comment]
Details please - maybe you could share a gist with a plot?

**Comment by joakim-hove** [comment]
Hello; would be good with some details here - i.e. a plot of `FOPT` and `FOPR`. And also - does this apply to *both* `flow`and `flow_ebos`- or only one of them?

**Comment by hnil** [comment]
Sorry, New compilation seems to have fixed this for flow. 
flow_ebos  not run anymore for my case since it is to strikt on the definition of dimensions...
NUMRES to infer the number of records in: COORDSYS
