### ISSUE TITLE
Keyword FPR, BPR

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-simulators#1054]
Hello.  I am trying to add the FPR,BPR keywords on the summary file and I get back some numbers between 0 and a bit more than 1.  Is that the same keyword as in Eclipse?  Should that be the Field Pressure and Block pressure at a given position?
Is that a percentage relative to the initial pressure on the EQUIL keyword?

Thanks..

**Comment by joakim-hove** [comment]
> I am trying to add the FPR,BPR keywords on the summary file and I get back some numbers between 0 and a bit more than 1. Is that the same keyword as in Eclipse? Should that be the Field Pressure and Block pressure at a given position?

Hmmm - that does not sound quite right! `FPR` should be the average field pressure, and `BPR` should be the pressure in a cell:
```txt
BPR
   1 2 3 /
   1 2 7 /
/
```
to get the block pressure in cells `(1,2,3)` and `(1,2,7)`. The pressure should be the absolute pressure - reported in the same units as in your input deck, so values in the range `O(1)` this sure sounds like bug somewhere. If you can post the deck - that would be good.

**Comment by dlmorenob** [comment]
Hi Joakim,

I installed the latest version and it is working fine now.  A comparison from the January version to yesterday's.

![screenshot from 2017-02-14 07-52-31](https://cloud.githubusercontent.com/assets/9252709/22929645/b6a484ce-f28a-11e6-9c33-a644be2e3f4f.png)
![screenshot from 2017-02-14 07-52-09](https://cloud.githubusercontent.com/assets/9252709/22929644/b6a2a3c0-f28a-11e6-93dc-d5ffd6d0662d.png)

Thanks.

**Comment by joakim-hove** [comment]
> I installed the latest version and it is working fine now.

:+1:
