### ISSUE TITLE
Phase densities not reported initially

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1058]
GAS_DEN, WAT_DEN and OIL_DEN not reported initially, but for subsequent report steps.

**Comment by andlaus** [comment]
is this for flow_ebos, flow_legacy or both?

**Comment by alfbr** [comment]
Possibly both, but testing is on flow_ebos

**Comment by andlaus** [comment]
okay. which deck did you use and where is this supposed to get written to? I could not find the string `GAS_DEN` in the ECL reference PRT file for Norne...

**Comment by alfbr** [comment]
It is written to the restart file.

**Comment by babrodtk** [comment]
Just created a PR that tries to address this: #1068 

The issue is that derived quantities are not dumped at all for the first report step, since they were not initialized until after the simulation had started in flow_legacy.

**Comment by andlaus** [comment]
#1068 has been merged and the FIP is reported before the initial time step for the first time. closing.
