### ISSUE TITLE
Any participants attending SPE Reservoir Simulation Conference in Montgomery, TX???

### ISSUE THREAD

**Issue by grizzlypapa** [OPM/opm-simulators#1065]
Would you like to meet for a beer?

**Comment by GitPaean** [comment]
Hi, we have a few people attending RSC now, like Knut Andreas Lie, Bård Skaflestad, Halvor Møll Nilsen, Olav Møyner.  Maybe you can try to find them there. Or you can leave your contact here, they can try to reach you.

**Comment by blattms** [comment]
I am there, too.ye
-- 
Diese Nachricht wurde von meinem Android-Mobiltelefonj. Kmg mit K-9 Mail gesendet.

**Comment by blattms** [comment]
In case you have not had a chance  for chat/beer. Let us meet tonight at 7 pm at the Hotel bar.

**Comment by grizzlypapa** [comment]
Finally checking back here. Have the OPM recently presented at the SPE RSC? I'll double check OnePetro, but I don't seem to be able to recall a presentation.

**Comment by GitPaean** [comment]
As what I know, there is no presentation about OPM in RSC.
