### ISSUE TITLE
Unconventional well visualization when using flow_ebos

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1067]
Some model2 realizations(realizations 6 - 11) simulated using flow_ebos shows an unconventional visualization of a well. The well in question, when visualized, is portrayed with an end point outside the grid and connected to what looks like an inactive grid block. The same model when simulated with E100 doesn't show this unconventional visualization. The pictures, datasets are available with @alfbr

**Comment by andlaus** [comment]
is this still relevant?

**Comment by nairr** [comment]
Just tested, the issue still remains

**Comment by blattms** [comment]
Closing as there is no flow_ebos anymore
