### ISSUE TITLE
OPMEXTRA

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-simulators#1089]
Recently a new keyword, OPMEXTRA, was introduced in opm-simulators restart output. As a result all previously produced restart files become useless, although the data associated with OPMEXTRA seems minor. Is is ok to ignore this keyword by disabling it? Otherwise a series of restart files for Model 2.2 would have to be recreated using 1 day simulations time each. 

It seems that for these kind of changes it would be nice to track some sort of a version number in the 
restart/output files.

**Comment by joakim-hove** [comment]
Comments / possibilities. These questions are mainly philosophical / political and not really technical:

1. If we just say f... it - we have given up on Eclipse compatibility anyways, we could easily add an integer field with a version number to the restart files. In my opinion the restart capabilities are still a bit much in flux for this - but it is certainly possible.

2. What should be semantics of the IO layer when a certain key is requested, but not found, as in the case you describe here. Currently the IO layer will throw in this case; the advantage is of course that the complexity is reduced - and we are guaranteed that the return value will be valid for the simulator. Personally I think this is the Right Way&trade; - but others might disagree. We could even send a per-key flag value to the `RestartIO::load( )` function - indicating whether a certain vector was optional or required.

3. I assume the content of the `OPMEXTRA` vector is essential to actually perform the restart (@atgeirr)?  - but if not I could easily help you hack up a script injecting bogus `OPMEXTRA` data into an existing restart file.

**Comment by atgeirr** [comment]
> Is is ok to ignore this keyword by disabling it?

I think a patch that made it optional in the sense that "if trying to read it and it is not found, ignore it" is fine for backwards compatibility with old restart files. As @joakim-hove points out, this requires a patch in opm-output to avoid always throwing, or that we create a query facility ("dear EclipseIO, do you have this field at that timestep").

About a version number, sure! Let's store it in the OPMEXTRA field. Although that might not help you right now.

The OPMEXTRA currently just contains the suggested next timestep (without it we typically do not start with the same timestep size).

I do think that the OPMEXTRA addition is a valuable one, and more improvements are coming. Expect eventually that you'll want to rerun old cases to take advantage of better restarts.

**Comment by joakim-hove** [comment]
> As @joakim-hove points out, this requires a patch in opm-output to avoid always throwing, 

OK - then my suggestion is that the `std::set<std::string> extra_keys` argument to the `RestartIO::load()` function is replaced with `std::map<std::string,bool> extra_keys` - where the `bool` value in the map is `true` for required keys - and `false`for optional keys, or something like that?

> or that we create a query facility ("dear EclipseIO, do you have this field at that timestep").

That is certainly also possible, but that would require a separate open and read of the restart file.

**Comment by atgeirr** [comment]
> OK - then my suggestion is that the std::set<std::string> extra_keys argument to the RestartIO::load() function is replaced with std::map<std::string,bool> extra_keys - where the bool value in the map is true for required keys - and falsefor optional keys, or something like that?

I like that.

> That is certainly also possible, but that would require a separate open and read of the restart file.

Then let's not.

**Comment by dr-robertk** [comment]
Sounds good. So it was actually ok to ignore it. In that case a warning is probably good enough until after the next release.

**Comment by joakim-hove** [comment]
> I like that.

Good - then I will implement that; but then of course it will be the responsability of calling scope to handle absent optional vectors correctly.

**Comment by atgeirr** [comment]
Actually I have another (closely related) opm-output wish: that we can have optional cell data, not just `extra_keys`. As soon as we start writing/reading hysteresis data etc. we'll be in the same situation again w.r.t. backwards compatibility. (Also, for cases without hysteresis it won't make sense, so we should not require to read it, but this particular bit can be handled on the simulator side.)

**Comment by joakim-hove** [comment]
> Actually I have another (closely related) opm-output wish: that we can have optional cell data, not just extra_keys. As soon as we start writing/reading hysteresis data etc. we'll be in the same situation again w.r.t. backwards compatibility.

We can certainly implement support for optional cell data; but will the cell data like e.g. hysteresis data be truly optional? I assume that when the simulator asks for hysteresis data to be provided from the restart file the simulator "*really means it* - and is not prepared to proceed without that data?

> Also, for cases without hysteresis it won't make sense

Well - for cases without hysteresis the simulator *should not ask* for hysteresis data?!

So - we can certainly implement support for optional cell data, but the scenario described thus far seems to me to be something the simulator should have 100% control over, without resorting to optional fields in the restart file. 

> we'll be in the same situation again w.r.t. backwards compatibility

This is overall work in progress - and backwards compatibility w.r.t. to old files is in my opinion not sufficient reason in itself to weaken the semantics of the simulator - ouptut interaction, at least not yet.

**Comment by andlaus** [comment]
>>  we'll be in the same situation again w.r.t. backwards compatibility
>
> This is overall work in progress - and backwards compatibility w.r.t. to old files is in my opinion not sufficient reason in itself to weaken the semantics of the simulator - output interaction, at least not yet.

do I interpret this correctly if I read "old files" as "files produced by E100"?

**Comment by joakim-hove** [comment]
> do I interpret this correctly if I read "old files" as "files produced by E100"?

No no -  more like produced by `flow_xxx` last week.

**Comment by andlaus** [comment]
right. *that* we should really not care about much, IMO. being able to write files which can be used by E100 and being able to restart from files made by E100 may come with the same issues, though?

**Comment by joakim-hove** [comment]
> being able to write files which can be used by E100 and being able to restart from files made by E100 may come with the same issues, though?

That is probably a quite significant task - don't know.

**Comment by andlaus** [comment]
sounds like it should be filed under the "future work" section ;)

**Comment by atgeirr** [comment]
About the hysteresis data: we do without now... (i.e. when restarting we do so with incorrect saturation history).

I did have the thought that optional data would help us (initially) in possibly restarting from ECL-produced restarts, although that is still far off. Current work focuses *only* on making flow_ebos restart properly.

**Comment by joakim-hove** [comment]
> About the hysteresis data: we do without now...

OK - good; then they are optional.

**Comment by andlaus** [comment]
we have fixed that issue, closing. please re-open if my memory failed me.
