### ISSUE TITLE
BlackoilModelEbos::updateState does not work for parallel grids.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1110]
In [BlackoilModelEbos.hpp#L671](/OPM/opm-simulators/blob/0b0ef7e20fb0d2e406a2a6bae74d80b3b017bcec/opm/autodiff/BlackoilModelEbos.hpp#L671) it calls cachedIntensiveQuantities for all elements, which is a bug. 

It seems like one cannot simply switch off non-interior cells because the code computes rs and rv which I assume must be needed even for non-interior cells by the ebos linearizer.

**Comment by blattms** [comment]
Connected to OPM/ewoms#163.

**Comment by dr-robertk** [comment]
I have checked this suggestions and made a small PR that moves the grid loop in getConvergence to be the outer loop. The PR is https://github.com/dr-robertk/opm-simulators/tree/PR/cleanup-ebos-fix 
With that the iterations counts are the same and so is the run time. Here the numbers: 

Current master:
================    End of simulation     ===============

Total time taken (seconds):   748.686
Solver time (seconds):        731.204
 Assembly time (seconds):     290.59
 Linear solve time (seconds): 367.822
 Update time (seconds):       15.6517
 Output write time (seconds): 17.4153
Overall Well Iterations:      835
Overall Linearizations:       1975
Overall Newton Iterations:    1633
Overall Linear Iterations:    24568

With Markus fix (including my suggestion):

================    End of simulation     ===============

Total time taken (seconds):   747.726
Solver time (seconds):        730.286
 Assembly time (seconds):     291.859
 Linear solve time (seconds): 363.127
 Update time (seconds):       18.8739
 Output write time (seconds): 17.1488
Overall Well Iterations:      835
Overall Linearizations:       1975
Overall Newton Iterations:    1633
Overall Linear Iterations:    24568

**Comment by blattms** [comment]
Great!

I like your version more.

**Comment by dr-robertk** [comment]
Actually, the generation of the vectors can be avoided since we only need the sum. I haven't gotten around to implement that but there is some improvements possible. Once you setup a PR I can make a PR into your branch.

**Comment by blattms** [comment]
I cherry-picked your commit into PR #1111.

**Comment by blattms** [comment]
My next step would is to unify BlackoiModelEbos::getConvergence and deail::getConvergence. Maybe that would be the better place to fix this? Then I could just ramble on. I could make the vectors go away, too, if you have more pressing things to do.

**Comment by dr-robertk** [comment]
@blattms Go ahead. I guess the first step is to make it work. Then we can optimize it.

**Comment by blattms** [comment]
Forget my last comment, my memory failed me. I just looked at the convergence stuff in StandardWellsDense again. The only things used is detail::getConvergence and that seems a bit of overkill for computing the average of B to me.

But aggree with postponing optimization and merging #1111
