### ISSUE TITLE
flow_ebos emits warning during startup on all processes.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1115]
I mean messages like:
```
Warning: The specified amount gas (R_s = 226.197) is more than the maximium
         amount which can be dissolved in oil (R_s,max=137.306) for cell (1, 1, 2). Using maximimum.
```
I assume these come from reading the eclipse file. Someone familiar with the ebos code should tell the reader to shut up on processes with rank>0.

**Comment by atgeirr** [comment]
For ease of reproducing: which case is this?

**Comment by blattms** [comment]
Any case. I used SPE1 or Equilibrium. But I am unsure whether the current master even gets that far in a parallel run. One might need all of my open PRs merged.

**Comment by atgeirr** [comment]
OK, I'll attack this after the others are merged, then! (Please remind me if I forget.)

**Comment by blattms** [comment]
*ping*

**Comment by andlaus** [comment]
BTW: some log messages seem to be swallowed (or not accounted) for parallel runs. A sequential Norne run says:

```
Error summary:
Warnings          27767
Info              1115
Errors            0
Bugs              0
Debug             0
Problems          16
```

while a parallel run with 6 processes yields:

```
Error summary:
Warnings          6631
Info              1105
Errors            0
Bugs              0
Debug             0
Problems          8
```

**Comment by blattms** [comment]
No flow_ebos anymore
