### ISSUE TITLE
Shutting down a well with WECON

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1142]
When using the the WECON keyword as follows:
```
WECON
      Well1 1* 1* 0.9000 1* 1* WELL / 
/
```
Flow shuts down the worst-offending connections, instead of the whole well (as specified in item - 7 of WECON), when the water cut limit of 0.9 is surpassed.

**Comment by GitPaean** [comment]
Sorry I did not notice this issue earlier, maybe was too busy to make a response.  Any way, please help to test if PR #1297 fixes the issue.

**Comment by atgeirr** [comment]
Reopened until we can confirm that the modified code indeed fixes @nairr's issue.

**Comment by nairr** [comment]
I just tried testing this with the current master, but now I am unable to run the Model (Brugge). 
Reason - 
> Error: [..../BlackoilModelEbos.hpp:394] Well Equation did not converge

@GitPaean - If you want I can send you the model by mail

**Comment by atgeirr** [comment]
> I am unable to run the Model (Brugge).

That's a bummer! I assume you are on a recent version of Flow?

**Comment by nairr** [comment]
Yes, the compiled it just an hour ago

**Comment by GitPaean** [comment]
That might not be related to this PR?

**Comment by GitPaean** [comment]
@nairr , could you please run without `WECON` keyword to see if it breaks at the same place for the same reason?

**Comment by nairr** [comment]
Yes, it crashes (still at timestep 0 and for the same reason) even without the WECON keyword. Clearly not related to this issue, will raise a different issue

**Comment by GitPaean** [comment]
` 
392             catch ( const Dune::FMatrixError& e  )
393             {
394                 OPM_THROW(Opm::NumericalProblem,"Well equation did not converge");
395             }
`
Basically, it means there is a singular matrix and it failed in getting inverted. (Can be other reason, while this one is the one I have been seeing often recently.)  And I changed this message to be more informative in the new PR.

**Comment by GitPaean** [comment]
I think this issue is not related anymore. Feel free to reopen it if disagreed.
