### ISSUE TITLE
Parallel flow_ebos results comparison fails for SPE3CASE1

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1154]
Inspired by the discussion in #1150 I did some further testing. I modified flow_ebos such that it always sets up the full linear system and solves it directly on a master process. Even in this setup I see deviations:
```
=== Executing comparison for summary file ===
Comparing '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/SPE3CASE1' to '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/mpi/SPE3CASE1'.
Comparing 2513 steps.
For keyword FOPR
(days, reference value) and (days, check value) = (3674.38, 275.664) and (3675.45, 275.537)
The absolute deviation is 0.127106. The tolerance limit is 0.02
The relative deviation is 0.000461089. The tolerance limit is 1e-05
Program threw an exception: [/home/mblatt/src/dune/opm/opm-output/opm/test_util/summaryRegressionTest.cpp:117] Deviation exceed the limit.
6 summary keyword(s) exhibit failures
	 FOPR
	 	 Fails for: 909 / 2513 steps.
		 Largest absolute error: 1.509250e+02
		 Largest relative error: 1.000000e+00
	 WBHP:INJ
	 	 Fails for: 938 / 2513 steps.
		 Largest absolute error: 9.140580e+02
		 Largest relative error: 1.000000e+00
	 WBHP:PROD
	 	 Fails for: 925 / 2513 steps.
		 Largest absolute error: 8.580970e+02
		 Largest relative error: 1.000000e+00
	 WGPR:PROD
	 	 Fails for: 9 / 2513 steps.
		 Largest absolute error: 6.200000e+03
		 Largest relative error: 1.000000e+00
	 WOPR:PROD
	 	 Fails for: 909 / 2513 steps.
		 Largest absolute error: 1.509250e+02
		 Largest relative error: 1.000000e+00
	 WWPR:PROD
	 	 Fails for: 531 / 2513 steps.
		 Largest absolute error: 3.506450e+01
		 Largest relative error: 1.000000e+00
=== Executing comparison for restart file ===
Comparing '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/SPE3CASE1' to '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/mpi/SPE3CASE1'.
Comparing SEQNUM...done.
Comparing INTEHEAD...done.
Comparing LOGIHEAD...done.
Comparing DOUBHEAD...done.
Deviation results for keyword DOUBHEAD of type DOUB:
Average absolute deviation = 0
Median absolute deviation  = 0
Average relative deviation = 0
Median relative deviation  = 0

Comparing IWEL...done.
Comparing ZWEL...done.
Comparing OPM_XWEL...
Occurrence in first file    = 13
Occurrence in second file   = 13
Grid coordinate             = (7, 2, 1)
(first value, second value) = (8.10951e+06, 8.10926e+06)

Program threw an exception: [/home/mblatt/src/dune/opm/opm-output/opm/test_util/EclFilesComparator.cpp:370] Deviations exceed tolerances.
The absolute deviation is 252.321, and the tolerance limit is 0.02.
The relative deviation is 3.11142e-05, and the tolerance limit is 1e-05.
Comparing '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/SPE3CASE1' to '/home/mblatt/src/dune/opm/opm-simulator/opm-parallel/tests/results/parallel/flow_ebos+spe3/mpi/SPE3CASE1'.

Common keywords for the two cases:
SEQNUM
INTEHEAD
LOGIHEAD
DOUBHEAD
IWEL
ZWEL
OPM_XWEL
OPM_IWEL
ICON
STARTSOL
PRESSURE
RS
RV
SGAS
SWAT
TEMP
ENDSOL
KRNSW_GO
KRNSW_OW
PCSWM_GO
PCSWM_OW
SOMAX
OPMEXTRA

Uncommon keywords for the two cases:

Failure for keyword OPM_XWEL
	 Fails for 1 entries
	 Largest absolute deviation: 2.523210e+02
	 Largest relative deviation: 3.111420e-05
Failure for keyword OPMEXTRA
	 Fails for 1 entries
	 Largest absolute deviation: 1.593150e+04
	 Largest relative deviation: 3.470600e-02
```

**Comment by blattms** [comment]
The weired thing is:
The difference in WBHP:PROD (Largest absolute error: 8.580970e+02) seems so large that I would assume to see it in the plotted well curves. But the curves really seem to be identical to my eyes.

**Comment by andlaus** [comment]
at an absolute pressure of 300 bar, an absolute deviation of 850 Pa is a relative one of about 2.5e-5 which may explain why you don't see a difference at manual examination. also, there something else must also be  wrong as the reference solution is for t=3674.38 days while the computed result is for about a day later, i.e., t=3675.45, if I interpret your results correctly.

**Comment by blattms** [comment]
Well, I guess we solved the mistery. For SPE3 the adaptive time stepping is completely different for the parallel run. As we output data for every substep and the comparison code does not seem to honor the timesteps we see these deviations.

I see 2 possibilities
1. Prescribe the timestep size and increase the maximum number of linear iterations allowed.
2. Only compare the data for matching time stamps.

**Comment by blattms** [comment]
For our case the deviation starts at timestep 115, substep 11. The parallel version does not converge here while the sequential one does.

**Comment by andlaus** [comment]
option 3) is to convince the simulator to converge for substep 11 of timestep 115? I suppose that would be the best solution, but I have no idea how much effort that is or if it is even feasible.

**Comment by blattms** [comment]
That is not feasible.

BTW: That was a atrificial test using a direct sequential solver. For
the default the deviations will start much earlier.

**Comment by alfbr** [comment]
There is a third possibility, and that is using compareSummary with option -i, which originally was intended for comparing flow with Eclipse. I am more leaning towards the comparing at equal timestamps though.

**Comment by notspiff** [comment]
Can you easily apply the same hack to flow_mpi?

**Comment by akva2** [comment]
me in the wrong window ^^. and a question: i will have to hack istl to use the true (ie not the preconditioned) residual for convergence in the iterative linear solvers, right? no option i'm missing or such.

**Comment by blattms** [comment]
Yes, I can. It is even simpler as flow_mpi has the full operator stored in the matrix.

The residual for the convergence is hard coded. But for most solvers it is the unpreconditioned one. The only exception seems to be GMRes

**Comment by akva2** [comment]
would be interesting whether you see the same residual mode drift there or not as a data point.

**Comment by blattms** [comment]
See 52b271f2a78dc636756446357ee0d0e7e76f2f9c for my changes. Currently, ISTLSolver::maybeSolveOnOne uses SFINAE to deduce wether flow_ebos is used. If we change that to use SFINAE to construct the full operator only where needed...

**Comment by blattms** [comment]
Will give that a try.

**Comment by blattms** [comment]
*gggrrrr* and I get bitten by float instead of double again. Need to install a new dune-version *sigh*.

**Comment by blattms** [comment]
Well, it turned out that there was a bug in the code where i add the well contributions to the matrix. After fixing this the serious deviations are gone when solving the linear system always directly on one process.
So at least for this special hack the deviations are gone.

**Comment by akva2** [comment]
\o/

tests score again :D

**Comment by blattms** [comment]
gone apart from these small differences:
```
Deviation results for keyword OPMEXTRA of type DOUB:
Average absolute deviation = 9.31323e-09
Median absolute deviation  = 9.31323e-09
Average relative deviation = 1.36838e-15
Median relative deviation  = 1.36838e-15
```
which are zero for flow_mpi.

**Comment by akva2** [comment]
still that's well within what we can expect.

**Comment by blattms** [comment]
No flow_ebos anymore
