### ISSUE TITLE
Flow_solvent test cases does not run with current release branch

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#1157]
For the SPE based cases I get: 

> Error: Program threw an exception: Wrong size on solution vector: KRNSW_GO

This is output related. Removing RPTRST from the deck "solves" the problem.

**Comment by atgeirr** [comment]
I believe this was fixed in #1152, so it should be ok for the next release tag.

**Comment by totto82** [comment]
It works in current master.
