### ISSUE TITLE
Negative saturation values are written to restart files

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1158]
This only affects few cells, and while it may not make any sense to truncate these values internally in the simulator, I do believe we should truncate all saturations to be within [0,1] when they are written to restart files.

**Comment by dr-robertk** [comment]
But then a restarted simulation would differ from the original simulation in a very subtle way. In that sense one shouldn't call it restart then.

**Comment by GitPaean** [comment]
We have a few numerical truncations for values like bhp or two big iteration increment. 

I do not think it is a problem to truncate the saturation values to be within [0,1], although it might need a little more work and testing.

And I agree with @dr-robertk 's point.

**Comment by GitPaean** [comment]
Actually, we have numerical truncation when handling the fractions in the well model already. I believe there should be more places and I believe it is a common practice in the numerical simulation to avoid problematic values generated during the simulation procedure.  Saturation values outside of [0,1] does not make much sense already, and should be okay to be truncated.

**Comment by alfbr** [comment]
> But then a restarted simulation would differ from the original simulation in a very subtle way. In that sense one shouldn't call it restart then.

Good point, so then we should actually truncate the values within the simulator (after testing for potential negative effects).
