### ISSUE TITLE
About the blocktype matrix vector operation in Dune

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1159]
We have matrix A is Matrix with block size 3X4 , B is a Matrix with block size 4X4,  X is a Vector with block size 4.     

A and B both have N X N blocks and X has N blocks.  

By C = A * B,  will we get a Matrix with block size 3 X 4?

By Y = A * B * X, will Y be the a Vector with block size 3?

Or the above operations are not allowed with Dune. 

Thanks.

**Comment by dr-robertk** [comment]
@GitPaean: I answer the second question first. 

Y1 = B * X (no probl, everything is 4x4)
Then, Y = A * Y1 is also ok, Y being block_size 3 and Y1 being  block_size 4 and A as above. 
You can easily test the other case by doing this: 

    //! calculates ret = A * B
    template< class K, int m, int n, int p >
    static inline void multMatrix ( const FieldMatrix< K, m, n > &A,
                                    const FieldMatrix< K, n, p > &B,
                                    FieldMatrix< K, m, p > &ret )
    {
      typedef typename FieldMatrix< K, m, p > :: size_type size_type;

      for( size_type i = 0; i < m; ++i )
      {
        for( size_type j = 0; j < p; ++j )
        {
          ret[ i ][ j ] = K( 0 );
          for( size_type k = 0; k < n; ++k )
            ret[ i ][ j ] += A[ i ][ k ] * B[ k ][ j ];
        }
      }
    }

Hope this helps.

**Comment by GitPaean** [comment]
Thanks for your answer. It is very helpful. I would like to learn more about DUNE with time. 

Closing this issue for now.
