### ISSUE TITLE
after yum install, no executable file under bin, but lib files

### ISSUE THREAD

**Issue by Rui-Xu** [OPM/opm-simulators#1163]
I followed http://opm-project.org/?page_id=245

Red Hat Enterprise Linux 6 or 7
First add the opm package repository:
sudo yum install ...

 to install it on CentOS .

I only have a couple of module in /lib folder but no executable file under /bin.

I was expecting there will be /bin/flow or /usr/bin/flow somewhere I can run and start to use it

**Comment by akva2** [comment]
hi,


the instructions for rhel/centos are pretty vague. make sure you install the opm-simulators-bin package. that's the one holding the simulator binaries.


cheers


arnem

________________________________
Fra: Rui Xu <notifications@github.com>
Sendt: 25. april 2017 00:29:35
Til: OPM/opm-simulators
Kopi: Subscribed
Emne: [OPM/opm-simulators] after yum install, no executable file under bin, but lib files (#1163)


I followed http://opm-project.org/?page_id=245

Red Hat Enterprise Linux 6 or 7
First add the opm package repository:
sudo yum install ...

to install it on CentOS .

I only have a couple of module in /lib folder but no executable file under /bin.

I was expecting there will be /bin/flow or /usr/bin/flow somewhere I can run and start to use it

**Comment by Rui-Xu** [comment]
Do you know where and how to install opm-simulators-bin package?


Thanks


Rui


________________________________

**Comment by Rui-Xu** [comment]
Thanks. Now I installed opm flow. I had another problem to run it.


$ flow SPE1CASE1.DATA
**********************************************************************
*                                                                    *
*                This is flow_ebos (version 2017.04)                 *
*              (eWoms version: 2017.04.0 ("Fabienne"))               *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*            and is part of OPM. For more information see:           *
*                       http://opm-project.org                       *
*                                                                    *
**********************************************************************

Reading the deck file 'SPE1CASE1.DATA'

***************Saturation Functions Diagnostics***************
System:  Black-oil system.
Relative permeability input format: Saturation Family I.
Number of saturation regions: 1

flow: symbol lookup error: /usr/lib64/libopmoutput.so.2017: undefined symbol: _ZN3ERT11EclFilenameERKSsS1_13ecl_file_enumb

Do you know what will be the cause? What is the minimum version requirement for OPM flow to install?

Thanks



________________________________

**Comment by andlaus** [comment]
> ```
> flow: symbol lookup error: /usr/lib64/libopmoutput.so.2017: undefined symbol: _ZN3ERT11EclFilenameERKSsS1_13ecl_file_enumb
>```
>
> Do you know what will be the cause?

that is due to a missing symbol in libecl/ERT. The strange thing is that this only happens after parsing the deck.

**Comment by Rui-Xu** [comment]
Do you know how i could make it work?



On Apr 27, 2017, at 13:11, Andreas Lauser <notifications@github.com<mailto:notifications@github.com>> wrote:


flow: symbol lookup error: /usr/lib64/libopmoutput.so.2017: undefined symbol: _ZN3ERT11EclFilenameERKSsS1_13ecl_file_enumb


Do you know what will be the cause?

that is due to a missing symbol in libecl/ERT. The strange thing is that this only happens after parsing the deck.

**Comment by andlaus** [comment]
yeah, you need a new package libecl. Possibly you made some mistake with adding the custom repo, or maybe something went wrong with the packages for RHEL. ideas, @akva2?

if you are impatient, you can compile from source or install Ubuntu 16.04 plus the packages for that distribution.

**Comment by atgeirr** [comment]
You could have an old version of ERT or OPM libs lying around, I suggest you look for that and delete them before re-installing.

**Comment by GitPaean** [comment]
This one is quite stale, should be closed.
