### ISSUE TITLE
small time step

### ISSUE THREAD

**Issue by hongtaoUTA** [OPM/opm-simulators#1171]
Hi,

I am running OPM with a super small time step, like 1e-8 day. When I tried to look at the data using ecl_summary, it gives me this:
-- Days   dd/mm/yyyy          WOPR:PROD 
----------------------------------------
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
   0.00   01/01/2015         3.4722e-09 
Is there any way to increase the precision of time in the output? Thanks

**Comment by joakim-hove** [comment]
There is no elegant run-time way to do that (yes - it should be!); but if you have compiled ERT/libecl yourself this is the line to change: https://github.com/Ensembles/ert/blob/master/libecl/src/ecl_sum.c#L894

If Python is an option the following untested script is more-or-less a sightly slower replica of `ecl_summary`:

```python
from ert.ecl import EclSum
import sys

s = EclSum(sys.argv[1])
vectors = [ s.__getitem__(key) for key in sys.argv[2:]]
v0 = vectors[0]
for index in range(len(v0)):
     print "%12.8f " % v0[index].days,
     for v in vectors:
           print "%12.7f % " v[index].value,
     print
```

Feel free to make an isse at https://github.com/Statoil/libecl if you have further questions.
