### ISSUE TITLE
error: NaN residual for phase water

### ISSUE THREAD

**Issue by hongtaoUTA** [OPM/opm-simulators#1180]
Hi All:

I got the following error when run OPM. It is two phase flow (oil/water). There is one injection well and one production well. Both controlled by the flow rate. When I increase the injection rate, OPM gives me this error:
Error: [/builddir/build/BUILD/opm-simulators-release-2017.04-final/opm/autodiff/BlackoilModelEbos.hpp:1021] NaN residual for phase water

Does anyone know what is the problem? Thanks

Hongtao

**Comment by atgeirr** [comment]
Without seeing the concrete case, it is hard for me to say exactly what happens here. However it seems likely that the Newton iterations are diverging (although the NaN is a little worrying). Does the simulator stop totally, or cut the timestep and eventually get through?

If you are able to share the deck it is possible that we could help you more, but no guarantee...

**Comment by hongtaoUTA** [comment]
Thank you.
I probably figured out the problem. This is a 1D problem with one injector and one producer. Injector and producer are controlled by the same flow rate. The pressure in the reservoir increases gradually to an abnormally high value. I think it is because fluid is compressible, so injector and producer would have different flow rate. 
I think maybe I should set the compressibility 0 or make the producer pressure controlled.

**Comment by andlaus** [comment]
> I think maybe I should set the compressibility 0

if you only do this, then you will just get the NaNs immediately ;)

> or make the producer pressure controlled.

that will work as far as I can see.
