### ISSUE TITLE
Strange behaviour with output=false and nonexising output_dir

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1223]
When using `output=false output_dir=non-existent-dir` where the output_dir does not exist, we do not create the output_dir and no files get written at all. In contrast if the output_dir does exist it will contain updated .CASE.DEBUG, CASE.PRT and step_timings_txt files after the run.

Bug or feature?

**Comment by blattms** [comment]
In any case step_timing.txt will be empty with `output=false`

**Comment by atgeirr** [comment]
I think the original intention was to not write anything to disk when output=false. This assumption has not been revisited after log-type output (to PRT and DEBUG files) was added, so the floor is open to opinions. I think that it would be useful to have both the current options (all output, only log output to disk) as well as the "missing" option (nothing to disk at all). Perhaps we should make it a string argument with options "all" (default), "log" and "none"?

**Comment by joakim-hove** [comment]
> Perhaps we should make it a string argument with options "all" (default), "log" and "none"?

That would get my vote.
