### ISSUE TITLE
flow_ebos: No check or error message for min(krw)>0 in SWOF

### ISSUE THREAD

**Issue by vkip** [OPM/opm-simulators#1232]
flow_ebos throws an "out of range" exception for the attached dataset. The problem seems to be detection of the critical water saturation since min(krw)>0.

Best regards,
[B.DATA.txt](https://github.com/OPM/opm-simulators/files/1098136/B.DATA.txt)

-Vegard.

**Comment by andlaus** [comment]
OPM/opm-material#235 should fix it. can you verify?

**Comment by andlaus** [comment]
I just merged OPM/opm-material#235. if this issue still persist, feel free to reopen it.
