### ISSUE TITLE
Build error - HAVE_PTHREAD not defined?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1234]
https://ci.opm-project.org/job/opm-output-PR-builder/76/console

**Comment by bska** [comment]
See my [comment](https://github.com/OPM/opm-simulators/pull/1189#issuecomment-311327027) in #1189 .

**Comment by joakim-hove** [comment]
> See my comment in #1189 .

Thank you - on it.

**Comment by joakim-hove** [comment]
Hmmmmm :-)
