### ISSUE TITLE
Seg. fault. mpi + restart

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#1255]
I tried to mpirun from restart file but flow_ebos segfaults. 
For instance the spe9 restart case in opm-data: 

mpirun -np 2 ../../opm-simulators-build/bin/flow_ebos SPE9_CP_SHORT_RESTART 

Is this a new issue? Or am I the first one to try this?

**Comment by totto82** [comment]
The issues seems to come from  Opm::EclipseIO::loadRestart: 

```
Thread 1 "flow_ebos" received signal SIGSEGV, Segmentation fault.
0x0000000000a74817 in Opm::EclipseIO::loadRestart(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Opm::RestartKey, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, Opm::RestartKey> > > const&, std::map<---Type <return> to continue, or q <return> to quit---
std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, bool> > > const&) const ()
```

**Comment by joakim-hove** [comment]
The `EclipseIO` class is *strictly serial* - is the calling code suitably protected with `if (is_io_rank())`?

**Comment by totto82** [comment]
NO. And the code for distributing the global solution to the local ones is not existing.  An invert of collectToIORank() needs to be written. I asked @dr-robertk to take a loop.

**Comment by blattms** [comment]
> An invert of collectToIORank() needs to be written. I asked @dr-robertk to take a loop. 

Please do not go down that road. There must be functionality for this
in CpGrid. Just look at the code for loadbalance with a data handle.

**Comment by dr-robertk** [comment]
That's probably the better solution.

**Comment by totto82** [comment]
This is fixed, and the feature added to the regular testing
