### ISSUE TITLE
What to do with flow_ebos, flow_ebos_2p, flow_ebos_polymer, and flow_ebos_solvent?

### ISSUE THREAD

**Issue by dr-robertk** [OPM/opm-simulators#1260]
I think to old executables can (and should) be removed along with the tests for those to reduce compile time and confusion.

**Comment by atgeirr** [comment]
I agree, but would like a solution to this testing-related issue first: How can I run a non-solvent case with the solvent simulator (or a 2-phase case with the 3-phase sim etc.) as a sanity-check. My suggestion is using a parameter such as `solver_choice=solvent` (or `2p` or `blackoil` etc.) with a default from RUNSPEC.

**Comment by dr-robertk** [comment]
@atgeirr: Before we decide that I would like to discuss whether we need or want that. In the current code that does not make sense because you would have to add all kind of hacks to make the solvent simulator run a pure blackoil case.

**Comment by GitPaean** [comment]
I think this issue is closed with https://github.com/OPM/opm-simulators/pull/1330
