### ISSUE TITLE
OPM_THROW in parallel running

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1262]
I have a question here I found when I worked on the code of the well modeling, while it applies to other part of the code also. 

When we have several processes in parallel, if some of the processes `OPM_THROW` exceptions, and other processes do not. What will happen to the simulation? Do we need to do something here?

**Comment by blattms** [comment]
That depends. If all processes throw and you do not catch the
exception, you are relatively save (all processes die). The problem
starts if only few processes throw. Unless you add a synchronization
point where you notify all processes of it and react accordingly, the
program will deadlock. Unfortunately, this situation might occur for
wells wheren some processes might not even see any of them,

**Comment by GitPaean** [comment]
The solution I can think of now is to return a `report` for the major functions related to wells, we then check the `report` from time to time.

**Comment by blattms** [comment]
If there is no communication happening in between, then yes. Otherwise
we get a deadlock. Is this about the wells?

**Comment by GitPaean** [comment]
I am not sure `OPM_THROW` in other parts of the simulator is a problem yet. I know several places they will throw all together but I am not sure they always do that. For the wells, it is sure a problem we need to fix in the future. We need to go through all the places that throw (some of them are not necessary) and make a solution.

**Comment by blattms** [comment]
These instances where we throw are a problem:

[ StandardWellsDense_impl.hpp#L501](/OPM/opm-simulators/blob/0c61f63900b484ac6aa0e2853ec04de69e6ebbe0/opm/autodiff/StandardWellsDense_impl.hpp#L516), [ StandardWellsDense_impl.hpp#L501](/OPM/opm-simulators/blob/0c61f63900b484ac6aa0e2853ec04de69e6ebbe0/opm/autodiff/StandardWellsDense_impl.hpp#L516) as they do not seem to be catch and handled when calling getWellConvergence.

We have to catch them at the call,communicate whether there was a throw on one rank, and react on all ranks.
