### ISSUE TITLE
Error: Program threw an exception: std::bad_alloc

### ISSUE THREAD

**Issue by camilomalagon** [OPM/opm-simulators#1271]
Hello,

I had installed Flow using an Oracle VM with in Ubuntu.  I want to make the first test of the simulator running one of the files of the DELF University Olympus Challenge 
http://www.isapp2.com/downloads/description-optimization-challenge-input-files.pdf

and I got the following error
```
Error: Program threw an exception: std::bad_alloc
```
I also get some other warnings during the starting of the run (see full screen below)

Can some one advice how to solve the Error first.  and hopefully advice on the other warnings

Thank you,

CMN

```
cmn@cmn-VirtualBox:~/Simulations/OLYMPUS_10$ flow OLYMPUS_10.DATA
Reading the deck file 'OLYMPUS_10.DATA'
Warning: Expected the kewyord: NUMRES to infer the number of records in: COORDSYS
Warning: Expected the kewyord: EQLDIMS to infer the number of records in: EQUIL
Only 2 fluid phases are enabled

***************Saturation Functions Diagnostics***************
System:  Oil-Water system.
Relative permeability input format: Saturation Family I.
Number of saturation regions: 4

================ Starting main simulation loop ===============
Warning: Keyword 'BASIC' is unhandled for output to file.
Warning: Keyword 'FLOWS' is unhandled for output to file.

Time step    0 at day 0/7305, date = 01-Jan-2016
  Substep 0, stepsize 120.78 days.
Error: Program threw an exception: std::bad_alloc
```

**Comment by camilomalagon** [comment]
I search on the error in google for "bad_alloc" error, it states that is insufficient memory allocation on C++.

Unable to know how to solve that issue.  I decide to run the simulator in a dedicated Ubuntu machine instead of using the Virtual Machine.

**Comment by blattms** [comment]
Hi,

On Tue, Oct 10, 2017 at 02:09:45PM +0000, camilomalagon wrote:
> I search on the error in google for "bad_alloc" error, it states that is insufficient memory allocation on C++.
> 
> Unable to know how to solve that issue.  I decide to run the simulator in a dedicated Ubuntu machine instead of using the Virtual Machine.
>

If it works on a dedicated Ubuntu machine and not on the virtual one
then I can only assume that the latter has not enough RAM available
for your problem. You can use "free -m" to see the available memory in
megabytes.

Markus
-- 
Dr. Markus Blatt - HPC-Simulation-Software & Services http://www.dr-blatt.de
Pedettistr. 38, 85072 Eichstätt, Germany,  USt-Id: DE279960836
Tel.: +49 (0) 160 97590858

**Comment by atgeirr** [comment]
> If it works on a dedicated Ubuntu machine and not on the virtual one
> then I can only assume that the latter has not enough RAM available
> for your problem. You can use "free -m" to see the available memory in
> megabytes.

It is also possible to increase the memory the VM is allowed to use (how depends on the VM tech used i.e. VirtualBox or VMWare or others).
