### ISSUE TITLE
segmentation fault with FLOW for model without wells 

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1302]
FLOW gives a segmentation fault when running a simple model without wells. I've included a gist of this model here:

> https://gist.github.com/nairr/a819ca11a87e558af1f19bbb6c3cbd02

This model without wells runs with flow_ebos version 2016.10 [and flow_legacy, E100] and not with the current version.

**Comment by atgeirr** [comment]
Old bugs resurface and become new! Probably we forgot to add a `if(!localWellsActive()) { return; }` somewhere. We'll figure this out. It should be fixed before the release.

**Comment by nairr** [comment]
My bad! I tested it with a slightly older version of FLOW. Sorry for the noise.

Closing.
