### ISSUE TITLE
Cannot run any simulator anynore

### ISSUE THREAD

**Issue by EnricoScantamburlo** [OPM/opm-simulators#1360]
I am on Centos and I am updated to the latest version and installed all updates. Every time I try to launch a simulation with any simulator I get this error:
```
Reading the deck file 'SPE1CASE1.DATA'
flow_ebos: symbol lookup error: /lib64/libopmparser.so.2017: undefined symbol: _ZN3ERT11smspec_nodeC1E19ecl_smspec_var_typeRKSsS3_
```

**Comment by atgeirr** [comment]
Possibly this could be caused by OPM transitioning from using ERT to libecl (which used to be part of ERT but is now standalone), and you having an old library installed. I suggest you try to uninstall any ERT packages and see if that helps.

**Comment by EnricoScantamburlo** [comment]
Thanks for the reply. Removing the old library and installing the new one fixed the problem
