### ISSUE TITLE
Include reservoir production volumes to opm-output

### ISSUE THREAD

**Issue by lars-petter-hauge** [OPM/opm-simulators#1363]
Hi

We're implementing summary keywords in opm-output that contains reservoir production volumes. I believe the current input to opm/output/eclipse/Summary::Summary only contains surface volumes.

Would it be possible to include reservoir volumes?

**Comment by atgeirr** [comment]
Short answer: yes it is possible.

Longer answer: I do not know how much time it would take, but it is not a two-line change, as currently those reservoir fluxes have only been needed on the inside of the well model code. Probably we must
 - ensure the fluxes are written correctly to the well state object
 - add something to the parallel communication part collecting data on the I/O node
 - add something to the (presumably modified on your end) output data storage object Opm::data::Rates.

**Comment by GitPaean** [comment]
An initial implementation was propose in #1405. Testing with more cases will be helpful.

**Comment by GitPaean** [comment]
PR #1405 has been merged, while this functionality has only been through very limited test. Please report if any discrepancy was found for specific cases.   Closing this issue now.
