### ISSUE TITLE
Add Carter Tracy aquifer model

### ISSUE THREAD

**Issue by kel85uk** [OPM/opm-simulators#1372]
This is to add the carter tracy aquifer model into OPM Flow.

**Comment by kel85uk** [comment]
Cool, looks like we can close this issue. Will open another one for parallel model support. Reopen if this isn't correct/desired.

**Comment by GitPaean** [comment]
You do not need to open an issue for this. Just creating new PR will be fine.

**Comment by atgeirr** [comment]
It seems Jenkins is not quite happy with the aquifer tests: https://ci.opm-project.org/job/opm-simulators/

This must be fixed, with high priority!

**Comment by GitPaean** [comment]
I will take a look. The jenkins was happy before merging.

**Comment by GitPaean** [comment]
Locally build shows the master branch is okay. I will try to test jenkins again.

**Comment by kel85uk** [comment]
Seems like there are some jenkins problems. Reopening.

**Comment by GitPaean** [comment]
> Seems like there are some jenkins problems. Reopening.

It was a false alarm.  Please refer to https://github.com/OPM/opm-simulators/pull/1489 . Unless you found something else, I think you should close this issue.

**Comment by kel85uk** [comment]
Ah cool. Thanks again for the update and guidance. 👍 @GitPaean
