### ISSUE TITLE
flow throw s for unrecoginized SUMMARY keywords

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1410]
SUMMARY keywords are among those only have output effects.  Please let me know if it is the desired behavior.  

```
Failed to create valid EclipseState object.
Exception caught: PARSE_UNKNOWN_KEYWORD: Keyword WOVPR not recognized.
terminate called after throwing an instance of 'std::invalid_argument'
  what():  PARSE_UNKNOWN_KEYWORD: Keyword WOVPR not recognized.
Aborted
```

**Comment by joakim-hove** [comment]
> SUMMARY keywords are among those only have output effects.

Yes - *we* know that this keyword is only related to summary output, and not  very interesting - for the parser it is just an unrecognized keyword - and those are handled according to the `PARSE_UNKNOWN_KEYWORD` setting: https://github.com/OPM/opm-parser/blob/master/lib/eclipse/include/opm/parser/eclipse/Parser/ParseContext.hpp

The parser currently has quite low *section awareness*, if that were different we could have used the fact that "we are now in the quite dull `SUMMARY` section. That would probably be a good thing, but it is a significant task.

**Comment by GitPaean** [comment]
> Yes - we know that this keyword is only related to summary output, and not very interesting - for the parser it is just an unrecognized keyword - and those are handled according to the PARSE_UNKNOWN_KEYWORD setting: https://github.com/OPM/opm-parser/blob/master/lib/eclipse/include/opm/parser/eclipse/Parser/ParseContext.hpp

Thanks for the explanation. I guess unless we want to change the policy against all `PARSE_UNKNOWN_KEYWORD`, it will just throw at the moment.
