### ISSUE TITLE
Error vector::_M_range_check: __n

### ISSUE THREAD

**Issue by dkolesnikov** [OPM/opm-simulators#1418]
Dear OPM community,

I have launched OPM on the 3-phase 3D problems. The fragment of logs is below:
```
> #### Reading the deck file '/shared_host/hds_inputs/41_60_10/5.data'
> #### Program threw an exception: vector::_M_range_check: __n (which is 18446744073709549156) >= this->size() (which is 24600)
> #### -------------------------------------------------------
> #### Primary job  terminated normally, but 1 process returned
> #### a non-zero exit code.. Per user-direction, the job has been aborted. 
```
Logs with 3 different decks are [here](https://github.com/OPM/opm-simulators/files/1775382/logs.zip).

What can I do with the error? It seems an inner C code problem. 
The possible similar issue can be this [one](https://github.com/OPM/opm-simulators/issues/689)

Thank you in advance,
Denis, Ph.D. student in comp. maths

**Comment by joakim-hove** [comment]
>  `#### Primary job  terminated normally, but 1 process returned`

Have you tried a scalar run?

**Comment by dkolesnikov** [comment]
Yes, all issues are still relevant.
> Have you tried a scalar run?

It seems the reason is that I've used mpirun. Running without it may allow work around this issue. I need to test it. I've also heard from my colleague that ECLIPSE process attached deck files with any errors. But it needs clarification.
I will write later.
