### ISSUE TITLE
Problem running a large case with MPI

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-simulators#1437]
Hello ,

When I tried to run SPE10 case in OPM using MPI and Zoltan with 40 cores, it somehow stopped showing the output (but job is still running) after the loadbalancing process as below. 
```
**********************************************************************
*                                                                    *
*                      This is flow 2018.04-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see http://opm-project.org          *
*                                                                    *
**********************************************************************

After loadbalancing process 5 has 40760 cells.
After loadbalancing process 6 has 40384 cells.
After loadbalancing process 18 has 37109 cells.
After loadbalancing process 24 has 40166 cells.
After loadbalancing process 15 has 39999 cells.
After loadbalancing process 23 has 32420 cells.
After loadbalancing process 33 has 33084 cells.
After loadbalancing process 3 has 42574 cells.
After loadbalancing process 34 has 4785 cells.
After loadbalancing process 7 has 43137 cells.
After loadbalancing process 1 has 44418 cells.
After loadbalancing process 11 has 40870 cells.
After loadbalancing process 14 has 29750 cells.
After loadbalancing process 17 has 40094 cells.
After loadbalancing process 10 has 41721 cells.
After loadbalancing process 25 has 43495 cells.
After loadbalancing process 38 has 44374 cells.
After loadbalancing process 0 has 42701 cells.
After loadbalancing process 22 has 41742 cells.
After loadbalancing process 37 has 43631 cells.
After loadbalancing process 27 has 48242 cells.
After loadbalancing process 16 has 43060 cells.
After loadbalancing process 39 has 33669 cells.
After loadbalancing process 29 has 44491 cells.
After loadbalancing process 28 has 43003 cells.
After loadbalancing process 20 has 42938 cells.
After loadbalancing process 35 has 45923 cells.
After loadbalancing process 36 has 44913 cells.
After loadbalancing process 13 has 41972 cells.
After loadbalancing process 31 has 41314 cells.
After loadbalancing process 8 has 47880 cells.
After loadbalancing process 30 has 43712 cells.
After loadbalancing process 12 has 42800 cells.
After loadbalancing process 21 has 42983 cells.
After loadbalancing process 26 has 44727 cells.
After loadbalancing process 9 has 45280 cells.
After loadbalancing process 4 has 50188 cells.
After loadbalancing process 2 has 50215 cells. 
```

I checked that with 1 or 2 core(s) the simulation starts to run. However, with 3 or more cores, the same problem occurs.  Have you seen this problem before? Is there any suggestions to fix this? 

Also, I have noticed that the grid partitioning is not well optimized here.  In above, the process 34 has 4785 cells while the process 2 has 50215 cells, meaning the the latter one has about 10.5 (~50215/4785) time more work than the former one!

**Comment by atgeirr** [comment]
We have recently also noticed this problem on some cases, for certain numbers of processes. We have not yet debugged it enough to figure out why.

The grid partitioning also seems suspiciously bad, I agree. This may or may not be related to the lock-up, we do not know yet. Which deck and other parameters did you use?

**Comment by sogoogos** [comment]
I am using SPE10_MODEL2.DATA in opm-data and another SPE10 input file I have also gave the same problem. 

Adding MINPV 20/ in the .DATA file made the simulation run with 40 cores, but it eventually stopped due to the segmentation fault.

**Comment by sogoogos** [comment]
Seems like using a newer Dune improves the situation. I switched from the version 2.4 to 2.6, and then was able to start the simulation without having the lock-up with 40 cores.  But I still have to check if it causes the segmentation fault I got previously with the newer DUNE. 

In the OPM homepage, it says "We currently support Dune 2.3 and 2.4, but will shortly change this to support 2.4 and 2.5 instead." Is there any potential problem using the 2.6 version?

**Comment by akva2** [comment]
dune 2.6 should be fully supported.

**Comment by andlaus** [comment]
actually, Dune master (which is will eventually become 2.7) *might* work as well.

@atgeirr: can you update the website?

**Comment by sogoogos** [comment]
Actually I still get the same lock-up when more cores are used like 100. 

@andlaus  Okay, I will test Dune master too and see if it improves the situation.

**Comment by atgeirr** [comment]
> @atgeirr: can you update the website

I will. But before I do that, what is the precise state? We support 2.4, 2.5, 2.6 (and experimentally: current master ~ 2.7)?

**Comment by andlaus** [comment]
> We support 2.4, 2.5, 2.6 (and experimentally: current master ~ 2.7)?

for 2.4 to 2.6 I can say with confidence that it works. for 2.7, `make flow` worked two weeks ago, but `make all` in opm-simulators was broken because some unneeded code produced a compiler error. (also, I haven't tested this using the default build system.)

**Comment by sogoogos** [comment]
With Dune 2.6 and current master, I encountered another problem which a simulation looks not working without outputting any messages, but cores are still running (below). I did not have this before with Dune 2.4. Maybe deadlock? I will check what is going on here with a debugger. 

```
...
Time step 236, stepsize 0.0399701 days.

Time step 236, stepsize 0.0131901 days.
Time step summary: newton its =  2, linearizations =  3 ( 0.196 sec), linear its = 131 ( 1.058 sec)

Time step 237, stepsize 0.0263803 days.
Time step summary: newton its =  2, linearizations =  3 ( 0.191 sec), linear its = 134 ( 1.077 sec)

Time step 238, stepsize 0.0791408 days.

Time step 238, stepsize 0.0261165 days.

Time step 238, stepsize 0.00861844 days.
Time step summary: newton its =  2, linearizations =  3 ( 0.196 sec), linear its = 106 ( 0.941 sec)

Time step 239, stepsize 0.0172369 days.

Time step 239, stepsize 0.00568817 days.
```
The above simulation stopped outputting while cores were still running.

**Comment by atgeirr** [comment]
> for 2.4 to 2.6 I can say with confidence that it works. for 2.7, make flow worked two weeks ago, but make all in opm-simulators was broken because some unneeded code produced a compiler error. (also, I haven't tested this using the default build system.)

Updated the prerequisites page.

> The above simulation stopped outputting while cores were still running.

I do not have too much to help here, but I notice that your stepsizes are small compared to the cases I usually run. Have you tried running with tighter tolerances? You could try running Flow with `tolerance_mb=1e-7 tolerance_cnv=1e-3` and see if that helps.

**Comment by sogoogos** [comment]
@atgeirr Changing tolerances did not help this issue. It just changed when the problem occurs during the simulation. For any cases, DDT debugger said rank 0 was stuck [here](https://github.com/OPM/ewoms/blob/8650fb6343daafdaf71fe25135a831ace5ce130b/ewoms/parallel/tasklets.hh#L100) in ewoms and the other 39 processes were stopped [here](https://gitlab.dune-project.org/core/dune-common/blob/master/dune/common/parallel/mpicollectivecommunication.hh#L329) in dune-common. Can you guess what is going on from that? and what is tasklets.hh for?

**Comment by andlaus** [comment]
Thanks for digging into this. unfortunately that suspiciously looks like some ill-advised fun with threads. what happens if you disable asynchronous output? (i.e. add

```
SET_BOOL_PROP(EclFlowProblem, EnableAsyncEclOutput, false);
```

to `opm/autodiff/BlackoilModelEbos.hpp`.) Depending on how fast your storage system is, the performance will suffer, but you will likely not run into this particular problem.

**Comment by andlaus** [comment]
also, it looks like you're using an not the latest master version of the code. the tasklet stuff has changed recently -- e.g. the wait() method is no more. does it still break on the latest master version of everything. (don't forget to also update your libecl, there was an non-backward compatible change there recently.)

**Comment by andlaus** [comment]
scratch my last comment: I did not misread...

**Comment by andlaus** [comment]
okay, I may have found a race condition in barriers for tasklets. does https://github.com/OPM/ewoms/pull/304 help in your case?

**Comment by sogoogos** [comment]
Thank you! Looks like it is working so far. I will keep running it until it finishes or gets an error.

**Comment by sogoogos** [comment]
Also, another issue occurs when more than one node is used like "-N 4 -n 40", meaning 10 cores per node.   
The debugger said one rank was stuck [here](https://gitlab.dune-project.org/core/dune-common/blob/master/dune/common/parallel/communicator.hh#L1524), and the other 39 were stopped [here](https://gitlab.dune-project.org/core/dune-common/blob/master/dune/common/parallel/mpicollectivecommunication.hh#L329).  The following figure shows parallel stack (call tree from multiple processes) from the debugger.  It looks like solver issue. Maybe this is a bug from Dune side? I got the same problem with GMRES solver too. 

<img width="1280" alt="screen shot 2018-03-29 at 10 52 18 pm" src="https://user-images.githubusercontent.com/24484961/38092989-a0704920-33a4-11e8-9d69-e96733608105.png">

**Comment by andlaus** [comment]
thanks for the backtrace. this error happens in the linear solver, due to a desynchronization/exception on one rank. @blattms is the expert for this part of the code.

**Comment by sogoogos** [comment]
It looks like OPM/ewoms#304 solved the issue of the segmentation fault I mentioned before. Thank you @andlaus!  I am closing this issue.
