### ISSUE TITLE
building libopmcommon.a throws multiple definition error

### ISSUE THREAD

**Issue by kingaj12** [OPM/opm-simulators#1461]
Hi, downloaded master branch and got a build error:

 libecl/lib/include/ert/ecl/EclKW.hpp:225: multiple definition of `ERT::EclKW ....

**Comment by joakim-hove** [comment]
> Hi, downloaded master branch and got a build error:

Hmm - this was really embarassing; I am looking into this now, not able to reproduce it at first attempt. If I can not reproduce and fix it reasonably fast I will revert as indicated by @bska

**Comment by kingaj12** [comment]
Yes this worked.  Seems to be libecl.  Thanks for the fix!

**Comment by joakim-hove** [comment]
OK - I think this: https://github.com/Statoil/libecl/pull/382 should fix it. Sorry.

**Comment by bska** [comment]
> I think [Statoil/libecl#382] should fix it.

It does in my case.  I no longer see the "multiply defined symbol" error from the linker.

**Comment by kingaj12** [comment]
Yes I no longer see it.  I think we can close this.  Thanks!
