### ISSUE TITLE
Restore async_output parameter

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-simulators#1496]
It was lost recently, perhaps in #1491.

**Comment by bska** [comment]
> t was lost recently, perhaps in #1491.

No, in #1399&mdash;specifically in commit a89a6af854202f0dfe54ff48c11e1d62442d1417.

**Comment by atgeirr** [comment]
Ok, perhaps my May result with the option was running an old version from Docker... Thanks for identifying the culprit!

**Comment by andlaus** [comment]
#1497 should fix it.

**Comment by andlaus** [comment]
(note that, as far as I can see, there never has been a way to change the default from flow after this functionality moved into the ebos core.)

**Comment by totto82** [comment]
I will close this. I have tested that it works.
