### ISSUE TITLE
Bug 2018-04: Missing Summary File Vectors.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1507]
The following input deck code did not produce the requested field polymer summary vector output
```
-- ==================================================================
-- 
-- SUMMARY SECTION 
-- 
-- ==================================================================
SUMMARY 
 
ALL

FCPR
FCPC
FCPT
FCIR
FCIC
FCIT
```
All  vectors in the *_PROBE keyword definitions should write out the requested summary vector to the summary file. If the data is not available, for example in the above example, if the the polymer option is not being used, then flow should still write out the requested vector set to zero. It is not necessary to issue a warning message in this case.

**Comment by lars-petter-hauge** [comment]
I'll start adding the rates and totals. I'll do groups, wells and connections at the same time.

Every bit of calculation is moved out of opm-common, so I'm guessing the concentration part will need to be added and populated from the simulator side as well?

**Comment by OPMUSER** [comment]
Thanks for looking into this.

The polymer variables mentioned above are not really concentrations they are the polymer production/injection totals and rates. It just how ECLIPSE named the variables.

**Comment by OPMUSER** [comment]
I think these are simply the ratio of the producing and injecting fluids. I say simply but I need to check what is the ratio. The numerator will be the polymer rate or cumulative and the denominator should be the liquid rates or cumulative liquid. However, we need to check this with an ECLIPSE run just to confirm the denominator.
