### ISSUE TITLE
AdaptiveTimeSteppingEbos.hpp - qualifiers discarded

### ISSUE THREAD

**Issue by kingaj12** [OPM/opm-simulators#1526]
Hi 

I downloaded the master branch today and got tripped up over a compile-time error:

    opm-simulators/opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp:240:25: error:
        passing 'const Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowGasOilProblem>' as 'this'
        argument discards qualifiers [-fpermissive]
                         ebosProblem.writeOutput(localWellData,
                         ^

The variable `ebosProblem` is defined on line 124:

    auto& ebosProblem = ebosSimulator.problem();

So perhaps there is a `const` missing somewhere in there?  I could probably dig it out and fix it myself, but I thought you ought to know.

**Comment by andlaus** [comment]
did you also update the ewoms module?

> So perhaps there is a const missing somewhere in there? I could probably dig it out and fix it myself, but I thought you ought to know.

if anything, there is a `const` too much ;)

**Comment by kingaj12** [comment]
Yes it looks like ewoms updated ok.  I have a mental block with const.  I really hate const.
 
----- Original message -----From: Andreas Lauser <notifications@github.com>To: OPM/opm-simulators <opm-simulators@noreply.github.com>Cc: Alan King <kingaj@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [OPM/opm-simulators] AdaptiveTimeSteppingEbos.hpp - qualifiers discarded (#1526)Date: Fri, Jun 29, 2018 4:33 AM 
did you also update the ewoms module?
So perhaps there is a const missing somewhere in there? I could probably dig it out and fix it myself, but I thought you ought to know.
if anything, there is a const too much ;)

**Comment by andlaus** [comment]
strange, the non-const version of `Simulator::problem()` was added sometime in 2016. could one of your local changes be responsible for the error?

> I really hate const.

I suppose that when you discuss this topic with @atgeirr or @bska I should have enough popcorn at hand. ;)

**Comment by atgeirr** [comment]
I have looked at this, but cannot reproduce it. The method `writeOutput()` is not const, and therefore requires a non-const object to be called, but the definition of `ebosProblem` on line 124 provides just that. The only thing I can think of is that you may have defined a new `ebosProblem` variable that somehow shadows it, i.e. the compiler is not trying to refer to the one defined on line 124, but to one defined elsewhere. Still, scoping should take care of this usually, which means that the likely variable definition is in the same function (below line 124). However that seems unlikely, as I have the same line numbers as you have, so you have not added anything!

So I am stumped here. I doubt I can help you further without access to (some of) the modifications you have made. Have you tried building a plain, clean, unmodified version of the current master, and do you get errors then as well?

**Comment by kingaj12** [comment]
I'll try again and send more detail.  Perhaps it is my compiler settings?
 
----- Original message -----From: "Atgeirr Flø Rasmussen" <notifications@github.com>To: OPM/opm-simulators <opm-simulators@noreply.github.com>Cc: Alan King <kingaj@us.ibm.com>, Author <author@noreply.github.com>Subject: Re: [OPM/opm-simulators] AdaptiveTimeSteppingEbos.hpp - qualifiers discarded (#1526)Date: Mon, Jul 2, 2018 8:23 AM 
I have looked at this, but cannot reproduce it. The method writeOutput() is not const, and therefore requires a non-const object to be called, but the definition of ebosProblem on line 124 provides just that. The only thing I can think of is that you may have defined a new ebosProblem variable that somehow shadows it, i.e. the compiler is not trying to refer to the one defined on line 124, but to one defined elsewhere. Still, scoping should take care of this usually, which means that the likely variable definition is in the same function (below line 124). However that seems unlikely, as I have the same line numbers as you have, so you have not added anything!
So I am stumped here. I doubt I can help you further without access to (some of) the modifications you have made. Have you tried building a plain, clean, unmodified version of the current master, and do you get errors then as well?

**Comment by kingaj12** [comment]
If you can't reproduce, then probably it is something in my local environment.  I actually don't have time right now to dig into it.  I decided to base my work on 2018.04 release for now, so this is not blocking me.  Let's close it, and if I hit it again when merging into 2018.10 we can revisit.
