### ISSUE TITLE
restart file not found unless pwd is the folder containing the restart file

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1537]
I'm unable to start a simulation from a restart file unless my present working directory is the folder containing the restart file, when I start FLOW

Error:

> Program threw an exception: Restart file REEK.UNRST not found!

**Comment by nairr** [comment]
Sure;

1. PWD = /data/DataExchange/Rohith
2. Path to .DATA =  ./orat_case1/REEK_ORAT.DATA 
Starting flow = ./opm_dev/opm-simulators/build/bin/flow ./orat_case1/REEK_ORAT.DATA
3:
RESTART
  REEK_ORAT 29 /

Error = Program threw an exception: Restart file REEK_ORAT.UNRST not found!

**Comment by joakim-hove** [comment]
OK - agree it is a bug.
