### ISSUE TITLE
Segmentation fault with flow

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1556]
Something seems to have been broken for a couple of days. Flow seg-faults after the first time step, it seems to affect all models. This is flow from git compiled for the last three days or so. Boost is version 1.58, Dune is 2.4.1, libecl is from git. GCC 4.9.2 on Red Hat 6. I can try to investigate a bit further if nobody else is bitten.

**Comment by alfbr** [comment]
Indeed, just built without openmp and the seg-fault is gone. I (and linuxbenchmarking) have been building with openmp since August 5th though, so this broke on August 15th for flow.

**Comment by andlaus** [comment]
possibly you did not rebuild all OPM modules when you enabled openMP?

**Comment by alfbr** [comment]
Yes, all modules were up-to-date.

**Comment by andlaus** [comment]
I'l close this since #1557 fixes the issue. feel free to reopen if not.
