### ISSUE TITLE
Error Message: ecl_smspec_fwrite: Unable to open fortio file, error: Bad address

### ISSUE THREAD

**Issue by camilomalagon** [OPM/opm-simulators#1565]
Hello 

I try to run a model I had ran a couple of month ago with out an issue and I am getting the error:

Error Message: ecl_smspec_fwrite: Unable to open fortio file, error: Bad address

I had added a screenshoot of it.
![screenshot from fortio error](https://user-images.githubusercontent.com/31506285/45075627-081fc080-b0e8-11e8-9fd3-310cd71af3fc.png)

Here with Ubuntu 18.04.1 LTS bionic, fresh install of flow 5 days ago.

**Comment by joakim-hove** [comment]
1. This is master branch of all modules?
2. Can you share the model?

**Comment by camilomalagon** [comment]
That was easy.! It is working now, thanks.
