### ISSUE TITLE
RTEMP gives strange error

### ISSUE THREAD

**Issue by hnil** [OPM/opm-simulators#1590]
Including in NORNE deck:
```
RTEMP
80 /
```
gives
```
Failed to create valid EclipseState object.
Exception caught: Malformed floating point number 'RPTRST'
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Malformed floating point number 'RPTRST'
Aborted (core dumped)
```
RPTRST is the next keyword in the deck.

**Comment by joakim-hove** [comment]
Please post some keywords before the RTEMP - are ignoring keywords?

**Comment by hnil** [comment]
Iin my file:
INCLUDE
 './INCLUDE/PETRO/EQLNUM_0704.prop' / 

-- extra regions for geological formations and numerical layers 
--INCLUDE
-- './INCLUDE/PETRO/EXTRA_REG.inc' / 

---------------------------------------------------------------------------------

SOLUTION

-- add rock temperature
RTEMP
80 /

RPTRST
'BASIC=5' 'FREQ=12' / -- write out restart data  every 12 months

The errors should be reproducible only by including  RTEMP just as the first in the SOLUTION section

**Comment by joakim-hove** [comment]
Transferred here: https://github.com/OPM/opm-common/issues/519
