### ISSUE TITLE
Information and issues with THERMAL option 

### ISSUE THREAD

**Issue by skahroba** [OPM/opm-simulators#1595]
I am trying to use OPM for geothermal simulations. Here are some issues/information that I faced/need regarding THERMAL option of OPM:

  1. The unit of rock heat capacity in `SPECROCK` should be `kJ/m3/K` but in the manual it is  `kJ/kg/K`.

  2. The `VISCREF` keyword does not work and results in errors. Therefore, it seems the viscosity of the fluids cannot be updated by temperature changing. Note that, temperature dependency of fluid properties is a very important factor in thermal simulations.
 
  3. Is there a keyword to report the fluid temperatures in the wells?

  4. The temperature in the producer gridblock slightly increases with time, which sounds like an artefact to me.

  5. Is temperature handled like a tracer in OPM? I mean the energy conservation is solved at the end of each converged timestep or the energy and flow equations are solved at the same time. 

Thanks for your help.

**Comment by totto82** [comment]
> The unit of rock heat capacity in SPECROCK should be kJ/m3/K but in the manual it is kJ/kg/K.

This is correct in the current code. Can you fix the manual?@OPMUSER: 

>  The VISCREF keyword does not work and results in errors. Therefore, it seems the viscosity of the fluids cannot be updated by temperature changing. Note that, temperature dependency of fluid properties is a very important factor in thermal simulations.

This is not very well tested. We can take a look. 

>    Is there a keyword to report the fluid temperatures in the wells?
No. How to calculate this consistently. Will output of produced energy help? That is trivial.  

>  The temperature in the producer gridblock slightly increases with time, which sounds like an artefact to me. 
Temperature is pressure dependent so it may happen. Of-course it could very well be a bug. We will need more info about the case to check this out. Can you share your deck via email? 

>Is temperature handled like a tracer in OPM? I mean the energy conservation is solved at the end of each converged timestep or the energy and flow equations are solved at the same time. 

It is solved fully implicitly.

**Comment by OPMUSER** [comment]
> The unit of rock heat capacity in SPECROCK should be kJ/m3/K but in the manual it is kJ/kg/K.
> This is correct in the current code. Can you fix the manual?@OPMUSER:

Fixed in 2018-10 version of the manual.

**Comment by skahroba** [comment]
> > The unit of rock heat capacity in SPECROCK should be kJ/m3/K but in the manual it is kJ/kg/K.
> 
> This is correct in the current code. Can you fix the manual?@OPMUSER:
> 
> > The VISCREF keyword does not work and results in errors. Therefore, it seems the viscosity of the fluids cannot be updated by temperature changing. Note that, temperature dependency of fluid properties is a very important factor in thermal simulations.
> 
> This is not very well tested. We can take a look.
> 
> > Is there a keyword to report the fluid temperatures in the wells?
> > No. How to calculate this consistently. Will output of produced energy help? That is trivial.
> 
> > The temperature in the producer gridblock slightly increases with time, which sounds like an artefact to me.
> > Temperature is pressure dependent so it may happen. Of-course it could very well be a bug. We will need more info about the case to check this out. Can you share your deck via email?
> 
> > Is temperature handled like a tracer in OPM? I mean the energy conservation is solved at the end of each converged timestep or the energy and flow equations are solved at the same time.
> 
> It is solved fully implicitly.

To which email address I can sen

**Comment by skahroba** [comment]
> > The unit of rock heat capacity in SPECROCK should be kJ/m3/K but in the manual it is kJ/kg/K.
> 
> This is correct in the current code. Can you fix the manual?@OPMUSER:
> 
> > The VISCREF keyword does not work and results in errors. Therefore, it seems the viscosity of the fluids cannot be updated by temperature changing. Note that, temperature dependency of fluid properties is a very important factor in thermal simulations.
> 
> This is not very well tested. We can take a look.
> 
> > Is there a keyword to report the fluid temperatures in the wells?
> > No. How to calculate this consistently. Will output of produced energy help? That is trivial.
> 
> > The temperature in the producer gridblock slightly increases with time, which sounds like an artefact to me.
> > Temperature is pressure dependent so it may happen. Of-course it could very well be a bug. We will need more info about the case to check this out. Can you share your deck via email?
> 
> > Is temperature handled like a tracer in OPM? I mean the energy conservation is solved at the end of each converged timestep or the energy and flow equations are solved at the same time.
> 
> It is solved fully implicitly.

To which email address I can send you the DATA deck? 
As a matter of fact I realized that the density variations with temperature are not handled in OPM. But more importantly is to consider the visscosity variations with temperature.

**Comment by OPMUSER** [comment]
If you are using 2018-10, then you can use the supported keywords are SPECHEAT, SPECROCK, OILVISCT, WATVISCT,GASVISCT, WATDENT, GASDENT (1), OILDENT(1), THCONR, THCONSF, HEATCR, HEATCRT, WTEMP, WINJTEMP (2), THCGAS, THCOIL, THCROCK, THCWATER, TEMPI, RTEMP and RTEMPVD .
(1): OPM extension
(2): partial (Only the part that makes sense for the Blackoil model)

Take a look at  opm-tests/spe1/SPE1CASE2_THERMAL.DATA for an example.

**Comment by skahroba** [comment]
Ture! But in order to use WATVISCT you need to determine a reference pressure using VISCREF, which is not working. And similar to E100 the density variations with temperature does not take into account.

**Comment by skahroba** [comment]
Ture! But in order to use WATVISCT you need to determine a reference pressure using VISCREF, which is not working. And similar to E100 the density variations with temperature does not take into account.

**Comment by slawekszklarz** [comment]
"Is there a keyword to report the fluid temperatures in the wells?
No. How to calculate this consistently. Will output of produced energy help? That is trivial."
@totto82 

Hi, I am working with geothermal optimization as well. It would be great to have OPM output the produced energy in the well at each time step.
