### ISSUE TITLE
.param file not recognized 

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#1600]
I'm using a daily build of flow; on testing it is not able to run in conjunction with a .param file.

![image](https://user-images.githubusercontent.com/18717906/47351816-12f2dc80-d6b9-11e8-8e24-aa7c047c2a14.png)

The .param file just contains a single argument as follows
![image](https://user-images.githubusercontent.com/18717906/47351951-4e8da680-d6b9-11e8-8d1a-a757574bf6f1.png)

The simulator works when I pass the deck file name as an argument as follows: 
`flow  --ecl-deck-file-name=SPE1CASE1.DATA`

**Comment by andlaus** [comment]
try to remove the two leading dashes from the parameter name in the file. (they are only valid as command line arguments.)

BTW: why do you need a parameter file if you only specify a single parameter?
BTW (2): you do not explicitly need to specify the parameter name for the deck file, i.e., you can also start the simulator using `flow SPE1CASE1`

**Comment by andlaus** [comment]
also, parameter files need to be explicitly specified via the `--parameter-file=$FILENAME` command line argument. I thought that @atgeirr added some magic to detect whether a deck or a parameter file was passed, but it seems that I misremember.

**Comment by nairr** [comment]
Thanks @andlaus - flow is only able to recognize the parameter file if I specify it explicitly via `--parameter-file=$FILENAME`. Additionally, as you've mentioned, the two leading dashes also need to be removed from the parameter name, when using the .param file for it to be recognized.

> BTW: why do you need a parameter file if you only specify a single parameter?

I'm using multiple parameters, just provided this as an example

@OPMUSER - I think some changes are required in the 2018.10 manual based on this information

**Comment by OPMUSER** [comment]
Done, but note that there are over 130 odd parameters that require documentation so I'll need some help on some, for example:

```
--flow-time-step-verbosity=INTEGER                          
Specify the "chattiness" during the time integration
```
Only the developer knows what the values should be and the effect.

A draft 2018-10 should be released for review this week.

**Comment by andlaus** [comment]
yes, that's an example of a developer oriented parameter. I think that you should only mention the user-oriented ones in the manual, though. Also note that there a few truely new parameters in 2018.10 when compared to 2018.04; the main thing which changed is their visibility via `--help`.

**Comment by alfbr** [comment]
> I think that you should only mention the user-oriented ones in the manual, though

Please don't, unless somebody steps up and writes a separate manual for developers. We need documentation of all current command line parameters in flow.

**Comment by andlaus** [comment]
I'm a bit confused by your statement: All developers which I know rarely read the manual and should thus be happy with the `--help` description, i.e., documenting such rather ad-hoc/debugging parameters is IMO just a waste of time/effort/money. given that it is not my time/effort/money, I won't try to prevent anyone from doing this, though.

**Comment by OPMUSER** [comment]
I think the best way to handle this is to document/mention all command line parameters and to shade in gray the developer focused options with a comment that the developer command line parameters are intended for use by the developers only.

**Comment by nairr** [comment]
I agree, it would create confusion if the parameters documented in the manual and through `--help` are not consistent

**Comment by atgeirr** [comment]
> I thought that @atgeirr added some magic to detect whether a deck or a parameter file was passed, but it seems that I misremember.

It is a feature I requested and agreed to implement, when time permitted. It just has not permitted it so far...

**Comment by alfbr** [comment]
> shade in gray the developer focused options with a comment that the developer command line parameters are intended for use by the developers only

That can maybe work. However, the command line switch that started the discussion has actually already been of interest to several users over here. Hence, I believe it may prove difficult to decide what a user may or may not be interested in.

**Comment by OPMUSER** [comment]
The command line -help lists all the option as lower case, for example:

`--ecl-deck-file-name=STRING
`

However in the PRT and DEBUG files, OPM Flow prints this:

`
EclDeckFileName="SPE02-BASE1-OPM-R02.DATA" # default: ""
`

So the command is lower case but the print out is mixed case. This is a bit confusing on Linux systems, but perhaps not a big deal as I'll state in the manual that all command line parameters must be lower case but the PRT and DBG files print mixed case.

**Comment by andlaus** [comment]
you can either use CamelCase or use the same syntax as in the command line to specify parameters in parameter files. (cf. @nairr's original message). The output is just always CamelCase because that's how parameters are specified in the c++ code.

**Comment by andlaus** [comment]
(the same is true for the command line, i.e., 

```
flow --EclDeckFileName=FOO.DATA
```

will be valid. the reason for using the lowercase-with-dashes output on `--help` is to make it blend in with the default convention for UNIX command line parameters.)

**Comment by GitPaean** [comment]
My small complaint is that we got a lot of parameter information when we do not give the correct command-line options by accident. The information is more than one screen long. It looks pretty scary and not very helpful. 

Maybe we do not need to do that, we can just refer people to `--help`.

**Comment by andlaus** [comment]
#1599 fixes that.

**Comment by OPMUSER** [comment]
Is  `--ecl-output-dir` deprecated   as it is missing from -help and the *.PRT and *DBG files?

**Comment by OPMUSER** [comment]
Ignore my last comment as it has changed to ` --output-dir`

**Comment by OPMUSER** [comment]
@andlaus I have documented the command line parameters based on RC1 and you comments. 

Thank you.

**Comment by andlaus** [comment]
You're welcome. I'll close this issue for now, if there are further questions, feel free to add them here..
