### ISSUE TITLE
Spurious output on well productivity index

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1619]
Since the week-end there is a lot of noise regarding well productivity index in the terminal output. It looks like this:
```
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
The effective radius is larger then the well drainage radius for well B-4H They are set to equal in the well productivity index calculations
```

**Comment by GitPaean** [comment]
Yes. It is a too large of amount, which makes the .DBG file and .PRT file difficult to analyze.

**Comment by totto82** [comment]
That's my fault. It should be fixed in OPM/opm-simulators#1614

**Comment by totto82** [comment]
In the terminal the output is terminated after 10 messages. I assumed the same was true for the .DBG and .PRT file, but I was wrong. Why don't we limit the number of equal messages for the log files?

**Comment by GitPaean** [comment]
> Why don't we limit the number of equal messages for the log files?

Maybe for debugging purposes, we do not want to miss some debugging information? while for screen output, we do not want to scare user away.

**Comment by totto82** [comment]
This is still an issue for models that are supposed to output well productivity index. @atgeirr Is is possible to make the output to .DBG stop after for instance 10 messages? An alternative is to make a internal logic that makes sure the message is only printed once.

**Comment by GitPaean** [comment]
Maybe you can output a summary for each well instead of each perforation, or a statistical summary for each report step.

**Comment by atgeirr** [comment]
> This is still an issue for models that are supposed to output well productivity index. @atgeirr Is is possible to make the output to .DBG stop after for instance 10 messages?

Yes, but this is a bad idea, since it will apply to all messages of the same severity category. The intention with the debug log was to skip no messages there.

> An alternative is to make a internal logic that makes sure the message is only printed once.

I think this is a better idea.
