### ISSUE TITLE
Parameter File Comment Not Working (2018-10)

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1628]
Previously it was possible to place comments in the parameter file using // a comment indicator at the beginning of the line, for example:
```
// 
// OPMRUN Parameter File 
// 
// File Name   : "/media/sf_D_DRIVE/User/BaxendaleD/Development/Python/Examples/SPE01-THEM01-OPM1810-R01.param"
// Created By  : david
// Date Created: 2018-11-14 10:10:50
// 
dbhp-max-rel=1
dp-max-rel=0.3
ds-max=0.2
dwell-fraction-max=0.2
ecl-deck-file-name="SPE01-THEM01-OPM1810-R01.DATA" 
```
This now gives:
```
david@EIPC02-VirtualBox:/media/sf_D_DRIVE/User/BaxendaleD/Development/Python/Examples$ flow --parameter-file='SPE01-THEM01-OPM1810-R01.param'
terminate called after throwing an instance of 'std::runtime_error'
  what():  SPE01-THEM01-OPM1810-R01.param:1: Parameter name '//' is invalid: First character must be a letter
Aborted (core dumped)
```

**Comment by andlaus** [comment]
the way to specify comments in almost everything is to use a hash character (`#`). Windows-style INI files use semicolons (';') instead, so this is also supported by OPM.

**Comment by OPMUSER** [comment]
Thank you for responding.

Okay this works for 2018-10, but 2018-04 users // as the comment. I'll update the manual accordingly for the next release of the manual
