### ISSUE TITLE
master branch broken?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1635]
```
1809 /home/kaib/OPM-test/debug/opm-simulators/opm/autodiff/FlowMainEbos.hpp:534:73:   required from ‘void Opm::FlowMainEbos<TypeTag>::runSimulator() [with TypeTag = Ewoms::Properties::TTag::EclFlowProblem]’
1810 /home/kaib/OPM-test/debug/opm-simulators/opm/autodiff/FlowMainEbos.hpp:234:29:   required from ‘int Opm::FlowMainEbos<TypeTag>::execute(int, char**) [with TypeTag = Ewoms::Properties::TTag::EclFlowProblem]’
1811 /home/kaib/OPM-test/debug/opm-simulators/flow/flow_ebos_blackoil.cpp:59:39:   required from here
1812 /home/kaib/OPM-test/debug/ewoms/ewoms/linear/matrixblock.hh:212:46: error: ‘typedef class Dune::FieldMatrix<double, 3, 3> Ewoms::MatrixBlock<double, 3, 3>::BaseType’ is private
1813      typedef Dune::FieldMatrix<Scalar, n, m>  BaseType;
1814                                               ^
1815 /home/kaib/OPM-test/debug/ewoms/ewoms/linear/matrixblock.hh:255:8: error: within this context
1816  struct MatrixDimension<Ewoms::MatrixBlock<Scalar, n, m> >
```

**Comment by GitPaean** [comment]
the related commit is bde227f4126b3bfeebb75a252409adb3f3bc488f ?

**Comment by GitPaean** [comment]
my dune version is 2.4.1 . Please let me know if it is something too old for OPM already.

**Comment by dr-robertk** [comment]
As I pointed out in the other PR it works for me. I'm using all master, including DUNE. So maybe the difference is buried somewhere there. BTW, DUNE 2.4 is ancient. I advise to upgrade to 2.6

**Comment by GitPaean** [comment]
okay. It is fine for the OPM upgrade with newer dune version. I think OPM can stop supporting DUNE2.4.1 when OPM decide not to support Ubuntu 16.04.

**Comment by dr-robertk** [comment]
Then I suggest that you upgrade to ubuntu 18.04 ;-)

**Comment by GitPaean** [comment]
With dune 2.5.2 
It is different error messages. 
```
163 In file included from /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/NewtonIterationBlackoilInterleaved.cpp:39:0:
164 /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/ISTLSolver.hpp: In member function ‘void Opm::ISTLSolver<MatrixBlockType, VectorBlockType, pressureIndex>::solve(Opm::ISTLSolver<MatrixBlockType, VectorBlockType, pre    ssureIndex>::Matrix&, Opm::ISTLSolver<MatrixBlockType, VectorBlockType, pressureIndex>::Vector&, Opm::ISTLSolver<MatrixBlockType, VectorBlockType, pressureIndex>::Vector&) const’:
165 /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/ISTLSolver.hpp:287:55: error: ‘ParallelISTLInformation’ was not declared in this scope
166              if (parallelInformation_.type() == typeid(ParallelISTLInformation))
167                                                        ^
168 /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/ISTLSolver.hpp:290:23: error: ‘ParallelISTLInformation’ does not name a type
169                  const ParallelISTLInformation& info =
170                        ^
171 /home/kaib/OPM-master-test/debug/opm-simulators/opm/autodiff/ISTLSolver.hpp:292:31: error: ‘info’ was not declared in this scope
172                  Comm istlComm(info.communicator());
173                                ^
```

**Comment by dr-robertk** [comment]
Fixed by https://github.com/OPM/ewoms/pull/429

**Comment by GitPaean** [comment]
The above error message with DUNE 2.5.2 is not related to OPM/ewoms#429 . Can be a problem of my own build of DUNE unless some people see the same. 

Will test it again with rebuilt DUNE again later when finding time.

**Comment by dr-robertk** [comment]
The corresponding patch was merged, closing.

**Comment by GitPaean** [comment]
> the latest issue above is caused by some now-mandatory header files not being included by ISTLSolverEbos.hpp. They have become mandatory because of the recent legacy-related cleanup. The problem is that what's mandatory is highly dependent on the concrete configuration...

Thanks for the information. When I find time (probably next month), I will do some experiments with it.

**Comment by blattms** [comment]
> Then I suggest that you upgrade to ubuntu 18.04 ;-)

We should not suggest broken (in the sense of MPI not working) ubuntu versions.

**Comment by dr-robertk** [comment]
Good point. Then we should wait for 20.04 ;-). I guess the MPI version in ubuntu 18.04 will be fixed a some point. I will also check if we can provide newer DUNE packages for the existing ubuntu versions.
