### ISSUE TITLE
WCONINJH wells ignore the WELTARG BHP

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1645]
It is found during a recent debugging. It is a bug should be fixed.

Otherwise, it will get something like xxxe+308 BHP limit, when under this control, the simulation basically needs to shut down.

**Comment by GitPaean** [comment]
Have not looked at it. It might need help from both parser and simulator.

**Comment by GitPaean** [comment]
this issue should be fixed by https://github.com/OPM/opm-simulators/pull/1362 and OPM/opm-common#593

**Comment by gcardozo123** [comment]
Hi, 
sorry for commenting in a closed issue, but was this happening with `WCONPROD` wells too?
