### ISSUE TITLE
Heads up: Libecl update required

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1667]
[ Sorry for spamming - I have tried sending this message to mailing list, but it does not seem to go through?]

I am now merging this libecl PR: https://github.com/Statoil/libecl/pull/538 and the accompanying PR in opm-common: https://github.com/OPM/opm-common/pull/575. After this you must fetch an updated version of libecl to build opm-common.

**Comment by GitPaean** [comment]
Small question. How to specify the ECL folder in cmake? Thanks.

**Comment by joakim-hove** [comment]
When compiling opm? Personally I prefer to install things and not rely on the sibling features. Then it is plain cmake all the way - pass `-DCMAKE_INSTALL_PREFIX=/some/path`  when configuring libecl, make sure to install with `make install` and configure opm-common with `-DCMAKE_PREFIX_PATH=/some/path`.

**Comment by GitPaean** [comment]
> When compiling opm?

Yes. I do use installed almost all the time, while I had some old development which relies on a old version of OPM and also libecl. I need them to be running to help debugging.

**Comment by blattms** [comment]
When using installed modules
+ If you absolutely insist you can set the CMake variable ecl_DIR to the place where eclConfig.cmake is located (Should be <install-dir>/share/cmake/ecl)
+ Preferably you use a consistent CMAKE_INSTALL_PREFIX and CMake should be smart enough to search there for libEcl. If I am mistaking (I hope not!), then you would need to set CMAKE_PREFIX_PATH to where you installed.

If you can live with uninstalled modules. Then just use the same source/build directory as for you opm modules and the right libecl will be found. (i.e. libecl is in the same directory where the opm modules are and you build int the same subdirectory, e.g.  libecl/build  and opm-common/build, ...)

**Comment by blattms** [comment]
heads up from 2018 is old news. closing
