### ISSUE TITLE
In what condition production rate differs from the one specified in WCONHIST?

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-simulators#1669]
In what condition production rate would differ from the one specified in WCONHIST?

I use WCONHIST with ORAT to specify oil production rate, but WORP and WOPRH are somehow different (below).  How can this happen in OPM? I use version 2017.04.

<img width="660" alt="screen shot 2018-12-02 at 4 38 17 pm" src="https://user-images.githubusercontent.com/24484961/49337128-af61b480-f651-11e8-9863-837167d1b769.png">

They are same in an ECL simulation.  
<img width="536" alt="screen shot 2018-12-02 at 4 50 26 pm" src="https://user-images.githubusercontent.com/24484961/49337175-7a099680-f652-11e8-8bb9-09930411dd6b.png">

**Comment by sogoogos** [comment]
I mean does someone have any idea what makes this happen?

**Comment by atgeirr** [comment]
I have two preliminary comments:
 - The ECL and OPM simulation results seem quite similar (hard to tell exactly without plotting in same diagram). The only difference is the WOPRH reported by OPM, we may have a bug related to its output.
 - The version you used is quite old, can you confirm if the current release version has the same behaviour?

**Comment by atgeirr** [comment]
I just ran a small test case derived from SPE1, and observed no difference between WOPR and WOPRH when running the well under ORAT history control, so it seems likely to me that this has been resolved in newer versions of OPM Flow. If this is not the case, please report, and we will try to reproduce the error and fix it.

**Comment by GitPaean** [comment]
@sogoogos , I am closing this issue for now. If the problem still exists, feel free to re-open the issue.
