### ISSUE TITLE
Wrong Include Syntax?

### ISSUE THREAD

**Issue by fgfuchs** [OPM/opm-simulators#1700]
According to 
https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html,
#include "file" should be used instead of #include \<file\> for header files of your own program.

**Comment by andlaus** [comment]
this is a matter of preference: opm-material and eWoms use quoted includes if the included file is closely releated with the includer (use common sense to determine boundaries), while the other OPM modules use a strict angle-brackets-only policy (except for config.h).

**Comment by atgeirr** [comment]
I have long advocated for angle brackets, but I am willing to change my mind if *thoroughly* convinced... It is probably possible to make counterintuitive examples, with either syntax.

**Comment by blattms** [comment]
No they do not.

Any header that is part of the current module might be considered a system header. A user might install opm-common to a different location then opm-material. There might be a header in opm-material that includes one in opm-common. How should that be done to make them found in this case by only including the one in opm-material if we use double quotes there?

I would intrepret non-system headersused by your program as all headers in the same codbase/module only. Program is only the *.cpp file (e.g. flow.cpp). Hence one can include all header in *.cpp using the quoted option but never in a header that might included somewhere else.

**Comment by andlaus** [comment]
I think @fgfuchs is right: for all practical purposes, the difference between the two is that the quoted include style adds the directory where the includer is located as the first entry of the list of search paths, the pointy-bracket style does not. hence if you do not change the *relative* location of the files during install, quoted includes will work just as fine as pointy ones (of course if you have naming collisions -- like config.h -- things may be different). personally, I read quoted includes as "this is very closely related to me and may contain some of my implementational details" and angled ones as <provides some infrastructure and I'm not interested in the implementational details>, but this is not a technical difference mandated by the C++ standard.

note that in my personal list of things we should worry about code this one comes on the *very* low end.

**Comment by GitPaean** [comment]
following https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html , I think the current implementation of using `<>` for `#include` is okay, although  both ways will work. 

`
By default, the preprocessor looks for header files included by the quote form of the directive #include "file" first relative to the directory of the current file, and then in a preconfigured list of standard system directories. For example, if /usr/include/sys/stat.h contains #include "types.h", GCC looks for types.h first in /usr/include/sys, then in its usual search path.
`

`
For the angle-bracket form #include <file>, the preprocessor’s default behavior is to look only in the standard system directories. The exact search directory list depends on the target system, how GCC is configured, and where it is installed. 
`

**Comment by atgeirr** [comment]
> Hence one can include all header in *.cpp using the quoted option but never in a header that might included somewhere else.

I guess this is an insight I was missing: we should always use angle brackets in hpp files, but may use quotes in cpp files. Not wanting to distinguish between public and private headers, and wanting a single simple rule, I end up with the "angle brackets everywhere" recommendation.

Thanks for the discussion, I do not think we have seen sufficient evidence to force a change here, so I will close the issue. Reopen only if you have some amazing insight or reference...
