### ISSUE TITLE
A process with 0 cells gets stuck forever

### ISSUE THREAD

**Issue by fgfuchs** [OPM/opm-simulators#1726]
Running `mpirun -np 11 ./bin/flow {...}/polymer_injectivity/2D_POLYMER_INJECTIVITY.DATA`
Gets stuck after

Manually moving well INJE01 to partition 2
Manually moving well PROD01 to partition 1
After loadbalancing process 0 has 0 cells.
After loadbalancing process 6 has 18 cells.
After loadbalancing process 7 has 14 cells.
After loadbalancing process 8 has 18 cells.
After loadbalancing process 10 has 18 cells.
After loadbalancing process 5 has 20 cells.
After loadbalancing process 9 has 20 cells.
After loadbalancing process 1 has 25 cells.
After loadbalancing process 3 has 20 cells.
After loadbalancing process 2 has 35 cells.

My bet is that a process with 0 cells causes the deadlock.

This only happens, when at least one process has 0 cells. For `mpirun -np 7` it works fine, for instance.

**Comment by blattms** [comment]
Would you mind providing a sample deck that triggers this?

**Comment by andlaus** [comment]
0 cells on rank? I guess you should use a larger deck with this many processes...

**Comment by fgfuchs** [comment]
I wouldn't, but I am not sure what that a "deck" is, or how to create it.

**Comment by fgfuchs** [comment]
I agree that it is a corner case that a process has 0 cells, but it would be nice that the computation wouldn't stall. My guess is that it probably is not too hard to fix.

**Comment by andlaus** [comment]
> I wouldn't, but I am not sure what that a "deck" is, or how to create it.

in this case I meant the .DATA file from which the grid is generated. (i.e., `{...}/polymer_injectivity/2D_POLYMER_INJECTIVITY.DATA`)

> I agree that it is a corner case that a process has 0 cells, but it would be nice that the computation wouldn't stall. My guess is that it probably is not too hard to fix.

I agree. maybe the simulator should even abort if it encounters partitions smaller than N cells? (with N ~ 1000.)

BTW: do you have ZOLTAN installed? without it, the grid partitioning gets very bad very quickly...

**Comment by fgfuchs** [comment]
yes, ZOLTAN is installed :)

**Comment by fgfuchs** [comment]
For testing it is good to allow for processes with only few cells.

**Comment by andlaus** [comment]
sequentially, I agree. As far as I can see, there's no point in using MPI for such cases even in testing, though.

**Comment by fgfuchs** [comment]
Depends on what one wants to test. For me it is essential at the moment.

**Comment by fgfuchs** [comment]
For performance runs, I agree that N < 1000 on each partition could be a good thing.

**Comment by andlaus** [comment]
out of curiosity: what do you want to achieve?

**Comment by fgfuchs** [comment]
stability: No deadlock for such cases. Either abort with an error message, or get rid of the deadlock.

**Comment by andlaus** [comment]
Ok, so you'd be happy with an error message if a partition with less than 1000 cells is encountered in MPI runs?

**Comment by fgfuchs** [comment]
I think the current situation is unfortunate: One starts a run, and without seeing why, it never terminates. Only after some minutes one might come to the conclusion that this needs to be terminated manually. However, the reason can only be guessed at.

My personal opinion is that the number of processes should be up to the user, with an info message for less than 1000 cells or so, and a warning for 0 cells. Maybe this should be discussed in one of the next meetings?

**Comment by atgeirr** [comment]
> My personal opinion is that the number of processes should be up to the user, with an info message for less than 1000 cells or so, and a warning for 0 cells. Maybe this should be discussed in one of the next meetings?

I agree at least to printing a warning for 0 cells, and most importantly: do not deadlock.

**Comment by blattms** [comment]
I guess we should open a new bug report as aborting if there is a
process with 0 cells is not what we want in the long term.
