### ISSUE TITLE
the running tests will not be able to pass after upgrading system

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#1755]
I just upgraded my computer from Linux Mint based on (Ubuntu16.04, gcc/g++ version is 5.5) to be Linux Mint 19.1 (based on Ubuntu 18.04). The gcc/g++ version is 7.3 now. 

I tested with the same version of dune. 

Under the old system, I never had problem to make the running test go through. 

With the new system, a lot of running test based on flow failed. 

I posted this issue to wonder whether someone else also had this problem or are there some solution to fix them?

Thanks.

**Comment by GitPaean** [comment]
following a discussion with @fgfuchs , it looks like he also has the same problem. The compiler version on his computer is gcc 8.3, something like that. 

Maybe we should discuss to relax some tolerance for comparison so the local test can be passed easier. 

Jenkins might should keep the original more stricter tolerance since the configuration of Jenkins does not change much?

**Comment by fgfuchs** [comment]
my compiler version is 8.2.1

**Comment by GitPaean** [comment]
It might not be the version of the compiler that makes the difference. I tried several version of linux mint without success.

**Comment by GitPaean** [comment]
Removing some compilation options `-march=native -mtune=native` makes things much better, while still one tests failed and with some examples, the `residual history` is slightly different.
