### ISSUE TITLE
End-point scaling not supported for 2 phase problem

### ISSUE THREAD

**Issue by sogoogos** [OPM/opm-simulators#1759]
Currently OPM does not support end-point scaling (such as `KRW`, `KRWR`, `SWU`, `SOWCR` etc) for 2 (oil/water) phase problem, but 3 phase. It just gives the following error if you try:
```
Exception caught: Saturations function must be specified using either family 1 or family 2 keywords Use either SGOF (or SLGOF) and SWOF or SGFN, SWFN and SOF3
```
Is there any plans that this will be supported? It sounds not too hard to do that since the end-point scaling feature is already implemented in 3 phase problem.

**Comment by bska** [comment]
> Is there any plans that this will be supported?

None that I know, but I also don't have full overview of all the ongoing activities.

> It sounds not too hard to do that since the end-point scaling feature is already implemented in 3 phase problem.

The code that initialises the entire end-point scaling feature basically assumes a three-phase system.  Reviewing it now I also notice some questionable logic for vertical scaling (especially three-point scaling using `KRWR` and similar keywords.)  Untangling this is regrettably nontrivial.

**Comment by bska** [comment]
@sogoogos : I believe we've finally solved this issue and that we now support end-point scaling in two-phase runs.  I'm therefore closing this now.  Please open a new issue if you notice any missing features.
