### ISSUE TITLE
FMTOUT Keyword Not Working for FEGRID Files (2018-10)

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1784]
The FMTOUT keyword in the RUNSPEC section instructs OPM Flow to write the grid data in formatted output to the *.FEGRID file. The file is created but the file format is unformatted (binary) instead of formatted.

Also the INIT index file FINSPEC is not written at all when the FMTOUT keyword is activated.

**Comment by OPMUSER** [comment]
Also don't forget that the FINSPEC file is not written out when the FMTOUT keyword is activated.

**Comment by joakim-hove** [comment]
I agree with all of @bska analysis - the fix should be simple, a bit uncertain of the value though? 

When it comes to the FINSPEC file I think your analysis is misleading - we *never* write an INSPEC file, formatted or not.

**Comment by bska** [comment]
> we _never_ write an INSPEC file, formatted or not.

Ah, right.  That said, in my recent work on restart files it's become clear to me that **most** of the information in the INSPEC (and RSSPEC) files should be mostly straightforward to generate from OPM Flow.  The sticky point is the `POINTER` and `POINTERB` arrays, which sadly are also about 85 percent (my guess) of the reason that those files exist in the first place.  You can get close using the `std::ofstream::tellp()` member function, but it's not clear to me that that function solves all of the associated issues.

**Comment by bska** [comment]
Quick update: My pull request equinor/libecl#610 was merged into LibECL's master branch.  Depending on the release manager's judgement that may mean that it becomes part of OPM's 2019.04 release in which case OPM Flow will create a formatted grid file (i.e., a proper `*.FEGRID` file) when the `.DATA` file requests `FMTOUT`.

**Comment by OPMUSER** [comment]
@bska fantastic, one less bug to worry about. I'll close this issue and open a separate one for the missing INSPEC file, so we can keep track of that issue.
