### ISSUE TITLE
Why does ISTLSolverEbos::prepare copy the matrix from Ebos?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1786]
I am having a hard understanding why this copy is there (or needed). AFAIK ebos will reuse its matrix object and the adress of `M.istlMatrix()` should not change (at least for flow and as long as we
do not use and AuxiliaryModules that change between time steps). 

In a parallel run we even make another copy that we use to impose Dirchlet boundary conditions in the overlap. (I would even assume that this could be done  directly on `M.istlMatrix()` without any impact outide of the linear solve).

what am I missing?

**Comment by atgeirr** [comment]
This was introduced in #1757, probably a bit over-cautious. I agree removing it should be ok.

**Comment by bska** [comment]
@atgeirr , @blattms : Did anything happen here?

**Comment by atgeirr** [comment]
The copying is no longer done. Closing.
