### ISSUE TITLE
2019-04-RC End-Point Arrays Missing from *.INIT

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1797]
The Norne model users end-point scaling, but the end-point arrays (SWL,SWU, etc. and the SWATINIT array) are not written to the *.INIT see #1738.

**Comment by OPMUSER** [comment]
Still missing from RC2

**Comment by bska** [comment]
@OPMUSER : As of PR OPM/opm-common#849 merged into master a few hours ago as of this writing we now output a common subset of the end-point arrays to Flow's `.INIT` file.  Specifically, we output drainage and imbibtion curve end-points but do not currently support directionally dependent end-points (e.g., `SGCRX-`). We also support `FILLEPS` to output the actual end-points, whether taken from direct assignment in the deck or derived from the corresponding saturation function table.

I believe we&mdash;meaning OPM Flow&mdash;don't correctly (or at all) handle `TOLCRIT` which will affect `*CR` end-points derived from the tables, but at least we're much closer to having a working system now.  PR OPM/opm-common#849 also activates the pertinent flags in the INIT file's `LOGIHEAD` vector which means that the ResInsight relative permeability plot is now able to distinguish the scaled from the unscaled curves in a cell even for result sets generated by OPM Flow.

This support is in master now and will become part of the next public release of OPM too. Thank you for prodding this issue regularly.  OPM Flow is better for it.

**Comment by OPMUSER** [comment]
You have just made one RE, and probably lots more, very happy campers :-)
