### ISSUE TITLE
initBlackoilStateFromDeck with RS,RV

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-simulators#180]
Hi
This afternoon(Beijing time) the KW RS and RV bothering me a lot, the problem is that. In ECLIPSE, if you don't specify **DISGAS** and **VAPOIL**, you **can't** use **RS** and **RV** to do the initialization, even you set all the values are 0, i.e 

```
RS
 113344*0/
RV
 113344*0/
```

But in OPM, even if there are no **DISGAS**, **VAPOIL** in deck file,  you must set

```
RS
 113344*0/
RV
 113344*0/
```

if you don't set, the problem is coming.

```
> #3  0x0000000000638621 in 
> Opm::initBlackoilStateFromDeck<Opm::UgGridHelpers::FaceCellsProxy, 
> double*, double*, Opm::BlackoilPropertiesInterface, 
> Opm::BlackoilState> ()
```

**Comment by atgeirr** [comment]
Did you find a solution to this, or does the problem remain?

**Comment by qilicun** [comment]
Sorry, I have forgot this issue... I think this happened when I debug Norne, to be honest, I didn't check it anymore after that, so I'm not sure whether OPM can behave as expected.

**Comment by atgeirr** [comment]
Let's leave it open then, but call it a noncritical issue (for the release).

**Comment by andlaus** [comment]
we I think we need to test if this still applies. If yes, the fix should be quite easy.

**Comment by totto82** [comment]
I have tested various variants of SPE1 and SPE3 with and without VAPOIL and DISGAS. And this seems to not be an issue anymore. It fails if VAPOIL is present but not RV. And don't  fail if both RV and VAPOIL is not present. i.e it behave as expected I think.

**Comment by atgeirr** [comment]
> I have tested various variants of SPE1 and SPE3 with and without VAPOIL and DISGAS. And this seems to not be an issue anymore. It fails if VAPOIL is present but not RV. And don't fail if both RV and VAPOIL is not present. i.e it behave as expected I think.

OK closing!
