### ISSUE TITLE
Transmissibilities written wrong

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#1851]
It seems like we are writing them to arrays using the cartesian index as exported by our grids (e.g. CpGrid). I.e. i is the fastest and k is the slowest running index. This is not the index assumed by Eclipse (k is fastest running index here). Hence, unless libecl does some reordering magic (which I highly doubt), the transmissibilities written must be wrong.

Can someone confirm that there is reordering in the output layer?

This was detected while working on #1848.

**Comment by bska** [comment]
> It seems like we are writing them to arrays using the cartesian index as exported by our grids (e.g. CpGrid). I.e. i is the fastest and k is the slowest running index

Yes, that's probably true.

> This is not the index assumed by Eclipse (k is fastest running index here).

I don't understand that sentence.  The convention in ECLIPSE is that the linear index follows the natural ordering
```
Ix = I + Nx*(J-1 + Ny*(K-1))
```
with `(I,J,K)` being one-based indices in the ranges `1..Nx`, `1..Ny`, and `1..Nz` respectively.  This is inspired by the typical Fortran loop nest
```fortran
Do K = 1, Nz
    Do J = 1, Ny
        Do I = 1, Nx
            use (I,J,K)
        End Do
    End Do
End Do
```
Moreover, the `TRANX` vector is documented as
```
Grid blocks are ordered with the X axis index cycling fastest,
followed by the Y and Z axis indices.
```
Are you saying that the convention is supposed to be reversed in the output?

**Comment by blattms** [comment]
Thanks for the clarification.
I guess, I was just saying nonsense.

**Comment by atgeirr** [comment]
Since NNCs are given explicitly with (from, to) logical cell coordinated, I would think that the order of TRANNNCs in the output should not matter as long as they match the NNCs given?

**Comment by blattms** [comment]
Thanks @bska for quoting the eclipse documentation. I did some debugging in the output code.

On the way to writing the values the TRANYXZ arrays are converted to compressed array [EclipseIO.cpp](https://github.com/OPM/opm-common/blob/272d0fc9a1491a5773cd9688fb53628732ef57a5/src/opm/output/eclipse/EclipseIO.cpp#L395), which then gets passed to  libecl for writing [here](https://github.com/OPM/opm-common/blob/272d0fc9a1491a5773cd9688fb53628732ef57a5/src/opm/output/eclipse/EclipseIO.cpp#L95). Somehow I have the impression that this writes a compressed array. Maybe @joakim-hove can confirm this? In that case this seems like a bug, but I am unsure where the bug actually is,

**Comment by joakim-hove** [comment]
> On the way to writing the values the TRANYXZ arrays are converted to compressed arrays at EclipseIO.cpp:395, which then gets passed to libecl for writing at EclipseIO.cpp:95. Somehow I have the impression that this writes a compressed array. Maybe @joakim-hove can confirm this?

Yes - I can confirm that the `TRANX`, `TRANY` and `TRANZ` vectors written where you indicate are indeed compressed. However - I don't think that is a bug, looking at [this INIT file](https://github.com/OPM/opm-tests/blob/master/norne/ECL.2014.2/NORNE_ATW2013.INIT) the `TRAN?` vectors are in compressed format - so to me there are no obvious bugs at least?

**Comment by blattms** [comment]
Thanks a lot.

**Comment by blattms** [comment]
Bug was in my script-
