### ISSUE TITLE
Negative rates anyone?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1889]
Hello;

in UDQ sequel flow now does something which resembles running (a slightly modified version of): https://github.com/OPM/opm-tests/blob/master/udq_actionx/UDQ_WCONPROD.DATA. The test case has the definitions:
```
UDQ
     WUOPRL   (WOPR OPL01 - 150) * 0.90/
/

WCONPROD
     'OPL02'  'OPEN' 'GRUP 'WUOPRL' .... /
/
```
i.e. UDQ named `WUOPRL` is defined as the 90% of OPR of well OPL01 minus 150, and that UDQ is used as target oil rate for well 'OPL02'. Initially the well 'OPL01' is closed with OPR == 0, hence the calculated UDQ used as control rate target for well OPL02 is negative, and flow crashes with:
```
 flow: /home/hove/work/OPM/opm-simulators/ebos/eclproblem.hh:1525: void Ewoms::EclProblem<TypeTag>::source(Ewoms::EclProblem<TypeTag>::RateVector&, const Context&, unsigned int, unsigned int) const ...
[with Context = Ewoms::FvBaseElementContext<Ewoms::Properties::TTag::EclFlowProblem>; TypeTag = Ewoms::Properties::TTag::EclFlowProblem; Ewoms::EclProblem<TypeTag>::RateVector = Ewoms::BlackOilRateVector<Ewoms::Properties::TTag::EclFlowProblem>]: Assertion `Opm::isfinite(rate[eqIdx])' failed.
Aborted
```
kind of fair enough? But of course the well renowned battleship eats negative rates for lunch and humps along with no problems, thank you very much, so I guess we also have to find a way. 

But exactly how should we treat negative target rates? It is of course trivial to add a `std::max(0, rate)` in the opm-common code[1], but that is maybe not the right place to enforce such policy?

[1]: I have tried that - and then flow actually seems to go through the case - with only minor modifications, which are actually of the same uncertain initialization nature.

**Comment by GitPaean** [comment]
If I understand correctly, UDQ created a WCONPROD , that has a negative oil target rate / limit? Then it is a question whether we should support it at all. Especially, since well 'OPL01' is closed, to me, it looks like corner case.  I will suggest to see how the commercial simulator handle this, then we can discuss how to handle it. 

We are having different opinions whether we should allow negative rates during solution, but your question is kind of different, the target, which we are trying to converge to, is a negative value.

**Comment by joakim-hove** [comment]
> If I understand correctly, UDQ created a WCONPROD , that has a negative oil target rate / limit

Yes

>  I will suggest to see how the commercial simulator handle this, then we can discuss how to handle it.

As I tried to indicate it humps along quite happily; I think if you plot UDQ variable well variables `WUOPRL:xxx` you will get the "correct" negative values, but how the well equations are converged internally I have no clue - but I guess there is a silent:
```
IF ( RATE .LT. 0.0 ) THEN 
       RATE = 0.0 
END IF
```
statement somewhere in the code.

**Comment by GitPaean** [comment]
> As I tried to indicate it humps along quite happily; I think if you plot UDQ variable well variables WUOPRL:xxx you will get the "correct" negative values

Can you plot the WOPR for the well that get negative oil target rate?

**Comment by joakim-hove** [comment]
> Can you plot the WOPR for the well that get negative oil target rate?

No I am sorry - I can not; I have just seen the results in an over-the-shoulder kind of way. I guess @tskille can come up with such plots - personally I would like if a reference solution was added to opm-tests.

**Comment by atgeirr** [comment]
I think the "compatible" answer here is probably to accept negative targets for well rates but interpret them as zero, i.e. in the input layer (the simulator only sees the zero target). I assume someone with access to Eclipse can run it to check that it behaves like that.

However there is another possible approach. Maybe, internally, all UDQs are ensured to be positive? I.e. the `var = max(0, var)` part is in the UDQ treatment, not the well controls? It seems unlikely but I think it cannot be ruled out until tested.

**Comment by GitPaean** [comment]
For WCONPROD, a zero rate target/limit basically means the well is close or shut (depending on whether crossflow is banned). 

A possible consequence for negative rate target/limit can be interpreted the well to be shut. 

Anyway, it will depends on our design, so a reference solution will help.

**Comment by joakim-hove** [comment]
> Maybe, internally, all UDQs are ensured to be positive?

No - that is certainly not the case. 

>to accept negative targets for well rates but interpret them as zero, i.e. in the input layer

That is a very comfortable solution - I am happy to implement that; I'll wait for qualified input though.
