### ISSUE TITLE
opm/autodiff - can we please remove/rename?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1894]
The code under "opm/autodiff/" - is it alive and kicking? Would be good if the file system entries could renamed, and if there is unused code there that should be deleted. 

For someone mainly working elsewhere it is not entirely clear which files are maintained and in use, and which are stale. Mixing two(?) simulators in here does not help ...

**Comment by GitPaean** [comment]
I think they are perfectly okay to be moved somewhere else, there are not much Autodiff things there at all.

**Comment by atgeirr** [comment]
There is no unused code (at least not much), most of what remains could be moved to opm/simulators/flow or something like that. The wells/ and linalg/ subdirs got most of the files that used to reside here.

**Comment by atgeirr** [comment]
I am going to do some light cleanup, so it will be emptier at least soon.

**Comment by atgeirr** [comment]
I have cleaned it up, but GitHub is failing trying to create a PR today. Anyway it is in the "cleanup-autodiff" branch on my github clone.

**Comment by bska** [comment]
> it is in the "cleanup-autodiff" branch on my github clone.

Okay.  Would you mind rebasing it on top of current master?

**Comment by bska** [comment]
> it is in the "cleanup-autodiff" branch on my github clone.

Okay.  Would you mind rebasing it on top of current master?

**Comment by atgeirr** [comment]
> Okay. Would you mind rebasing it on top of current master?

Done it. Github still not cooperating.

**Comment by bska** [comment]
> > Okay. Would you mind rebasing it on top of current master?
> 
> Done it. Github still not cooperating.

https://www.githubstatus.com/

**Comment by bska** [comment]
> > Okay. Would you mind rebasing it on top of current master?
> 
> Done it. Github still not cooperating.

https://www.githubstatus.com/

**Comment by atgeirr** [comment]
Finally... #1899

**Comment by joakim-hove** [comment]
Thank you.

**Comment by atgeirr** [comment]
Please merge #1899 if you are happy with it.
