### ISSUE TITLE
flow under valgrind - is it realistic?

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1906]
Hello;

as a f...ing desperate measure in trying to debug the test failures in https://github.com/OPM/opm-common/pull/774 i tried running the restarted flow under valgrind - that virtually basically exploded in warnings - I have not (yet at least) found anything which smells like the problem I am debugging. Do we consider running under valgrind as realistic?

**Comment by GitPaean** [comment]
I have not followed the problem in OPM/opm-common#774 . 

But my previous experience showed it is totally realistic, it has helped to find some real problems much quicker than checking code itself. 

The most recent one is https://github.com/OPM/opm-common/issues/815 .  

GDB basically pointed to the wrong place while valgrind pointed to the real cause.
