### ISSUE TITLE
COMPLUMP Not Supported?

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1929]
This took a while to figure out why the wells were not producing. The manual says the keyword COMPLUMP is implemented, but ecl-strict-parsing=true says it is not.

Easy enough to change the manual, but this is a common keyword that is used to group connections, so it would be beneficail to implement this keyword.

**Comment by bska** [comment]
> The manual says the keyword COMPLUMP is implemented, but ecl-strict-parsing=true says it is not.

Thanks for the report.  There is definitely some confusion in this area.  First, Flow does support (some?) of the `COMPLUMP` functionality.  For instance, the [3D_WECON_TEST](https://github.com/OPM/opm-tests/blob/5969ec63b4b0f61779d8e845e6d2e6b00d735a92/wecon_wtest/3D_WECON.DATA) in the opm-tests repository&mdash;part of Flow's regression test suite&mdash;uses [`COMPLUMP`](https://github.com/OPM/opm-tests/blob/5969ec63b4b0f61779d8e845e6d2e6b00d735a92/wecon_wtest/3D_WECON.DATA#L194-L197) for one of its wells, albeit in a rather limited fashion.  The COMPLUMP usage here was added in PR OPM/opm-tests#33.  Secondly, `COMPLUMP` was regrettably classified as "unsupported" in `ecl-strict-parsing=true` until very recent.  I removed the misclassification in PR #1876, but this was after the 2019.04 release.

Your issue may well be related to COMPLUMP, but on the other hand COMPLUMP may not be the only contributing factor.

**Comment by OPMUSER** [comment]
I still cannot get the wells to flow, even when I use:

```
-- -- WELL PRODUCTION STATUS - OPEN SELECTED COMPLETIONS                   
--                                                                              
--  WELL    WELL   --LOCATION--  COMPLETION                                     
--  NAME    STAT     I   J    K  FIRST LAST                                     
WELOPEN                                                                         
'GP05'      OPEN                                                               /
'GP05'      OPEN     0   0    0   140  237                                     /
          
'GP08'      OPEN                                                               /
'GP08'      OPEN     0   0    0   151  237                                     /
          
'GI-D01'    OPEN                                                               /
'GI-D01'    OPEN     0   0    0    1   114                                     /
/

```
or
```

--
--       WELL CONNECTION DATA                           
--                                                                              
-- WELL  --- LOCATION ---  OPEN   SAT   CONN   WELL   KH    SKIN   D     DIR   
-- NAME   II  JJ  K1  K2   SHUT   TAB   FACT   DIA    FACT  FACT   FACT  PEN   
COMPDAT                                                                        
'GP05'    1*  1* 140 237   OPEN   1*    1*    0.708  1*    0.0    1*    'Z'    /
'GP08'    1*  1* 151 237   OPEN   1*    1*    0.708  1*    0.0    1*    'Z'    /
'GI-D01'  1*  1*   1 114   OPEN   1*    1*    0.708  1*    0.0    1*    'Z'    /
/               
```       
I have commented out the group controls, just in case that was the issue. It looks like the well or completions are not being opened. 

Note all wells and completions are SHUT in the include files, and then after that I OPEN the selected wells and completions. Everything is in the one time step - could that be the problem?

In the commercial simulator, there is a WELSPECS report and other reports where you can see what connections are open, so are there any debug switches that can print out the status of the connections?

**Comment by joakim-hove** [comment]
> The manual says the keyword COMPLUMP is implemented

The basic functionality of the `COMPLUMP` keyword - i.e. grouping connections together under a common ID *is* supported, however subsequently keywords must be "completion aware" - and there might be missing functionality there ...

**Comment by joakim-hove** [comment]
> however subsequently keywords must be "completion aware"

OK - I have looked into the `WELOPEN` implementation - there are certainly several problems with the `COMPLUMP` handling in the `WELOPEN` keyword; there might be more problems - but at least this is problematic:
```
WELOPEN                                                                         
...
'GP05'      OPEN     0   0    0   140  237                                     /
...
```
The connections at `I=0, J=0, K=0` are *not* treated as defaults by flow - then you should use `3*` instead. There are two reasons why the `0 0 0` values are not treated as defaults: First of all - the manual says that a negative value is the default - i.e. the `0` is actually not the default, but more important is the slightly philosofical question: 

Should a '*' in the deck and manually entering the default value explicitly be differentiated? flow is not 100% consistent on this - but the preference is certainly on treating them differently, a `*` to signal "I want the default value" has higher semantic value than entering the explicit default value manually, but I realize opinions might be split on this.

So - I would try replacing your `0` values with `*`, but I will not guarantee that is enough ... :-(

**Comment by GitPaean** [comment]
> The connections at I=0, J=0, K=0 are not treated as defaults by flow 

I believe it is a inconsistency in the manual and we can fix from our end in OPM.  It is said later `zero or negative value` will match any value as location index.  Either we treat `0` or `negative` value separately or not, they should have same behavoir.   If we do not handle `0` value here, we will have the same problem again and again.

**Comment by joakim-hove** [comment]
> If we do not handle 0 value here

We handle the `0`

**Comment by GitPaean** [comment]
> We handle the 0

Okay. Sorry for not finishing reading your update.

**Comment by GitPaean** [comment]
@OPMUSER , I am not the one implemented COMPLUMP, while I did something related recently. 

If your case can be shared, I can try to re-produce your problem and let you know what is going on with your deck. It can be something missing in OPM. My email is kai.bao@sintef.no

**Comment by OPMUSER** [comment]
Okay I spent some time looking at this and I don't think it is a COMPLUMP issue take a look at #1932.
It appears that if well is SHUT and all its completions are SHUT, the well cannot be put back on production.

**Comment by OPMUSER** [comment]
Will close this as it appears to be symptom rather than issue - see #1932.
