### ISSUE TITLE
Cannot Initialize Dry Gas Run

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2029]
One cannot initialize a dry gas run because the the RVCONST and the RVCONSTT keywords are not supported, even though the dry gas PVDG table is recognized.

Is this a known issue?

Test deck attached.
[GASW-BASE01-OPM1904-R01.zip](https://github.com/OPM/opm-simulators/files/3666454/GASW-BASE01-OPM1904-R01.zip)

**Comment by quagdoo** [comment]
I can verify that this is the case - I converted the Norne case and got an exception and very little info to check if I have made a mistake in the first place.

`Program threw an exception: Could not initialize the problem.`

In a Gas-Water system, the documentation says that RVCONST(T) are just for reporting so I suspect the fact that it doesn't initialise is a bit of bigger problem than these keywords. I've included my DATA deck. I guess the work-around is just use more physics and longer run times!

[NORNE_ATW2013_PVDG.DATA.gz](https://github.com/OPM/opm-simulators/files/4138236/NORNE_ATW2013_PVDG.DATA.gz)

**Comment by quagdoo** [comment]
The manual says the following is green (implemented):

> 8.3.200 PVDO – OIL PVT PROPERTIES FOR DEAD OIL

Could you provide a working example of a case where this works? Just so I can test it.

**Comment by bska** [comment]
### PVDO Example Models ###

The following models in [opm-tests](https://github.com/OPM/opm-tests/tree/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36) use `PVDO`:

* [`SPE1CASE2_2P.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe1/SPE1CASE2.DATA)
* [`SPE10_MODEL1.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe10model1/SPE10_MODEL1.DATA)
* [`SPE10_MODEL1_CP.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe10model1/SPE10_MODEL1_CP.DATA)
* [`SPE10_MODEL2.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe10model2/SPE10_MODEL2.DATA)
* [`SPE5CASE_GAS_EHYSTR2_0.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe5_ehystr2_0/SPE5CASE_GAS_EHYSTR2_0.DATA)
* [`SPE5CASE_SOLVENT_EHYSTR2_1.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe5_ehystr2_1/SPE5CASE_SOLVENT_EHYSTR2_1.DATA)

### PVDG Example Models ###

Similarly, the following models&mdash;and several more in the same resource directory&mdash;use `PVDG`:

* [`SPE1CASE2_OILGAS.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe1/SPE1CASE2_OILGAS.DATA)
* [`1_STDWELL_MODEL3.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/model3/1_STDWELL_MODEL3.DATA)
* [`SPE5CASE_SOLVENT_EHYSTR2_1.DATA`](https://github.com/OPM/opm-tests/blob/ec31f391d6ca8ebf3f251084bc5cdaf89fbddd36/spe5_ehystr2_1/SPE5CASE_SOLVENT_EHYSTR2_1.DATA)

Note however that none of these models use `RSCONST`, `RSCONSTT`, `RVCONST`, or `RVCONSTT`.

**Comment by OPMUSER** [comment]
To be clear, the problem is associated with the two phase case, just gas and water. Having dead oil in the model would make it a three phase problem.

**Comment by quagdoo** [comment]
Apologies OPMUSER is correct - my deleted comment on PVDO is not relevant to this case. It was confusing, so I deleted it.

All the models from bska are not gas/water simulations. The PVDG cases have dry gas PVT table but it is combined with dead oil PVDO table, making it three phases.

It should be possible to just run with WATER & GAS in the RUNSPEC and these cases are not initialising.

**Comment by goncalvesmachadoc** [comment]
@quagdoo Gas-water is not currently supported by OPM-flow.
