### ISSUE TITLE
Error "has no member named 'filename' "  when building this "opm-simulators" module 

### ISSUE THREAD

**Issue by G86char** [OPM/opm-simulators#2078]
Hi, when I built the "opm-simulators" module, there were errors with "MissingFeatures.cpp" file. 

I followed the instructions on the OPM website:

1. Installing the third-party libraries on the prerequisites page.
2. installing the "libecl" library
3. building the opm modules in the following order: opm-common, omp-matetial, opm-grid, and opm-models one by one. 

However, when I built the opm-simulators module,  the program failed.  
I copied the error messages as following:

***************************************************************************************************
```
OPM/opm-simulators/opm/simulators/flow/MissingFeatures.cpp: In function ‘void Opm::MissingFeatures::checkOptions(const Opm::DeckKeyword&, std::multimap<std::__cxx11::basic_string<char>, Opm::MissingFeatures::PartiallySupported<T> >&, const Opm::ParseContext&, Opm::ErrorGuard&)’:
OPM/opm-simulators/opm/simulators/flow/MissingFeatures.cpp:63:45: error: ‘const struct std::pair<std::__cxx11::basic_string<char>, long unsigned int>’ has no member named ‘filename’
                     + "In file " + location.filename + ", line " + std::to_stri
                                             ^
```
******************************************************************************************************

I used "git" to get the codes, and the OS is ubuntu 16.04.6, and the compiler is gcc 5.4.0.

Any suggestions about how to fix those errors ?   or Is there any wrong steps when I built the modules?   Thanks.

**Comment by joakim-hove** [comment]
> installing the "libecl" library

That is not needed any longer.

> However, when I built the opm-simulators module, the program failed. [...]

This code has changed very recently - my guess is that you have got a slightly too old version of opm-common; update that to screaming latest and greatest and things should work.

**Comment by G86char** [comment]
Hi, joakin-hove,  thanks for your comments.

I looked through the codes, and found that the problem "location" is a "pair" struct,  so I changed the code as following:  "location.filename"  ->  "location.first".    "location.lineno" -> "location.second".

Then I can build it successfully.  

I will update my "opm-common" module, and test it.

**Comment by atgeirr** [comment]
> I looked through the codes, and found that the problem "location" is a "pair" struct, so I changed the code as following: "location.filename" -> "location.first". "location.lineno" -> "location.second".
> 
> Then I can build it successfully.

This will fail again after you update opm-common, as this is precisely what was changed: location is now a custom class, and no longer just a pair. You will then have to roll back your change.

In general, OPM should compile and work if you check out (or update) all modules at the same time. Updating only one module will often lead to compile errors.

**Comment by G86char** [comment]
atgeirr, thanks so much for your explanation for this "location" class thing.  It is clear now. 

I just tried to git all the modules.  However, this time there was building issue at opm-grid module. 

I will git all modules tomorrow, and try some lucky.

**Comment by atgeirr** [comment]
> I just tried to git all the modules. However, this time there was building issue at opm-grid module.

A big pull request was just merged in opm-grid one hour ago, with a matching one in opm-simulators. If you were really unlucky you could have updated to see only one of them, but it is also possible you see a compile error that does not happen on our test server for some reason. Please post your compile error and I'll take a look.

**Comment by joakim-hove** [comment]
> I just tried to git all the modules. However, this time there was building issue at opm-grid module.

You have been unlucky; in general the master versions compile and work.

**Comment by G86char** [comment]
Hi, atgeirr and joakim-hove,

I just re-git all the modules and built them one by one following the instructions on the website.  And it works this time!    Great!    

It seems that I just git the codes at the wrong time.  

Thanks for your comments and help.  I do appreciate it.  

Let's close this issue.

**Comment by blattms** [comment]
Just for the record. I did experience the same error yesterday with up to date source but a stale build directories. The build system probably cannot determine that the dependency change needs a rebuild or does not do the dependency tracking correctly in some cases. With a clean build directory everything worked.
