### ISSUE TITLE
DUNE_FEM VERSION macros are not created during cmake for opm-simulators

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#2093]
This is one of the several causes that opm-simulators does not compile with dune-fem.

**Comment by akva2** [comment]
add here https://github.com/OPM/opm-simulators/blob/master/CMakeLists.txt#L83

**Comment by GitPaean** [comment]
Thanks. I will create the PR.

**Comment by blattms** [comment]
Seems like this is closed now. Was there a PR about this or should the changes be incorporated in #2098 ?

**Comment by blattms** [comment]
@akva2 Shouldn't the version information travel downstream? opm-models does have the version information available if dune-fem is found.

**Comment by akva2** [comment]
Well, these waters get muddy with header only libraries. You can build your opm-models with dune-fem, but your opm-simulators without, and those two are completely disconnected as such.

**Comment by GitPaean** [comment]
@blattms , the PR is here, https://github.com/OPM/opm-simulators/pull/2094 , which was merged already.
