### ISSUE TITLE
OPM Flow 2019-04 BOX Keyword Bug

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2097]
The Box statement is suppose to use 1* as a default parameter, for example:
```
--
--       DEFINE INPUT BOX FOR EDITING INPUT ARRAYS
--       
--       ---------- BOX ---------                
--       I1  I2   J1  J2   K1  K2                
BOX                                             
         1*  1*   1*  1*    3   3                          / DEFINE BOX AREA  
```
This works in the commercial simulator but OPM Flow aborts with:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
Aborted (core dumped)
```
If one explicitly sets the values instead of defaulting, for example:
```
--
--       DEFINE INPUT BOX FOR EDITING INPUT ARRAYS
--       
--       ---------- BOX ---------                
--       I1  I2   J1  J2   K1  K2                
BOX                                             
          1  20    1  1     3   3                          / DEFINE BOX AREA  
```
Then this works. It would good to fix this in the up coming release.

**Comment by joakim-hove** [comment]
Hmm - that was quite surprising; is this with version 2019.04?

Sorry about the stupid question: In the example you quote here the line with defaults is actually commented out - I assume that was a typo?

**Comment by OPMUSER** [comment]
Yes 2019-04 and yes a typo (corrected to avoid confusion)

**Comment by stefoss23** [comment]
I am not sure using the BOX keyword is supposed to be used this way, even if it works with Eclipse. 
The BOX keyword does not have any default values.
When using item1 = "1*", an std::vector<int> object of size 0 is assigned to item 1. When accessing the object with index 0, apparently expecting the size to be 1, it fails. 

Parsing this keyword with (* * * * 3 3) is OK, but it fails during initiation of EclipseState. 

Perhaps throwing a better phrases exception in  ```c++ T DeckItem::get( size_t index ) const``` would improve the error messaging?

**Comment by OPMUSER** [comment]
But 1* does work in the commercial simulator and should also work for ADD, EQUALS, MULTIPLY etc. as well. Using` * * * * 3  3` will fail in the commercial simulator as one needs to use` 1*` instead, or even `4*` to default the values. 

The default values are taken from the current BOX, so the first BOX statement should pickup the dimensions of the the model.

**Comment by stefoss23** [comment]
True, this should actually work for BOX 1* 1* 1* 1* 3 3 /.

**Comment by OPMUSER** [comment]
Works in 2019-10 RC3, closing - tusen tak
