### ISSUE TITLE
test_ParallelRestart fails for gcc 5.4.0 

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#2271]
Locally I get the follow error with master
```
/home/thsa/workspace/opm/opm-simulators/tests/test_ParallelRestart.cpp:1353:57: error: converting to ‘std::tuple<double, double, double>’ from initializer list would use explicit constructor ‘constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {double, double, double}; <template-parameter-2-2> = void; _Elements = {double, double, double}]’
```
I use gcc 5.4.0 with standard flags including -std=c++14

**Comment by bska** [comment]
> I use gcc 5.4.0 with standard flags including -std=c++14

Confirmed.  This is also partly the reason that our nightly Ubuntu "xenial" (16.04 LTS) build [currently fails](https://ci.opm-project.org/job/opm-nightly-xenial/215/console).

**Comment by akva2** [comment]
arf, the darn explicit constructor bites again. need to use std::make_tuple, working on it.
