### ISSUE TITLE
Parser Typo

### ISSUE THREAD

**Issue by quagdoo** [OPM/opm-simulators#2306]
Typo in ENDSCALE

File location [opm-common/src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDSCALE](https://github.com/OPM/opm-common/blob/5e546086fb5b326f4cde59642d294b62756f0edf/src/opm/parser/eclipse/share/keywords/000_Eclipse100/E/ENDSCALE#L3)
```json
{"name" : "IRREVERS"   , "value_type" : "STRING" , "default" : "REVER"}
```
should have a letter S at the end:
```json
{"name" : "IRREVERS"   , "value_type" : "STRING" , "default" : "REVERS"}
```
Result is that a warning is issued where is should not unless the wildcard `1*` is used instead.

**Comment by joakim-hove** [comment]
Thank you - I have let a fix hitch-haik here: https://github.com/OPM/opm-common/pull/1438
