### ISSUE TITLE
Ubuntu 18.04 packages are broken

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#2338]
Just a heads-up if any are bitten. The packages in the Ubuntu 18.04 ppa has been updated with Dune packages for version 2.6.0, but the OPM binaries have not been compiled against those yet. Hence, anybody who tries to follow our install recipe will get installation failure. Work-around (until the packages are recompiled against Dune 2.6.0) is to install Dune before the OPM ppa is added, then Dune 2.5.1 packages will already be installed, and the installation of OPM binaries should succeed.

**Comment by akva2** [comment]
this is now fixed.
