### ISSUE TITLE
Build fails with CMake 3.6

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#2375]
Cmake fails with the following message:

CMake Error at CMakeLists.txt:28 (if):
   if given arguments:
     "NOT" "CMAKE_DISABLE_FIND_PACKAGE_CUDA" "AND" "CMAKE_VERSION" "VERSION_GREATER_EQUAL" "3.8"
 
   Unknown arguments specified

**Comment by blattms** [comment]
Will take a look after lunch.
