### ISSUE TITLE
Parallel regression

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2410]
It seems like we have introduced a parallel regression between Monday and yesterday. See also the discussion in PR #2406. The deviation in the plots of Norne are very noticable and yet have not been discovered by our tests.

The branch off point of that PR is still working (both with the PR changes and without), that is

| module | commit |
|---|---|
| opm-common | OPM/opm-common@ab757c4a1 (HEAD -> master, upstream/master, upstream/HEAD) Merge pull request opm/opm-common#1528 from akva2/internalize_surface_conditions |
| opm-grid | OPM/opm-grid@cf10a7f22 (HEAD -> add-missing-loadbalance-with-datahandle, origin/add-missing-loadbalance-with-datahandle) Add missing loadBalance method taking data handle and egde weights. |
| opm-material | OPM/opm-material@0ac137f (HEAD -> master, upstream/master, upstream/HEAD) Merge pull request opm/opm-material#410 from akva2/use_state_surface_conditions |
| opm-models | OPM/opm-models@418e076bb (HEAD -> master, upstream/master, upstream/HEAD) Merge pull request opm/opm-models#596 from akva2/conditional_test_suite |
| opm-simulators | 1301e8062 (HEAD -> master, upstream/master) Merge pull request #2393 from akva2/serialize_surface_conditions |

Last perfect norne_parallel seems to be [PR 2386](https://ci.opm-project.org/job/opm-simulators-PR-builder/690/). @akva2 thinks that this might have been introduced in change to an module upstream to opm-simulators. I tend to agree.

[Good well plot of PR 2386](https://github.com/OPM/opm-simulators/files/4291666/plot_2386.pdf), 
[Regression plot of PR 2406](https://github.com/OPM/opm-simulators/files/4291668/plot_2406.pdf)

**Comment by joakim-hove** [comment]
Is this regression in master per se - or is it master + #2406 which gives a regression?

The plots show one well - is the regression similar for all wells?

**Comment by blattms** [comment]
Like I tried to tell: The regression seems to be in master.

For the well plots please take a look yourself at https://ci.opm-project.org/job/opm-simulators-PR-builder/705/ It is never all wells, but ont only one.

**Comment by akva2** [comment]
This is a fresh run with master + unrelated code; https://ci.opm-project.org/job/opm-models-PR-builder/76/

The only discrepancy i can spot is a minor difference for well C-4H. Is that

**Comment by blattms** [comment]
Yep, did the same check with same result. Maybe it is a hickup due to a missing rebase and my PR is simply missing some stuff that needs to be there but is not as it happened after the branch off.

**Comment by akva2** [comment]
Maybe. I don't think there is a regression at least (phew).

**Comment by blattms** [comment]
looks good with a rebased PR on my system.

The more modules the merrier...
