### ISSUE TITLE
Parallel initstateequil.hh runs on a distributed grid but seems to assume a global one.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2423]
I was about to clean up initstateequil.hh as it seemed that getting the global field properties is superfluous. I have to admit that this code leaves me a bit clueless. Is this well tested in parallel?

What strikes me is this:
 [In the constructor of InitialStateComputer](OPM/opm-simulators/blob/a449b2e2e6a2f1bf420a20440f4b70b321d3e64d/ebos/equil/initstateequil.hh#L933) it's `temperature_` member is a vector of the number of elements of the local grid (called after loadbalance). Later in the constructor there is a call to [updateInitialTemperature](/OPM/opm-simulators/blob/a449b2e2e6a2f1bf420a20440f4b70b321d3e64d/ebos/equil/initstateequil.hh#L1086) which overwrites the vector by the global field property with key "TEMPI".  But the grid passed to the constructor is a loadbalanced parallel one (I see this in my gdb session, the backtrace shows that this is called during `problem_finishInit` in the Simulator of opm-models/opm/models/utils/simulator.hh). Later on this array is then used in `Opm::EQUIL::computeRs` and this function seems to assume that the temperature for the i-th cell its stored in `temperature_[i]`, but this array seems to be unchanged from before.

It also seems that all the region stuff cannot work on a distributed grid as it does see the cells of the region that belong to another processor.

I am lost, what am I missing?

**Comment by akva2** [comment]
i've always been under the impression this was broken in parallel. i just reproduced the existing code when i did my pass over there tbh. you will see that the parallel temperature dependent test has very coarse tolerances, way too coarse to make sense. this was the case before and after my changes.

**Comment by joakim-hove** [comment]
> [...] updateInitialTemperature which overwrites the vector by the global field property with key "TEMPI" [...]

I do not know details here; but the temperature stuff is not much used and not well maintained.
