### ISSUE TITLE
filesystem error: cannot make absolute path: Invalid argument []

### ISSUE THREAD

**Issue by hakonhagland** [OPM/opm-simulators#2508]
When running `flow` from the master branches:

```
$ flow SPE1CASE1.DATA
**********************************************************************
*                                                                    *
*                      This is flow 2020.04-pre                      *
*                                                                    *
* Flow is a simulator for fully implicit three-phase black-oil flow, *
*             including solvent and polymer capabilities.            *
*          For more information, see https://opm-project.org         *
*                                                                    *
**********************************************************************

Using 1 MPI processes with 2 OMP threads on each 

Reading deck file 'SPE1CASE1.DATA'
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot make absolute path: Invalid argument []
Aborted (core dumped)
```
After running it with gdb, it seems the error is on [line #177](https://github.com/OPM/opm-simulators/blob/202235abe0239276536f6be5f1f38b87c66ed098/flow/flow.cpp#L177) in `flow.cpp`:
```C++
output_dir = absolute(path(baseName).parent_path()).string();
```
here `baseName` is `SPE1CASE1.DATA` and `path(baseName).parent_path()` returns the empty string `""`, finally running `filesystem::path::absolute` on an empty string :
```C++
absolute(path(baseName).parent_path())
```
gives the error.

**Comment by goncalvesmachadoc** [comment]
We have encountered same issue when trying to compile/install flow in the cluster (Cent OS 6):
![OPM_run_fail](https://user-images.githubusercontent.com/54812829/78032759-ca3b5a80-7365-11ea-9721-e1a9b2a3da83.PNG)

**Comment by blattms** [comment]
Are we still supporting RedHat/CentOS 6 in master? I thought we dropped them because of limited c++17 compiler support.

**Comment by blattms** [comment]
But I might be wrong. What compiler is it?

**Comment by blattms** [comment]
Seems like I am wrong. Commit messages indicate that redhat6 should still work. But one needs devtoolset-8.

**Comment by hakonhagland** [comment]
I am using Ubuntu 19.10, gcc version 9.2.1.

**Comment by joakim-hove** [comment]
> flow SPE1CASE1.DATA

Should of course not be necessary, but have have you tried: `flow ./SPE1CASE1.DATA`?

**Comment by hakonhagland** [comment]
@joakim-hove Yes, using `flow ./SPE1CASE1.DATA` gives the same error..

**Comment by goncalvesmachadoc** [comment]
> Seems like I am wrong. Commit messages indicate that redhat6 should still work. But one needs devtoolset-8.

We have gcc 9 and devtoolset-8...

**Comment by akva2** [comment]
it's a change in filesystem behavior.  can you please try with #2514

**Comment by hakonhagland** [comment]
@akva2 Thanks! The PR seems to work for me, but I had to try it on an older version of `master` due to some unrelated compilation problems. So I have not tested it on the current master.
