### ISSUE TITLE
2020-04-RC2: Production and Injection Reports

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2559]
Reports look very good, just a few comments to improve readability/usability:

- Can we get rid of `-nan` and replace with "blanks" instead. 
![image](https://user-images.githubusercontent.com/17958927/80183280-20d14700-863b-11ea-978e-bd30ad656006.png)

- All the reports print the data without any reference to the time step or date, which makes it challenging to find the data for a given date. So is it possible to have a report header for the production and injection report that contains this information? We could just use the same one as for the FIPNUM report, just change BALANCE to WELLS
![image](https://user-images.githubusercontent.com/17958927/80184957-1c5a5d80-863e-11ea-9ad7-24d20fff8dce.png)

- There is something also wrong with numbers, for example field oil rate is zero but the group and wells have oil rate numbers. Here is the OPM Flow report:
![image](https://user-images.githubusercontent.com/17958927/80185402-dbaf1400-863e-11ea-86ec-8c4802ceb1d6.png)
And here is the commercial simulator's report at the same report step.
![image](https://user-images.githubusercontent.com/17958927/80185683-55470200-863f-11ea-991a-0eda558925fb.png)
Notice how the commercial simulator's production report contains the field production. whereas the OPM Flow report does not. There is a similar issue with injection report as well.

**Comment by goncalvesmachadoc** [comment]
Hi  @OPMUSER . I will make the changes and check the field report.

**Comment by OPMUSER** [comment]
@goncalvesmachadoc is it possible to get the changes into the 2020-04 release?

**Comment by goncalvesmachadoc** [comment]
I will try to finalize it today. :)

**Comment by OPMUSER** [comment]
Fantastic.

**Comment by goncalvesmachadoc** [comment]
@OPMUSER I have submitted a PR for changing NaN output for empty space. The header that is printed is not specifically for FIPNUM, but for all reports; it is printed at each time step, independently of what else is asked to be printed to the PRT file. Do you want me to add a header to each report (including another one for FIPNUM)?

**Comment by OPMUSER** [comment]
Sorry for the late reply I'm not in your time zone.

In the commercial simulator each report has it's own header, which look all the same except for the title of the report (Balance, Wells etc.). This is because you can switch off reports by using the NOTHING option on the RPTSCHED keyword, and then switch others on Also, there are various forms of the reports (WELL=2, for example) and sub reports as well.

For the time being just add a Wells report header.

Does that answer your question?

**Comment by goncalvesmachadoc** [comment]
Yes, thank you David!

**Comment by OPMUSER** [comment]
Closing as fixed.
