### ISSUE TITLE
2020-04-RC2: Feature Status and Keyword Status

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2560]
Here is what I have for the current status that needs developer input.

![image](https://user-images.githubusercontent.com/17958927/80192353-9e03b880-8649-11ea-8007-e4008c49cf7f.png)

I also need to know what has been implemented or changed from the 2019-10 release. Ideally, we should aim to get the manual out in a couple of weeks after the binaries are released. 

Note have over 1900 keyword entries in my database, so getting this down to only 17 for developer comment is an achievement.

**Comment by joakim-hove** [comment]
`WTADD`: This is not supported; in the MissingFeatures it is misspelled `WTAD` - fix coming.

`MINVALUE`: This is fully operational

`NOECHO`: Is not working - will be added to missing features.

`PRORDER`: Not supported at all; not in defintion and not in missing features - fix coming.

`PRVD`: Not support at all. Fix coming

`ROCKTABW`: Not supported - will be added to missing features

`SKIPREST`: Will delete from missing features

`SATOPTS`: Will remove from missing features

`WLIFT`: Will add to missing features

The others I do not know.

**Comment by joakim-hove** [comment]
We need definitions for: `PRVD` and `PRORDER`- should I add those, or do you want to give it a  shot?

**Comment by joakim-hove** [comment]
PRORDER was in after all - PRVD added here: https://github.com/OPM/opm-common/pull/1742

**Comment by OPMUSER** [comment]
Getting there, this is what I currently have for the current status that needs developer input.

![image](https://user-images.githubusercontent.com/17958927/80338338-a7ca2d80-888e-11ea-8c0e-faa279e8e220.png)

**Comment by joakim-hove** [comment]
`DEADOIL`: This is not used; it is not in MissingFeatures, since it is a E300 keyword my suggestion would be to remove it completely.

`GRAVITY`: I will add it to `MissingFeatures`

`SALTVD`: Some code in - no idea of the state it is in.

`THCSOLID`: E300 keyword - not supported in any way.

`THERMEX1`: As `DEADOIL`

`VISCREF`: Makes sense to remove from missing features

`WEFAC`: This is active and working.

**Comment by OPMUSER** [comment]
SALTVD is not ignored but it defines the salt concentration as zero for all depth, ignoring the input. I think we should mark this as MissingFeatures until this is working correctly

**Comment by OPMUSER** [comment]
@joakim-hove Just leave SALTVD as is, as I'll add a note to the manual stating that is not working.

**Comment by OPMUSER** [comment]
Close.
