### ISSUE TITLE
No summary output from user defined quantities

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#2581]
It seems like UDQ's do not get summary output. Tested on current master with a proprietary data set. We should probably get this tested on a model4 variety.

**Comment by joakim-hove** [comment]
Hmmm - that was surprising; I was really quite certain that worked. The `udq_actionx/UDQ_ACTIONX` test should be enough to work on this - that should produce UDQ summary vector `WUPR1:{WELL}` and `WUPR3:{WELL}`

**Comment by alfbr** [comment]
Thanks for the clarification, then I will test further on my side to unravel the trigger.
