### ISSUE TITLE
2020-04-RC3 Tracers Not Supported by Flow

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2587]
I get this message when I activate tracers in the param file:

```
Warning: Keyword 'TRACERS' is not supported by flow.
In file /media/sf_D_DRIVE/Linux/OPM/Norne/Model/NOR01-BASE01-OPM2004-R04.DATA, line 50

```
Is this correct?

**Comment by akva2** [comment]
you have to give --enable-tracers=true, and it *should* (tm) work in serial runs.

**Comment by OPMUSER** [comment]
Okay I was running parallel with --enable-tracers=true, I'll try again in serial.

**Comment by OPMUSER** [comment]
Same message in serial job.

**Comment by akva2** [comment]
yes, that's because it's still in the unsupported keyword list. question is do they actually work in a serial run?

**Comment by OPMUSER** [comment]
Will take a look once the jobs finishes and let you know.

**Comment by totto82** [comment]
The tracer support in Flow is very limit and in an experimental condition. Last time I checked only water tracers worked. I don't think anybody is working on this right now.

**Comment by OPMUSER** [comment]
Well it writes out the arrays but the results are garbage, and there is no summary data.
![image](https://user-images.githubusercontent.com/17958927/80962765-3d8e2b80-8e40-11ea-8a46-70bbfa5660a1.png)

**Comment by OPMUSER** [comment]
I'll mark this as not working. Also I thought the BRINE option and TRACERS went together, is that correct?

**Comment by totto82** [comment]
No BRINE and TRACERS have different implementations.

**Comment by OPMUSER** [comment]
Thanks @akva2 and @totto82
