### ISSUE TITLE
2020-04-RC3: Exception.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2596]
Trying to get the Volve model to run as a test and noticed the following:

- In serial model OPM Flow traps an exception in the SCHEDULE section, which I cannot identify at this stage; however the program terminates as expected. So that is correct.

- In parallel mode, again OPM Flow traps an exception in the SCHEDULE section, which is in a different location (based on the line number) and again I cannot identify the cause. However, in this case the program **does not terminate**, but appears to go into a loop. 

- I then re-ran the model in serial mode several times and got the same behavior, but the exception in the SCHEDULE section is always at a different line number.  

Has anybody else seen this behavior?

I'm not too concerned about getting this model to run at this stage, just that we may have a horrible bug in the release.

**Comment by OPMUSER** [comment]
The GitHub version of the Volve model appears to run without the aforementioned issues, but lots of time steps chops -:-(

**Comment by GitPaean** [comment]
@OPMUSER , which model are you referring to.

**Comment by OPMUSER** [comment]
There is the original Volve model that Equinor released into the public domain, and there is also a model on GitHub that Chris Dinneen has got sort of working - see the attached file for reference.


[README.zip](https://github.com/OPM/opm-simulators/files/4592212/README.zip)

**Comment by GitPaean** [comment]
It looks like you are testing the newer version (2016) of the DATA. The DATA on my machine is 2016 version. 

Have not invested much time on this model, not sure about the status about how OPM supports this case.

**Comment by OPMUSER** [comment]
Close input file issue.

**Comment by blattms** [comment]
> > It looks like you are testing the newer version (2020) of the DATA. The DATA on my machine is 2016 version.
> > Have not invested much time on this model, not sure about the status about how OPM supports this case.
> 
> I have the same issue. The Volve 2020 model doesn't seem to be available on the Github page.

Isn't it [here](https://github.com/dabiged/Volve2OPM)? Would you mind trying it with the master version (not the release)?

**Comment by discover-volve** [comment]
Thank you! I tried the Volve 2020. The simulation does work however I still like to understand the changes between the 2016 and 2020 model. Thank you for helping me :)

**Comment by blattms** [comment]
Judging from the [readme,](https://github.com/dabiged/Volve2OPM/blob/master/README.md) he downloaded the [version](https://www.equinor.com/en/how-and-why/digitalisation-in-our-dna/volve-field-data-village-download.html) available from Equinor. If that is is the 2016 version (I cannot judge this), then the relevant modifications are in commits [f3f1315f72](https://github.com/dabiged/Volve2OPM/commit/f3f1315f722f661a254b2228c9ce73f3cf8ae406) and [9045b04c4](https://github.com/dabiged/Volve2OPM/commit/95b04c43ef24dd8c5d211b7c869fd523c2dc3b77).

If that version is not the 2016 version, then you need to look at the diff between the version. On Linux you could use `meld version2016 version2020` for this if the version are located in directories version2016 and version2020 (depending on the size of the files this might take some time). I am sure you will find tools for other operating systems, too.

**Comment by discover-volve** [comment]
I'm sure he downloaded the 2016 version from the Equinor portal. Thank you for bringing my attention to the commits. I'll got through it.

**Comment by dabiged** [comment]
Hi All, I am responsible for the volve2OPM project. I am happy to answer any questions anyone has, though any changes I made to the original files should be discoverable through the commit history, or a diff on the relevant files.

**Comment by discover-volve** [comment]
I'm putting together an article based on your work. Will share it with you. Thank you for your support!
