### ISSUE TITLE
Restarting Calls an Exception (Nighly Build)

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2651]
Using the Norne model to restart from a 2004 OPM Flow restart, using the current nightly build results in an exception.

![image](https://user-images.githubusercontent.com/17958927/83739353-0b165f00-a688-11ea-80ba-adefc7064d10.png)

If this is incompatible, then it should be trapped.

**Comment by atgeirr** [comment]
This crash and the one in #2653 look very similar, crashing in the same function call, ISTLSolverEbos::prepare().

**Comment by OPMUSER** [comment]
Yes, I'll double check when I get a minute.

OPM User
opmuser0@gmail.com

**Comment by OPMUSER** [comment]
@atgeirr yes you are correct it is an mpirun issue  (#2653 )- closing
