### ISSUE TITLE
Norne Crashes Using mpirun on Nightly Build

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2653]
Crashes on parallel but runs okay in sequential.

![image](https://user-images.githubusercontent.com/17958927/83743414-46fff300-a68d-11ea-887f-c4cafec0cbb1.png)

**Comment by blattms** [comment]
Will take a look

**Comment by blattms** [comment]
That must something Ubuntu package specific. I do not get it with master on Debian.

**Comment by OPMUSER** [comment]
I can confirm that mpirun jobs do not work for any case under Ubuntu 18-04 LTS, not just for Norne.
```

Warning: OwnerCellsFirst option is true, but ignored.
Property tree for linear solver:
{
    "tol": "0.01",
    "maxiter": "200",
    "verbosity": "0",
    "solver": "bicgstab",
    "preconditioner": {
        "type": "ParOverILU0",
        "relaxation": "0.90000000000000002",
        "ilulevel": "0"
    }
}   
```
Decks and log file attached, all the jobs run fine under sequential.

Question: Do we check that the mpirun -np command is consistent with the number of CPU's available? 
[TestCases.zip](https://github.com/OPM/opm-simulators/files/4739328/TestCases.zip)

**Comment by bska** [comment]
> I can confirm that mpirun jobs do not work for any case under Ubuntu 18-04 LTS

Right.  Did you acquire the MPI functionality from Ubuntu's package repository using `apt`, from OPM's associate packages, or did you build the MPI support yourself&mdash;e.g., from an [OpenMPI release](https://www.open-mpi.org/software/ompi/v4.0/)?  The reason I ask is that the OpenMPI packages that ship with Ubuntu 18.04 LTS are known to be broken.  I think @akva2 knows additional details.

From personal experience I know that the Ubuntu packages occasionally do something that's not entirely unlike MPI, but I finally gave up and built OpenMPI myself.  That was straightforward enough, but brought some fallout that was painful to deal with so it's not something I recommend.

**Comment by OPMUSER** [comment]
Bård,

Joakim provide a python script to download everything from OPM's 
associate packages.


OPM User
opmuser0@gmail.com

**Comment by bska** [comment]
> Joakim provide a python script to download everything from OPM's associate packages.

That's good to know, thank you for the additional detail.  Unfortunately, that also means that the problem is more serious than I first anticipated.  If our own MPI packages fail we will have to look more into the issue.

**Comment by joakim-hove** [comment]
> That's good to know, thank you for the additional detail. Unfortunately, that also means that the problem is more serious than I first anticipated. If our own MPI packages fail we will have to look more into the issue.

Well Bård; thank you for the vote of confidence - I'll just reproduce the script here - so you can evaluate for yourself whether I am worthy of your confidence:

**One shot repo init:**
```
#!/bin/bash

apt update
apt upgrade

wget -qO - https://opm-project.org/package/nightly-bionic/repokey.gpg | apt-key add -

apt-add-repository https://opm-project.org/package/nightly-bionic
```

**Idempotent update script**
```python
#!/usr/bin/env python
from __future__ import print_function
import time
import sys
import subprocess
import shlex


def cmd(cmd_string):
    argv = shlex.split(cmd_string)
    subprocess.check_call( argv )




def update_flow(date_string):
    print("Deleting old versions of flow")
    cmd("apt purge -y libopm-common1")
    if date_string is None:
        print("Installing latest nightly version of flow")
        cmd("apt-get install -y libopm-common1 libopm-grid1 libopm-simulators1-bin")
    else:
        print("Installing nightly version of flow from: {}".format(date_string))
        cmd("apt-get install -y libopm-common1={0}* libopm-grid1={0}* libopm-simulators1={0}* libopm-simulators1-bin={0}*".format(date_string))


date_string = None

if len(sys.argv) == 2:
   date_string = sys.argv[1]
   try:
       _ = time.strptime(date_string, "%Y-%m-%d")
   except ValueError:
       sys.exit("Sorry - the date string: {} is invalid - expected format YYYY-MM-DD".format(date_string))

update_flow(date_string)
```

**Comment by blattms** [comment]
I can replicate this with the version of 2020-06-22 and SPE1CASE2 with 2 processes. Installing the nightly images also installs libopenmpi2 version 2.1.1.9~bionic from opm-project.org which is supposed to be the fixed mpi package.

If I download master and compile myself (with the same openmpi) it works (whether I build shared libraries or not). According to ldd the linked non-opm libraries are the same. I am clueless.

**Comment by akva2** [comment]
can u try LTO locally ?

**Comment by blattms** [comment]
I did test the self-compiled version with `-DWHOLE_PROG_OPTIM=ON` and it still works.

**Comment by bska** [comment]
@OPMUSER : Are you still seeing this issue?
