### ISSUE TITLE
Does CollectDataToIORank::isGlobalIdxOnThisRank Return True for Ghost Cells?

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#2665]
The [EBOS Output Module](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/ecloutputblackoilmodule.hh) contains the following lines
```C++
// Initialize block output
for (const auto& node: summaryConfig) {
    if (node.category() == SummaryConfigNode::Category::Block) {
        if (collectToIORank.isGlobalIdxOnThisRank(node.number() - 1)) {
            std::pair<std::string, int> key = std::make_pair(node.keyword(), node.number());
            blockData_[key] = 0.0;
        }
    }
}
```
This code&mdash;lines 187 through 195&mdash;creates locations to host block-related summary quantities like
```
BPR
  13 29 8 /
/
```
which are subsequently populated in [`processElement()`](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/ecloutputblackoilmodule.hh#L688-L725) and communicated to the I/O rank using [`CollectDataToIORank::collect()`](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/eclwriter.hh#L281-L282).

The reason I ask is that I'm trying to analyse a weird symptom in Flow's summary file output in the context of parallel simulation runs.  If I add the summary vectors below to [`NORNE_ATW2013`](https://github.com/OPM/opm-tests/blob/64f2bef4cba614a02442f67de9ceb7c8225c043c/norne/NORNE_ATW2013.DATA) I occasionally get zeros in the summary output from a parallel run when the a sequential run produces non-zero values.
```diff
--- a/norne/NORNE_ATW2013.DATA
+++ b/norne/NORNE_ATW2013.DATA
@@ -449,6 +449,18 @@ INCLUDE
 INCLUDE
  './INCLUDE/SUMMARY/wpave.inc' /

+BPR
+  13 29 8 /
+/
+
+BWSAT
+  13 29 8 /
+/
+
+BGSAT
+  13 29 8 /
+/
+
```
Using the [summary](https://github.com/OPM/opm-common/blob/6a742a20fd6a540a16be343ebb864a5d7619a3cb/test_util/summary.cpp) program as follows
```sh
summary NORNE_ATW2013 TIME YEARS BPR:* BWS* BGS*
```
I'm seeing output like the following for a parallel run (`mpirun -np 4`)
```
     1324.000000        3.624914      228.879883        0.176966        0.066557
     1333.000000        3.649555        0.000000        0.000000        0.000000
     1334.000000        3.652293      228.461044        0.176973        0.066886
     1335.000000        3.655031        0.000000        0.000000        0.000000
     1338.000000        3.663244        0.000000        0.000000        0.000000
     1347.000000        3.687885        0.000000        0.000000        0.000000
     1348.000000        3.690623        0.000000        0.000000        0.000000
     1351.000000        3.698836        0.000000        0.000000        0.000000
     1356.500000        3.713895      228.616806        0.176955        0.065855
     1362.000000        3.728953      228.637436        0.176952        0.065678
     1364.000000        3.734428        0.000000        0.000000        0.000000
```
whereas the sequential run produces the more reasonable, if nevertheless somewhat different, output
```
     1324.000000        3.624914      228.882645        0.176970        0.066554
     1333.000000        3.649555      228.492386        0.176976        0.066876
     1334.000000        3.652293      228.463501        0.176977        0.066885
     1335.000000        3.655031      228.449188        0.176977        0.066867
     1338.000000        3.663244      228.443863        0.176978        0.066752
     1347.000000        3.687885      228.542435        0.176969        0.066270
     1348.000000        3.690623      228.549515        0.176968        0.066225
     1351.000000        3.698836      228.579285        0.176964        0.066079
     1356.500000        3.713895      228.618103        0.176958        0.065858
     1362.000000        3.728953      228.638382        0.176956        0.065681
     1364.000000        3.734428      228.636444        0.176956        0.065634
```
---
If, and that's a BIG 'if', [`CollectDataToIORank::isGlobalIdxOnThisRank()`](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/collecttoiorank.hh#L743) were to return `true` for ghost cells, then that would at least be a plausible reason for `collect()` to generate non-deterministic block-data values.  Since [`PackUnPackBlockData::unpack()`](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/collecttoiorank.hh#L630) uses [assignment](https://github.com/OPM/opm-simulators/blob/b1adbd45cbe071bdec87a39308703b6e39282301/ebos/collecttoiorank.hh#L642) it is possible to generate both zero and non-zero values if there are multiple data sources and only one of these is the proper data owner.

On the other hand, if `CollectDataToIORank::isGlobalIdxOnThisRank()` **never** returns `true` for ghost cells, then I need to look deeper into this issue.

**Comment by blattms** [comment]
Not totally familiar with that code, but judging from the code it does return true for ghost cells.

`ElementIndexScatterHandle` is designed to read the global index for each cell on the undistributed grid and writes what it receives to the distributed array regardless of the partition. That means that for all cells present in that distributed grid `CollectDataToIORank::isGlobalIdxOnThisRank()` it returns true if the cell with the global index is represented. The scatter happens in [line 327 ff](/OPM/opm-simulators/blob/23a9f4732bc48266bb19fba9d751db95ea94d620/ebos/collecttoiorank.hh#L327-L329) and  [line 353 ff.](/OPM/opm-simulators/blob/23a9f4732bc48266bb19fba9d751db95ea94d620/ebos/collecttoiorank.hh#L353-L355). Gather and Scatter is [lines 229](/OPM/opm-simulators/blob/23a9f4732bc48266bb19fba9d751db95ea94d620/ebos/collecttoiorank.hh#L229-L238)

I guess the assumption is that all data needs to be correct also in the ghost layer. I would have assumed that that would be the case for the fluid properties, also? But apparently not. Maybe we need to add communication somewhere to achieve that?

**Comment by bska** [comment]
> I guess the assumption is that all data needs to be correct also in the ghost layer. I would have assumed that that would be the case for the fluid properties, also? But apparently not. Maybe we need to add communication somewhere to achieve that?

Yeah, that's likely.  I can "solve" my immediate problem by applying the one-character patch below&mdash;adding up all the individual contributions&mdash;and get output of the form
```
     1324.000000        3.624914      228.879883        0.176966        0.066557
     1333.000000        3.649555      228.489868        0.176973        0.066877
     1334.000000        3.652293      228.461044        0.176973        0.066886
     1335.000000        3.655031      228.446777        0.176974        0.066868
     1338.000000        3.663244      228.441544        0.176974        0.066752
     1347.000000        3.687885      228.540573        0.176965        0.066270
     1348.000000        3.690623      228.547699        0.176964        0.066224
     1351.000000        3.698836      228.577682        0.176960        0.066078
     1356.500000        3.713895      228.616806        0.176955        0.065855
     1362.000000        3.728953      228.637436        0.176952        0.065678
     1364.000000        3.734428      228.635590        0.176953        0.065631
```
for the case of `NORNE_ATW2013`.  That patch feels **really** hacky, so I'd prefer a more general and well thought-out solution.

What's a little bit confusing however, is that the restart output&mdash;e.g., the `PRESSURE` and `SGAS` vectors in `CASE.UNRST`&mdash;use the same data sources yet don't have those same symptoms.  There's clearly something else going on.  Maybe the data is just not exchanged as frequently as the [`evalSummaryState()`](https://github.com/OPM/opm-simulators/blob/f03dd20b9600f136c46fbf6c9f2b12d73b887ba3/ebos/eclproblem.hh#L991) call in `EclProblem<>::endTimeStep()` implicitly assumes?

---

```diff
diff --git a/ebos/collecttoiorank.hh b/ebos/collecttoiorank.hh
index a58eef2f..0756e6d7 100644
--- a/ebos/collecttoiorank.hh
+++ b/ebos/collecttoiorank.hh
@@ -639,7 +639,7 @@ public:
                 buffer.read(name);
                 buffer.read(idx);
                 buffer.read(data);
-                globalBlockValues_[std::make_pair(name, idx)] = data;
+                globalBlockValues_[std::make_pair(name, idx)] += data;
             }
         }
```

**Comment by blattms** [comment]
I guess the correct fix for gathering would be to change `ElementIndexScatterHandle::scatter` to check
the partition of the Entity and only save the read value from the buffer if the partition is Interior (or maybe InteriorBorder).

**Comment by blattms** [comment]
On second thought this might change length of arrays in other parts of  the code. Maybe we should store the partition type in addition to the index during scatter and use that latter when needed.

**Comment by blattms** [comment]
Concerning the other question:
Maybe some values only need data from the current cell (`SGAS`, `PRESSURE`), while other are actually calculated also from values of neighboring cells?

**Comment by bska** [comment]
> Maybe we should store the partition type in addition to the index during scatter and use that latter when needed in a function is `isGlobalIdxOwnedOnProcess`.

I think that's a good idea, and I tried to do something similar over the weekend. Unfortunately I made a mistake somewhere so all of the block parameters consistently came out as `0.0` for all processes.

> Maybe some values only need data from the current cell (`SGAS`, `PRESSURE`), while other are actually calculated also from values of neighboring cells?

That's certainly possible, but in the case that prompted this question we're exclusively talking about block (i.e., individual cell) values in the summary file and those would (should?) be equivalent to the `SGAS` and `PRESSURE` array sources.

**Comment by blattms** [comment]
It was not a race condition but rather a total index mess. I hope #2778 fixes this.
