### ISSUE TITLE
TRANX, TRANY, TRANZ seem not working in newest release

### ISSUE THREAD

**Issue by Wenyue-Sun** [OPM/opm-simulators#2708]
Hi, I'm using the TRANX keyword in the EDIT section. However, the cells (covered by TRANX) will end up having TRANX being zero regardless of what values are specified in the deck. (Same issue will happen for TRANY/Z keywords)

BTW: Tried on the benchmark SPE1 sim deck.

**Comment by blattms** [comment]
Would you mind telling us, what modifications you applied on which spe1 case and/or sharing the deck.
For the unmodified cases I cannot replicate the issue with ResInsight.

There has been a problem with TRANX/Z for 1D and 2D cases that is also in the release. In  has been fixed
in master via PR #2673, though.

**Comment by Wenyue-Sun** [comment]
Sure. 

NOTE in Line 106 to 112, I added: 
============
BOX
  1 10 1 3 1 1 /

TRANX
 30*20 /

ENDBOX
=============

So I tested both flow20.04 and flow2019.10, both show a static TRANX map as: 
![TranxSPE1](https://user-images.githubusercontent.com/17682458/88067158-41267a00-cb34-11ea-8e39-79f5a12b6dc1.png)
(The blue boxes, which I modified, have tranx value being zero (or almost zero)).

DataSet:
[SPE1CASE2_2P.TXT](https://github.com/OPM/opm-simulators/files/4954068/SPE1CASE2_2P.TXT)

PS:
With flow 2019.10 version, the TRANX/Y/Z works properly if the BOX keyword is not used, which flow 20.04 seems not working with/without BOX keyword.

**Comment by blattms** [comment]
FYI we are working on this one.

**Comment by bska** [comment]
@Wenyue-Sun : Are you still having this issue?

**Comment by Wenyue-Sun** [comment]
@bska  The newest build has this issue solved.

**Comment by bska** [comment]
> The newest build has this issue solved.

Thank you for testing and closing the issue.
