### ISSUE TITLE
PARSE_EXTRA_RECORDS error while running Volve simulation model

### ISSUE THREAD

**Issue by discover-volve** [OPM/opm-simulators#2710]
I am trying to run the Volve_2016.Data reservoir model on the OPM simulator. The model works fine with an Eclipse simulator. However, the simulation gets killed with the below error.

`Error: String: '2950.0      128.8' invalid. Too many records in keyword: RSVD at: 236.`

```
Failed to create valid EclipseState object.
Exception caught: PARSE_EXTRA_RECORDS: String: '2950.0      128.8' invalid. Too many records in keyword: RSVD at: 236.
```

I can get around this error by commenting the records after the 236th line in the RSVD keyword. 
But the simulation again gets killed because of other errors:
```
Failed to create valid EclipseState object.
Exception caught: Unknown enum state string: 4
```

I have attached the complete simulation log file of the error. Please help me run the model, this important to help me educate my students. 
[Volve_Eclipse_run_log.txt](https://github.com/OPM/opm-simulators/files/4949928/Volve_Eclipse_run_log.txt)

**Comment by joakim-hove** [comment]
Hello,

I am sorry to heat about your parsing problems - this is a part og the codebase I am quite familiar with and hopefully I can help. Right now i am on holiday so it might take sone time.

**Comment by discover-volve** [comment]
Sure, I'll be looking forward to your reply. :)

> Hello,
> 
> I am sorry to heat about your parsing problems - this is a part og the codebase I am quite familiar with and hopefully I can help. Right now i am on holiday so it might take sone time.

**Comment by joakim-hove** [comment]
Where can I find the Volve simulation model?

**Comment by discover-volve** [comment]
You can download the model from my drive folder: [Download here](https://drive.google.com/file/d/1YcgXSQMyPtNokfuWhmJdoQ2mQ2R-hRn6/view?usp=sharing) 
The OPM manual has a lot of reference to the Volve simulation model. But I do not see any information about issues in running the model.

**Comment by joakim-hove** [comment]
OK; I have now downloaded the Volve case from the provided link. My analysis of parsing problems is as follows:

> `Error: String: '2950.0 128.8' invalid. Too many records in keyword: RSVD at: 236.`

This is my opinion an error in the input deck; the `NTEQUL` item in the `EQLDIMS` keyword should indicate how many records the `RSVD` keyword should have. In the deck provided the `EQLDIMS` keyword looks like:
```
EQLDIMS
    12  ... /
```
i.e. the `NTEQUL` value equals 12 - whereas the `RSVD` keyword has 13 regions - i.e. one to much[1]. To fix this you can either 
increase the value of the `NTEQUL` item in the `EQLDIMS`keyword to 13, and probably also make some other fixes (at least the `EQUIL` keyword), or alternatively you can remove the last record in the `RSVD` keyword.

I removed the last record in the `RSVD` keyword, then I did not encounter this error:

>`Failed to create valid EclipseState object.`
>`Exception caught: Unknown enum state string: 4`

Instead I got the following error message:
```
String ''P-F-14'      'OPEN'      'ORAT'    298.200   3138.700  43367.000  3*    262.000  1* /' not formatted/recognized as valid keyword at: "/home/hove/Downloads/Volve_Reservoir_Model-Eclipse_model/Reservoir_Model-Eclipse_model/Volve_sim_model_PPA-Eclipse Res Model/SCH_010916_10DAYS.SCH":4869
terminate called after throwing an instance of 'std::invalid_argument'
  what():  PARSE_RANDOM_TEXT: String ''P-F-14'      'OPEN'      'ORAT'    298.200   3138.700  43367.000  3*    262.000  1* /' not formatted/recognized as valid keyword at: "/home/hove/Downloads/Volve_Reservoir_Model-Eclipse_model/Reservoir_Model-Eclipse_model/Volve_sim_model_PPA-Eclipse Res Model/SCH_010916_10DAYS.SCH":4869
Aborted (core dumped)
```
which seemed to indicate that the keyword around line 4869 was quite malformed - I added a `WCONHIST` header and a terminating slash `/` - and then everything parsed ok for me? 


[1]: The default behavior in this situation is to abort - as you have experienced, but by using the `ParseContext` mechanism you can set `PARSE_EXTRA_RECORDS` behavior to be more lenient.

**Comment by discover-volve** [comment]
Thank you for your analysis. I'll run the code and share my results.

**Comment by discover-volve** [comment]
Thank you for your analysis. I'll run the code and share my results.
