### ISSUE TITLE
Error: Failed to create EclipseState Object for Volve Dataset

### ISSUE THREAD

**Issue by discover-volve** [OPM/opm-simulators#2734]
I'm trying to run the Volve dataset on the OPM Flow simulator. I have made a lot of changes to the simulation files to make them compatible with the Flow simulator. I do not get any keyword errors and the only warning messages I receive are related to the "ECHO" and "NOECHO" keyword. These keyword are ignored by the OPM Flow simulator and should not be a problem in running a simulation. However, I get the following run error when I start the simulation. 

```
Failed to create valid EclipseState object.
Exception caught: Unknown enum state string: 4
```
Please help me understand this error and solve the issues associated with it.  The edited dataset can be accessed here: https://drive.google.com/file/d/1kf9bDTQpRhE0cqbgYhI5U62htWiyg3fH/view?usp=sharing

**Comment by joakim-hove** [comment]
There is a `WCONHIST`keyword at `SCH_010916_10DAYS.SCH:4868` which is not properly terminated with a `/`

**Comment by discover-volve** [comment]
Thank you for your help. The simulation now runs. 
I would really like to contribute to the OPM project but will need some onboarding to initiate. I really wish for the success of this project.

**Comment by blattms** [comment]
Using it and reporting here is definitely a good first step.
