### ISSUE TITLE
flow does not print header and options anymore

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2757]
in neither *PRT nor *DBUG. Instead it starts with output from Eclipse file reading.

**Comment by bska** [comment]
I'm seeing this too.  A recent change has inadvertently removed this very useful information.

**Comment by atgeirr** [comment]
Are any of you looking at this right now? If not, I can do so (must fix unrelated compile error first though).

**Comment by bska** [comment]
> Are any of you looking at this right now?

Just for the record: I am not.

**Comment by akva2** [comment]
i believe this was left out when we moved from flow_tag.hpp to Main.hpp. There is no call to printPRTHeader.

**Comment by blattms** [comment]
Just go for it @atgeirr
