### ISSUE TITLE
Excessive time step choping for Norne when using flexible solvers.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2759]
Runing `flow --linear-solver-configuration=ilu0 NORNE_ATW2013` results in excessive time step chopping for current master. Same for CPR. Using the default, i.e. without the flexible solver bx skipping the argument, works as before.

**Comment by akva2** [comment]
I can reproduce.

However, results are ballpark similar (and no apparent excessive time step cutting) if --matrix-add-well-contributions=true is given with the flexible solver (ilu0). Maybe this is an implicit requirement with the flexible solver?

**Comment by blattms** [comment]
the connection with the wells might hint at the changes in #2694.

**Comment by GitPaean** [comment]
I guess `--matrix-add-well-contributions=true` is required for `cpr`.

**Comment by akva2** [comment]
as stated, this was with ilu0, not cpr.

**Comment by blattms** [comment]
Seem like when running with 1 process there is an if-else missing in  [ISTLSolverEbos.hpp#L771-L775](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/linalg/ISTLSolverEbos.hpp#L771-L775).

**Comment by blattms** [comment]
Will try to fix

**Comment by blattms** [comment]
Well, I still have to compile and run norne before posting a pr. hence if yours is tested....

**Comment by atgeirr** [comment]
This is indeed a bug as described above, https://github.com/OPM/opm-simulators/pull/2706 has also fixed this I think, but has become stale.

**Comment by blattms** [comment]
Maybe we should not hide bug fixes in feature PRs?

**Comment by atgeirr** [comment]
> Maybe we should not hide bug fixes in feature PRs?

I was actually not aware it would have fixed a bug in the existing code, I just made sure it worked in the new...
