### ISSUE TITLE
Unexpected SIGABRT when debugging

### ISSUE THREAD

**Issue by plgbrts** [OPM/opm-simulators#2763]
I get a SIGABRT when I debug flow using the test input file (opm-tests\spe1\SPE1CASE2_2P.DATA). This test runs without issues if no breakpoints are set.
When a break point is set  (e.g. line 613 opm-material/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp) and going to the next line a SIGABRT is given and an error message "The futex facility returned an unexpected error code".  Below the output of a dbg session.
Any advice on how to proceed would appreciated.

Paul Egberts
TNO 

**My configuration:**
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git

**Output of a dbg session:**
```
=thread-group-added,id="i1"
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
Loaded '/lib64/ld-linux-x86-64.so.2'. Symbols loaded.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Breakpoint 1, main (argc=2, argv=0x7ffffffede88) at /mnt/c/ProgramFiles/opm-latest/opm-simulators/flow/flow.cpp:27
27	{
Loaded '/lib/x86_64-linux-gnu/libpthread.so.0'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libdunegeometry.so.2.6-git'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libdunecommon.so.2.6-git'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libumfpack.so.5'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libm.so.6'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libgomp.so.1'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libstdc++.so.6'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libgcc_s.so.1'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libc.so.6'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libamd.so.2'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libsuitesparseconfig.so.5'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libblas.so.3'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libcholmod.so.3'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/libdl.so.2'. Symbols loaded.
Loaded '/lib/x86_64-linux-gnu/librt.so.1'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libcolamd.so.2'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libccolamd.so.2'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libcamd.so.2'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libmetis.so.5'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/liblapack.so.3'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libgfortran.so.4'. Symbols loaded.
Loaded '/usr/lib/x86_64-linux-gnu/libquadmath.so.0'. Symbols loaded.
[New Thread 0x7ffffb650700 (LWP 26910)]
[New Thread 0x7ffffae40700 (LWP 26911)]
[New Thread 0x7ffffa630700 (LWP 26912)]
[New Thread 0x7ffff9e20700 (LWP 26913)]
[New Thread 0x7ffff9610700 (LWP 26914)]
[New Thread 0x7ffff8e00700 (LWP 26915)]
[New Thread 0x7ffff85f0700 (LWP 26916)]
[New Thread 0x7ffff7de0700 (LWP 26917)]

Thread 1 "flow" hit Breakpoint 2, Opm::EclEpsScalingPoints<double>::init (this=0xcbdc6e0, epsInfo=..., config=..., epsSystemType=Opm::EclOilWaterSystem) at /mnt/c/ProgramFiles/opm-latest/opm-material/opm/material/fluidmatrixinteractions/EclEpsScalingPoints.hpp:613
613	            saturationPcPoints_[0] = epsInfo.Swl;
Execute debugger commands using "-exec <command>", for example "-exec info registers" will list registers in use (when GDB is the debugger)
[Switching to thread 9 (Thread 0x7ffff7de0700 (LWP 26917))](running)
=thread-selected,id="9"

Thread 9 "flow" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff7de0700 (LWP 26917)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
```

**Comment by blattms** [comment]
I am having trouble to reproduce this, hence I can only guess:

- Maybe it is your combination of gcc and gdb. The former is 7.4 and the latter is 8.1. Are these versions of g++ and gdb the defaults for Ubuntu. Maybe you can try matching ones or the defaults?
- There are also some warnings that make me a bit uneasy:  
```
Warning: Debuggee TargetArchitecture not detected, assuming x86_64.
=cmd-param-changed,param="pagination",value="off"
Stopped due to shared library event (no libraries added or removed)
```
 But i have no clue what they mean.

**Comment by akva2** [comment]
it's an outdated ubuntu install. is this in wsl? i cannot reproduce, neither on my main focal box or on my (updated) bionic install. so my main tip would be to update your distro.

**Comment by plgbrts** [comment]
Thanks for the suggestions. I will look into it further. For now  I updated and upgraded my 18.04 ubuntu: gcc is now 7.5 and gdb is (still) 8.1. The issue is still there.  @Arne: do you suggest to go to ubuntu 20.04?

**Comment by akva2** [comment]
well, as it does not fail on my ubuntu 18.04 with gcc 7.5 either, i'm not necessarily advocating that. though my boxes are now on 20.04 and they all work well, so i see no reason not to update as such. but we still have not found what your issue might be unfortunately.

can you try explicitly setting OMP_NUM_THREADS=1 so openmp does not spawn its thread pool?
this is a debug binary and not a relwithdebinfo one?

**Comment by plgbrts** [comment]
I have set the two variables as you suggested, unfortunately the issue remains. It is indeed a debug binary.  As you and Markus cannot reproduce the problem I feel it is a wsl related issue (assuming both of you are not using wsl).  Currently I am using wsl 1 but hopefully soon be able to use wsl 2 when I get a windows upgrade. Hopefully shifting to wsl 2  helps.
Anyhow, if someone in the OPM community can successfully use gdb  with wsl 1 or 2 or if it fails to work  I would be interested to know.

**Comment by plgbrts** [comment]
After receiving the windows 10 upgrade to 1909 and installation of wsl2 the problem was resolved

**Comment by blattms** [comment]
Cool. Thanks for getting back
