### ISSUE TITLE
Problem running ECL data files

### ISSUE THREAD

**Issue by dibyatanuk** [OPM/opm-simulators#2783]
Hi,
 
I was trying to run SPE1 case from ECL tutorial data files folder on opm-simulator. I am facing the following problems:
 
1. I get an error on BGSAT, saying that ‘BGSAT contains too many items’. This is unexpected because it is defined exactly the way indicated in OPM documentation.

2. When I removed BGSAT and all other block outputs from the data deck, I get another error saying ‘Failed to create EclipseState object. Exception caught: EclipseGrid needs cornerpoint or cartesian keywords.’. There are also a bunch of preceding warnings:

![image](https://user-images.githubusercontent.com/70562236/92987853-f564d100-f4e3-11ea-8eac-8648380966ef.png)
 
Kindly help me with the problem. I am attaching the data deck and PRT files for your reference.
 
Thanks in advance!
 
Regards,
Dibyatanu

**Comment by joakim-hove** [comment]
> I get an error on BGSAT, saying that ‘BGSAT contains too many items’. 

The `BGSAT` keyword should look like this:
```
BGSAT
    1 2 3 /
     4 5 6 /
/
```

If your `BGSAT' keyword indeed looks like this the problem might be elsewhere - in a keyword immediately before or after. When something is wrong it can often be difficult to exactly pinpoint where and give a correct error message.

> Failed to create EclipseState object. Exception caught: EclipseGrid needs cornerpoint or cartesian keywords.’.

The simulator did not understand/find the keywords used to describe the grid - again that might be the real problem, or the problem might be something else with the keywords in the immediate vicinity.

>There are also a bunch of preceding warnings:

These warnings just say that a certain keyword is not supported (i.e. ignored by OPM Flow) - whether that is a real problem or not will be up to you to judge, but in general this should not be a problem.

> [...] I am attaching the data deck and PRT files for your reference.

Be very careful that you are actually allowed to publish the data deck if you post it here. I would rather suggest you work with the testcases located here: https://github.com/OPM/opm-tests/

**Comment by dibyatanuk** [comment]
Thanks, Joakim.

You were right regarding the construction of the BGSAT keyword. Apparently ECLIPSE doesn’t need the terminating / after each block address, hence the problem.

I am still struggling with the data deck though. This time the error I get is ‘Segmentation fault: 11’. Could you please lead me to what this one refers to?

Re: sharing the data file, I am glad that I forgot to add the attachment. I will surely take a note of sharing permissions in the future.

Regards,
Dibyatanu

**Comment by bska** [comment]
@dibyatanuk : I'm closing this issue now.  Please open another if you still see similar issues running other models.
