### ISSUE TITLE
Need for oil phase in well implemenation

### ISSUE THREAD

**Issue by goncalvesmachadoc** [OPM/opm-simulators#2790]
We are working on debugging the water single-phase executables flow_onephase and flow_onephase_energy. The first place it breaks is in the StandardWell_impl.hpp:
![image](https://user-images.githubusercontent.com/54812829/93462143-21b68e00-f8e6-11ea-9126-d63d00b30f08.png)
We would like to have a better insight on why the need for oil requirement in here before start "messing" with the code. We also would need to change it for the implementation of water-gas model.

**Comment by GitPaean** [comment]
It is a assumption from past. We should update it to handle the situation without oil involved.

**Comment by GitPaean** [comment]
I can be wrong. 

Most likely you need to add guard when you use `pu.phase_pos[Oil]`, this function might be fine.  

And you need to remove the first line of assertion. 

Not sure about other parts yet.
