### ISSUE TITLE
Nightly Crashes on Norne in Parallel

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2834]
Nightly crashes on Norne in parallel log file attached. Runs in serial okay

[NOR01-PRED01-OPM-NB-R00.zip](https://github.com/OPM/opm-simulators/files/5322535/NOR01-PRED01-OPM-NB-R00.zip)

Have a nice day :-)

**Comment by atgeirr** [comment]
> Duplicate

... of what issue? A fixed one? In any case, it works for me with 2 and 8 processes this morning.

**Comment by blattms** [comment]
I think we should add the operating system somewhere (Ubuntu ???)
