### ISSUE TITLE
Deadlock/ MPI message truncation when using CPR and AMG

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2894]
running norne with the current rc of flow from the Ubuntu packages with 16 processes I am experiencing the following:
1. using `--linsolver=amg` an exception is thrown:
```
Time step 0, stepsize 1 days, at day 0/8, date = 06-Nov-1997
Restart file written for report step:   0/247.  Date: 1997/11/06
[galadriel:4255] *** An error occurred in MPI_Alltoallv
[galadriel:4255] *** reported by process [21692417,6]
[galadriel:4255] *** on communicator MPI_COMM_WORLD
[galadriel:4255] *** MPI_ERR_TRUNCATE: message truncated
[galadriel:4255] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[galadriel:4255] ***    and potentially your MPI job)
[galadriel:04239] 2 more processes have sent help message help-mpi-errors.txt / mpi_errors_are_fatal
[galadriel:04239] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
```
2. using using `--linsolver=cpr` flow deadlocks (most probably in the setup phase of the first linear solve).

This should not hold back the release, but the parallel versions using CPR/AMG should be marked as experimental.

**Comment by atgeirr** [comment]
That run works for me (without the PARMETIS[via ptscotch] redistribution), but I suspect you see the same problem that I observed when I tested with ptschotch. I suspect it happens (sometimes at least) when redistributing to a number of processes between 1 and N (where N is the number of processes originally).

Halvor managed to trigger a similar error (quite possibly the same) by running SPE9 with 9 processes, using `--cpr-reuse-setup=0` and the following json configuration:
```
{
    "maxiter": "20",
    "tol": "0.01",
    "verbosity": "2",
    "solver": "bicgstab",
    "preconditioner": {
        "type": "cpr",
        "weight_type": "quasiimpes",
        "finesmoother": {
            "type": "ParOverILU0",
            "relaxation": "1"
        },
        "pressure_var_index": "1",
        "verbosity": "0",
        "coarsesolver": {
            "maxiter": "1",
            "tol": "0.10000000000000001",
            "solver": "loopsolver",
            "verbosity": "0",
            "preconditioner": {
                "type": "amg",
                "alpha": "0.33333333333300003",
                "relaxation": "1",
                "iterations": "1",
                "coarsenTarget": "10",
                "pre_smooth": "1",
                "post_smooth": "1",
                "beta": "1.0000000000000001e-05",
                "smoother": "ILU0",
                "verbosity": "3",
                "maxlevel": "15",
                "skip_isolated": "0"
            }
        }
    }
}
```
I think if you can reproduce that it would be a much smaller case and easier to debug.

**Comment by hnil** [comment]
low --matrix-add-well-contributions=false --linsolver=cpr_spe9.json --cpr-reuse-setup=0 /data/hnil/GITHUB/OPM/opm_source/master/opm-tests/spe9/SPE9_CP.DATA --output-dir=test_spe9 --linear-solver-reduction=1e-2

**Comment by blattms** [comment]
I think I found the problem (at least for AMG but I would assume that this also holds for CPR):

In DUNE we assume that finite element/volume matrices have a symmetric sparsity pattern (not only in the interior/owner region) and this assumption is used to build the ParMETIS/PTScotch graph more easily. ParMETIS requires that for any vertices v and u that share edge there is one from u->v and one from v->u, and hence the number of edges is always even.

In OPM we have started to violate this to quench out some bits of performance for ILU0 (skipped all nonzeros in overlap rows besides the diagonal!) and this now falls on our feet as the graph passed to ParMETIS/Scotch might have an uneven number of edges. Even if it has an even number (by chance), the processing of it might be wrong.

If the agglomeration happens to 1 process, this not an issue because ParMETIS/PTScotch is not used at all. There is an option to always request that. There is also a define to request partitioning sequentially and/or on the communication graph, I am just not sure whether these were tested during the last years.

**Comment by atgeirr** [comment]
> I think I found the problem (at least for AMG but I would assume that this also holds for CPR):

Your analysis sounds good to me. I guess the fix will be to look at our owned rows when building the graph passed to ParMETIS, and not the owned columns?

**Comment by blattms** [comment]
For the release I see two options

- Backport #2899 
- List it as a know bug and tell users that they need to compile themselves and set -DAMG_REPART_ON_COMM_GRAPH in the compile flags (maybe we can use that define for compiling the final binary packages, though).

**Comment by blattms** [comment]
> Your analysis sounds good to me.

I am starting to doubt part of it. Namely, the part where the unsymmetry (of the parallel ParMETIS graph) comes from. The local part  ParMETIS graph only knows owned/interior vertices and is created from the matrix rows associated with them. Hence the ghost/overlap changes I mentioned above should have no influence on the symmetry.

**Comment by bska** [comment]
> For the release I see two options

As the release manager I'm not doing anything for the release until we're sure the issue is fully resolved.  This is a release blocker.

**Comment by blattms** [comment]
Not sure what you mean by fully resolved. If that means totally understood where the problem comes from and cleanly fixed it (e.g. upstream),  this might postpone things quite a bit. I need to prioritize other work and do not intend to spend a lot more time here the next weeks.

Maybe @totto82 or @atgeirr can double check  #289 if that helps.

**Comment by bska** [comment]
> If that means totally understood where the problem comes from and cleanly fixed it (e.g. upstream)

Yes, that is what I mean.  Fully analyzed, with a fix in place and verification that the fix actually solves the problem.

> this might postpone things quite a bit.

Yes, that's why it's so serious.

**Comment by blattms** [comment]
Then quite a bit might become next year.

Let me sum up this issue:
1. It probably has been there for quite some time (At least 2020.04 and 2019.10)
2. Due to the a problem of the build system the problem only surfaced for ParMETIS and not for PTScotch (because even if it was there, it was not used). 
3. There is no issue for the default solver (only CPR and AMG). That is why only few noticed.
4. For people with PTScotch installed the bug only appeared, when the buildsystem was fixed in #2038. Again, if people had ParMETIS it was there before (There were reports about this).
5.There are to PRs that are at least working around the problem #2898 (approved and tested by others) and #2899 .
6. The apparent problem for the user is the deadlock which (at least on my system) is fixed by both PRs. (It should solve the problem for both ParMETIS and PTScotch).
7. Reverting #2038 will only fix the problem for people with PTScotch (by deactivating it). For people with ParMETIS it will persist.
8. It is unclear where the unsymmetry actually comes from. Finding that out will take time that does not seem to be available.

**Comment by atgeirr** [comment]
I propose merging #2898 to have a workaround, then backport that to the release. The release may then have non-optimal scaling with CPR, but at least it should run without risk of crashing, unlike the current code (and previous release).

Then we may take more time to investigate the issue, and merge #2899 to have a more "likely to give a good solution" approach in master. The reason I suggest merging #2898 to the release instead of #2899 is that I think the first is a bit safer and sure to work (and it has been tested and verified by @totto82).

**Comment by bska** [comment]
I concur with [@atgeirr's comment](https://github.com/OPM/opm-simulators/issues/2894#issuecomment-722401327). That seems to me the most prudent option for the release.

**Comment by atgeirr** [comment]
> I concur with [@atgeirr's comment](https://github.com/OPM/opm-simulators/issues/2894#issuecomment-722401327). That seems to me the most prudent option for the release.

I will then merge #2898.

**Comment by blattms** [comment]
For the record. The cause was discovered 5 years ago in #357. We skip small values in the matrix for performance.

**Comment by atgeirr** [comment]
> We skip small values in the matrix for performance.

Are you sure? Back then, this happened in the fastSparseProduct() function used in the AD library in use at the time. Where does it happen now?

**Comment by blattms** [comment]
No I am not sure. Just hoped to get around an investigation.

**Comment by atgeirr** [comment]
Could it possibly happen in the AMG itself? That at some coarse levels, some small entries are ignored? (I admit it does not sound likely.)
