### ISSUE TITLE
pvt region index in BlackoilWellModel::checkGroupHigherConstraints inconsistent in parallel run.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#2921]
In parallel this is much worse. Not only might the pvt region computed have no association to the wells of the group, but may also be different from process to process as there might be no local wells and if there are the first one might not be the same well
[BlackoilWellModel_impl.hpp#L2390](https://github.com/OPM/opm-simulators/blob/0dcfc6036339f1b9fa10100db21666acea4d37d4/opm/simulators/wells/BlackoilWellModel_impl.hpp#L2390) 

~There is a very problematic data access at [BlackoilWellModel_impl.hpp#L2390](https://github.com/OPM/opm-simulators/blob/0dcfc6036339f1b9fa10100db21666acea4d37d4/opm/simulators/wells/BlackoilWellModel_impl.hpp#L2390) where we do
`pvt_region_idx_[well_perf_data_[0][0].cell_index]`. The problem is that well_perf_data has an entry for each global well, but if the
well at index 0 is not in this process's then `well_perf_data_[0]` is an empty vector.~

I would fix this, but it is very misty what the original code is trying to do. At least it is not clear to me, why anyone would query a well without even testing if that well belongs to the group we are computing for.

This really stalls me and I need help.

**Comment by blattms** [comment]
Closing. I need to double check. Might reopen.

**Comment by blattms** [comment]
Indeed, the erroneous data access seems to be in my branch.

Still, I do not get why the pvt region index can be independent of the group we calculate for.

**Comment by atgeirr** [comment]
> Still, I do not get why the pvt region index can be independent of the group we calculate for.

We do not really know how it is intended to be done (as stated in the comment above). The current approach is a temporary solution that has turned into a long-term one. How can we choose a single PVT region for a group, that could includes several wells, each of which is perforated in multiple PVT regions? My guess is that a different approach is required long term, that uses pvt properties of cells involved already calculated and do not evaluate the pvt functions here. @bska do you have a better understanding of this?

**Comment by blattms** [comment]
Reopened and changed the description. There definitely is a bug if there is more than one pvtregion in parallel.

AT the very least we need to decide which well will govern the pvtregion used in parallel. Should be the first global one in the schedule? (Still not correct but at least consistent)

**Comment by blattms** [comment]
Will prepare something that at least fixes the parallel inconsistency.

**Comment by bska** [comment]
> How can we choose a single PVT region for a group, that could includes several wells, each of which is perforated in multiple PVT regions?

I don't know this but my best guess would be that a group's `RESV` flows is just the typical sum, possibly modified by efficiency factors, of its children's `RESV` flows.  This ultimately reduces to `RESV` flows at the well level and at least for those there is a well-defined region definition supplied in [item 11](https://github.com/OPM/opm-common/blob/8ffb918650b8f0b00b326729da8c3f3cb2c76ebf/src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELSPECS#L53-L57) (table for converting surface to reservoir rates) and [item 13](https://github.com/OPM/opm-common/blob/8ffb918650b8f0b00b326729da8c3f3cb2c76ebf/src/opm/parser/eclipse/share/keywords/000_Eclipse100/W/WELSPECS#L63-L67) (FIP region from which to calculate average pressure &c) of `WELSPECS`.  On the other hand, our parser [doesn't really handle item 13](https://github.com/OPM/opm-common/blob/8ffb918650b8f0b00b326729da8c3f3cb2c76ebf/src/opm/parser/eclipse/EclipseState/Schedule/KeywordHandlers.cpp#L1185-L1189) and will implicitly reset non-zero values back to zero.

**Comment by joakim-hove** [comment]
> On the other hand, our parser doesn't really handle item 13 and will implicitly reset non-zero values back to zero.

I don't know why item 13 is ignored in the input process; my assumption was that it was quite some fidgety stuff which was perceived as not needed at the time. Should be a small effort to fix.
