### ISSUE TITLE
GPU support in Docker images

### ISSUE THREAD

**Issue by Tongdongq** [OPM/opm-simulators#2942]
The [website](https://opm-project.org/?page_id=853) contains a tutorial on how to run Flow in Docker. To use a GPU from within a Docker container, an extra argument is needed.
`docker run openporousmedia/opmreleases:latest ...`
`docker run --gpus 'all,"capabilities=compute,utility"' openporousmedia/opmreleases:latest ...`
This exposes all GPUs to the container, and allows computation on it. Perhaps `utility` is not needed, but `nvidia-smi` is a useful utility tool.
The [official docs](https://docs.docker.com/config/containers/resource_constraints/#access-an-nvidia-gpu) have more info on how to install the `nvidia-container-runtime
` package and use Docker with an NVIDIA GPU.

[Dockerhub](https://hub.docker.com/r/openporousmedia/opmreleases) lists a few releases, but the latest is 2019.10.
@atgeirr I tag you because pushed the images to Dockerhub.

**Comment by atgeirr** [comment]
I have pushed the latest release to Dockerhub, thank you for the reminder. I am not familiar with GPU and Docker myself, if you have suggestions for additional or changed content for the tutorial, please send it to me, and I will integrate it!
