### ISSUE TITLE
2020-10 SUMMARY keywords WTICHEA and WTPCHEA Reporting Incorrect Temperature

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#2952]
For this release we added support for well-level temperature summary output in thermal simulations (SUMMARY keywords WTICHEA and WTPCHEA). However, the reported temperature is incorrect, compared to the commercial simulator, as you can see below.

![image](https://user-images.githubusercontent.com/17958927/100585043-e42fa180-3327-11eb-8536-920a48cdf549.png)

**Comment by cim456** [comment]
Yes, the keyword WTICHEA was fixed after the release freeze and the current master matches the commercial simulator. @plgbrts will work on fixing WTPCHEA before the end of this year. We are trying to be sure first how it is computed. Our first thought was to report the temperature at reference depth, but it seems the commercial simulator computes an average using all cells connected to the well. Do you have any insights?

**Comment by goncalvesmachadoc** [comment]
That is fixed now. Can we close this issue?

**Comment by bska** [comment]
> Can we close this issue?

Happily!  Thanks a lot for checking up on this.
