### ISSUE TITLE
Only build flow

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#3048]
For my day to day work I only need to compile the binary `flow` - not varants like `flow_ebos_foam` or `flow_libebos_polymer_injectivity`. Is it possible to get a cmake switch to only build `flow`? I have tried setting `BUILD_FLOW_BLACKOIL_ONLY=ON` but I still get variants like `flow_ebos_oilwater_brine` - and the link time is quite long ...

**Comment by GitPaean** [comment]
is `flow_blackoil` enough for you?

**Comment by joakim-hove** [comment]
Ehhh - I really don't know/understand the details of the opm-simulators buildsystem. My typical workfliow is AS follows:

1. I run the testa with ctest.
2. Some tests fail and in the investigation I run `flow CASE.DATA` - possibily with the debugger.

I don't really know where `flow_blackoil` comes into the picture?

**Comment by akva2** [comment]
you can do make flow_blackoil. not 'make', nor 'make flow'. but that's a separate binary. flow consists of all the variants, not just blackoil. if you want to run the tests, you have to build the full simulator suite because all of them are tested.

**Comment by totto82** [comment]
For testing you will need to build `flow`. But while developing `flow_blackoil` or your own `flowFoo` where what every you are interested in is disabled/enabled is very time saving since you only build you variant.

**Comment by GitPaean** [comment]
Yes. `flow` contains all the following
```
241 set(COMMON_MODELS brine energy extbo foam gasoil gaswater oilwater oilwater_polymer polymer solvent)
242 set(FLOW_MODELS   blackoil oilwater_brine oilwater_polymer_injectivity)
```

`flow_balckoil`
it only contains `0   $<TARGET_OBJECTS:flow_libblackoil>`

But ctest need a full build of `flow`.

**Comment by joakim-hove** [comment]
OK - thank you; I will use `make flow_blackoil` for my interactive endeveours.

**Comment by joakim-hove** [comment]
OK - thank you; I will use `make flow_blackoil` for my interactive endevours.
