### ISSUE TITLE
Always print what solver/precondioner is used on the GPU

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#3052]
Currently this is only done if verbosity is at least 2 (i.e. almost never). Nevertheless the flexible solvers always print their configuration and we see in the `*.DBG` file:
```
Found 2 OpenCL platforms

Chosen:
Platform name      : AMD Accelerated Parallel Processing
Platform version   : OpenCL 2.0 AMD-APP (3212.0)

Found 1 OpenCL devices

Chosen:
CL_DEVICE_NAME            : gfx803
CL_DEVICE_VERSION         : OpenCL 1.2 

Property tree for linear solver:
{
    "tol": "0.01",
    "maxiter": "200",
    "verbosity": "0",
    "solver": "bicgstab",
    "preconditioner": {
        "type": "ParOverILU0",
        "relaxation": "0.90000000000000002",
        "ilulevel": "0"
    }
}
```
That is a bit confusing. IMHO there should be information on the GPU solver and that it is preferred.

**Comment by blattms** [comment]
@Tongdongq Please take a look at this.

**Comment by blattms** [comment]
BTW Coloring should also be printed there. Then there is no need to search in the print out of the command line arguments.

**Comment by Tongdongq** [comment]
Where can I edit this?

**Comment by blattms** [comment]
You shouldn't. Simply print the OpenCL solver information after the OpenCL platform/device information

**Comment by Tongdongq** [comment]
Is this fixed with https://github.com/OPM/opm-simulators/pull/3150?

**Comment by blattms** [comment]
Probably, Thanks. Closing.
