### ISSUE TITLE
Time datastructure used in opm

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#3080]
In current master the elements of time on opm is mainly handled with a combination of `std::time_t time_point` and `double seconds` - it works, but is not very forward leaning. As part of the https://github.com/OPM/opm-common/issues/2176 refactor I have used `std::chrono` as datatype for timepoints. Up until now the `std::chrono` members have been a little bit on the side, and not really used - but with: https://github.com/OPM/opm-common/pull/2310 the `std::chrono`variables are used for real - and then comes some problems/questions. The core of the problem is that the default time point:
```
std::chrono::system_clock::time_point tp;
```
represents time as *nanoseconds* since the epoch - that implies that the default time will roll around 2280 - I guess that is a bit too soon? So then I see the following alternatives:

**Update:** I was distracted while writing this issue, and in the meantime @bska mentioned several of the important points. Anyway here comes the rest:

Since we only have the old C api for calendar service we must use `std::time_t` *somewhere* in the code. I guess the alternatives are:
1. Current situation : `std::time_t` everywhere downstream of opm-common.
2. Alternative: fully private calendering services in opm-common and `std::chrono` everywhere downstream. 

**Conversion between `std::time_t` and `std::chrono`**: The standard method for converting between `std::time_t` and `std::chrono::system_clock::time_point` are the functions:
```C++
std::time_t = std::chrono::system_clock::to_time_t( );
std::chrono::system_clock::time_point tp = std::chrono::system::clock::from_time_t();
```
these functions only exists for the default `std::chrono` timepoint type, so if we wish to use an alternative resolution we must implement and maintain our own conversion routines (no big deal).

1. The novel use of `std::chrono` in `Schedule` datastructures could be reveresed - just stick with `std::time_t` and be done with it.
2. Accept 292 years as maximum time range and do a gradual transition from `std::time_t` to `std::chrono`
3. Use our own resolution with `std::chrono` - e.g. milliseconds should give use `292 * 10^6` years - that ought to be enough for everybody!

Alterantives 2 and 3 are in principle quite similar, but since alternative 3 also requires us to implement our own conversion routines I would say that would require more attention to a private implementation and also a larger up front change. 

My preference is with alternative 3 - as I see it is the most forward leaning, but that will (probably) changes many places. Would suggest to add the changes as part of  https://github.com/OPM/opm-common/pull/2310. 

**double / std::chrono::duration<>:** A related but somewhat different question is the timetype to use for seconds in the simulator; we could use `std::chrono::duration<double>` to look cool - or we could just stick with plain `double`? 

Please speak up your opinions!

**Comment by bska** [comment]
> he core of the problem is that the default time point:
> 
> ```C++
> std::chrono::system_clock::time_point tp;
> ```
> 
> represents time as _nanoseconds_ since the epoch

There's not guarantee of that.  The libstdc++ **implementation** however uses that choice.

**Comment by bska** [comment]
Just a quick follow-up: There's nothing that prevents us from using/storing time points as
```C++
std::chrono:time_point<std::chrono::system_clock, std::chrono::microseconds>
```
to get more range out of the type&mdash;roughly 292,000 years in the case of libsdc++'s implementation of `system_clock`.  The problem with **that** however, is that `system_clock` (in C++17) is the only facility that provides calendar services, and that it does so in terms of `std::time_t` and the low-level `std::tm` type along with `std::localtime()`/`std::gmtime()`.  In other words, unless we want to implement a complete calendar service, we're stuck with `std::time_t` meaning all uses of (any customisation of) `time_point` has to go through
```C++
std::chrono::system_clock::to_time_t();
std::chrono::system_clock::from_time_t();
```
In C++20 we get **a lot** more calendar services (dates and time zones) which will make this problem moot.

**Comment by bska** [comment]
@joakim-hove : I believe this can be closed now.

**Comment by joakim-hove** [comment]
An initial direction has been selected here
