### ISSUE TITLE
Geothermal case: heat flow balance error with varying DZ

### ISSUE THREAD

**Issue by MarkTNO** [OPM/opm-simulators#3132]
Good afternoon,

We have a horizontally continuous model with only water present with two wells: one injector (injecting 30 degC water) and one producer. This creates a cold water bubble around the injector.
The 'simple' model (on the left in the picture below) has a continuous grid spacing. In the 'simple_1' model (on the right in the picture below) the over- and underburden consist of 1 layer with large DZ. The cold water bubble in the simple_1 model on the right is much smaller.
This 'simple_1' model was also run in Eclipse100 which gave a similar result to the simple model.

Additionally we compared the injected heat in the well (cold: 30 degC vs initial temp 84 degC) to the total cooling of all cells in the models (per grid cell: _delta_temp * bulk_volume * (1-por) * SPECROCK + deltaTemp * bulk_volume * por * SPECHEAT_) :
- injection well: _(30 degC - 84 degC) * 30 years * 365 days * 7200 m3/day * 3.8 kJ/kg/K * 1000kg/m3 = -1.62E13 kJ_ injected heat
- simple model OPM: _-1.6E13 kJ_ sum delta heat of all cells
- simple_1 model OPM: _-1.0E13 kJ_
- simple_1 model Eclipse100: _-1.59E13kJ_

The -1.0E13kJ for simple_1 model OPM is too small. This calculation confirms our visual conclusion based on the pictures below that the cold water bubble in the 'simple_1' model is too small. Dividing the over- and underburden into two z layers gave a similar result for simple_1 OPM, meaning that the bubble is still too small.

I can provide the OPM and Eclipse decks if needed. I discussed this with my colleague Cintia (@goncalvesmachadoc). We are both available for questions.

Kind regards,
Mark Vrijlandt

![simple](https://user-images.githubusercontent.com/25008935/112176197-2e4ed280-8bf8-11eb-9661-3914c4a8c92b.jpg)

**Comment by totto82** [comment]
Looks like boundary issues. Are you using `flow_onephase_energy ` for your simulations? By default flow impose no thermal flow boundaries, but there is an compile time option to keep the geothermal gradient by allowing for thermal flux across the boundary.  Look for `enableThermalFluxBoundaries `in `eclproblem.hh`.

**Comment by MarkTNO** [comment]
We are using flow with a shallow contact above the model, meaning only water in the model.

If there are no thermal boundary conditions, does that mean that there is no heat exchange? Because in this case extra heat is somehow introduced into to the model (cold bubble too small). I also tried padding the model with extra cells above and below (see image below.) The problem of a small cold water bubble still occurs.

Could it be that there is an issue with heat conduction with these very elongated cells?

![image](https://user-images.githubusercontent.com/25008935/112442614-4fc0d300-8d4c-11eb-81c1-4262a7278032.png)

**Comment by totto82** [comment]
> Could it be that there is an issue with heat conduction with these very elongated cells?

That seems plausible. I noticed that thermal conductivity uses a different definition of cell center coordinates than the standard  transmissibility. I will do some checking to see if this could be the cause. 

> I can provide the OPM and Eclipse decks if needed. 

A deck file would be nice. If its small and shareable you can just upload it here, or just send to me by email. I don't need the data files.

**Comment by MarkTNO** [comment]
I sent you an email with input deck for the three models.

**Comment by MarkTNO** [comment]
Bug fix solved the issue: https://github.com/OPM/opm-simulators/pull/3138

Thanks for the quick action!
