### ISSUE TITLE
OPM Simulators Module does not Have a LICENSE File

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#3139]
Did we simply forget to add a LICENSE file (with a copy of GPL v3) to our top-level directory in opm-simulators or is there some other reason that this file does not exist?

**Comment by atgeirr** [comment]
> is there some other reason that this file does not exist?

Not to my knowledge, please add!

**Comment by bska** [comment]
> > is there some other reason that this file does not exist?
> 
> Not to my knowledge, please add!

Thanks for confirming.  I've added the file in #3142.
