### ISSUE TITLE
Official Debian Packages

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#3172]
This is for people interested in this effort. The current state is on [salsa.debian.org](https://salsa.debian.org/blattms/opm-simulators). This is currently being finalized (mainly coming up with good package descriptions), and will then be submitted to debian.

**Comment by blattms** [comment]
After preparing packages for the new release, we found a Sponsor (Anton Gladky), who so kind as to upload the packages to the [NEW queue of ftp master.](https://ftp-master.debian.org/new.html). There it will be manually checked (e.g. license, etc.) and either rejected  or added to official Debian. This process can take a while. It is a volunteer effort after all. There 372 packages in the queue (some for 8 month).

Anyway, interaction and support for Anton and Debian (Science) was amazing.

- [ITP bug for OPM at Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=987381)

**Comment by joakim-hove** [comment]
> After preparing packages for the new release, we found a Sponsor

Great news - fantastic effort!

**Comment by alfbr** [comment]
This is great news, thank you for a tedious and impressive effort! Crossing fingers for acceptance :-)

**Comment by blattms** [comment]
Well, you can only do a good job if the base is good. Hence this is a team effort: Good software quality from all OPM devs, a very good starting point for the Debian packages  prepared by @akva2, and the amazing suppport and tools (git-buildpackage, pristine-tar, autopkgtest, linitian, ...) provided by Debian.

**Comment by blattms** [comment]
:tada: :partying_face: Next step taken. Yesterday QA of ftpmaster have accepted opm-common and opm-material into Debian unstable. I assume the rest will follow in due time.

**Comment by bska** [comment]
> Yesterday QA of ftpmaster have accepted opm-common and opm-material into Debian unstable.

Congratulations @blattms!  Great achievement.

**Comment by atgeirr** [comment]
Nice! What does this mean for us in terms of keeping the Debian packages up to date?

**Comment by blattms** [comment]
That we, as in @akva2 and me, mostly maintain the packages and try to find a workflow where we base Ubuntu packages on them to save work. Not sure whether that answer your question.

**Comment by blattms** [comment]
opm-models got accepted, too.

Unfortunately, opm-grid, opm-simulators, and opm-upscaling were rejected because of copyright attribution inconsistencies. I used the new names for institutions in debian/copyright (without any clarifying comments), but our headers still reference Statoil, IRIS, UniResearch, etc. Hence the reviewer simply had to reject them as it seemed like we did miss some in our copyright attribution.

Already on it, but the re-review might take some time again.

**Comment by atgeirr** [comment]
Thanks for the update, and the work! What is the best practice dealing with renamed entities? I think changing "IRIS 2012" to "NORCE 2012" is not good, as NORCE did not exist then for example. Attributing to "IRIS, now part of NORCE" in the attribution file may be the best, leaving the copyrights in old files as they are?

**Comment by blattms** [comment]
Well I think the institutes involved should discuss this and change themselves. There has been PR #3191 for discussion that never received any attention...

I'll comment anyway. IMHO if there is a merger than the new entity probably acquires all the copyright of the previous ones (which seize to exists). Same for  a rename. Hence it it is the other way around... A non-existing entity cannot hold copyright.

What we do here will have no effect on the last release. Changes for the packages have been done (hopefully sufficiently) in 
+ https://salsa.debian.org/science-team/opm-grid/-/commit/fd5c1e7830c8894f8db9d5d2d4aede96885eddd6 
+ https://salsa.debian.org/science-team/opm-simulators/-/commit/21251f777adb87332971ffb96f1d6b587de13918
+ https://salsa.debian.org/science-team/opm-upscaling/-/commit/1b354c5d315006dda9627a8cdd7ca8f24993cff7

**Comment by alfbr** [comment]
> What we do here will have no effect on the last release. Changes for the packages have been done (hopefully sufficiently) in
> 
>     * https://salsa.debian.org/science-team/opm-grid/-/commit/fd5c1e7830c8894f8db9d5d2d4aede96885eddd6
> 
>     * https://salsa.debian.org/science-team/opm-simulators/-/commit/21251f777adb87332971ffb96f1d6b587de13918
> 
>     * https://salsa.debian.org/science-team/opm-upscaling/-/commit/1b354c5d315006dda9627a8cdd7ca8f24993cff7

This looks fine from our end, I support merging it into master.

**Comment by blattms** [comment]
BTW: Seems like packages might get into official Ubuntu automatically, See proposals for jammy:
+ https://launchpad.net/ubuntu/+source/opm-common
+ https://launchpad.net/ubuntu/+source/opm-material
+ https://launchpad.net/ubuntu/+source/opm-models

**Comment by blattms** [comment]
Debian packages opm-common, opm-material, opm-models have migrated to Debian testing. The rest have been fixed and reuploaded for review in the NEW queue of ftpmaster.
See [my qa dashboard](https://qa.debian.org/developer.php?email=markus%40dr-blatt.de), where you can also look at the build failures on various platforms

**Comment by blattms** [comment]
The remaining packages got accepted by ftpmaster last night and are currently build for sid. I will have to prepare source only uploads for them such that they can migrate to testing. Once done I will close this issue

**Comment by blattms** [comment]
As those will be proposed to Ubuntu 22.04 with feature freeze on February 21. There is a chance that OPM version 2021.10 will become official packages of that Ubuntu release, too. But its tight.

**Comment by blattms** [comment]
Some more fixes were needed, but now all packages have migrated to Debian testing (architectures amd64, arm64, ppc64el). That means that OPM will become part of the next official Debian release.

I am still struggelling with how Ubuntu works. But it seems to me that there will at least be packages based on the Debian ones in the Ubuntu universe repository that might usable with 22.04 or later.

I am also now able to upload updates of the packages myself.

Closing this.

**Comment by blattms** [comment]
Just noticed that currently 5 out of 6 packages migrated to [Ubuntu 22.04,](https://packages.ubuntu.com/search?keywords=libopm&searchon=names&suite=all&section=all), just opm-simulators is still missing. Will try to find out why. Might just be the long build time.

**Comment by gladk** [comment]
Graham, could you please check, why opm-simulators was not
synced into the Ubuntu automatically?

There is a family of packages opm-*, which are needed for some kind of
simulations of porous media. But only one of packages is missing.

Thanks!


Anton


Am Di., 8. März 2022 um 13:47 Uhr schrieb Markus Blatt <
***@***.***>:

**Comment by ginggs** [comment]
opm-simulators 2021.10-4 was auto-sync'd into Ubuntu, however it FTBFS there:
https://launchpad.net/ubuntu/+source/opm-simulators/2021.10-4

From the buildlog:
```
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
My guess is OOM, and reducing parallelism in the build may work around that.

**Comment by blattms** [comment]
Hi Graham,

that seems very likely. On Salsa I had to disable parallel building, too.
It is quite a pity that we tend to sometimes need more than 3GB peak RAM 
per process when building.

Thanks for looking into it.

**Comment by ginggs** [comment]
I tried setting `--max-parallel=2` but ended up having to go with `--max-parallel=1`.
I then ran into an issue with LTO, which is not yet enabled in Debian, and needed to disable it.

I've uploaded opm-simulators 2021.10-4ubuntu1 with the changes above:
https://launchpad.net/ubuntu/+source/opm-simulators/2021.10-4ubuntu1

Currently, the only way is by modifying the packaging.  It would be good if we could get these changes into Debian so that opm-simulators can be autosync'd again.

**Comment by blattms** [comment]
@ginggs Thanks  a lot. I am in the process of putting your changes into the [salsa repo](https://salsa.debian.org/science-team/opm-simulators) Not sure whether releasing 2021.10-5 with only this change makes sense, but it will definitely be part of the next release.
Do you recall what the problem with LTO was?

**Comment by ginggs** [comment]
No need for releasing 2021.10-5 with only this change.

Sorry, I didn't keep the failed LTO build log.  You should be able to reproduce it building in Ubuntu 22.04, otherwise I can try again tomorrow.

**Comment by blattms** [comment]
No worries. I can do that. Just need to set up a machine or a chroot.
