### ISSUE TITLE
2021-04 Bug in Release: Numerical Aquifers.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3228]
The numerical aquifer test cases fail, probably because the the AQUCON and AQUNUM keywords for numerical aquifers are in the unsupported list of keywords, may be somebody should remove them from the list.

Perhaps we should have a patch release, after I have gone the rest of the new implementations.

[AQF01-NUM01.zip](https://github.com/OPM/opm-simulators/files/6450920/AQF01-NUM01.zip)
[AQF01-NUM02.zip](https://github.com/OPM/opm-simulators/files/6450922/AQF01-NUM02.zip)

**Comment by OPMUSER** [comment]
I ran the jobs in the wrong VM which why they failed, so let me run again with the correct version and get back to everyone.

**Comment by OPMUSER** [comment]
The numerical aquifer test cases run but the AQUCON and AQUNUM keywords for numerical aquifers are reported as unsupported, may be somebody should remove them from the missing features list.

![image](https://user-images.githubusercontent.com/17958927/117652519-d5e28d00-b1c5-11eb-8f69-a7e309dfc6dd.png)

Note we get different results to the commercial simulator (red lines). The blue and and green lines are OPM 2104 and OPM 2104 MPI and are identical.

Note also that none of the numerical summmary vectors are not written out either, as per:

```
--
--       NUMERICAL AQUIFER (FIELD)
--
FNQR
FNQT
--
--       NUMERICAL AQUIFER
--
ANQP
/
ANQR
/
ANQT
/       

```

**Comment by totto82** [comment]
I think the aquifer pore volumes should be taken out from the relaxed pv calculation. That should Make it possible to use the same tolerances.

**Comment by OPMUSER** [comment]
Sorry, I forgot about the re-runs -will that tomorrow.

OPMUser

**Comment by OPMUSER** [comment]
Okay, in the figure below NUM01 is the previous non-MPI case, -R01 is with `--relaxed-max-pv-fraction=0`, and -R02 is with `--relaxed-max-pv-fraction=0` and `--tolerance-cnv=0.00001`

![image](https://user-images.githubusercontent.com/17958927/117931310-9d5fc200-b331-11eb-82d2-735bc6eed1ca.png)

So changing the converge parameters only slightly improves the match

Interesting that gas is also significantly different:

![image](https://user-images.githubusercontent.com/17958927/117932007-7786ed00-b332-11eb-8575-5a0ec772060b.png)

But the pressure is close until near the end of the run.

![image](https://user-images.githubusercontent.com/17958927/117932264-b7e66b00-b332-11eb-9903-1a01cc16f532.png)

It would be good to have the numeric aquifer summary keywords FNQR and FNQT to see if there was a difference with the aquifer influx.

There are very small differences between the TRANX, TRANY and TRANZ values between the ECL and OPM cases. Take a look of the histrogram data in the figure below:

![image](https://user-images.githubusercontent.com/17958927/117935036-e4e84d00-b335-11eb-91d6-dc2add57c70e.png)

**Comment by GitPaean** [comment]
Okay. Let me take a look. These two cases are regression tests and we checked many many times before.

**Comment by GitPaean** [comment]
@OPMUSER  thank you for testing this.  Could you please also add the tuning by using argument `--enable-tuning=1` when you test it?

Let us check the results first, then we check the problem related to `TRANX, TRANY and TRANZ`. 

> FNQR and FNQT 

You can use ANQR, ANQP and ANQT for this purpose for now.

**Comment by OPMUSER** [comment]
So to update, we have good news and bad news. First the good news, running with the TUNING keyword active gives identical results for all three OPM Flow runs, including the original case with just the TUNING keyword active (R03), as you can see below:

![image](https://user-images.githubusercontent.com/17958927/118098458-850da700-b406-11eb-9dea-886acd38f91d.png)

The AQF01-NUM01 case is the original case without the TUNING keyword (shown by the yellow lines), which was the cause of this journey. So this begs the question, should not the default for enable-tuning be `true`, instead of `false`? After all we will always be comparing to the commercial simulator.

Now for the bad news. **None of the aquifer keywords** are written to the SUMMARY or RSM file, including the ANQR, ANQP and ANQT variables, and there is no warning message indicating that they are ignored, see the attached.

```
Warning: Unhandled summary keyword ALL/FAQR
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/FAQRG
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/FAQT
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/FAQTG
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/FWGR
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/GWGR
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword ALL/WWGR
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 188

Warning: Unhandled summary keyword FNQR
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 199

Warning: Unhandled summary keyword FNQT
In /media/sf_D_DRIVE/Linux/OPM/Aquifer/OPM2104/AQF01-NUM01.DATA line 200

```
[AQF01-NUM01-ECL.zip](https://github.com/OPM/opm-simulators/files/6471292/AQF01-NUM01-ECL.zip)
[AQF01-NUM01-R01.zip](https://github.com/OPM/opm-simulators/files/6471305/AQF01-NUM01-R01.zip)
[AQF01-NUM01-R02.zip](https://github.com/OPM/opm-simulators/files/6471309/AQF01-NUM01-R02.zip)
[AQF01-NUM01-R03.zip](https://github.com/OPM/opm-simulators/files/6471312/AQF01-NUM01-R03.zip)
[AQF01-NUM01.zip](https://github.com/OPM/opm-simulators/files/6471343/AQF01-NUM01.zip)

**Comment by GitPaean** [comment]
Hi, thanks for reporting back. 

I am testing the master branch, which is more handy for me. The summary keywords are output with the master branch
```
summary.x AQF01-NUM01.
ANQP:1                   ANQR:1                   ANQT:1                   FOPR                     FPR                      
TCPU                     WBHP:PROD1               WGOR:PROD1               WOPR:PROD1               WWCT:PROD1               
YEARS 
```

It was implemented from the commit  https://github.com/OPM/opm-common/pull/2252/commits/74921e3668cc42cbcb675df55a07b2eb6b252396

Later today, I can test the release branch. Today it is holiday here.

**Comment by OPMUSER** [comment]
@GitPaean Yes may it didn't make it into the release.

**Comment by GitPaean** [comment]
@OPMUSER , I did not notice you changed the specification for aquifer summary keywords in your attached decks. 

It looks like we do not support the following way for aquifer summary keywords,  

```
ANQP
/
ANQR
/
ANQT
/       
```
@bska  might have some insight about this issue. If I did not read wrong, if we do not specify the aquifer lists, we should output the information for all the aquifers. 
In the opm-tests c

**Comment by OPMUSER** [comment]
Yes using:
```
ANQP
1 /
ANQR
1 /
ANQT
1 /       
```
Outputs the aquifer information.

Now using:
```
ANQP
/
ANQR
/
ANQT
/       
```
Should also work to get all the aquifer data and is a standard format for nearly all summary variables except the block variables.

I mark this as bug in the manual.

**Comment by GitPaean** [comment]
@OPMUSER , please open an issue regarding the aquifer summary keywords, it will be addressed specifically.  If you have no other comments, this issue can be closed after the summary keywords issue is opened.  `TUNING` related can also be a separate issue. The difficulty is that it is really case dependent and making it default can have some significant performance impact depending how the keyword and case are setup.

**Comment by bska** [comment]
> please open an issue regarding the aquifer summary keywords, it will be addressed specifically.

For what it's worth, I'm fixing this right now.  I need these summary vectors for restart purposes anyway.

**Comment by bska** [comment]
> > please open an issue regarding the aquifer summary keywords, it will be addressed specifically.
> 
> For what it's worth, I'm fixing this right now.

PR OPM/opm-common#2473 was just merged.  The master branch now supports summary vectors for numeric aquifers (i.e., keywords `AQNP`, `AQNR`, and `AQNT`) without explicit lists of aquifer IDs.

**Comment by OPMUSER** [comment]
Closing as numerical aquifer summary issue is now #3266
