### ISSUE TITLE
EclWriter Constructor Dereferences Nullpointer in Parallel When Constructing IO Rank Collection Member

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#3237]
Note: The underlying issue may have existed for a long time, but I came across it just now because I was debugging a parallel restart issue using a build that does **not** define `NDEBUG`.

When constructing the `collectToIORank_` data member of class `EclWriter` we make an unconditional call to [`Vanguard::equilCartesianIndexMapper()`]((https://github.com/OPM/opm-simulators/blob/a192ccb417fe0a0df9f51727a3c2b314f4b56d13/ebos/eclwriter.hh#L197)).  This call, in turn, typically resolves to [`EclCpGridVanguard::equilCartesianIndexMapper()`](https://github.com/OPM/opm-simulators/blob/a192ccb417fe0a0df9f51727a3c2b314f4b56d13/ebos/eclcpgridvanguard.hh#L321) which asserts that the member function is only called on the IO rank.  Indeed, the underlying pointer is null on ranks other than the IO rank whence the member function dereferences a null pointer in order to return a reference to the mapper object.

As I said, I don't know when we introduced this issue because I've not really run debugging builds in while.  We still need to fix the issue though.

**Comment by bska** [comment]
@akva2: You did work in this area recently as part of #3204.  Would you mind having a look at how easy it'd be to solve this?

**Comment by akva2** [comment]
Ouch, this is caused by my refactorization. I pass (by calling the vanguard) the equilCartesianIndexMapper unconditionally in the constructor to collectToIORank now.

**Comment by bska** [comment]
https://github.com/akva2/opm-simulators/blob/9def2fab122d87a793482a43257b13554fa28b99/ebos/collecttoiorank.hh#L312

> this is caused by my refactorization.

Actually, I don't think that's true.  Looking at the source code for the [`CollectToIORank` constructor](https://github.com/akva2/opm-simulators/blob/9def2fab122d87a793482a43257b13554fa28b99/ebos/collecttoiorank.hh#L294) just prior to #3204, the call to [`Vanguard::equilCartesianIndexMapper()`](https://github.com/akva2/opm-simulators/blob/9def2fab122d87a793482a43257b13554fa28b99/ebos/collecttoiorank.hh#L312)) is still unconditional.

**Comment by akva2** [comment]
okay, i yield haha.
