### ISSUE TITLE
Ubuntu Installation Question

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3320]
What is the correct apt install command?

On the web site for the 2021-04 release we have:
```
sudo apt install libopm-simulators1-bin
```
and on the installation documentation page we have:
```
sudo apt-get install libopm-simulators-bin
```
Both work.

Apart from the the command difference there is a difference in libopm-simulators **()/(1)** -bin

**Comment by akva2** [comment]
no other difference. the latter is an alias for the former.

**Comment by atgeirr** [comment]
Should I change it on the website?

**Comment by OPMUSER** [comment]
@atgeirr Yes, let me know which one so that the manual is consistent.

**Comment by atgeirr** [comment]
I removed the "1" from the release post.

**Comment by OPMUSER** [comment]
Tusen tak.
