### ISSUE TITLE
EclWriter Constructor Dereferences Null Pointer in Parallel

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#3328]
I was analyzing an unrelated problem when I ran into the following assertion failure in [`eclcpgridvanguard.hh`](https://github.com/OPM/opm-simulators/blob/d57a8514a2e22aa697bcced7cc2fe1c2fe0814a8/ebos/eclcpgridvanguard.hh#L117)
```C++
assert( globalTrans_ != nullptr );
```
I tracked this back to the immediate caller in the constructor for [`EclWriter<>`](https://github.com/OPM/opm-simulators/blob/d57a8514a2e22aa697bcced7cc2fe1c2fe0814a8/ebos/eclwriter.hh#L125).  I can make the assertion failure go away with the following change, but I don't know if this just papers over some other, deeper issue
```diff
diff --git a/ebos/eclwriter.hh b/ebos/eclwriter.hh
index bcde644bc..827b7b77b 100644
--- a/ebos/eclwriter.hh
+++ b/ebos/eclwriter.hh
@@ -122,7 +122,7 @@ public:
                    simulator.vanguard().gridView(),
                    simulator.vanguard().cartesianIndexMapper(),
                    simulator.vanguard().grid().comm().rank() == 0 ? &simulator.vanguard().equilCartesianIndexMapper() : nullptr,
-                   simulator.vanguard().grid().comm().size() > 1 ? simulator.vanguard().globalTransmissibility() : problem.eclTransmissibilities(),
+                   simulator.vanguard().grid().comm().rank() == 0 ? simulator.vanguard().globalTransmissibility() : problem.eclTransmissibilities(),
                    EWOMS_GET_PARAM(TypeTag, bool, EnableAsyncEclOutput))
         , simulator_(simulator)
     {
```

**Comment by akva2** [comment]
the patch is definitely wrong.
 It originally was
```
        if (!collectToIORank_.isParallel())
        {
            // in the sequential case we must use the transmissibilites defined by
            // the problem. (because in the sequential case, the grid manager does
            // not compute "global" transmissibilities for performance reasons. in
            // the parallel case, the problem's transmissibilities can't be used
            // because this object refers to the distributed grid and we need the
            // sequential version here.)
            globalTrans = &simulator_.problem().eclTransmissibilities();
        }
        else
        {
            globalTrans = &(simulator_.vanguard().globalTransmissibility());
        }
```
The problem here is one of order. We grab the transmissibilities too early, before they have been set up. I have to change from a
constructor param to a setter to get the orders correct again.

**Comment by bska** [comment]
> the patch is definitely wrong.

Fair enough.  Please ensure that you run all your future refactoring patches in debug mode before you submit them to avoid this problem going forward.
