### ISSUE TITLE
Issue with OPERATE Keyword

### ISSUE THREAD

**Issue by georcav** [OPM/opm-simulators#3405]
Hello everyone.

I am receiving the following message during the build of a grid from an ECLIPSE case.

The file with the OPERATE Keyword is a .INC file.

**Error: 
An error occured while creating the reservoir properties
Internal error: The OPERATE and OPERATER keywords are not supported for keywords with global storage.**

**Comment by joakim-hove** [comment]
OK - can you paste in the `OPERATE` keyword here?

**Comment by georcav** [comment]
-- Generated [
-- Format      : ECLIPSE keywords (ASCII)
-- Exported by : Petrel 2017.4 Schlumberger
-- User name   : Pc
-- Date        : Wednesday, June 16 2021 12:25:13
-- Project     : I29Oct.pet
-- Generated ]

OPERATE                                -- Generated : Petrel
-- Property Modifier 'Copy of E_010X' [JVNA-007_c30+], step 1
  MULTZ 46 53 59 60 30 30 MULTX MULTZ 0.01 /
  MULTZ 46 52 61 61 30 30 MULTX MULTZ 0.01 /
  MULTZ 47 53 58 58 30 30 MULTX MULTZ 0.01 /
  MULTZ 47 52 62 62 30 30 MULTX MULTZ 0.01 /
  MULTZ 48 52 57 57 30 30 MULTX MULTZ 0.01 /
  MULTZ 49 52 63 63 30 30 MULTX MULTZ 0.01 /
  MULTZ 50 51 56 56 30 30 MULTX MULTZ 0.01 /
  MULTZ 51 51 64 64 30 30 MULTX MULTZ 0.01 /
  /

**Comment by joakim-hove** [comment]
OK - this is a known limitation in the current input parsing; for various reasons a few of the fields require special case treatment in the grid processing, including (at least) `MULTZ, PORV` and `ACTNUM`, and for those keywords the `OPERATE/OPERATER` doe not work. Should be fixed one day - but It is not entirely trivial and will not be tomorrow.

As for your case a workaround would be to use the `MULTIPLY` keyword instead:
```
MULTIPLY
    MULTZ 0.01 46 53 59 60 30 30 /
    MULTZ 0.01 46 52 61 61 30 30 /
    ....
/ 
```

**Comment by georcav** [comment]
Joakim, thanks for the answer

**Comment by georcav** [comment]
Now a new error message after changing the OPERATE keyword to MULTIPLY.

**Internal error: Malformed integer 'MULTX'**

**Comment by joakim-hove** [comment]
> Internal error: Malformed integer 'MULTX'

Hmm - ok; from the error message it looks like you have left the "MULTX" operator from the `OPERATE`keyword intact, observe the extact syntax of the `MULTIUPLY keyword:
```
MULTIPLY
-- Property     factor     I1    I2     J1    J2    K1    K2   
    MULTZ      0.01        46    53     59    60    30    30 /
/
```

**Comment by georcav** [comment]
Thanks
