### ISSUE TITLE
Error when trying to use GPU

### ISSUE THREAD

**Issue by georcav** [OPM/opm-simulators#3412]
Hello everyone,

I have been trying to test the GPU functionality in flow, but get the following error when use --gpu-mode=cusparse command.

**Error: [/build/opm-simulators-jTZUtd/opm-simulators-2021.04-rfinal/opm/simulators/linalg/ISTLSolverEbos.hpp:148] Error cannot use GPU solver since neither CUDA nor OpenCL were found by cmake**

Have the following cuda installation.

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by Tongdongq** [comment]
Your `build/config.h` probably has a line with `/* #undef HAVE_CUDA */` because cmake couldn't find your CUDA install.
Can you check the cmake output, in particular the CUDA part?

**Comment by blattms** [comment]
To prevent incompatibilities, OPM's buildsystem will force nvvc to use the detected C++ compiler (usually c++) underneath. On some system this compiler might be to new (e.g. on my Debian system the default is g++-8, but nvcc  9.* only supports g++-7). If that compiler is not supported detection will fail. There should be message about this when running CMake.

Just specify the correct compiler to CMAKE (e.g. via `cmake -DCMAKE_CXX_COMPILER=/usr/bin/g++-7`)

https://docs.nvidia.com/cuda/archive/10.1/cuda-installation-guide-linux/index.html#system-requirements

**Comment by georcav** [comment]
Thanks both for your answers. Are there any particular requirements for CUDA to work? I mean should I use a particular version of nvcc or c++ compiler? Just to make sure before going any further with cmake.

**Comment by blattms** [comment]
C++ compiler needs to support the c++17 standard and needs to be compatible with nvcc. Which one that is depends on your system. What operating system are you using?

**Comment by georcav** [comment]
Ubuntu 20.04, nvcc 10.1 and g++8

**Comment by blattms** [comment]
I am closing this as I assume that it is resolved. If it is not, please reopen.
