### ISSUE TITLE
Volve2OPM dataset run error

### ISSUE THREAD

**Issue by georcav** [OPM/opm-simulators#3444]
Hello everyone,
I have been trying to run Chris Dinneen Volve dataset, and get the following initializing error.

Program threw an exception: Could not initialize the problem: Negative thickness (inverted top/bottom faces) in cell 0.

Any idea what might be happening?

**Comment by OPMUSER** [comment]
Hard to say without further information, we don't have the Volve dataset 
in our test suite. Download the Norne model instead from:

https://github.com/OPM/opm-tests/tree/master/norne

And see if this runs to confirm everything is working

OPM User

**Comment by bska** [comment]
> ```
> Could not initialize the problem: Negative thickness (inverted top/bottom faces) in cell 0.
> ```

This diagnostic is emitted whilst processing `EQUIL` if **both** of the following conditions hold

1. Item 9 of the `EQUIL` keyword ("N") is **negative** (treat cell as horizontal, divide vertical range into `2 * (-N)` subintervals of equal thickness, and compute the cell's initial condition from averaging the subintervals' equilibrated states)
2. The face centre of the cell's topological **top** face happens to be deeper (greater depth) than the face centre of the cell's topological **bottom** face.

I don't really have a good suggestion here.  Flow currently does not support the "tilted" equilibration option (item 9&ndash;N&ndash;is positive).  Maybe setting `N = 0` will get you somewhere, but please be aware that the initial condition is probably going to be very different to the `N < 0` case or `N > 0` case for that matter if the cells have a greater vertical than horizontal extent.

**Comment by bska** [comment]
> 2. The face centre of the cell's topological **top** face happens to be deeper (greater depth) than the face centre of the cell's topological **bottom** face.

Come to think of if, the way we [compute the top and bottom face centre depths](https://github.com/OPM/opm-simulators/blob/847288ea68c1ea7cc029ec8af423a7eb1168a13d/ebos/equil/initstateequil.hh#L1505-L1508) looks a little suspicious to me an may in fact be a bug.  Normally in a corner-point cell corners 0..3 correspond to the top face and corners 4..7 correspond to the bottom face.  We changed this procedure in #2941 (commit 6c06a7246619aa9fcc86a15d88fec237b789ce1d) which I approved but this detail clearly escaped my attention.

@totto82 : How did you verify that using corners 0..3 for the bottom face and corners 4..7 for the top face was the right thing to do here?

**Comment by georcav** [comment]
I have run the Norne model without problem, along several other tests.

Originally the item 9 of the EQUIL keyword is positive and the run returns the following error:

Program threw an exception: Could not initialize the problem: Cannot initialise model: Positive item 9 is not supported in EQUIL keyword, record 1

When the N value is changed to negative returns the error I sent before:

Program threw an exception: Could not initialize the problem: Negative thickness (inverted top/bottom faces) in cell 0

And when the N value is set to zero returns this message, turning off the simulation:

Warning: Equilibration region 12 has no active cells


================ Simulation turned off ===============

I understand that the model could be run with 2019 versions of OPM, but apparently can't be run with a 2020 version of OPM. I have seen a couple of other problems regarding non convergence of the model in 2020 versions, commits #2948 and  #2915.

The dataset that Chris Dinneen used to run in opm 2019 is found in https://github.com/dabiged/Volve2OPM.

**Comment by OPMUSER** [comment]
@georcav The */Warning: Equilibration region 12 has no active cells/* 
message is correct, the commercial simulator states the same and is 
displayed below:



And I think this is the problem, not the geometry of the blocks. If I do 
the following:

 1. Change EQLDIMS(NTEQUIL) to 11.
 2. Comment the EQUIL record number 12.
 3. Set EQUIL(EQLOPT3) to zero.
 4. Comment out the 12th RSVD data set.

Then the model runs.

So I think the issue is that code is trying to initialize 12 equilibrium 
regions, as per the EQLDIMS keyword, but the grid processing results in 
only 11 (which is correct).

Note it is common for this type of situation to occur, users often zero 
pore-volume out parts of a reservoir to investigate the other areas in 
order to speed up run time, so I'm surprised this has not happened 
previously.

OPM User

**Comment by OPMUSER** [comment]
I guess no pretty pictures allowed in email responses, so here it is:
![kimclkfjhehnkoch](https://user-images.githubusercontent.com/17958927/125725683-b4a82b37-bf38-4dd2-b88e-f20abb674b85.png)

**Comment by georcav** [comment]
@OPMUSER Thanks for the answer.

I did the changes you recommend, the warning is gone but the simulation is turned off. It doesn't run. 

At the end the question is what was different in OPM 2019 regarding OPM 2020 for the model to run.

**Comment by bska** [comment]
> the simulation is turned off. It doesn't run.

Does the `.DATA` file include the `NOSIM` keyword?

**Comment by georcav** [comment]
@bska 

It has the NOSIM keyword and I commented it. Additionally rolled back some of the changes recommended by @OPMUSER  in particular 1,2, and 4.

After that the simulation run

================    End of simulation     ===============

Number of MPI processes:        12
Threads per MPI process:         2
Total time (seconds):         6413.68 
Solver time (seconds):        6413.57 
 Assembly time (seconds):      686.96 (Failed: 221.3; 32.2%)
   Well assembly (seconds):     62.44 (Failed: 20.3; 32.5%)
 Linear solve time (seconds): 5278.88 (Failed: 2128.3; 40.3%)
   Linear setup (seconds):     252.80 (Failed: 91.9; 36.4%)
 Update time (seconds):        296.32 (Failed: 98.1; 33.1%)
 Pre/post step (seconds):      114.85 (Failed: 3.7; 3.2%)
 Output write time (seconds):   24.17
Overall Linearizations:       9973    (Failed: 3218; 32.3%)
Overall Newton Iterations:    8839    (Failed: 3218; 36.4%)
Overall Linear Iterations:  404300    (Failed: 164165; 40.6%)
Initial step Sw
![image](https://user-images.githubusercontent.com/86379565/125816705-9f539967-a7b0-407e-ab0e-0975af7eaa5e.png)
Final step Sw
![image](https://user-images.githubusercontent.com/86379565/125816834-a55e33cd-da1b-4988-8c2e-d85182dec70f.png)
