### ISSUE TITLE
2021-10-PRE Unsupported Keywords: ROCKOPTS

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3501]
@totto82 Added ROCKOPTS to unsupported keyword list, as there are no opm-test examples, is this correct? If ROCKOPTS is supported what is supported?

@alfbr is under the impression that ROCKOPTS is supported.

**Comment by totto82** [comment]
I don't think we support ROCKOPTS. 
SPE1CASE2_ROCK2DTR should give an indication of what we support for rock compressibility (ROCKCOMP)

**Comment by alfbr** [comment]
Then my memory failed me.

**Comment by OPMUSER** [comment]
Okay confirmed ROCKOPTS not supported.
Close
