### ISSUE TITLE
Convergence issues in openclSolver when --matrix-add-well-contributions=false

### ISSUE THREAD

**Issue by Tongdongq** [OPM/opm-simulators#3635]
When the wellcontributions are applied separately, openclSolver doesn't converge enough anymore.
Dune takes about 10m on my machine, with or without wellcontributions.
OpenclSolver with wellcontributions included about 12m. But openclSolver without wellcontributions included takes 10 minutes to get to Report step 35, after which I killed it.

**Comment by blattms** [comment]
Resolved via merge of #3746.
