### ISSUE TITLE
Master: BRINE and PRECSALT Parallel  Exception

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3768]
Running the SPE1CASE1_BRINE.data and SPE1CASE1_PRECSALT.data test cases in parallel causes multiple:

```
Error: [/home/david/OPM/GitHub/opm-common/src/opm/io/eclipse/EclUtil.cpp:436] Error reading binary data, inconsistent header data or incorrect number of elements
ERROR: Uncaught std::exception when running tasklet: [/home/david/OPM/GitHub/opm-common/src/opm/io/eclipse/EclUtil.cpp:436] Error reading binary data, inconsistent header data or incorrect number of elements. Trying to continue.
Restart file written for report step   1/120, date = 01-Feb-2015 00:00:00
```
Also for the SPE1CASE1_PRECSALT.data case the binary files are corrupted causing OPM ResInsight to crash.

**Comment by blattms** [comment]
You should run into the same error in a parallel run. Usually the reason is a previously aborted run that resulted in only parts of the file being written.

**Comment by blattms** [comment]
Closing because of last comment,
