### ISSUE TITLE
What does failed % mean at the end of simulation?

### ISSUE THREAD

**Issue by DanatKMGE** [OPM/opm-simulators#3784]
Good day! What do % mean around the failed? How can I get it to be 0.0%?

For example: 

```
================    End of simulation     ===============

Number of MPI processes:         1
Threads per MPI process:         2
Total time (seconds):         1096.69
Solver time (seconds):        1095.90
 Assembly time (seconds):      329.17 (Failed: 50.8; 15.4%)
   Well assembly (seconds):      6.63 (Failed: 0.9; 13.1%)
 Linear solve time (seconds):  554.41 (Failed: 40.2; 7.3%)
   Linear setup (seconds):      68.53 (Failed: 11.8; 17.2%)
 Update time (seconds):        177.77 (Failed: 29.4; 16.6%)
 Pre/post step (seconds):       22.01 (Failed: 0.3; 1.2%)
 Output write time (seconds):   11.61
Overall Linearizations:       3272    (Failed: 504; 15.4%)
Overall Newton Iterations:    2963    (Failed: 504; 17.0%)
Overall Linear Iterations:   35280    (Failed: 2068; 5.9%)
```

**Comment by bska** [comment]
> What do % mean around the failed?

This reports the fraction of time (or iterations) that was attributed to this operation as part of timesteps that for whatever reason did not produce a converged solution and subsequently prompted a timestep cut.

> How can I get it to be 0.0%?

That'll require creating a model that does not have timestep cuts throughout the simulation.  Without knowing more about your case I can't really give advice.

**Comment by atgeirr** [comment]
This can be confusing, I propose that we change "failed" to "wasted" as that more accurately describes what it is.
