### ISSUE TITLE
Failed to compile according to instructions

### ISSUE THREAD

**Issue by User22814** [OPM/opm-simulators#3813]
Hello to all! I am relatively new. Recently I found your project, I was very interested. I tried to compile opm-simulators, as described in the link https://opm-project.org/?page_id=231. First made git clone https://github.com/OPM/opm-simulators.git. Then created a folder build: **mkdir opm-simulators/build**, after **cd opm-simulators/build**, then **cmake ..** . All like in instruction. But I have problems:
```
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0  
-- Check for working C compiler: /usr/bin/cc    
-- Check for working C compiler: /usr/bin/cc -- works       
-- Detecting C compiler ABI info                  
-- Detecting C compiler ABI info - done   
-- Detecting C compile features                  
-- Detecting C compile features - done         
-- Check for working CXX compiler: /usr/bin/c++         
-- Check for working CXX compiler: /usr/bin/c++ -- works         
-- Detecting CXX compiler ABI info                                       
-- Detecting CXX compiler ABI info - done          
-- Detecting CXX compile features             
-- Detecting CXX compile features - done        
CMake Error at CMakeLists.txt:59 (find_package):    
By not providing "Findopm-common.cmake" in CMAKE_MODULE_PATH this project 
has asked CMake to find a package configuration file provided by "opm-common", but CMake did not find one.  
Could not find a package configuration file provided by "opm-common" with any of the following names:  
opm-commonConfig.cmake      
opm-common-config.cmake   
Add the installation prefix of "opm-common" to CMAKE_PREFIX_PATH or set 
"opm-common_DIR" to a directory containing one of the above files.  If 
"opm-common" provides a separate development package or SDK, be sure it has been installed.   
-- Configuring incomplete, errors occurred!    
See also "/mnt/c/Ubuntu/OPM-simulator/opm-simulators/build/CMakeFiles/CMakeOutput.log".
```

**cmake version: 3.16.3**
**GNU Make 4.2.1**
Also previously downloaded opm-simulators binaries

I will be very glad to help! Thank you.

**Comment by blattms** [comment]
HI,

thanks for testing OPM.

This error indicates that opm-common is not found. Did you build that before?
There is a dependency chain for the modules and you need to build according to it, i.e opm-common, opm-material, opm-grid, opm-models, opm-simulators. You can either do that with the for-loop on the page you mentioned or manually.

I assume you have downloaded all the modulesand they lie side by side, and you have DUNE and other dependencies installed.
Then you can do:

```
mkdir opm-common/build; cd opm-common/build
cmake -D USE_MPI=ON  .. && make -j4
cd ../..
mkdir opm-material/build; cd opm-material/build
cmake -D USE_MPI=ON  .. && make -j4
cd ../..
....
```

As you are on Ubuntu you might of course also use packages from the [ppa.](https://opm-project.org/?page_id=245) There are also nigthtly builds.

**Comment by User22814** [comment]
Did as you say. First compile opm-common. But not compiled
[output opm-common.zip](https://github.com/OPM/opm-simulators/files/8067274/output.opm-common.zip)

**Comment by blattms** [comment]
Well, the problem is in the error message. CMake did not find boost. Please make sure to install all [prerequisites](https://opm-project.org/?page_id=239). That page is linked at the start of the build instructions.

**Comment by User22814** [comment]
All is OK. On Linux system all compiled. But Can compile this on Windows 11, on Visual Studio Code? How can I do this ?

**Comment by alfbr** [comment]
> All is OK. On Linux system all compiled. But Can compile this on Windows 11, on Visual Studio Code? How can I do this ?

It is reported that compiling works fine on Windows with WSL and WSL2:
https://docs.microsoft.com/en-us/windows/wsl/install
just follow the same recipe as you just used.

**Comment by goncalvesmachadoc** [comment]
After the steps already mentioned are done, If you want to use visual code with wsl2 for compiling/debugging flow, the basic steps would be: 

Create a "opm.code-workspace" file in your repository (example [opm.zip](https://github.com/OPM/opm-simulators/files/8074783/opm.zip) )
Press F1. Choose: CMake: Configure All Projects. Choose gcc.
Press F1. Choose: Cmake: Build All Projects. (make sure opm-simulators is the active folder)
Press F1: Choose:  Cmake: Debug

**Comment by User22814** [comment]
> > All is OK. On Linux system all compiled. But Can compile this on Windows 11, on Visual Studio Code? How can I do this ?
> 
> It is reported that compiling works fine on Windows with WSL and WSL2: https://docs.microsoft.com/en-us/windows/wsl/install just follow the same recipe as you just used.

WSL is Ubuntu, only on Windows. I would like to fully adapt to Windows. Make it as a separate .exe file. as a standalone application. Maybe I'll try to do it with a opmrun. Does anyone have such experience?

**Comment by User22814** [comment]
Now I use OPM on WSL on Windows.  But I want to adapt it to Windows without WSL.

**Comment by alfbr** [comment]
> Now I use OPM on WSL on Windows. But I want to adapt it to Windows without WSL.

Why? Please note that the post-processing application Resinsight in OPM does indeed compile and run without WSL, since it has a graphical user interface. There is a cost associated with it.

**Comment by akva2** [comment]
OPM/Flow does not build on native windows.

opm-run is a frontend. It should support wsl, ie, you run it natively on windows and it launches flow in wsl for you.

**Comment by User22814** [comment]
> OPM/Flow does not build on native windows.
> 
> opm-run is a frontend. It should support wsl, ie, you run it natively on windows and it launches flow in wsl for you.

I know it. That is, it is impossible to bind to Windows without WSL?

**Comment by User22814** [comment]
> Well, the problem is in the error message. CMake did not find boost. Please make sure to install all [prerequisites](https://opm-project.org/?page_id=239). That page is linked at the start of the build instructions.

I was able to compile. All OK

**Comment by alfbr** [comment]
> I know it. That is, it is impossible to bind to Windows without WSL?

Nothing is impossible, but there is a significant cost to it. In addition to significant developer resources, just supporting it would need a dual infrastructure on the build/test side.

**Comment by User22814** [comment]
Is it possible just to build this project on Visual Studio on Windows without WSL? Or are there places in the code related only to the Linux system?

**Comment by OPMUSER** [comment]
To be clear, OPM Flow  (the simulator) only works under Linux based operation systems, including virtual machines and Windows Subsystem for Linux (WSL).

OPMRUN is graphical interface to OPM Flow, that works under Linux and Windows. So for example running OPMRUN on a Windows host allows you select the files on the Windows host and submit the job to OPM Flow via WSL. The software handles all the file naming changes for both systems. So effectively you have OPM Flow running in Windows via WSL, with all the input and output files stored on the Windows host. The process is transparent to the user. To my knowledge this is the way most Windows based users run OPM Flow.

OPMRUN also has various other features that are useful for reservoir engineers.

**Comment by User22814** [comment]
> To be clear, OPM Flow (the simulator) only works under Linux based operation systems, including virtual machines and Windows Subsystem for Linux (WSL).
> 
> OPMRUN is graphical interface to OPM Flow, that works under Linux and Windows. So for example running OPMRUN on a Windows host allows you select the files on the Windows host and submit the job to OPM Flow via WSL. The software handles all the file naming changes for both systems. So effectively you have OPM Flow running in Windows via WSL, with all the input and output files stored on the Windows host. The process is transparent to the user. To my knowledge this is the way most Windows based users run OPM Flow.
> 
> OPMRUN also has various other features that are useful for reservoir engineers.

That is, in principle, you can not try to adapt OPM for Windows without WSL?

**Comment by OPMUSER** [comment]
Correct OPM Flow requires a Linux based OS. There has been some discussion on making a Windows port, but as @alfbr pointed out there is a distinct lack of enthusiasm for such a project, especially now that OPM Flow can run under Windows via WSL, and with OPMRUN this process is transparent to the user once OPM Flow is installed in WSL.

**Comment by User22814** [comment]
> Correct OPM Flow requires a Linux based OS. There has been some discussion on making a Windows port, but as @alfbr pointed out there is a distinct lack of enthusiasm for such a project, especially now that OPM Flow can run under Windows via WSL, and with OPMRUN this process is transparent to the user once OPM Flow is installed in WSL.

Tried to start, everything works. But the output is much slower than through the terminal. Output means window for output in OPMrun.

**Comment by atgeirr** [comment]
> That is, in principle, you can not try to adapt OPM for Windows without WSL?

The simulator OPM Flow does not use any Linux-specific features in its own code (case in point: it builds fine on macOS). However it depends on other libraries and frameworks, most notably the Dune framework. While in principle everything in OPM should compile just fine on any platform, with any standard compliant C++ compiler, every required library must also be available. So to port OPM Flow you must start with Dune. I have no idea how much work that would be. (There is also another minor point: we require a POSIX-compliant OS for some functionality, I think that is available on Windows though, but I could be wrong.)

**Comment by bska** [comment]
> > That is, in principle, you can not try to adapt OPM for Windows without WSL?
> 
> The simulator OPM Flow does not use any Linux-specific features in its own code (case in point: it builds fine on macOS)

That's not entirely true.  While we no longer use the `fnmatch()` library function, we do use a number of other Posix-only functions.  For instance, the colourised warning and error messages depend on Posix features that we would need to reimplement if we were ever to consider creating native Windows binaries.

**Comment by OPMUSER** [comment]
> Tried to start, everything works. But the output is much slower than through the terminal. Output means window for output in OPMrun.

Yes, the OPMRUN window is a bit slower because we have to parse the output. However, you can also run via a terminal as well via selecting the Background Processing option.

![image](https://user-images.githubusercontent.com/17958927/154222319-95643ced-1116-4f49-81ff-1a690756cd37.png)

**Comment by User22814** [comment]
Why is the output of text in the output window in Danata much slower than in the terminal?

> > Tried to start, everything works. But the output is much slower than through the terminal. Output means window for output in OPMrun.
> 
> Yes, the OPMRUN window is a bit slower because we have to parse the output. However, you can also run via a terminal as well via selecting the Background Processing option.
> 
> ![image](https://user-images.githubusercontent.com/17958927/154222319-95643ced-1116-4f49-81ff-1a690756cd37.png)

What does "Run in No Simulation Mode" mean?

**Comment by OPMUSER** [comment]
> What does "Run in No Simulation Mode" mean?

This option switches on the NOSIM keyword for data checking only. Thus you can check all the jobs in the queue to see if there are any errors, if no errors you can run the jobs using the _Run in Standard Simulation Mode_.
