### ISSUE TITLE
Out of Range Pressure Value When Calculating Potential Rates At End of Converged Timestep

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#3818]
A client recently reported that the simulator crashed while running one of their models.  I got access to the model in question and initially traced the immediate cause of the crash to evaluating the maximum Rv value at a well/reservoir connection (perforation) using a connection pressure of `NaN`.  @GitPaean then did a deeper analysis to establish that the `NaN` pressure value originated in function `StandardWellEval::computeConnectionDensities()` since this function was called with Rs and Rv values that multiplied to `1`.  In turn that means [dividing by `1 - Rs*Rv`](https://github.com/OPM/opm-simulators/blob/d7b5d0f6860ee1a736a3b4f3661a1ce792bfe255/opm/simulators/wells/StandardWellEval.cpp#L942-L961) ends up dividing by zero rendering all subsequent calculations meaningless.

We further determined that this calculation was initiated in the context of computing well potentials at the end of a converged timestep through `BlackoilWellModel::timeStepSucceeded()`, but only for one of the model's wells.  That well was a standard, i.e., not multi-segmented, history-controlled gas injection well (keyword `WCONINJH`).  When computing the potential flow rates we use the "most strict BHP value from available limits", as defined by function [`WellInterfaceGeneric::mostStrictBhpFromBhpLimits()`](https://github.com/OPM/opm-simulators/blob/eb7ffdb47cbe75e31dd99aa5a3aace48fb469019/opm/simulators/wells/StandardWell_impl.hpp#L1874).  History-controlled injection wells do not typically have a BHP limit which leads to [`mostStrictBhpFromBhpLimits()`](https://github.com/OPM/opm-simulators/blob/eb7ffdb47cbe75e31dd99aa5a3aace48fb469019/opm/simulators/wells/WellInterfaceGeneric.cpp#L172-L185) typically returning the default upper BHP limit for injection wells, 6891.2 barsa/100,000 psia.  This, in turn, is outside the valid pressure range for most PVT tables which explains the unphysical Rs and Rv values encountered during `computeWellRatesWithIterations()`.

I can make the model in question run to completion, and with mostly plausible production results, if I apply the change below (using observed BHP instead of BHP limit) but this feels really hacky to me and I'd really like a better solution.  I also get some diagnostic messages of the form
```
well <NAME>: has negative potentials and is not operable
Well <NAME> will be shut as it can not operate under current reservoir conditions.
```
but those may of course be real problems that would be present regardless of the altered BHP limit.

Maybe we should not even consider calculating potential flow rates for history controlled wells, especially injectors?

---

```diff
diff --git a/opm/simulators/wells/WellInterfaceGeneric.cpp b/opm/simulators/wells/WellInterfaceGeneric.cpp
index aa1ffc772..b60f33b8c 100644
--- a/opm/simulators/wells/WellInterfaceGeneric.cpp
+++ b/opm/simulators/wells/WellInterfaceGeneric.cpp
@@ -172,8 +172,16 @@ bool WellInterfaceGeneric::wellHasTHPConstraints(const SummaryState& summaryStat
 double WellInterfaceGeneric::mostStrictBhpFromBhpLimits(const SummaryState& summaryState) const
 {
     if (well_ecl_.isInjector()) {
-        const auto& controls = well_ecl_.injectionControls(summaryState);
-        return controls.bhp_limit;
+        if (well_ecl_.predictionMode()) {
+            const auto& controls = well_ecl_.injectionControls(summaryState);
+            return controls.bhp_limit;
+        }
+        else {
+            // History controlled well.  Use observed BHP value instead of
+            // BHP limit since the latter is likely to be the default value
+            // upper BHP limit of 100,000 psia (6891.2 barsa).
+            return this->well_ecl_.getInjectionProperties().BHPH;
+        }
     }
 
     if (well_ecl_.isProducer( )) {
```

**Comment by GitPaean** [comment]
A fix candidate was proposed here, https://github.com/OPM/opm-simulators/pull/3853 @bska

**Comment by bska** [comment]
> A fix candidate was proposed here, #3853

Thanks for the heads up, @GitPaean.  As it happens, that proposed fix does not make a difference to this problem.

**Comment by GitPaean** [comment]
> Thanks for the heads up, @GitPaean. As it happens, that proposed fix does not make a difference to this problem.

Basically, in #3853 , for the situation, `1 - rs * rv <= 0.`, the contributions of rs and rv are ignored. I do not say it is the most reasonable fix, but it is one way to avoid the problem in this issue.

**Comment by bska** [comment]
> I do not say it is the most reasonable fix, but it is one way to avoid the problem in this issue.

Maybe, butI tested  #3853 and the PR does not make any difference to the model that prompted this issue.

**Comment by GitPaean** [comment]
> Maybe, but I tested https://github.com/OPM/opm-simulators/pull/3853 and the PR does not make any difference to the model that prompted this issue.

If you ran into the same problem, we need to check why.

**Comment by bska** [comment]
> > Maybe, but I tested #3853 and the PR does not make any difference to the model that prompted this issue.
> 
> If you ran into the same problem, we need to check why.

Yes, I did run into the exact same issue both with #3853 and without it.

**Comment by GitPaean** [comment]
> Yes, I did run into the exact same issue both with https://github.com/OPM/opm-simulators/pull/3853 and without it.

Sure, we should investigate this. I will try to reproduce your observation first when finding time.

**Comment by bska** [comment]
I'm no longer able to reproduce this problem and I'll close the issue now.  If the problem recurs I'll reopen.
