### ISSUE TITLE
source code

### ISSUE THREAD

**Issue by loveduah1** [OPM/opm-simulators#3819]
Please, how do I access the OPM-simulators source codes on my computer?

**Comment by bska** [comment]
Hi,

Thank you for your interest in OPM.  All of OPM's development happens right here on GitHub using the git version control system.  Depending on what you want to do with the source code the access method may span from just reading the code in your browser to downloading/installing binary packages to compiling from source.

We outline the binary package option in our [installation instructions](https://opm-project.org/?page_id=36).  If you want to look through the source code on your local machine then you will need to use a git client to download it from github.  There are some brief instructions on how to do that in our page that describes [how to build the software from source code](https://opm-project.org/?page_id=231), but these all assume basic familiarity with Linux systems and using command line tools.

If you want to **contribute** to OPM you should fork the relevant the repositories to your own GitHub account and download the sources from there, possibly with an "upstream" link to the main OPM repositories in https://github.com/OPM.

Without knowing more about what you want to achieve I cannot really give a good answer here.

**Comment by loveduah1** [comment]
Good morning, Sir.



Thank you for the prompt response. I am a student using OPM for a research
project. I have installed the software on ubuntu (virtual machine) and
have completed the "My First Reservoir Simulation
<https://opm-project.org/?page_id=197>" tutorial. I would, however, want to
add more injectors to the 1st SPE Comparative Solution Project  (CSP), but
I am struggling to find the input file to work with.  I, therefore, want to
read the OPM source code so that I know which file to edit. If you can
point me in the right direction, I would appreciate it.

**Comment by OPMUSER** [comment]
The input files all have the extension DATA, for example SPE1.DATA. The DATA file can also read in other input files using the INCLUDE statement.

Use should download the manual for further details at:

[https://opm-project.org/?page_id=955](url)

**Comment by bska** [comment]
> I [...] want to add more injectors to the 1st SPE Comparative Solution Project (CSP), but I am struggling to find the input file to work with.

I see.  As @OPMUSER says you don't really need the simulator's source code to determine that.  We don't put any specific filenames into the source code, although I think you could infer that we look for files named `*.DATA` if you look closely enough and in the right places.

If you want to add more wells to your simulation case you will need to change the `SCHEDULE` section of the input `.DATA` file.  The language of this file is documented in the manual mentioned earlier, and you'll want to use at least the `WELSPECS` and `COMPDAT` keywords to add new wells and reservoir connections/perforations.

**Comment by loveduah1** [comment]
Thank you

**Comment by loveduah1** [comment]
To include an additional well, I edited the SCHEDULE, WELSPECS,  and
COMPDAT sections of the SPE1CASE1.DATA file yet I keep getting the same
plots as the original model (in the tutorial). It seems as though the new
well doesn't exist. Attached is the edited file.

**Comment by OPMUSER** [comment]
see #3822

**Comment by OPMUSER** [comment]
Please close this ticket
