### ISSUE TITLE
BUILD_TIMESTAMP (among others) prevents reproducible builds

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#3832]
The CMake scripts in opm-common are used to generate the header project-timestamp.h that contains a timestamp of the last cmake run. Unfortunately, this means that every build of the flow and the library differs even if there is no other change and makes build unreproducible. Does not seem nice. Maybe someone can comment on the purpose of this?

I fail to see why the time of the cmake run should matter at all. Maybe we should rather use the time the last source file was changed?
Might be challenging without git and just tarballs, though. Seems like we are relying on having git available at more places, which is probably also not the case for Debian package or anybody else using tarballs.

https://tests.reproducible-builds.org/debian/rb-pkg/bookworm/i386/opm-simulators.html

**Comment by bska** [comment]
For what it's worth we emit this information at the start of our `.PRT` file along with the git commit ID (live sources) or release name (release version) of the opm-simulators repository.  The timestamp was introduced in #2506 and there's some discussion/justification for the change in that PR.

**Comment by blattms** [comment]
well, I will definitely deactivate it for the packages as it does not make sense (Should check what even uses as hash if there is no git information). Still don't get why the time I run CMake should allow me to determine which version of the (other) modules I might use. The git hash gives all the information (but only for the current module).

**Comment by atgeirr** [comment]
> Anyway, it is clear that for the packages the information is not helping. There we should skip the build time and use the package version instead of the OPM version.

I think including the OPM version is important (i.e. 2021.10 in the above example), we should not replace that with package version.

Is your primary concern that
 - the executable binaries and libraries differ even if there are no code changes, or that
 - the generated simulation output differ even if there are no code changes, or
 - both?

**Comment by blattms** [comment]
Let me clarify: The package version (e.g. 2021.10-1, or 2022.04~git<hash>) always includes the OPM version, but also indicates what additional patches are included, or the git hash for pre-release versions. That is why it should used.

Reproducible builds means that whenever I build a source version with the same options/tools on the same architecture the output should be bitwise the same. https://reproducible-builds.org/

**Comment by blattms** [comment]
FYI A more objective reasoning why timestamps should not be used: https://reproducible-builds.org/specs/source-date-epoch/

**Comment by blattms** [comment]
Even with the patches the builds will not be identical if the kernel changed between them.

**Comment by atgeirr** [comment]
I think we all agree that this is a good idea? As long as the package version contains the version and possibly git hash I at least have nothing against this change. When we introduced the timestamp we agreed that it could do no harm, now we know (a little) better.
