### ISSUE TITLE
Start OPM from another folder

### ISSUE THREAD

**Issue by User22814** [OPM/opm-simulators#3841]
Hello! Sorry for the stupid question. I'm trying to start OPM. When I go to a folder with a .DATA file. The calculation is launched. But how to run a .DATA file while in another folder?
Try **wsl flow --parameter-file=C:/Ubuntu/Eclipse.DATA**, but have error:
```
Parameter file "C:/Ubuntu/Eclipse.DATA" does not exist or is not readable.

flow
Recognized options:
    -h,--help                                     Print this help message and exit
    --help-all                                    Print all parameters, including obsolete, hidden and deprecated ones.
    
...

--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Thanks for the answer

**Comment by OPMUSER** [comment]
Yes this will not work because you are referencing the *.DATA file using the Windows file system, when you need to reference the *.DATA file using the WSL Linux system.

If you install OPMRUN, a front-end GUI for OPM Flow, then you don't have to worry about this. The software will run under Windows and allow you to select the file using the Windows file system, and submit the job to WSL Linux using the Linux file name.

**Comment by atgeirr** [comment]
One additional comment: The --parameter-file option expects a file containing program options (the same that you can enter on the command line to adjust the behaviour of OPM Flow), and not the simulation deck (the .DATA file). When you run OPM Flow you just put the deck name on the command line by itself. For example: flow SPE1CASE2.DATA.

**Comment by User22814** [comment]
> Yes this will not work because you are referencing the *.DATA file using the Windows file system, when you need to reference the *.DATA file using the WSL Linux system.
> 
> If you install OPMRUN, a front-end GUI for OPM Flow, then you don't have to worry about this. The software will run under Windows and allow you to select the file using the Windows file system, and submit the job to WSL Linux using the Linux file name.

I'm referring to the Linux Subsystem. I am using the command:
wsl flow --parameter-file=C:/Ubuntu/Eclipse.DATA

**Comment by User22814** [comment]
How can I run the .DATA file through the cmd or Powershell Windows?

**Comment by bska** [comment]
> How can I run the .DATA file through the cmd or Powershell Windows?

I don't think that's possible as we don't create native Windows binaries.  In **principle** there's nothing that would prevent us from doing so, but in practice we don't currently have the manpower or expertise needed to support Windows as a native platform.

Also, please note what @atgeirr said in his earlier [comment](https://github.com/OPM/opm-simulators/issues/3841#issuecomment-1072101681):

> The `--parameter-file` option expects a file containing program options [...] and not the simulation deck (the `.DATA` file)

We have another option, `--ecl-deck-file-name`, that can be used to point to the simulation input file (i.e., the `.DATA` file), but you're supposed to be able to run flow just using a command like
```sh
flow path/to/simulation/CASE.DATA
```
This will probably not work with an NTFS path though, so you'll need to look into how to access the Windows filesystem through WSL as well.  You may also want to look at the `--output-dir` option if you'd like to redirect the simulation output files to a location that's different from the directory containing the `.DATA` file.

Sadly I don't know nearly enough about WSL to give more specific advice here.

**Comment by goncalvesmachadoc** [comment]
![image](https://user-images.githubusercontent.com/54812829/158976321-f1ddf561-8c99-4d4c-ba5f-58b39bed1887.png)
  Use /mnt/c instead of C:

**Comment by OPMUSER** [comment]
Yes as @akva2 and @goncalvesmachadoc stated above, you to use the Linux file name not the Windows file name. As I said before if you take the time to install OPMRUN you don't need to worry about this, as well as other benefits.

**Comment by User22814** [comment]
Thanks for ALL!!! I understand
