### ISSUE TITLE
Understanding flow logging levels relative to `flow --output-mode` command line argument

### ISSUE THREAD

**Issue by hakonhagland** [OPM/opm-simulators#3844]
As I understand it, the debugging (`deferred_logger.debug()` logging level has lower priority than the info (`deferred_logger.info()`) logging level. I am wondering if there a correspondence between the flow command line argument `--output-mode` and the logging level ?
```
$ flow --help | grep output-mode
    --output-mode=STRING                          Specify which messages are going to be printed. Valid values are: none, log, all (default). Default: "all"
```
For example, could I print only `info()` messages and not `debug()` messages? I note that e.g. [WellInterface_impl.hpp](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/WellInterface_impl.hpp) uses both types of logging levels.

**Comment by hakonhagland** [comment]
Seems like the stdout message types are hardcoded [here](https://github.com/OPM/opm-common/blob/master/opm/common/OpmLog/LogUtil.hpp#L43) : 
```
 const int64_t StdoutMessageTypes = MessageType::Info + MessageType::Warning + MessageType::Error + MessageType::Problem + MessageType::Bug;
```
Does this mean that debug messages (`MessageType::Debug`) will never be shown?

**Comment by atgeirr** [comment]
This is all setup in readDeck.cpp, the function setupLogging(). The command line option only has three levels: no output, only logging output (i.e. no restart or summary files)  or complete output. The debug() messages only go to the DBG file, note() messages go to DBG and PRT, and info() messages go to DBG, PRT and the standard output.

The logging system makes a distinction between the logging call site, where it is up to the programmer of that call site to use an appropriate level (such as info() or debug()), and the logging backends that are setup in setupLogging(). Each log file (and the std output) is set up as a separate backend. You can change the code there to make different or custom logging setups.

For example, you may want to leave out note() level messages from the DBG file, that is completely configurable by writing a little bit of code.

**Comment by atgeirr** [comment]
> Does this mean that debug messages (`MessageType::Debug`) will never be shown?

For logs using that particular set of flags, yes. In setupLogging() you will see that this particular message type filter is used for the log writing to standard output (only).

**Comment by hakonhagland** [comment]
> In setupLogging() you will see that this particular message type filter is used for the log writing to standard output (only).

@atgeirr Yes thanks for clarifying this. This looks like a sophisticated logging system. However, as I understand it is currently not possible to have the debug log messages in for example [WellInterface_impl.hpp](https://github.com/OPM/opm-simulators/blob/master/opm/simulators/wells/WellInterface_impl.hpp#L288) go to screen by giving the command line option. I would have to change the parameters in `setupLogging()` and recompile flow for this to happen. It seems like it is better to use `info` logging level for debugging output to the screen then.

**Comment by blattms** [comment]
The debugging output (and many of the rest, see #3726) will go to the *.DBG file. You could do `tail -f CASE.DBG` while running flow.
