### ISSUE TITLE
Error: Solver failed to converge after cutting timestep 10 times.

### ISSUE THREAD

**Issue by thewillingone** [OPM/opm-simulators#3852]
Hello, I hope you are all well. Please help, I'm practicing for research purposes and I'm having problems and here I listed my concerns.

1. I'm not sure if I should limit the production rate in WCONPROD keyword to a specific production rate like 12,000 in my trial run, if I only wanted to know the impact of total production by the injection of CO2. 
2. I get Problem: Solver convergence failure - Numerical problem encountered until I get Error: Solver failed to converge after cutting timestep 10 times.
3. Is my TSTEP wrong?

Attached here are the files and the conditions of the simulation. Please some guidance would suffice.

[Basecase.zip](https://github.com/OPM/opm-simulators/files/8363496/Basecase.zip)

**Comment by OPMUSER** [comment]
I got this run, but the changes I made were only cosmetic changes to the input deck and the type of data written out, so I don't know why my changes made this run. Although having  lines greater than 132 characters is known to create issues in E100.

Running deck attached - please close issue.

[BASECASE-01.zip](https://github.com/OPM/opm-simulators/files/8370676/BASECASE-01.zip)

**Comment by thewillingone** [comment]
Hello there again @OPMUSER , Good day to you. I hope you are well.

 I reconfigured the case file and stumbled on many Problems about convergence and 2 errors. I also observed that %Failed is very high. Although this case ran and produced results. I can't say it's reliable because of the problems and errors. Any insights on this. 
 
 Attached below is the file. 
 
[Basecase.zip](https://github.com/OPM/opm-simulators/files/8478590/Basecase.zip)

**Comment by OPMUSER** [comment]
You need to check the material balance error for all three phases at the end of the run, for example:

![image](https://user-images.githubusercontent.com/17958927/163122053-b250893b-bd85-487e-9745-3cc12495bb2b.png)

Should be a small percent less than 2-3%.

Most numerical issues are associated with input, so check that your relative permeability curves are smooth and continuous, same for the PVT data. 

I tried to running this with 2021-10 but it keeps on crashing:

```
Starting time step 23, stepsize 4.66923 days, at day 3777.79/3834.62, date = 05-May-2010
flow: /build/opm-simulators-9Blz1A/opm-simulators-2021.10-rfinal/opm/simulators/wells/StandardWellGeneric.cpp:96: static double Opm::StandardWellGeneric<Scalar>::relaxationFactorFraction(double, double) [with Scalar = double]: Assertion `old_value >= 0. && old_value <= 1.0' failed.
[EIPC-02:00084] *** Process received signal ***
[EIPC-02:00084] Signal: Aborted (6)
[EIPC-02:00084] Signal code:  (-6)
[EIPC-02:00084] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x143c0)[0x7f4da07a13c0]
[EIPC-02:00084] [ 1] /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xcb)[0x7f4d9f5e303b]
[EIPC-02:00084] [ 2] /lib/x86_64-linux-gnu/libc.so.6(abort+0x12b)[0x7f4d9f5c2859]
[EIPC-02:00084] [ 3] /lib/x86_64-linux-gnu/libc.so.6(+0x22729)[0x7f4d9f5c2729]
[EIPC-02:00084] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x34006)[0x7f4d9f5d4006]
[EIPC-02:00084] [ 5] /lib/x86_64-linux-gnu/libopmsimulators.so.2021.10(_ZN3Opm19StandardWellGenericIdE24relaxationFactorFractionEdd+0x90)[0x7f4da1b63600]
[EIPC-02:00084] [ 6] /lib/x86_64-linux-gnu/libopmsimulators.so.2021.10(_ZN3Opm16StandardWellEvalINS_19BlackOilFluidSystemIdNS_26BlackOilDefaultIndexTraitsEEENS_15BlackOilIndicesILj1ELj0ELj0ELj0ELb0ELb0ELj0ELj0EEEdE33relaxationFactorFractionsProducerERKSt6vectorIdSaIdEERKN4Dune11BlockVectorINSC_13DynamicVectorIdS8_EESaISF_EEE+0x75)[0x7f4da1aff505]
[EIPC-02:00084] [ 7] /lib/x86_64-linux-gnu/libopmsimulators.so.2021.10(_ZNK3Opm16StandardWellEvalINS_19BlackOilFluidSystemIdNS_26BlackOilDefaultIndexTraitsEEENS_15BlackOilIndicesILj1ELj0ELj0ELj0ELb0ELb0ELj0ELj0EEEdE28updatePrimaryVariablesNewtonERKN4Dune11BlockVectorINS7_13DynamicVectorIdSaIdEEESaISB_EEEdd+0x29d)[0x7f4da1affe0d]
[EIPC-02:00084] [ 8] flow(+0x922e37)[0x7f4da35bde37]
[EIPC-02:00084] [ 9] flow(+0x9232a5)[0x7f4da35be2a5]
[EIPC-02:00084] [10] flow(+0x891113)[0x7f4da352c113]
[EIPC-02:00084] [11] flow(+0x8afc87)[0x7f4da354ac87]
[EIPC-02:00084] [12] flow(+0x92fa15)[0x7f4da35caa15]
[EIPC-02:00084] [13] flow(+0x930f9a)[0x7f4da35cbf9a]
[EIPC-02:00084] [14] flow(+0x8898dc)[0x7f4da35248dc]
[EIPC-02:00084] [15] /lib/x86_64-linux-gnu/libopmsimulators.so.2021.10(_ZN3Opm24BlackoilWellModelGeneric20updateWellPotentialsEibRKNS_13SummaryConfigERNS_14DeferredLoggerE+0x406)[0x7f4da195bf26]
[EIPC-02:00084] [16] flow(+0x8f0f6a)[0x7f4da358bf6a]
[EIPC-02:00084] [17] flow(+0x913aec)[0x7f4da35aeaec]
[EIPC-02:00084] [18] flow(+0x91626e)[0x7f4da35b126e]
[EIPC-02:00084] [19] flow(+0x88851b)[0x7f4da352351b]
[EIPC-02:00084] [20] flow(+0x1176d5)[0x7f4da2db26d5]
[EIPC-02:00084] [21] flow(+0xb71ad)[0x7f4da2d521ad]
[EIPC-02:00084] [22] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3)[0x7f4d9f5c40b3]
[EIPC-02:00084] [23] flow(+0x10c3fe)[0x7f4da2da73fe]
[EIPC-02:00084] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------

```
If you ave managed to get a complete case then send me the case and I'll take a look when I have a minute.

**Comment by thewillingone** [comment]
Hello there again, sorry for the late reply as I studied the case to resolve the errors. It seem that when I change UNITS for BOTH INPUT AND OUTPUT from METRIC to FIELD, there occurs then the problems for the solver. But when I just use the METRIC system, then it has no problems.

May I know based from your experience what causes this? 

I attached the simulation cases for the field and metric units below.


[Basecase.zip](https://github.com/OPM/opm-simulators/files/8499459/Basecase.zip)

**Comment by OPMUSER** [comment]
The decks are identical except for the FIELD/METRIC keywords.

When you use the FIELD keyword then the simulator expects all the input data to be in field units (ft., stb. Mscf, stb/Mscf, ect.). Similarly for METRIC, m, m3, m3, m3/m3, etc.

By just changing the units from METRIC to FIELD you have told the simulator that to use FIELD units but the actual input data is still in METRIC, so garbage in gives garbage out. If you wish to use FIELD units then you have to manually convert all the data to the correct unit set.

**Comment by thewillingone** [comment]
Thank you for your insights sir. I will close this issue now as my queries has been answered.
