### ISSUE TITLE
What programs to install with packages?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#3889]
It is a bit embarrassing to ask this in public as a seasoned OPM developer :flushed: 

- Should we also ship the flow_oilwater*, flow_onephase* and the other variants? I assumed that flow covers all of these
- Should we ship printvfp?

**Comment by totto82** [comment]
The _flow_onephase_ and _flow_onephase_energy_ are not included in flow. (I don't know why) onephase is a bit misleading since it only works for WATER and WATER + THERMAL.

**Comment by goncalvesmachadoc** [comment]
For the reservoir engineers, would be very helpful to have  also the onephase versions as binaries so they can install it themselves without asking for help with compiling.

**Comment by totto82** [comment]
I suggest we add the current one-phase (WATER) and one-phase + energy to the flow main binary. Can you do that @goncalvesmachadoc or @blattms . I am traveling the next days, and since we want it in the release it should be done asap.

**Comment by blattms** [comment]
I will do that today.
I guess it suffices to run these cases using flow (and we do need to add the other programs to the package) @goncalvesmachadoc ?

**Comment by blattms** [comment]
Done with the merge of #3891
