### ISSUE TITLE
2022-04-RC1: Assertion `fabs(triple) > 0.0' failed.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#3896]
Got this:

```
Processing grid
flow: /home/david/OPM/GitHub/opm-grid/opm/grid/cpgpreprocess/preprocess.c:774: is_lefthanded: Assertion `fabs(triple) > 0.0' failed.
Aborted (core dumped)
```
Note also this message goes to the terminal but **not** to the *.PRT file, does the buffer need to be flushed?

Deck attached.
[UNISIM-I-D-deterministic.zip](https://github.com/OPM/opm-simulators/files/8580562/UNISIM-I-D-deterministic.zip)

**Comment by bska** [comment]
> ```
> is_lefthanded: Assertion `fabs(triple) > 0.0' failed.
> ```

I know why this is happening but sadly I don't know how to fix it&mdash;at least not easily.  The low-level check for left-handed vs. right-handed coordinate systems in the corner-point processing code implicitly assumes that all pillars have well-defined, unique top-point coordinates.  In the attached model the pillar top points are all at the **same** coordinate location if there are no active cells along a particular pillar and the aforementioned assumption therefore does not hold.  In particular the "same coordinate" property leads to zero lateral model extents from the first to the last pillars in the X and Y directions and this is the direct cause of the failing assertion.  We will need a more elaborate check to handle this situation.

> Note also this message goes to the terminal but **not** to the *.PRT file

Yes.  That's an unfortunate side effect of the corner-point processing code being written a language different from that of the logging system.  Right now the corner-point processing code does not, indeed cannot, know how to call the logging system.  It is certainly possible to retrofit logging into the corner-point processing through a C wrapper of the C++ logging system, but I expect it'd be at least a couple of days' work.

**Comment by tpradeep** [comment]
Dealing with the same issue. Any fix planned for this?

**Comment by bska** [comment]
> Dealing with the same issue. Any fix planned for this?

PR OPM/opm-grid#625 is known to fix a number of known instances of this problem but may not fix all of them.  I would nevertheless like to see that work to make it into the upcoming April release (2023.04) of the simulator.

**Comment by blattms** [comment]
Has been merged now and will be in the release. @tpradeep Would be cool if you could retest with current master if that is not too much effort.

**Comment by tpradeep** [comment]
I tested using the master branch. Seems like the bug fixed. No issues with grid processing. Thanks.

**Comment by blattms** [comment]
Thanks a lot for testing. Glad to hear this.
