### ISSUE TITLE
Possibly Conflicting Grid Views Employed in Load Balancing

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#3927]
Unless there is an externally defined load balancing routine, function `EclGenericCpGridVanguard<>::doLoadBalance_()` will [calculate face transmissibilities](https://github.com/OPM/opm-simulators/blob/26a9582ecec0b7d68a23a2bc81d07fff07ef6266/ebos/eclgenericcpgridvanguard.cc#L109) and pass those into [`CpGrid::loadBalance()`](https://github.com/OPM/opm-simulators/blob/26a9582ecec0b7d68a23a2bc81d07fff07ef6266/ebos/eclgenericcpgridvanguard.cc#L163-L165).  In this instance, the loop that calculates the transmissibilities uses an [`ElementMapper`](https://github.com/OPM/opm-simulators/blob/26a9582ecec0b7d68a23a2bc81d07fff07ef6266/ebos/eclgenericcpgridvanguard.cc#L111) defined in terms of a `GridView` that's passed as an [argument](https://github.com/OPM/opm-simulators/blob/26a9582ecec0b7d68a23a2bc81d07fff07ef6266/ebos/eclgenericcpgridvanguard.cc#L81) into `doLoadBalance_()`, but the loop itself explicitly uses [`CpGrid::leafGridView()`](https://github.com/OPM/opm-simulators/blob/26a9582ecec0b7d68a23a2bc81d07fff07ef6266/ebos/eclgenericcpgridvanguard.cc#L104).

Are these two `GridView`s ever expected/allowed to differ?  If so, isn't there a danger in using the mapper from one with the entities of the other?  If not, why do we take a `gridv` parameter in `doLoadBalance_()`?

**Comment by akva2** [comment]
I did not introduce any change in my PR, ref https://github.com/OPM/opm-simulators/pull/3219/commits/215a8b7c25cfe61c20e59aa1b2e4544af6d94689#diff-9eeedf72c7fd6413cdc5dcc04ee2756c3db0076f3d5220d443ba762f33eb451cL198

**Comment by blattms** [comment]
IMHO just change it.
