### ISSUE TITLE
How can I run simulator "flow " with GPU? 

### ISSUE THREAD

**Issue by lilux618** [OPM/opm-simulators#3940]
I notice in the source code there are .cu files , it seems that the simulator can be used with GPU , but I didn't find the introductions on GPU, How can I run simulator "flow "  with GPU ?

**Comment by lilux618** [comment]
Thank you ! It seems that I must compile this code, are there any introductions about it ?

**Comment by Tongdongq** [comment]
There are some [instructions](https://opm-project.org/?page_id=231).
Note that Flow is built by opm-simulators, so opm-upscaling might not be necessary.
Make sure to check the values of `HAVE_CUDA` and `HAVE_OPENCL` in `opm-simulators/build/config.h`.

**Comment by blattms** [comment]
Closing this as requester seemed successful.
