### ISSUE TITLE
How to change the parameters about mesh?

### ISSUE THREAD

**Issue by lilux618** [OPM/opm-simulators#3943]
I am new with opm , when I run the case NORNE_ATW2013 in TUTORIALS , I found that the grid is `46 112 22`. I want to increase the number of meshes, but when I modify the parameters in NORNE_ATW2013.DATA line 44
```
DIMENS
46 112 22   /
```
the mesh and results  haven't  changed, why?

**Comment by blattms** [comment]
Are you saying that after increasing these numbers the model still runs without errors? I would have assumed that the parser throws some errors. But it could be that this is overwritten by SPECGRID in INCLUDE/GRID/IRAP_1005.GRDECL, anyway. That file should setup the whole grid. Please read section 6.2 in the [OPM manual](https://opm-project.org/wp-content/uploads/2022/05/OPM_Flow_Reference_Manual_2022-04_Rev-0_Reduced.pdf). It has Norne as an example for an unstructured Cornerpoint grid. Unfortunately, those grids cannot be made larger by just changing a few lines.
d

**Comment by OPMUSER** [comment]
Just to add to what @blattms said. 

The DIMENS keyword defines the grid size, so :
```
DIMENS
46 112 22   /
```
Sets the grid size and the simulator expects 46 x 112 x 22 values for the grid properties, PORO, PERMX etc. So if you just changed the DIMENS keyword and not changed the PORO, PERMX, etc array properties, then bad things will happen :-)

There are ways to increase the dimensions of an existing grid using the current grid to generate the new grid and the associated grid properties, but I need to know a bit more what you are trying to accomplish.
