### ISSUE TITLE
Left Handed Grids

### ISSUE THREAD

**Issue by KarimoWusal** [OPM/opm-simulators#3944]
Dear OPM prousers,

I have issues with running the simulation, as I see errors associated with left handed grids. I see that OPM can not work with left handed grids properly. I tried change grids from left handed to right handed grids by changing just appropriate 2 columns (1st and 4th columns) below CORD keyword, and I keep seeing this error. I couldnt find automatic conversion neither in Eclipse nor Tnavigator. Do you recommend anything else to change grids from left handed to right handed?

Please, do not ignore this issue, your all helps will be appreciated ^_^

**Comment by OPMUSER** [comment]
@bska Happy days are here again!

I have tested the latest master, with three separate client models that previously failed due to the left-handed grid issue, they now all run with OPM Flow. All three models were generated via an alternative commercial simulator.

So well done.

**Comment by blattms** [comment]
Closing this as it seems resolved. Please reopen if you disagree.
