### ISSUE TITLE
Compile error !

### ISSUE THREAD

**Issue by lilux618** [OPM/opm-simulators#3947]
When I compile opm-simulators , I got error like this 
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/60692776/174573969-63a120bc-829b-439f-a4fe-c05992190407.png">

what's wrong with me ?  I have already successfully compiled opm-common opm-material opm-grid opm-models .

**Comment by atgeirr** [comment]
I do not know for sure what is the problem. Maybe your Dune version is too old? Which version of Dune do you have installed?

**Comment by lilux618** [comment]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/60692776/174697406-19edbc28-9121-4c7c-958e-f300581398d7.png">
This is my dune version

**Comment by lilux618** [comment]
<img width="597" alt="image" src="https://user-images.githubusercontent.com/60692776/174701421-70a323ed-60ac-4f9f-98cf-87e8a24728cb.png">

**Comment by atgeirr** [comment]
Your version (2.6) is still supported by OPM, a change was merged that did not take that into account, causing your compile issue. With the latest version of opm-simulators (since #3949), your problem should be fixed.
