### ISSUE TITLE
Development new model

### ISSUE THREAD

**Issue by Nurtas93** [OPM/opm-simulators#3962]
Dear OPM Developers,

My research work related with Wettability Alteration and I chose the direction of Reservoir simulation. The first goal is to develop simulator for modeling Surfactant flooding. I started considering projects with open source code and OPM project very interested for me. 
I read the description of OPM flow attached as recommended  David  Baxendale and he also suggested write my issues to the developers.  Currently I’m in internship at the research center in Kazakhstan, and I’ve access to the licensed comercial reservoir simulators . So, I think we can use the mathematical description of Surfactant model from comercial simulators and  try to implement this model in OPM. Also I tried to read the C++ code of Polymer model in github  and I’ve difficulties to understand this code. Because the code connected with many different modules and classes.  The questions is what I need to learn to understand the code and in which modules I need to make changes to implement surfactant model? 

Please , give me some feedback!

Best regards,

Nurtas Smagulov

**Comment by GitPaean** [comment]
Hi, Nurtas, 

Welcome to the OPM community. 

It is good that you have tried to read the code in the polymer model, which is almost the closest functionality in OPM to the surfactant flooding you want to do, although polymer and surfactant work pretty differently. Maybe the solvent model is also relevant.

To have the surfactant functionality in OPM, basically it includes the following parts:
1. OPM-flow needs to parse and interpret the surfactant related keywords
2. You need to incorporate the interpreted surfactant keyword information to the simulation, it includes adding the transport equations for the surfactant and using the surfactant to modify the physical properties for the water and oil phase. Wells need to be able to inject and produce surfactant. 
3. Output the results related to surfactant. 

Not necessarily the case for everyone, but I think it might help the debug and development in OPM if you can compare with surfactant development in MRST (https://www.sintef.no/projectweb/mrst/),  (book chapter at https://www.cambridge.org/core/books/advanced-modeling-with-the-matlab-reservoir-simulation-toolbox/using-state-functions-and-mrstls-adoo-framework-to-implement-simulators-for-chemical-eor/187669ED69EEB01838368CD7B2338981) . 

There were quite some efforts made there to get the correct surfactant results and the source code is public. 

Anyway, feel free to reach to us if you have more questions. 

Yours sincerely, 
Kai Bao

**Comment by Nurtas93** [comment]
> Hi, Nurtas,
> 
> Welcome to the OPM community.
> 
> It is good that you have tried to read the code in the polymer model, which is almost the closest functionality in OPM to the surfactant flooding you want to do, although polymer and surfactant work pretty differently. Maybe the solvent model is also relevant.
> 
> To have the surfactant functionality in OPM, basically it includes the following parts:
> 
> 1. OPM-flow needs to parse and interpret the surfactant related keywords
> 2. You need to incorporate the interpreted surfactant keyword information to the simulation, it includes adding the transport equations for the surfactant and using the surfactant to modify the physical properties for the water and oil phase. Wells need to be able to inject and produce surfactant.
> 3. Output the results related to surfactant.
> 
> Not necessarily the case for everyone, but I think it might help the debug and development in OPM if you can compare with surfactant development in MRST (https://www.sintef.no/projectweb/mrst/), (book chapter at https://www.cambridge.org/core/books/advanced-modeling-with-the-matlab-reservoir-simulation-toolbox/using-state-functions-and-mrstls-adoo-framework-to-implement-simulators-for-chemical-eor/187669ED69EEB01838368CD7B2338981) .
> 
> There were quite some efforts made there to get the correct surfactant results and the source code is public.
> 
> Anyway, feel free to reach to us if you have more questions.
> 
> Yours sincerely, Kai Bao



> Hi, Nurtas,
> 
> Welcome to the OPM community.
> 
> It is good that you have tried to read the code in the polymer model, which is almost the closest functionality in OPM to the surfactant flooding you want to do, although polymer and surfactant work pretty differently. Maybe the solvent model is also relevant.
> 
> To have the surfactant functionality in OPM, basically it includes the following parts:
> 
> 1. OPM-flow needs to parse and interpret the surfactant related keywords
> 2. You need to incorporate the interpreted surfactant keyword information to the simulation, it includes adding the transport equations for the surfactant and using the surfactant to modify the physical properties for the water and oil phase. Wells need to be able to inject and produce surfactant.
> 3. Output the results related to surfactant.
> 
> Not necessarily the case for everyone, but I think it might help the debug and development in OPM if you can compare with surfactant development in MRST (https://www.sintef.no/projectweb/mrst/), (book chapter at https://www.cambridge.org/core/books/advanced-modeling-with-the-matlab-reservoir-simulation-toolbox/using-state-functions-and-mrstls-adoo-framework-to-implement-simulators-for-chemical-eor/187669ED69EEB01838368CD7B2338981) .
> 
> There were quite some efforts made there to get the correct surfactant results and the source code is public.
> 
> Anyway, feel free to reach to us if you have more questions.
> 
> Yours sincerely, Kai Bao

Thank you for your answer! I'll follow to your recommendations!
