### ISSUE TITLE
--linsolver=amg 

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#3963]
If i try to run flow with --linsolver=amg I get this error message. 
```
Error: [/home/AD.NORCERESEARCH.NO/tosa/workspace/opm/opm-simulators/opm/simulators/linalg/PreconditionerFactory.hpp:530] Preconditioner type amg is not registered in the factory. Available types are: GS ILU0 ILUn Jac ParOverILU0 SOR SSOR cpr cprt cprw
```
I am sure this used to work some weeks ago. Could it be that `constexpr (std::is_same_v<O, Dune::MatrixAdapter<M, V, V>>)`  in  line 405 in the same file as above  evaluates to false now?

**Comment by atgeirr** [comment]
I think you are right. But the guard is there for a purpose. Could you try to add `--matrix-add-well-contributions=true`? Then the matrix operator is used.

**Comment by totto82** [comment]
Worked thanks.
