### ISSUE TITLE
Clang does not compile for GPU

### ISSUE THREAD

**Issue by Tongdongq** [OPM/opm-simulators#3966]
Edit: It works when using `clang++` instead of `clang`. But it needs quadmath to be disabled.

The current masters don't compile for me with clang-14.0.0 or clang-13.0.1. I've also tried 12.0.0 and 11.0.0 but CMake cannot find Threads. Building with g++-8.4 is fine.

The errors when both CUDA and OpenCL are found by CMake:
```
In file included from /opm-simulators/opm/simulators/linalg/bda/opencl/BILU0.cpp:28:
In file included from /opm-simulators/opm/simulators/linalg/bda/opencl/BILU0.hpp:28:
In file included from /opm-simulators/opm/simulators/linalg/bda/opencl/opencl.hpp:29:
In file included from /prerequisites/OpenCL-CLHPP/include/CL/opencl.hpp:538:
In file included from /cm/shared/apps/cuda11.6/toolkit/11.6.0/targets/x86_64-linux/include/CL/opencl.h:30:
In file included from /cm/shared/apps/cuda11.6/toolkit/11.6.0/targets/x86_64-linux/include/CL/cl.h:23:
In file included from /cm/shared/apps/cuda11.6/toolkit/11.6.0/targets/x86_64-linux/include/CL/cl_platform.h:409:
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:52:1: error: conflicting types for '_mm_prefetch'
_mm_prefetch (const void *__P, enum _mm_hint __I)
^
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:52:1: note: '_mm_prefetch' is a builtin with type 'void (const char *, int) noexcept'
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:54:3: error: argument to '__builtin_prefetch' must be a constant integer
  __builtin_prefetch (__P, (__I & 0x4) >> 2, __I & 0x3);
  ^                        ~~~~~~~~~~~~~~~~
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:130:19: error: use of undeclared identifier '__builtin_ia32_addss'
  return (__m128) __builtin_ia32_addss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:136:19: error: use of undeclared identifier '__builtin_ia32_subss'
  return (__m128) __builtin_ia32_subss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:142:19: error: use of undeclared identifier '__builtin_ia32_mulss'
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:148:19: error: use of undeclared identifier '__builtin_ia32_divss'; did you mean '__builtin_ia32_minss'?
  return (__m128) __builtin_ia32_divss ((__v4sf)__A, (__v4sf)__B);
                  ^
/usr/lib/gcc/x86_64-linux-gnu/8/include/xmmintrin.h:142:19: note: '__builtin_ia32_minss' declared here
  return (__m128) __builtin_ia32_mulss ((__v4sf)__A, (__v4sf)__B);
...
```
The `OpenCL-CLHPP/include/CL/opencl.hpp` comes from [here](https://github.com/KhronosGroup/OpenCL-CLHPP). If I don't pass that, it uses `rocm/5.1.1/opencl/include/CL/cl2.hpp`, which leads to the same include trace and error.

If I disable OpenCL, it still fails:
```
/usr/bin/ld: CMakeFiles/flow_libblackoil.dir/flow/flow_ebos_blackoil.cpp.o: undefined reference to symbol '_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1ERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode@@GLIBCXX_3.4.
/cm/shared/apps/gcc/11.2.0/usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
```
Although this might be easily fixed by passing a library dependency correctly.

Background: I'm trying to use hipcc, which is based on clang-14.

**Comment by bska** [comment]
> ```
> undefined reference to symbol '_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1ERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode@@GLIBCXX_3.4.
> ```

That's "undefined reference" to `std::ifstream::ifstream(const std::string&, std::ios_base::openmode)` (specialised from the `basic_ifstream<>` [constructor](https://en.cppreference.com/w/cpp/io/basic_ifstream/basic_ifstream)).  All of these diagnostic messages refer to symbols in the implementation of the standard library and aren't **directly** caused by OPM problems, so there's probably something deeper at play.  Are you able to compile, link, and run a simple example such as
```C++
#include <iostream>
#include <string>

int main()
{
    const auto hello = std::string { "hello" };
    auto name = std::string{};
    while (std::cin >> name) {
        std::cout << hello << ", " << name << '\n';
    }
}
```
using the Clang-14 compiler?

**Comment by Tongdongq** [comment]
It turns out I was using `clang` instead of `clang++`.
Compiling without OpenCL works now, but I still get the same errors for `BILU0.cpp`.

**Comment by bska** [comment]
> Compiling without OpenCL works now, but I still get the same errors for `BILU0.cpp`.

Okay.  I'm not sufficiently familiar with OpenCL to give any specific advice here, but is there some kind of basic "hello world"-like example for OpenCL that does not require OPM and that you can use to verify that your OpenCL toolchain works correctly?

**Comment by Tongdongq** [comment]
I added `#include <CL/cl.hpp>` to your basic example, and I get similar errors (no prefetch() error). `g++` works fine of course.
[`cl_platform.h`](https://github.com/KhronosGroup/OpenCL-Headers/blob/main/CL/cl_platform.h) sees `__SSE__` is defined, and includes `/apps/gcc/8.2.0/lib/gcc/x86_64-pc-linux-gnu/8.2.0/include/xmmintrin.h` and defines:
```c
    #if defined( __GNUC__ )
        typedef float __cl_float4   __attribute__((vector_size(16)));
    #else
        typedef __m128 __cl_float4;
    #endif
```
But I think the problem is in/with that header, not with the typedef afterwards.
I could understand if `clang` needs a header from a clang directory, not a gcc one.
The [official clang xmmintrin.h](https://clang.llvm.org/doxygen/xmmintrin_8h_source.html) does not appear to have `__builtin_ia32_addss` or `__builtin_ia32_mulss`.

**Comment by Tongdongq** [comment]
This is resolved now, but I disable quadmath by manually commenting it out in `build/config.h`.
I tried passing
`-DUSE_QUADMATH=OFF`
`-DHAVE_QUAD=OFF`
`-DCMAKE_DISABLE_FIND_PACKAGE_QUAD=ON`
`-DCMAKE_DISABLE_FIND_PACKAGE_Quad=ON`
`-DCMAKE_DISABLE_FIND_PACKAGE_QUADMATH=ON`
`-DCMAKE_DISABLE_FIND_PACKAGE_QuadMath=ON`
But these don't work.
`FindQuadMath.cmake` and `OpmInit.cmake` in `opm-common/cmake/Modules` give some hints, but I haven't figured it out yet.

**Comment by bska** [comment]
> I disable quadmath by manually commenting it out in `build/config.h`.

Right.  For what it's worth, I ran into a similar situation recently and traced the source back to the Dune build system automatically enabling and linking in QuadMath if that package is detected/available at configure time.  If you have the time and inclination I'd suggest rebuilding Dune from scratch whilst passing
```sh
-DCMAKE_DISABLE_FIND_PACKAGE_QuadMath=ON
```
and then to rebuild all of OPM with that same flag to ensure consistency.

**Comment by Tongdongq** [comment]
This works, thanks for the help.
