### ISSUE TITLE
Grid graph

### ISSUE THREAD

**Issue by Theophile88** [OPM/opm-simulators#3967]
Hi,
First, thanks a lot for sharing this great work!
Not sure if this is the right place to ask (any support forum?).
Would it be possible to export (or get) the grid graph (nodes/edges representation from transmissibilities, NNC, etc...) using opm modules?
I would really appreciate ff you could point me in the right direction!

**Comment by atgeirr** [comment]
The best place to ask questions would be the mailing list, see https://opm-project.org/?page_id=358

On the grid graph question: there is no direct way as far as I know, but it should of course be possible to do. The closest you can get right now is probably in the (binary) output files, that contain NNC information and transmissibilities for regular (nnc) connections.

**Comment by Theophile88** [comment]
Thanks for your reply. I will use the output files to build the graph.

**Comment by Theophile88** [comment]
> Maybe I don't understand the question, but we do construct a grid graph representing this for loadbalancing (includes all grid faces and nnc faces and wells). It is in [ZoltanGraphFunctions.hpp#L123](https://github.com/OPM/opm-grid/blob/master/opm/grid/common/ZoltanGraphFunctions.hpp#L123). You could pass `nullptr` for the wells to neglect those. Not based on transmissibilities though and maybe not what you need.

Thanks! It seems it is what I need.

**Comment by blattms** [comment]
Cool. closing.
