### ISSUE TITLE
Broken PPA

### ISSUE THREAD

**Issue by xjules** [OPM/opm-simulators#3982]
When installing ` sudo apt-get install libopm-simulators-bin` on Ubuntu-18.04 getting this error:
```sh
Cannot add PPA: 'ppa:~opm/ubuntu/ppa'.
ERROR: '~opm' user or team does not exist.
Error: Process completed with exit code 1.
```

Reference: https://github.com/equinor/ert/runs/7555095348?check_suite_focus=true

**Comment by blattms** [comment]
Hi,

at least the current version of OPM is not available for 18.04 anymore, but it might work to install an older one. Still, I would not recommend that. Please upgrade to 20.04 if possible.

The official instructions are [here](https://opm-project.org/?page_id=245). I somehow assume that the ppa is not added properly. there sould be no `~` in there (i.e. it should read ".ppa:opm/ppa").

**Comment by blattms** [comment]
maybe check the sources.list file. Mine looks like this:
```
root@galadriel:~# cat /etc/apt/sources.list.d/opm-ubuntu-ppa-bionic.list
deb http://ppa.launchpad.net/opm/ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/opm/ppa/ubuntu bionic main
# deb-src http://ppa.launchpad.net/opm/ppa/ubuntu bionic main
root@galadriel:~# 
```

**Comment by xjules** [comment]
Thanks @blattms! Setting Ubuntu to 20.04 helped.
