### ISSUE TITLE
Curious error in the pressure solution may be a clue to finding a bug

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#3984]
[2022.04.0] The attached test model came about as I was looking into a subtle but consistent difference between the pressure solution in Flow compared to Eclipse. The attached model illustrates this and may help you to identify if there is an underlying bug of some sort. 

Model files
[Test_Water.zip](https://github.com/OPM/opm-simulators/files/9213252/Test_Water.zip)

Brief summary: The test model is a 1 x 1 x 1 single phase water cell and Flow seems to have some sensitivity to the formation compressibility (ROCK). The model is 1000 m x 1000 m area x 10 m thick, 1.0 ntg, 0.1 porosity, Bw 1.0, so pore volume is exactly 1 mln rm3. Initial pressure is 300 bara at datum 3000 m (i.e. initial FPR 300,5 bara). The schedule has 1000 rm3/d injection x 100 days with a maximum of 500 bara.  

Case 1 (Water1F, Water1E) has total compressibility 200E-6/bar, where Flow shows a slightly higher gradient of pressure increase and also plateaus at around 513 bara which is significantly higher than the maximum injection pressure 500 bara,  

![image](https://user-images.githubusercontent.com/47630958/181609309-a8c9daf6-240e-4240-ae26-889e75630458.png)

Case 2 (Water2F, Water2E) has an artificially high total compressibility 5000E-6/bar. This is obviously on the high end but done as one way to to amplify this discrepancy. This may help can guide you to the root cause. Flow now shows a much higher gradient of pressure increase, rising to 350 bara compared to the correct final pressure of 320 bara (i.e. initial pressure 300 bara + injection 0.1 mln rm3 / pore volume 1 mln rm3 / total compressibility 5000E-6 = 320 bar). 

![image](https://user-images.githubusercontent.com/47630958/181612211-7bd13243-0ce1-4109-9c79-129560b226e8.png)

**Comment by atgeirr** [comment]
Thank you for the report, looking at it.

**Comment by atgeirr** [comment]
It looks like the pressure in the cell is fine. If you add
```
BPR
1 1 1 /
/
```
to the SUMMARY section and look at the time series it looks like it is fine. The field pressure output (FPR) is not, however. I do not know why, will leave this problem for our output wizard to become available.

@bska please take a look when you have time.

**Comment by bska** [comment]
The `FPR` value is calculated in the simulator and apart from unit conversions (SI -> output units, e.g., "bara") the output code does not touch that value in any way.  I'll have to look more closely into the way we calculate average values on the simulator side.

**Comment by bska** [comment]
> I'll have to look more closely into the way we calculate average values on the simulator side.

I've identified a problem in that calculation and I am testing a solution to it.  Right now I'm getting `FPR` simulation results as shown in the figure below.  I believe this solves the immediate problem but I want to make sure that I don't break anything else before I submit a PR candidate.  To that end, @EdmundStephens, would you permit us&mdash;the OPM project&mdash;to use your `Water2F` model as part of our regression test suite?  Having that model in our automated portfolio will prevent the problem from recurring in the future.

In that event we'll place a copy of the deck in our [opm-tests](https://github.com/OPM/opm-tests) repository and equip the input file with a copyright and licence notice of the form
> ```
> -- This reservoir simulation deck is made available under the Open Database
> -- License: http://opendatacommons.org/licenses/odbl/1.0/. Any rights in
> -- individual contents of the database are licensed under the Database Contents
> -- License: http://opendatacommons.org/licenses/dbcl/1.0/
> 
> -- Copyright (C) 2022 Edmund Stephens
>
> -- This simulation model exercises single-phase water capabilities with high rock compressibility
> ```
except we will of course accommodate any request to alter the description as you see fit.

---

![FPR-fixed](https://user-images.githubusercontent.com/1871438/183499591-b8ccae87-50cd-4d0a-92c6-552dc57270ab.png)

**Comment by EdmundStephens** [comment]
Yes that is a great idea to help the project. No probs with the description as you have it.

**Comment by blattms** [comment]
@EdmundStephens Please note that all models in opm-tests are distributed under the [Open Database license](http://opendatacommons.org/licenses/odbl/1.0/) and the content under the [database contents license](http://opendatacommons.org/licenses/dbcl/1.0). Hence @bska is actually asking whether you are willing to change the license the model to these licenses. Please review these licenses, double check with whomever you have to and confirm that this is OK.

**Comment by EdmundStephens** [comment]
This is fine. I am contributing my feedback entirely in a personal capacity and my own time. It is what I can do by way of giving back to you as thanks for your supporting this as an open source project. So there is no problem or conflict using this simple deck as a test model, you are very welcome. 

Incidentally after 20+ years in the industry and/or helping with university courses, I have quite a number of test decks which you may find useful which I regularly use for example to validate data. For example models testing hysteretic relperms and residual saturations in a 1d column, Many years ago I was in software, and I get how useful it is to have a good set of reliable test models, so if I can contribute in this small way let me know.

**Comment by akva2** [comment]
yes! all simple models that verify functionality is very welcome contributions. even better when they disclose existing bugs.
