### ISSUE TITLE
Exception when adding wellcontributions to matrix

### ISSUE THREAD

**Issue by Tongdongq** [OPM/opm-simulators#4012]
When running NORNE with `--matrix-add-well-contributions=true`, I get this error:
```
Program threw an exception: vector::_M_range_check: __n (which is 1574) >= this->size() (which is 0)
```

Probably `cartesian_to_compressed_` is not initialized, I did not find any other OPM files using it, other than the `BlackoilWellModel` files.
This leads to `BlackoilWellModel::addNeighbors()` throwing an exception.

Maybe `/opm-simulators/ebos/eclbasevanguard.hh:updateCartesianToCompressedMapping_()` is supposed to update it, but it writes to `cartesianToCompressed_`.

GDB snippet:
```
128	            for ( size_t c=0; c < connectionSet.size(); c++ )
(gdb) 
130	                const auto& connection = connectionSet.get(c);
(gdb) 
131	                int compressed_idx = cartesian_to_compressed_.at(connection.global_index());
(gdb) p connection.global_index()
$1 = 1574
(gdb) p cartesian_to_compressed_ 
$2 = {<std::_Vector_base<int, std::allocator<int> >> = {
    _M_impl = {<std::allocator<int>> = {<__gnu_cxx::new_allocator<int>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<int, std::allocator<int> >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, 
        _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}
```

**Comment by bska** [comment]
Confirmed.  Seems to be fallout from the ALUGrid work in commit 5c2b60bcd (PR #3972).
