### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by fgfuchs** [OPM/opm-simulators#4036]
Compiling the latest version of opm results in the following errors:

- opm-simulators/ebos/eclnewtonmethod.hh:36:10: fatal error: opm/material/common/Unused.hpp: No such file or directory
- opm-simulators/opm/simulators/linalg/bda/BdaBridge.cpp:27:10: fatal error: opm/material/common/Unused.hpp: No such file or directory
- opm-simulators/opm/simulators/wells/StandardWell_impl.hpp:23:10: fatal error: opm/input/eclipse/Schedule/Well/WellInjectionProperties.hpp: No such file or directory

Any idea what is going wrong?

**Comment by akva2** [comment]
out of date opm-simulators. opm-material's Unused.hpp was removed weeks ago, and those includes are not there in master.

**Comment by fgfuchs** [comment]
Yeah, I saw that, too just now. Thanks anyway!
