### ISSUE TITLE
Reduce User-Level Messages Concerning Action Handling

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#4042]
As of this writing, and PR #4003, we output a number of messages concerning actions which do not trigger to the console and the `.PRT` file. I would like to propose that we direct those messages exclusively to the `.DBG` file instead and to reserve the console and `.PRT` file to report actions which do trigger at a particular time. In running important real field cases we've experienced the "non-triggered" action messages exceeding 100,000 lines which greatly reduces the utility of the `.PRT` file. I will state unequivocally that the messages concerning non-triggered actions are very useful for developers in analysing underlying issues, but that's why I think they belong in the `.DBG` file instead.

We also report a block of keywords which get rerun as a result of an action triggering and I would like to direct this message block to the `.DBG` file too.

**Comment by atgeirr** [comment]
I agree.
