### ISSUE TITLE
Should wells be able to be SHUT/STOPPED during the history matching mode?

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#4192]
When testing the running with Norne, I saw some worrying messages like the following, 

```
Starting time step 0, stepsize 20 days, at day 1121/1152, date = 01-Dec-2000
 well D-1H gets STOPPED during iteration 
 well D-1H gets REVIVED during iteration 
    Well D-1H control mode changed from RESV to BHP
 Newton its= 9, linearizations=10 (0.5sec), linear its=148 (2.3sec)
.....
Starting time step 0, stepsize 3 days, at day 1560/1576, date = 13-Feb-2002
 well C-1H gets SHUT during iteration 
 well C-1H gets REVIVED during iteration 
    Well C-1H control mode changed from RATE to BHP
 Newton its= 5, linearizations= 6 (0.3sec), linear its= 49 (0.8sec)
```

Not totally sure we should allow shutting wells at all for the historic model.

**Comment by bska** [comment]
> Not totally sure we should allow shutting wells at all for the historic model.

We've been going back and forth on this.  The argument in favour of allowing wells to shut in the historic period is that when you're doing history matching/ensembles then the fact that a particular realization ends up shutting a well can be fed back to the optimisation algorithm as a defect and help guide the search direction.  There may be benefits in other use cases too, but this is the one I've most frequently heard.

Whether or not the Norne model should get into this situation may be a different matter though.

**Comment by GitPaean** [comment]
> The argument in favour of allowing wells to shut in the historic period is that when you're doing history matching/ensembles then the fact that a particular realization ends up shutting a well can be fed back to the optimisation algorithm as a defect and help guide the search direction. 

Thanks for the feedback. I am not aware of this. But if this is the design, then the issue is not a problem.  

> Whether or not the Norne model should get into this situation may be a different matter though.

For the Norne running, it shuts/stops wells during the newton iterations, so it is not really a problem for the final results. I was more concerned with the design of the code. 

Closing the issue now.
