### ISSUE TITLE
2022-10-RC1: Where is the release.

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#4203]
I cannot find the above release in the repositories, there is a 2022-10 branch but that will not compile on my machine. So what is the status and who is the release manager?

**Comment by GitPaean** [comment]
It compiled fine on my machine. @atgeirr  is the release manager this time.

**Comment by OPMUSER** [comment]
So this is the branch we should test against, yes. Why no notification?

Unlike my better half, I cannot read minds :-)

**Comment by OPMUSER** [comment]
Okay, now I get this:

```
Start: git rebase upstream/master opm-common
Dir  : /home/david/OPM/GitHub/opm-common
     : Rebasing (1/1)
     : Auto-merging dune.module
     : CONFLICT (content): Merge conflict in dune.module
     : error: could not apply d894ef99d... Bump version for release.
     : hint: Resolve all conflicts manually, mark them as resolved with
     : hint: "git add/rm <conflicted_files>", then run "git rebase --continue".
     : hint: You can instead skip this commit: run "git rebase --skip".
     : hint: To abort and get back to the state before "git rebase", run "git rebase --abort".
     : Could not apply d894ef99d... Bump version for release.
```

How to fix? All repositories have this error.

**Comment by GitPaean** [comment]
which branch are you trying to rebase based on `upstream/master`?

**Comment by GitPaean** [comment]
You should not rebase `release/2022.10/rc1` to upstream/master. 

You should just use the branch `release/2022.10/rc1`.

**Comment by OPMUSER** [comment]
@GitPaean thank you.

**Comment by atgeirr** [comment]
> So this is the branch we should test against, yes. Why no notification?

It was announced on the mailing list as usual. It looks to me like that email went through, please tell me if it did not!

**Comment by OPMUSER** [comment]
> It looks to me like that email went through, please tell me if it did not!

It did not, so I re-registered again using the same credentials and that was accepted. Don't know what is going on.

**Comment by OPMUSER** [comment]
Would also like to get the NewtonMaxIteration PRs in as well, so that we have all the Newton command line parameters together (https://github.com/OPM/opm-simulators/pull/4185 and https://github.com/OPM/opm-models/pull/741)
