### ISSUE TITLE
Flow seems to be reporting the gas viscosity in the WAT_VISC array 

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#4246]
[v2022.04] In the attached project the model CANUELO1.data was run in Flow with enable-opm-rst-file=true.

[CANUELO1.zip](https://github.com/OPM/opm-simulators/files/9946421/CANUELO1.zip)

In the output the WAT_VISC array data seems to be reporting the **_gas_** viscosity instead of the **_water_** viscosity. . 

![image](https://user-images.githubusercontent.com/47630958/200185913-ca2b65e8-86c6-4867-944c-01e8bc877974.png)

**Comment by bska** [comment]
> In the output the WAT_VISC array data seems to be reporting the gas viscosity instead of the water viscosity.

Thank you for the report.  You are completely correct, and this is a programming error in the output code.  The `gasPhaseIdx` in the [output vector table](https://github.com/OPM/opm-simulators/blob/87bf1b6020710268fae329515e71e18852470679/ebos/eclgenericoutputblackoilmodule.cc#L709) should be `waterPhaseIdx` instead.  I will fix this in the development sources and with a little understanding from the release manager, we might be able to get the fix into the 2022.10 release.

**Comment by bska** [comment]
> I will fix this in the development sources and with a little understanding from the release manager, we might be able to get the fix into the 2022.10 release.

@EdmundStephens : PR #4249 has the suggested fix and a plot of the revised water viscosity.  I think we'll be able to get this into the 2022.10 release too.
