### ISSUE TITLE
Completions slider limits should be limited to visible well

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#4247]
[v2022.06.1] In the well planning perforation property editor, the Start MD and End MD sliders normally start at MD=0. Please can the slider min / max be set to the visible well trajectory.

This would make using the slider possible when the reservoir is at large MD values (e.g. ~9000) as is often the case, whereas currently the lack of mouse precision is very awkward. The sliders already work nicely when the Well Targets check box 'Generate Target At Sea Level' is off.  

![image](https://user-images.githubusercontent.com/47630958/200251987-b0a1269f-8dd8-4419-bb90-4fbe0011f16b.png)

**Comment by bska** [comment]
Is this a Flow issue or a ResInsight issue?

**Comment by EdmundStephens** [comment]
Sorry it’s a ResInsight comment. I will repost there later.

**Comment by bska** [comment]
> Sorry it’s a ResInsight comment. I will repost there later.

Understood, thanks a lot for information! Please close this issue once the ResInsight issue is opened.
