### ISSUE TITLE
Add well target entry and movement control for heel section 

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#4248]
[v2022.06.1] Please can a well target entry and movement control gripper be generated to control the heel section. With no grid to click on, it is not possible to generate this point by clicking, but it would be useful to be able to adjust it once generated. The point should also appear in the Well Targets list so that it is editable / exportable. 

![image](https://user-images.githubusercontent.com/47630958/200254065-79eef9ed-c09b-46ab-a14f-e9f0d261c825.png)

**Comment by bska** [comment]
Is this a Flow issue or a ResInsight issue?

**Comment by EdmundStephens** [comment]
Sorry this is also a ResInsight issue, I will repost later.

**Comment by bska** [comment]
> Sorry this is also a ResInsight issue, I will repost later.

Understood, thanks a lot for information!  Please close this issue once the ResInsight issue is opened.
