### ISSUE TITLE
OPM 2022.04 gives assertion error on simple setup

### ISSUE THREAD

**Issue by eivindjahren** [OPM/opm-simulators#4341]
The following simple setup worked fine with opm 2021-10 but results in error
```
 flow: ./opm/simulators/timestepping/TimeStepControl.cpp:140: virtual double Opm::PIDTimeStepControl::computeTimeStepSize(double, int
, const Opm::RelativeChangeInterface&, double) const: Assertion `errors_[i]>0' failed.
```

when run with 2022.04

TEST.DATA
----------------
<details>

```
RUNSPEC
UNIFOUT

METRIC
DIMENS
 2 2 2 /
START
   1 'JAN' 2000 /
OIL
WATER
WELLDIMS
 0 /
EQLDIMS
 /
TABDIMS
 1* 1* 30 30 /
GRID
INIT
INCLUDE
 'TEST.GRDECL' /
PORO
 8*0.3 /
PERMX
 8*150 /
PERMY
 8*150 /
PERMZ
 8*150 /
PROPS
SWOF
 0.1 0.0    1.0 0.0
 0.5 2.0E-6 0.1 0.0
 1.0 1.0E-5 0.0 0.0 /
PVTW
 270.0 1.0 5e-05 0.3 0.0 /
DENSITY
 860.0
 1030.0
 0.8 /
PVTO
 0.001 15.0    1.0 0.1 /
 1.6   5000.0  1.8 0.5
                                    9000.0  1.7 0.6/
 /

SOLUTION
EQUIL
 1000
 4800
 1000
 0
 1000
 0
 0
 0
 0
 /
SUMMARY
FOPR
SCHEDULE
RPTSCHED
 'PRES'/
RPTRST
 'BASIC=1' /
TSTEP
 366 /
END
```
</details>

TEST.GRDECL
--------------------
<details>

```
SPECGRID
 2 2 2 1 F
 /
COORD
 0.0 0.0 0.0 0.0 0.0 3.0
 1.0 0.0 0.0 1.0 0.0 3.0
 2.0 0.0 0.0 2.0 0.0 3.0
 6.123233995736766e-17 1.0 0.0 6.123233995736766e-17 1.0 3.0
 1.0 1.0000000000000002 0.0 1.0 1.0000000000000002 3.0
 2.0 1.0000000000000002 0.0 2.0 1.0000000000000002 3.0
 1.2246467991473532e-16 2.0 0.0 1.2246467991473532e-16 2.0 3.0
 1.0000000000000002 2.0 0.0 1.0000000000000002 2.0 3.0
 2.0 2.0000000000000004 0.0 2.0 2.0000000000000004 3.0

 /
ZCORN
 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 0.0 0.0
 0.0 0.0 0.0 0.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0 1.0
 1.0 1.0 1.0 1.0 1.0 1.0
 2.0 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0 2.0 2.0
 2.0 2.0 2.0 2.0
 /
```
</details>

**Comment by GitPaean** [comment]
Hei, @eivindjahren .  The challenge brought by this case is that there is nothing going on with this case, and the adaptive time step calculation, which based on the change of results between time steps, failed to get a proper calculation of the time steps.   More specially, the following code https://github.com/OPM/opm-simulators/blob/87a357f77e67a767cc4a3f0290d825e3176c097c/opm/simulators/timestepping/TimeStepControl.cpp#L156

When the `errors_[2]==0`.  It is an corner situation we should handle.  The comment here is just trying to give you some explanation. Maybe it can help you to fix your deck for you experiments. I will try to provide a PR, but I am not the one most familiar with the time step control size calculation.

**Comment by GitPaean** [comment]
A PR https://github.com/OPM/opm-simulators/pull/4415 was created to fix the running with this type of corner situation. Not saying it is the most proper way, but it can be the start.

**Comment by GitPaean** [comment]
With https://github.com/OPM/opm-simulators/pull/4415# merged, this issue should be solved. I am closing this issue. Feel free to reopen it if the problem persists on your side. @eivindjahren

**Comment by eivindjahren** [comment]
Looking at the PR I see that the offending assert is removed, and from what I understand there is an error message in place instead. Hopefully this new error message can make it possible to understand why the input I have shown above fails. The test data comes from the integration tests with xtgeo where we attempt to have xtgeo's reading of output from opm match opm's reading: https://github.com/equinor/xtgeo/tree/master/tests/test_opm_integration .

**Comment by GitPaean** [comment]
Hei, @eivindjahren, 

The original assertion failure is because `error == 0`, where `const double error = relChange.relativeChange(); `

With the PR #4415, we can handle the situation with `error == 0` by using the  if branch 
```c++
else if (errors_[1] == 0 || errors_[2] == 0.)
```
. As we provides a solution for the failing assertion condition, we do not need that assert anymore. 

In another word, with the PR#4415 merged, the case (TEST.DATA) can be run properly by OPM-flow, there should be no error message given during the OPM-flow running. 

Let me know if it is clear to you.
