### ISSUE TITLE
2023.04-pre: KRNUMX-, KRNUMY- and KRNUMZ- Issue

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#4408]
If one activates the `KRNUMX`, `KRNUMY`, and `KRNUMZ` keywords in the input deck, then the data is written to The *.INIT file.

However, if you use the `KRNUMX-`, `KRNUMY-`, and `KRNUMZ-` keywords the data is **not** written to the *.INIT file. Whereas, the commercial simulator does write the data out. 

Now in the manual we `SATOPS(IRREVERS)` as not supported, which means the` KRNUM-` series of keywords should cause the simulator to STOP, but this does not happen, as the run continues. If I compare a `KRNUM+` run with a (`KRNUM+/KRUNM-`), case then the results are identical. Thus, supporting the augment that the `KRNUM-` keywords are not supported. Secondly, if I compare OPM Flow's `KRNUM-` against the commercial simulator, then the commercial simulator gives different results.

Thus, we should either implement `KRNUM-` series of keywords, or set these keywords as unsupported and stop the simulation.

I know the easy answer, but what do others think. 

See [#3113/opm-common](https://github.com/OPM/opm-common/pull/3113) for a confusing discussion.

**Comment by bska** [comment]
> If one activates the `KRNUMX`, `KRNUMY`, and `KRNUMZ` keywords in the input deck, then the data is written to The *.INIT file.
> 
> However, if you use the `KRNUMX-`, `KRNUMY-`, and `KRNUMZ-` keywords the data is **not** written to the *.INIT file. Whereas, the commercial simulator does write the data out.

The `.INIT` file [contains](https://github.com/OPM/opm-common/blob/2b2c05d9a145aa809af41969dc079f05dcfeb485/src/opm/output/eclipse/WriteInit.cpp#L334-L335) all integer tables known to the `FieldPropsManager::keys<int>()`.  These, ultimately, are the arrays available in the model that are **also** in the list of "known" integer arrays.  As of right now, and as you've identified, the `KRNUM*-` arrays are not recognised by the property handling system and are therefore just ignored.

> Thus, we should either implement `KRNUM-` series of keywords, or set these keywords as unsupported and stop the simulation.

Until such time as we actually support the keywords the simulator should stop.

**Comment by totto82** [comment]
> Thus, we should either implement KRNUM- series of keywords, or set these keywords as unsupported and stop the simulation.

It shouldn't be to much work to implement KRNUM*- but I dont think we have any use case for that at the moment so I suggest that we add it in the unsupported list first.

**Comment by OPMUSER** [comment]
@totto82 I have update the manual to indicate that KRNUM*- keywords are not supported.

Will close.
