### ISSUE TITLE
Keyword Operate

### ISSUE THREAD

**Issue by rcgz** [OPM/opm-simulators#4459]
![Capture PNG1](https://user-images.githubusercontent.com/103476917/218862405-904fa490-171e-4703-abb2-f3f24b197a71.jpg)

When running the model, it presents us with this error with the Operate keyword, we tried to correct the data but it gave us another error

![Capture PNG2](https://user-images.githubusercontent.com/103476917/218862708-6257d09a-a43c-49eb-a8d4-12b421528882.jpg)
 
what could be the error?

**Comment by atgeirr** [comment]
That is a very unhelpful error message, for sure! It is usually triggered because some well name, group name, or pattern name was not found. Without the deck I cannot tell for sure, but I would advise to check that the name/pattern strings in your deck match where they should be equal. Can you provide the bottom lines of the .DBG file?

**Comment by joakim-hove** [comment]
My guess: `OPERATE` applied to `MULTZ`?

**Comment by OPMUSER** [comment]
@rcgz can you copy and paste the original `OPERATE/OPERATER` section as well as your work around, and I'll take a look.

In the mean time, if you need a work around you can always use OPM ResInsight's Grid Property Calculator to perform the calculations.

![image](https://user-images.githubusercontent.com/17958927/218978254-a53eb97b-164d-4b0d-a465-3704885086e0.png)

![image](https://user-images.githubusercontent.com/17958927/218979034-e8aa54b3-2a96-4711-a423-2c7d2f88360e.png)

The calculator also has conditionals as well, so you should be able to duplicate the `OPERATE/OPERATER` calculation.

**Comment by blattms** [comment]
I second @joakim-hove concerning the first error message, here. We have seen this at other places and fixed the error message, see #3055. I think there is a low priority plan to fix the underlying issue of said bug-report.

Concerning the second one, we indeed need more information or a simple test model.

**Comment by rcgz** [comment]
[P10_HM.zip](https://github.com/OPM/opm-simulators/files/10743875/P10_HM.zip)

is .dbg file

![Captura de pantalla 2023-02-15 092355](https://user-images.githubusercontent.com/103476917/219054285-a804db82-97be-4aaa-9605-2604b13ef6c1.png)

and that's how we have the data

**Comment by rcgz** [comment]
[P10_HM.zip](https://github.com/OPM/opm-simulators/files/10743964/P10_HM.zip)

is .dbg file

![Captura de pantalla 2023-02-15 093012](https://user-images.githubusercontent.com/103476917/219056097-1523b829-ac2c-4ba3-b60f-a2ca7ed3fdf9.png)

and that's how we have the data

**Comment by atgeirr** [comment]
Hi, I looked at the DBG file, and while it unfortunately did not make me any wiser as to what exactly is causing the error, it does indicate that the version of OPM Flow you are running is somewhat old (2021.10). I suggest testing your case with a newer version, as the problem may be addressed already. Release 2022.10 is as of now the latest release, the next release should be 2023.04.

**Comment by rcgz** [comment]
how can we install the latest version of OPM Flow, since we follow the steps as they are in the manual. 
We tried with updated versions of ubuntu, but OPM does not work and we work with version 20.04 of ubuntu.

**Comment by OPMUSER** [comment]
> My guess: OPERATE applied to MULTZ?

@joakim-hove is correct, the error is caused by using the MULTZ array in the OPERATE keyword. This is a known limitation of the simulator. You will have the same issue even in the 2022-10 release.

You need to find an alternative work flow to work around this, as per the suggestion above.

**Comment by OPMUSER** [comment]
@rcgz Concerning upgrading the version of OPM Flow, are using a Linux box, a VM, or WSL?

**Comment by OPMUSER** [comment]
@rcgz 
> You need to find an alternative work flow to work around this, as per the suggestion above.

If applicable, using PERMZ instead of MULTZ will work.

**Comment by rcgz** [comment]
@OPMUSER we are working in VM

we apply PERMZ, but it alters the results by increasing oil production.
Is there any other alternative?

**Comment by verauser** [comment]
@rcgz you can change MULTZ for TRANZ

**Comment by OPMUSER** [comment]
> you can change MULTZ for TRANZ

That will not work, same problem as MULTZ, but different error message:

```
Error:
An error occurred while creating the reservoir properties
Internal error: INFO: No such keyword: TRANZ
```

@rcgz Since you are using Petrel why not do the calculation in Petrel and export the final MULTZ array? Otherwise use OPM ResInsight.

**Comment by OPMUSER** [comment]
> @rcgz  we are working in VM

Okay, assuming you are on a Windows box using VirtualBox:

1. Clone your original VM, so that you have a duplicate.
2. Upgrade the clone VM to Ubunto 22-04 LTS (see https://itsubuntu.com/how-to-upgrade-ubuntu-22-04-lts/)
3. Then follow the manual to install OPM Flow.

**Comment by rcgz** [comment]
@OPMUSER I tried it with ubuntu 22.04, but I got to the line `apt-cache search opm-simulators` and I can't progress in the opm installation.

**Comment by OPMUSER** [comment]
Okay, did you do the following:

1. `sudo apt-get update`
2. `sudo apt-get install software-properties-common`
3. `sudo apt-add-repository ppa:opm/ppa`
4. `sudo apt-get update`
5. `apt-cache search opm-simulators`
6. `sudo apt-get install mpi-default-bin`
7. `sudo apt-get install libopm-simulators-bin`

Please paste the contents of executing the above commands.

**Comment by rcgz** [comment]
I try many time install ubuntu 22.04 but It couldnt work, when the process its finished the virtual box doesnt start and  OPM only intall in ubuntu 20.04 version

**Comment by rcgz** [comment]
![WhatsApp Image 2023-02-22 at 16 39 33](https://user-images.githubusercontent.com/103476917/220765957-4eea2300-f28d-4d9c-93a9-bf76ee5a11bf.jpeg)

Even installed Ubuntu 22.04 version and the last OPM version according your recomendations it doesn work. Still appear "operate" keyword error.  Thus we try to use grid property calculator but only work with add operator.  

If there other option for "operate" keyword that you can help me.

**Comment by rcgz** [comment]
[P10_HM.zip](https://github.com/OPM/opm-simulators/files/10808703/P10_HM.zip)

is .dbg file

**Comment by OPMUSER** [comment]
@ Good to see you have found a workaround.
