### ISSUE TITLE
Seemingly wrong keyword referenced in OPM user manual

### ISSUE THREAD

**Issue by eivindjahren** [OPM/opm-simulators#4541]
On page 2494 of https://opm-project.org/wp-content/uploads/2022/12/OPM_Flow_Reference_Manual_2022-10.pdf , Table F46  uses keyword "SEQNUM" while the example uses keyword "SEQHDR".

**Comment by bska** [comment]
Thanks a lot for the the report; You've found a problem in the manual.  Summary files use the `SEQHDR` keywords while restart files use the `SEQNUM` keyword.  Table F.46 must be updated to list/show `SEQHDR` instead of `SEQNUM`.  I've assigned this issue to @OPMUSER who maintains the manual.

**Comment by OPMUSER** [comment]
@bska Thanks fr the clarification.

@eivindjahren Thanks for the report.
I have updated the manual accordingly for the 2023-04 release, please close the issue
