### ISSUE TITLE
Cell Pressures

### ISSUE THREAD

**Issue by loveduah1** [OPM/opm-simulators#4610]
Hello,
Please how do I measure the pressure in a cell, or at a grid point?
I want results (for pressures) similar to the output of BWSAT for block saturation.

**Comment by loveduah1** [comment]
Please I think I found it 

BPR. 

thank you

**Comment by bska** [comment]
> BPR.

Yes, that is correct.  Entering
```
BPR
  I J K /
```
in the `SUMMARY` section will generate a timeseries of block pressures in cell (I,J,K)&mdash;assuming that cell is active&mdash;in the summary file.  That timeseries can be plotted using ResInsight or some other tool, e.g., [qsummary](https://github.com/OPM/qsummary).

**Comment by loveduah1** [comment]
Thank you Sir.

**Comment by blattms** [comment]
I closed this one, because it seemed answered. I am sorry if this seemed rude. Now I see that it was actually reopened 1 hour ago by @loveduah1. Is there a reason for this?

**Comment by loveduah1** [comment]
I was having challenges starting a new issue on github so I opened this issue to test if I could comment, but that did not work at the time. Let me close it now because everything is working now.
