### ISSUE TITLE
Flow: Exception

### ISSUE THREAD

**Issue by loveduah1** [OPM/opm-simulators#4649]
Hello 
Please, do I get the error below when I run the attached? I'm not sure what I am getting wrong. 
```
processing grid
Total number of active cells: 121 / total pore volume: 32326531 RB
Program threw an exception: input global index above valid range
```
[Base.zip](https://github.com/OPM/opm-simulators/files/11452854/Base.zip)

**Comment by bska** [comment]
There are two, well three if you count two instances of the same separately, problems here.

1. Your SUMMARY section references cells outside the grid's dimensions.  In particular, your `BGSAT` and `BWSAT` summary vectors both want output from cell `(1,1,3)` and that cell does not exist in your model which has dimensions $11\times 11\times 1$.
2. There is no timestepping in your SCHEDULE section which makes some internal logic reference report steps that don't exist.

We recently added a diagnostic check for the first issue&mdash;PR OPM/opm-common#3510&mdash;but we don't have similar checks in place for the second problem.  That's a bug in the simulator.  In any case, once I replace cell `(1,1,3)` with `(1,1,1)` and add a timestepping sequence, your model runs through on my machine.

**Comment by loveduah1** [comment]
Thank you.

**Comment by loveduah1** [comment]
Hello 
1) Please how do I write 

TSTEP
30/  --to report in days? That's daily reporting time for 30 days.

2) How do I know or set the saturation of a model? I want to set the water saturation of the attached to 100% but I am not sure if saturation is assumed to be 100% or not.

[MATCH.zip](https://github.com/OPM/opm-simulators/files/11501102/MATCH.zip)

**Comment by loveduah1** [comment]
Please for the TSTEP issue above, how do I avoid writing the schedule 30 times, but can get daily reporting data in the rsm

DATES
1 DEC 2023 /
/
WELOPEN
'INJW' 'SHUT' /
'INJG' 'OPEN' /
/

DATES
/
2 DEC 2023 /
/
WELOPEN
'INJW' 'SHUT' /
'INJG' 'OPEN' /
/

**Comment by bska** [comment]
You're asking at least two different questions, and it's hard to know exactly what you want to accomplish.

1. Do you want to limit the simulator's maximum timestep size to 1 day for (summary) reporting purposes?  If so you can use the `--solver-max-time-step-size-in-days=1` command-line option or enter a `TUNING` keyword or the form
    ```
    TUNING
    1.0 1.0 /
    /
    /
    ```
    and then run the simulator with the `--enable-tuning=true` command-line option
2. Do you want restart-file output every day?  In that case you'll need to have 30 report steps of one day each in your time-stepping description.  The easiest way to write that is
    ```
    TSTEP
      30*1.0 /
    ```
    but you should be aware that writing that will run with constant controls over the full 30-day period.

Finally, you mention the `.RSM` file.  My personal view is that while useful in a pinch, especially if you want to share result files with someone who does not have the full set of tools, the `.RSM` file is inferior to the actual summary file set (`.SMSPEC` and `.UNSMRY`).  It is always better to use the `summary` utility to extract the time series you need than to manually try to parse the `.RSM` file.

**Comment by loveduah1** [comment]
Thank you, sir

**Comment by bska** [comment]
> Hello
> 
> Please how do I know or set the saturation of a model? I want to set the water saturation of the attached model to 100%

In general you form the initial condition in one of two distinct ways, 

1. By explicitly assingning the per-cell valuta of the phase saturations, fluid pressure and dissolved gas/oil and vaporised oil/gas ratios. This is the "enumerated" method using the PRESSURE and SWAT/SGAS keywords. 

2. By using the simulator's built-in "equilibration" facility which assumes that all masses are at gravitational equilibrium and that the gas/oil and oil/water contacts (equivalently the free gas, free oil, and free water levels) are known at the start of the simulation run. This method uses the EQUIL and RSVD (or similar) keywords.

Your model appears to be based on this second method. In that case, the easiest way to get an initial water saturation of `1.0` (100%) is to place the oil/water contact above the formation. In other words, if the top of your model's formation is at 5000 feet, then your oil/water contact should be no deeper than 5000 feet in order to guarantee that the initial water saturation is 1.0 In every cell. Please see the manual for how to specify the oil/water contact in the EQUIL keyword.

That said, your model only declares a single active phase, WATER, in the RUNSPEC section. In that situation you will never get anything other than SWAT=1.0 throughout the model. The only free variable will be the fluid pressure. If that's not your intended study case, you need to declare more active phases in the RUNSPEC section.

**Comment by loveduah1** [comment]
Thank you, Sir.

**Comment by loveduah1** [comment]
Hello,

Please why am I getting the error below from the attached file?
================ Starting main simulation loop ===============


Report step  0/1 at day 0/366, date = 31-Dec-2014

Starting time step 0, stepsize 1 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.330000 days


Starting time step 0, stepsize 0.33 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.108900 days


Starting time step 0, stepsize 0.1089 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.035937 days


Starting time step 0, stepsize 0.035937 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.011859 days


Starting time step 0, stepsize 0.0118592 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.003914 days


Starting time step 0, stepsize 0.00391354 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.001291 days


Starting time step 0, stepsize 0.00129147 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.000426 days


Starting time step 0, stepsize 0.000426184 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.000141 days


Starting time step 0, stepsize 0.000140641 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.000046 days


Starting time step 0, stepsize 4.64115e-05 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Compute initial well solution for new well PROD failed. Continue with zero initial rates

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Problem: Solver convergence failure - Numerical problem encountered
Timestep chopped to 0.000015 days


Starting time step 0, stepsize 1.53158e-05 days, at day 0/366, date = 31-Dec-2014

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Warning: Message limit reached for message tag: WELL_INITIAL_SOLVE_FAILED

Error: [./opm/simulators/wells/StandardWell_impl.hpp:2080] Infinite primary variable after update from wellState well: PROD

Error: Solver failed to converge after cutting timestep 10 times.
Program threw an exception: [./opm/simulators/timestepping/AdaptiveTimeSteppingEbos.hpp:547] Solver failed to converge after cutting timestep 10 times.
[START.txt](https://github.com/OPM/opm-simulators/files/11803354/START.txt)

**Comment by GitPaean** [comment]
thanks for the reporting, the following is some of my investigation. 

At the first time step, 

the well `PROD` enters the following code in BlackoilWellModel_impl.hpp
```c++
        if (alternative_well_rate_init_) {
            // Update the well rates of well_state_, if only single-phase rates, to
            // have proper multi-phase rates proportional to rates at bhp zero.
            // This is done only for producers, as injectors will only have a single
            // nonzero phase anyway.
            for (auto& well : well_container_) {
                if (well->isProducer()) {
                    well->updateWellStateRates(ebosSimulator_, this->wellState(), local_deferredLogger);
                }
            }
```

It enters the function `updateWellStateRates`. 

In the function `updateWellStateRates`, the initial well rates in the well state is 
[0] = {double} 0
[1] = {double} -0.022081568740000002
[2] = {double} 0

With code
```c++
 std::vector<double> well_q_s = computeCurrentWellRates(ebosSimulator, deferred_logger);
```
well_q_s is 
[0] = {double} 0
[1] = {double} -0.71818269344579422
[2] = {double} 0

then the following code is used to scale the well rates
```c++
        const double initial_nonzero_rate = ws.surface_rates[nonzero_rate_index];
        const int comp_idx_nz = this->flowPhaseToEbosCompIdx(nonzero_rate_index);
        for (int p = 0; p < this->number_of_phases_; ++p) {
            if (p != nonzero_rate_index) {
                const int comp_idx = this->flowPhaseToEbosCompIdx(p);
                double& rate = ws.surface_rates[p];
                rate = (initial_nonzero_rate/well_q_s[comp_idx_nz]) * (well_q_s[comp_idx]);
            }
        }
```

For this case, `nonzero_rate_index` is 1, `comp_idx_nz` is 0. then you will see you will get a inf and nan during the scaling for the surface_rates of the well. 
[0] = {double} inf
[1] = {double} -0.022081568740000002
[2] = {double} -nan(0x8000000000000)

we should not scale the well rates when `well_q_s[comp_idx_nz] == 0`. 

my best guess is that you are trying to produce oil in a region there is no oil at all? but it is just a guess.

**Comment by loveduah1** [comment]
Thank you

**Comment by GitPaean** [comment]
I did not read through everything here. not totally whether it should be closed. feel free to re-open it if you want to. @loveduah1

**Comment by bska** [comment]
> I did not read through everything here. not totally whether it should be closed

I think it's fine to close this issue now, because the discussion had drifted on to topics different from those that prompted the initial investigation.  If other problems arise we should open a different issue.
