### ISSUE TITLE
EclTransmissibility::applyNncToGridTrans_ Returns a Value Which is Never Used

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#4799]
I assume I'm missing something since the current code is effectively unchanged since commit 5e83a26908 and I'm not at all familiar with this code, but [`EclTransmissibility<>::applyNncToGridTrans_()`](https://github.com/OPM/opm-simulators/blob/207e57804d9713090004fe002efa401cc1804c74/ebos/ecltransmissibility.hh#L199-L200) [returns](https://github.com/OPM/opm-simulators/blob/207e57804d9713090004fe002efa401cc1804c74/ebos/ecltransmissibility_impl.hh#L875) a value&ndash;a `tuple<>` of `vector<NNCdata>` objects&ndash;which in turn is [just discarded](https://github.com/OPM/opm-simulators/blob/207e57804d9713090004fe002efa401cc1804c74/ebos/ecltransmissibility_impl.hh#L469) at the call site.  This means that the effort to [identify unrepresented NNCs](https://github.com/OPM/opm-simulators/blob/207e57804d9713090004fe002efa401cc1804c74/ebos/ecltransmissibility_impl.hh#L864-L866) is effectively wasted.

Is this intentional?  If so, should we make the return type be `void` instead to make it clear that the function does not need to return anything?

**Comment by blattms** [comment]
Even after looking at the history, I have literally no idea why that is there.
Yes, please remove.

**Comment by bska** [comment]
>> should we make the return type be `void` instead to make it clear that the function does not need to return anything?
>
> Yes, please remove.

Cool.  I'll make a PR to that effect.
