### ISSUE TITLE
Calculation of gas dissolved in water ratio

### ISSUE THREAD

**Issue by gdfldm** [OPM/opm-simulators#4972]
https://github.com/OPM/opm-simulators/blob/763d25541a7b1a0bbf885c7f0be57596b5f5e33f/opm/simulators/wells/StandardWellConnections.cpp#L348

I think this should be
`rsw = gasrate / waterate;`

**Comment by totto82** [comment]
Thanks for noticing. I will provide a fix soon.

**Comment by blattms** [comment]
BTW: The fix will also be part of the release.

**Comment by totto82** [comment]
It is fine that this is part of the release, but I don't think it is very important bugfix to include in the release. I hope it dont slow down the release process. It only affects models where you try to inject dissolved CO2 in water or if you start producing CO2 in well in a CO2STORE case. This may be relevant if you plan to reduce the over-pressure.
