### ISSUE TITLE
combining --load-step with different --output-dir triggers warning

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#5019]
I copied all input and output files of a run to a different directory. To make sure I do not pollute them I specify `--output-dir=bool-fix` together with `--load-step=800` and get the following warning:
```
Loading serialized state for report step 800

Warning: Command line parameters mismatch:
Differences:
	-OutputDir=""
	+OutputDir="bool-fix" # default: ""
```
This is correct, but I am wondering whether there will be any side effects when doing this.

**Comment by akva2** [comment]
No. You can probably add it to the ignore list, https://github.com/OPM/opm-simulators/blob/master/opm/simulators/flow/SimulatorFullyImplicitBlackoilEbos.cpp#L70

**Comment by blattms** [comment]
Seems like I can also use a different `--save-step` together with. That's awesome.
