### ISSUE TITLE
H2STORE and mutiple regions

### ISSUE THREAD

**Issue by mscsiro** [OPM/opm-simulators#5061]
Hi, I was wondering if the `H2STORE` (and possibly `CO2STORE`) works with `SATNUM`? I am getting an error:
```
"TableContainer has a max: of 1 tables. Table number: 1 illegal. " with
TABDIMS
2 /
```
I am using the OIL/GAS implementation of `H2STORE` and `CO2STORE`. 
Thank you :-)

**Comment by totto82** [comment]
> Hi, I was wondering if the H2STORE (and possibly CO2STORE) works with SATNUM? 
Yes it is. (but it does not work with PVTNUM > 1)

**Comment by mscsiro** [comment]
I just made some minor modifications to the test case. Here is the updated data file. 
-- Test case for diffusion in co2-brine system
----------------------------------------------------------------------------
RUNSPEC
----------------------------------------------------------------------------
TITLE
   CO2STORE DIFFUSIVE

DIMENS 
20 1 20 /

EQLDIMS
/

TABDIMS
/

OIL
GAS
H2STORE
DISGAS
DIFFUSE
--THERMAL

METRIC

START
   1 'JAN' 2019 /

WELLDIMS
   2 10 1 1 /

UNIFIN
UNIFOUT

TABDIMS 
 2 1 40 30 1* 1* 1* 1 /

----------------------------------------------------------------------------
GRID
----------------------------------------------------------------------------

NOECHO

INIT

DX 
  400*5 /

DY 
  400*100 /

DZ 
  400*5 /

TOPS
  20*0.0 /

PORO 
  399*0.3
1E10/

PERMX 
40*2000
20*0.1
340*2000/

PERMY
40*2000
20*0.1
340*2000/
  
PERMZ 
40*2000
20*0.1
340*2000/
----------------------------------------------------------------------------
PROPS
----------------------------------------------------------------------------

ROCK
  1.0 1e-6 /
  
SGOF
0       0     0.9     0
0.1	0	0.9	0
0.9	0.9 	0 	0.0 /
0       0      0.9     50.0
0.1	0	0.9	50.0
0.9	0.9 	0 	0.0 /

SALINITY
 0.7/ 35-40g/l  -> 35-40g /kg -> 0.63-0.72 mol/g

REGIONS
SATNUM
40*1 20*2 340*1 /
----------------------------------------------------------------------------
SOLUTION
---------------------------------------------------------------------------
EQUIL
 0 200 1000 0 0 0 1 1 0 /    
RTEMPVD
  0 50
  100 50
/
RSVD
  0 0.0
  100 0.0 /

RPTRST
 'BASIC=2' 'ALLPROPS'/
	
----------------------------------------------------------------------------	
SUMMARY
----------------------------------------------------------------------------
SCHEDULE
----------------------------------------------------------------------------

RPTRST
 'BASIC=2' 'ALLPROPS'/

WELSPECS
-- Item #: 1	 2	3	4	5	 6
	'INJ'	'G1'	1	1	1*	'GAS' /
/

COMPDAT
-- Item #: 1	2	3	4	5	6	7	8	9
	'INJ'	1	1	20	20	'OPEN'	1*	1*	0.5 /
/

WCONINJE
	'INJ'	'GAS'	'OPEN'	'RATE'	1000 1* 400 /
/

TSTEP
50*10
/

WCONINJE
-- Item #:1	 2	 3	 4	5      6  7
	'INJ'	'GAS'	'OPEN'	'RATE'	1000 1* 400 /
/

END

**Comment by totto82** [comment]
> TABDIMS
> /

Remove duplicated TABDIMS!

**Comment by mscsiro** [comment]
That was embarrassing that I didn't check for that! :-( 
Thank you :-)
