### ISSUE TITLE
Issues while running flow from Python.

### ISSUE THREAD

**Issue by flammmes** [OPM/opm-simulators#5100]
I encountered a few issues while trying to run some test cases from python. 
In contrast running all of them from terminal produced no such issues.
```python
import os
import numpy as np
from opm.simulators import BlackOilSimulator
from opm.io.parser import Parser
from opm.io.ecl_state import EclipseState
from opm.io.schedule import Schedule
from opm.io.summary import SummaryConfig
parser = Parser()
#deck = parser.parse('opm/opm-tests/spe5_co2eor/SPE5CASE1_DYN.DATA')
#deck = parser.parse('opm/opm-tests/co2store/CO2STORE.DATA')
#deck = parser.parse('opm/opm-tests/co2store/CO2STORE_GW.DATA')
#deck = parser.parse('reveal/deck.DATA')
state = EclipseState(deck)
schedule = Schedule(deck, state)
summary_config = SummaryConfig(deck, state, schedule)
sim = BlackOilSimulator(deck, state, schedule, summary_config)
sim.step_init()
sim.step()
```
SPE5CASE1_DYN
[errors_SPE5CASE1_DYN.txt](https://github.com/OPM/opm-simulators/files/13901364/errors_SPE5CASE1_DYN.txt)

CO2STORE
[errors_CO2STORE.txt](https://github.com/OPM/opm-simulators/files/13901388/errors_CO2STORE.txt)

CO2STORE_GW
[errors_CO2STORE_GW.txt](https://github.com/OPM/opm-simulators/files/13901401/errors_CO2STORE_GW.txt)

Finally in my deck i used OIL, GAS and CO2STORE keywords along with SGOF and it produced those errors:
[errors_deck.txt](https://github.com/OPM/opm-simulators/files/13901435/errors_deck.txt)

I was however able to work around this by adding the WATER and SWOF keywords in the deck, which is strange considering CO2STORE requires only two phase keywords. Trying to run it as a gas water system produced the same errors as CO2STORE_GW.

**Comment by totto82** [comment]
> which is strange considering CO2STORE requires only two phase keywords

The PyBlackOilSimulator only works for the traditional blackoil. i.e. not 2-phase and not solvent. If you want to run 2p or solvent. You will need to create something like a  PyBlackOilGasWaterSimulator. I dont think it would require too much work to extend the python wrappers to allow for other variants of Flow, but it has not been done.

**Comment by flammmes** [comment]
Thank you very much for the feedback. I will close the issue and try to implement what you recommended.
