### ISSUE TITLE
We should stop using the WellsManager and Wells struct.

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-simulators#532]
This change has been requested by many. See discussion in #528 for example.

Also, it must be considered in the context of multi-segment wells.

**Comment by GitPaean** [comment]
We need to handle at least two kinds of wells at the same time since now. We  need something really new here, such like a well container can hold more than one type of well.

**Comment by bska** [comment]
> We need to handle at least two kinds of wells at the same time since now

What are those kinds?  Multi-segmented and "regular"?  In that case, I'd prefer that we implement the most general and allow the other as a special case.  I really don't want to have to introduce special case handling in the clients of the new facility.

**Comment by GitPaean** [comment]
There are some other different type of wells from different simulators. 

I think within the `regular` and multi-segment well, multi-segment well is the more general one, we can convert regular well to multi-segment well. That can be good. And also, I think with a well container to handle different type of wells separately can be more flexible for future extension, I mean a third or more types of wells come up.

I am open to either way, but it is just a decision we need to make.

**Comment by bska** [comment]
It's still not clear to me what other types of wells you're thinking of.  More general well-bore topology?  More general completions?  Different bore-hole flow models?

**Comment by GitPaean** [comment]
I do not know a lot of well models at the moment. Frictional well is not more complicated than multi-segment well. FlexWell I am not sure. Some people mentioned Navier-Stokes for well modeling, while I have never read about it. 
I am talking about the possibility for future. And also, I am open to any solution.

**Comment by atgeirr** [comment]
> what other types of wells you're thinking of

Multi-segment wells primarily (your first point), but in the longer term we may want to consider quite general coupling to well models (or well simulations).

**Comment by bska** [comment]
> in the longer term we may want to consider quite general coupling to well models (or well simulations).

Sure, but at present this is like generalising from zero examples.  There is no way we'll be able to anticipate the needs of those more complicated situations right now, so the only thing we can and should do is take multisegmented wells into account and hopefully make the result flexible to change when the actual need arises.

**Comment by qilicun** [comment]
If we decided to use the multi-segment well as the only well struct, opm-polymer should make some changes(not only well related),especially for shear model from eclipse technical manual.  but these changes are not that clear to me.

**Comment by GitPaean** [comment]
> If we decided to use the multi-segment well as the only well struct, opm-polymer should make some changes(not only well related),especially for shear model from eclipse technical manual. but these changes are not that clear to me.

I am not sure what the final solution will be, while basically most (if not all) of the well rated functions need to be updated afterwards.

**Comment by joakim-hove** [comment]
I hope we can implement something along these lines:

1. Everything input related is implemented in `EclipseState::Schedule` class.
2. The `WellState` class is much tighter bound to the specific simulator; in particular the simulator should fully manage the `WellState` object - and it should not be necessary to ever see a `WellState`object outside of the simulator `run` method. 

That way it should be simple(?) to create specialized `WellState` classes for specific simulator <-> well model combinations - without having to be very general.

**Comment by atgeirr** [comment]
I am not sure we agree about the `WellState` classes: it depends a little on what you mean by "the simulator". They currently serve the following purposes:
 - To communicate state with the model's "take one timestep" function (it is both input and output argument).
 - To communicate state to the output system.

Is there something I am missing? What do you want changed?

**Comment by joakim-hove** [comment]
> I am not sure we agree about the WellState classes:

Probably not - and you are the expert here; so bear with my rambling.

> To communicate state with the model's "take one timestep" function (it is both input and output argument).

Is it necessary to *communicate state* here; can we not limit ourselves to just 'hold onto state'.

> To communicate state to the output system.

That could be part of the simulator API?

**Comment by blattms** [comment]
Closing as I believe both have been killed by various refactorings
