### ISSUE TITLE
Cmake version bump breaks build on Red Hat 7

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#5339]
The offending commit is this:
https://github.com/OPM/opm-simulators/commit/e9d6b326ccb641321f6c6ad48ff00f353d69ba2b
where the cmake version was bumped from 3.10 to 3.21. The newest version available on Red Hat 7 is 3.17.5. This broke build on our end. @multitalentloes great if you can have a look.

**Comment by multitalentloes** [comment]
I am looking into this now

**Comment by bska** [comment]
I **suppose** one option could be to make the HIP support contingent on CMake >= 3.21 and to reset the minimum required CMake version to whatever's available on Ubuntu 22.04 LTS since that's what we claim to support in master.  Another option could possibly be to get a more recent CMake version on RHEL through EPEL (or even APEL).  I'll defer the feasibility of the latter to @akva2.

**Comment by alfbr** [comment]
> Another option could possibly be to get a more recent CMake version on RHEL 7 through EPEL (or even APEL). I'll defer the feasibility of the latter to @akva2.

Please note that even if such an rpm exists, it will need to be installed on all nodes at our end. I really prefer reverting to at least 3.17 until we move over to Red Hat 8 (which hopefully is by summer).

**Comment by multitalentloes** [comment]
Im not a cmake connoisseur, but would this cmake file be valid if we revert the version back to 3.10, and then wrap the HIP code inside an if statement of this kind?

> if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.21")

**Comment by bska** [comment]
>> Another option could possibly be to get a more recent CMake version on RHEL 7 through EPEL (or even APEL). I'll defer the feasibility of the latter to @akva2.
>
> Please note that even if such an rpm exists, it will need to be installed on all nodes at our end

True, at least if "all nodes" refers to those machines which **build** the latest master version of the simulator.

> would this cmake file be valid if we revert the version back to 3.10, and then wrap the HIP code inside an if statement of this kind?
> ```cmake
> if(CMAKE_VERSION VERSION_GREATER_EQUAL "3.21")
>```

Yes, something like that.  I don't remember the exact syntax for the version check.

**Comment by multitalentloes** [comment]
Okay I created a very simple PR using this check, #5340
