### ISSUE TITLE
Experiencing parallel deadlocks on models

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#5359]
just a heads up:

I am haunted these days. Currently, I have simulations deadlocking where rank 0 wants to complain about: "Input vector must have full size (on rank 0)" and hangs in an AllReduce at /opm-models/opm/models/utils/simulator.hh:175, while other are still (or already?) trying to serialize and wait in a broadcast at /opm-simulators/opm/simulators/utils/MPISerializer.hpp:62

**Comment by blattms** [comment]
The problems are here:
- [opm-models/opm/models/utils/simulator.hh:239](https://github.com/OPM/opm-models/blob/d9bf4ad4d3e39829513b8b24c66a2774b47f17a1/opm/models/utils/simulator.hh#L239) ` { problem_->finishInit(); }`
- calling [opm-simulators/opm/simulators/flow/FlowProblem.hpp:450](https://github.com/OPM/opm-simulators/blob/2ea6cea8950b67d8c4cb48867a74b887ad323b1d/opm/simulators/flow/FlowProblem.hpp#L450) `eclWriter_->writeInit(equilGridToGrid);`

One process already left this call while the other is trying to communicate...

**Comment by bska** [comment]
For what it's worth, PR OPM/opm-common#4011, and especially commit OPM/opm-common@58c67c0fc1 was in response to a similar symptom.  The root cause may or may not be the same, but it is (potentially) a bit telling that the message

> Input vector must have full size...

is (likely) generated in [`EclipseGrid::compressedVector<>()`](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp#L145-L146).

**Comment by blattms** [comment]
Thanks.
Arrgh and of course it is my MULTPV PR.

**Comment by blattms** [comment]
I think the problem is that MULTPV used in writeInit in a parallel run is of the size of the local grid, but we actually expect the size of the global grid (EclipseGrid).

**Comment by bska** [comment]
> MULTPV used in writeInit in a parallel run is of the size of the local grid,

Maybe.  [`writeInit()`](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/output/eclipse/WriteInit.cpp#L678) [supports](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/output/eclipse/WriteInit.cpp#L483) two sizes

1. [Number of active cells in global grid](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp#L141-L143)
2. [Size equal to number of global cells in global grid](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/input/eclipse/EclipseState/Grid/EclipseGrid.hpp#L148-L156)

in which the "global grid" is the [object](https://github.com/OPM/opm-common/blob/1814c316cb5e526a04e9cc29406815c45da66f29/opm/output/eclipse/EclipseIO.cpp#L179-L180) used to [construct the `EclipseIO` instance](https://github.com/OPM/opm-simulators/blob/2ea6cea8950b67d8c4cb48867a74b887ad323b1d/opm/simulators/flow/EclGenericWriter_impl.hpp#L218-L221).  Anything else will be rejected.
