### ISSUE TITLE
Issue with running CPR when the well contributions are added to the matrix

### ISSUE THREAD

**Issue by razvnane** [OPM/opm-simulators#5413]
Running flow with the options `--matrix-add-well-contributions=true --linear-solver=cpr` gives the following error:

`../opm/simulators/linalg/PreconditionerFactory_impl.hpp:660] Preconditioner type cprw is not registered in the factory. Available types are: DILU DuneILU GS ILU0 ILUn Jac ParOverILU0 SOR SSOR amg cpr cprt famg kamg`

At minimal the message is confusing if CPR should only work when the well contributions are not added to the matrix, otherwise this is a bug.

**Comment by atgeirr** [comment]
The message is correct, but not very helpful. The CPRW preconditioner indeed requires no well contributions in the matrix. The `cpr_trueimpes`, `cpr_quasiimpes` and `cpr_trueimpesanalytic` options can work with or without, but in general work a lot better with well contributions. The option `cpr` is currently an alias for `cprw` which may be a bad choice, maybe we should have no such alias at all, forcing the user to choose `cprw` or one of the three options above explicitly? Also keep in mind that we are in the process of making the CPRW method the default.

**Comment by atgeirr** [comment]
To further explain the error message: The above strings (`cpr_trueimpes` etc.) are option for the command line arguments. They are actually shortcuts the behind the curtain will get converted into a ParameterTree definition of the linear solver setup (by using `--linear-solver=mylinearsolverconfig.json` and a JSON file by that name you can directly control all aspects). This ParameterTree will have a preconditioner field, which is either `cpr`, `cprw` or a non-cpr preconditioner. The weight function indicated as true-impes, quasi-impes etc. is an independent choice. This explains why you do not see `cpr_trueimpes` etc. in the list of available types.

While that error message is precise, it is only user friendly if you are actually working at the expert level, inputing your own JSON file definition. I propose we add a higher-level interception of this situation.

**Comment by razvnane** [comment]
Thanks for your feedback, that makes very clear what the issue is. I will switch to using a JSON file input.
