### ISSUE TITLE
Plan to drop support for DUNE 2.7 (and 2.8)?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#5425]
All supported Ubuntu versions are now using DUNE 2.9 as well as Debian stable.
Is jenkins is still not on Debian stable? Then we have to upgrade it before doing the move.

**Comment by akva2** [comment]
yes updating jenkins is on my agenda but i hit some small troubles packaging up everything needed. i'll get back to my efforts soon, when they are done upgrading should be fairly straight forward.
