### ISSUE TITLE
What is the easiest way to get an array of cell results using the python wrappers?

### ISSUE THREAD

**Issue by flammmes** [OPM/opm-simulators#5484]
I can easily load a summary file and get the values of everything written in the deck.
For example
```python
from opm.io.ecl import ESmry
summary = ESmry('i.1050/SPE3CASE1R2.SMSPEC')
summary['FOPR'] 
```
This produces a 1d array of the variable with length equal to the reporting time steps.

What about obtaining the arrays that corresponds to specific cell results for all cells at all reporting timesteps, supposing that we use 
```
RPTRST
 'BASIC=2' 'ALLPROPS' /
```
in the deck, which means that at the end of each timestep, a restart point is created so the cell results should be accessible. In ResInsight we can right click the reservoir-> export property to file and we get them. 
However, I need to be able to load these properties (Dynamic or static) in a scripting way similar to the summary ones and get arrays of shape (`nx`,`ny`,`nz`,`t`) or even (`nx*ny*nz`,`t`) and reshape manually. This may be important when we try to perform closed loop reservoir management and certain cell values may be needed at restart points. Sure we can manually select cells to add in the summary file but this is not very efficient.

I know that we can load egrid and restart files using python wrappers like this
```python
from opm.io.ecl import EGrid
from opm.io.ecl import ERst
grid = EGrid('i.1050/SPE3CASE1R2.EGRID')
rst = ERst('i.1050/SPE3CASE1R2.UNRST')
```
but after that, how can we take the cell results?

I apologize if this has been answered before but I couldn't find any relevant recent posts or anything in the documentation.

**Comment by bska** [comment]
I don't think there's something built into the `ERst` class that will do exactly what you want, so you'll have to adapt what's there to get it.  The `ERst` class' subscript operator takes a string and a sequence number&ndash;i.e., a report step number&ndash;and returns the cell results for the named array at that report step.  You could probably write something along the lines of
```python
sg = [ rst['SGAS', step] for step in rst.report_steps ]
```
to load the gas saturation in all cells at all times.  Do note, however, that the dynamic properties are **typically** reported for active cells only.  If the active cells constitute a strict subset of the `Nx * Ny * Nz` Cartesian input cells you'll probably have to map those back to the Cartesian cells if you really want size `Nx * Ny * Nz` for each report step.

**Comment by flammmes** [comment]
Thank you very much for your answer. I guess it wouldn't be too hard to map them back. We can simply map the values of sg[i] to the positions of ones in the ACNTUM array, replacing the ones with the corresponding values from sg[i].
Something along the lines of
```
sparse_sg_template = ACTNUM_array

for i in  rst.report_steps:
      sparse_sg[i] = sparse_sg_template
      sg_index = 0
      for j in range(len(sparse_sg_template)):
            if sparse_sg_template == 1:
                  sparse_sg[i][j] == sg[i][sg_index]
                  sg_index +=1
```
which should give the correct map.

Fyi the method you wrote returns only the dynamic properties and not the static ones which shouldn't be a problem since we can derive them from the deck.

**Comment by bska** [comment]
For what it's worth, the static properties such as pore-volume, saturation and PVT region indices, saturation function end-points, transmissibilities &c, are all stored in the `.INIT` file rather than the `.EGRID` or `.UNRST` files.  Moreover, the `PORV` array always has full size (i.e., `Nx * Ny * Nz`) even if the number of active cells is less than this, and `PORV == 0` in inactive cells.  Therefore you could do something along the lines of
```python
import numpy as np
from opm.io.ecl import EclFile, ERst
init = EclFile('i.1050/SPE3CASE1R2.INIT')
rst = ERst('i.1050/SPE3CASE1R2.UNRST')
porv = init['PORV']
active = porv > 0
sgas = []
for step in rst.report_steps:
    sg = np.array(porv.size)
    sg[active] = rst['SGAS', step]
    sgas.append(sg)
```
Fair warning: It's been a while since I used NumPy, so you may have to adapt this a bit, but this should give you an idea of how to proceed.

**Comment by flammmes** [comment]
That's even better. Thank you once more, this has all been very helpful.
