### ISSUE TITLE
CPR implementation for enhanced models

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-simulators#549]
The current CPR implementation fails with the solvent and polymer models, since it assumes that the number of conserved quantities to solve for is 3. A restructuring similar to the one made by @dr-robertk for the interleaved/block structured solver is necessary.

**Comment by dr-robertk** [comment]
I suggest to restructure the CPR such that we use a interleaved version for the whole system and the elliptic only for the pressure components.

**Comment by atgeirr** [comment]
Yes, that could yield an improvement over both existing implementations.

**Comment by andlaus** [comment]
I'm not sure if CPR is even working for the base model at the moment. does anyone know more?

**Comment by totto82** [comment]
It works. But it is not faster. This is still an issue, but not very important.

**Comment by atgeirr** [comment]
Actually I think it does not work very well at the moment. I get lots of these:
```
Error: [/Users/atgeirr/opm-build-release/opm-simulators/opm/autodiff/CPRPreconditioner.hpp:556] CPRPreconditioner failed to solve elliptic subsystem.
```
and Norne fails to run through because of this. So it definitely needs resurrection. Also, it is only available for flow_legacy I think. For flow_ebos a new approach as outlined long ago by @dr-robertk above should be implemented.

**Comment by blattms** [comment]
Closing as I doubt that it applies to the new CPR implementation.
