### ISSUE TITLE
Eigen not found if autoinstalled Eigen is used

### ISSUE THREAD

**Issue by atgeirr** [OPM/opm-simulators#550]
First reported in the context of opm-polymer by @dr-robertk, if Eigen is not found by opm-autodiff, it will auto-install (clone) a copy and use it, but that will not be visible to downstream modules depending on opm-autodiff.

One solution would be to remove the auto-install, instead requiring that Eigen is found during setup (as other prerequisites are), this may be the best solution if the prerequisite is easy to satisfy (it was not at the time the auto-install feature was created, packages for Ubuntu were only for a too-old version I think).

**Comment by andlaus** [comment]
do we still have modules that are downstream of opm-simulators and that use Eigen?

**Comment by atgeirr** [comment]
Potentially, yes. So this issue will remain a thorn until we no longer use Eigen.

**Comment by blattms** [comment]
Resolved since Eigen is not used anymore.
