### ISSUE TITLE
Help with obtaining results in text format

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-simulators#563]
Dear all,

The recent changes are quite good, congratulations.  It's really exciting to see the advance of the simulator and its integration with ResInsight.

I would like to ask one thing though.  I need to obtain the results in a text editor format such as .txt.  In the previous versions a vector result file was generated.  Is there a way to generate the output data for a specific well in a text format? much like the .RSM file generated by Eclipse when you used the EXCEL keyword on the SUMMARY section?

We are using the software for a bachelor thesis and would like to get the results in a format we could manipulate the final results for we are calculating economic values with production rates and totals.

I appreciate any help that could be provided.

Thanks.
David.

**Comment by alfbr** [comment]
Hi David, I am a bit unsure about the state of text based output, but you can extract well curves without it. Go to the opm-utilities repository and you will find summaryplot for plotting the curves. If you have a look at that code, it is basically a python wrapper to ert for extracting the well curves from summary files. Merry Christmas! Alf

**Comment by dlmorenob** [comment]
Alf,

Thank you.  I saw the script.  I will generate the text files, thanks.  On
the other hand, I would like to ask, have you guys removed the support for
the generation of vtk output files?  Is there a keyword for that?

Merry Christmas and thanks,

David

2015-12-24 5:06 GMT-05:00 Alf Birger Rustad <notifications@github.com>:

> Hi David, I am a bit unsure about the state of text based output, but you
> can extract well curves without it. Go to the opm-utilities repository and
> you will find summaryplot for plotting the curves. If you have a look at
> that code, it is basically a python wrapper to ert for extracting the well
> curves from summary files. Merry Christmas! Alf
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OPM/opm-autodiff/issues/563#issuecomment-167081067>.
>



-- 

*David Leonardo Moreno Bedoya*

**Comment by alfbr** [comment]
As I said, I am unsure about the state. Vtk may still be possible from the autodiff simulators, but it is not tested to the same level. Paraview is unfortunately a poor solution for reservoir simulation, and the industry is all supporting the Eclipse formats. We would love to have the resources to provide and support open file format standards, but we are certainly not there now. As it is now, users are better off using the Eclipse file formats.

**Comment by atgeirr** [comment]
The output is still available, it just is not turned on by default. Relevant options (on command line or in .param file). Some relevant options:
   - `output_vtk=true` turn on vtk output
   - `output_matlab=true` turn on plaintext output
   - `output_dir=<dirname>` root locations for output file

You will then find the vtk output in the `vtk_files` subdir and the plaintext files in various subdirs (`saturation` etc.).

**Comment by dlmorenob** [comment]
Thank you.


2015-12-27 16:44 GMT-05:00 Atgeirr Flø Rasmussen <notifications@github.com>:

> The output is still available, it just is not turned on by default.
> Relevant options (on command line or in .param file). Some relevant options:
>
>    - output_vtk=true turn on vtk output
>    - output_matlab=true turn on plaintext output
>    - output_dir=<dirname> root locations for output file
>
> You will then find the vtk output in the vtk_files subdir and the
> plaintext files in various subdirs (saturation etc.).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OPM/opm-autodiff/issues/563#issuecomment-167443439>.
>



-- 

*David Leonardo Moreno Bedoya*

**Comment by andlaus** [comment]
Besides the possibilities mentioned above, you can also convert the results into text format using the shell the tools shipped by the ERT libraries (no python required):

- compile ERT with the applications:
```sh
cd $YOUR_ERT_BUILD_DIRECTORY
cmake -DBUILD_APPLICATIONS=ON
make
make install
```
- after this, there are several binaries in the ERT install directory. the ones which is propbably most useful for you is `summary.x` which you can use to inspect the ECL summary files. the list of quantities in the summary files can be extracted via 
```sh
$ERT_INSTALL_PATH/bin/summary.x $YOUR_CASE
```
and the data for one such quantity can be extracted using
```sh
$ERT_INSTALL_PATH/bin/summary.x $YOUR_CASE $QUANTITY
```
- if you want a quick way to visualize the curve, you can use `gnuplot`:
```sh
$ERT_INSTALL_PATH/bin/summary.x $YOUR_CASE $QUANTITY > foo.csv
gnuplot
[...]
plot "foo.csv" using 1:3 w lp
```
- ERT also ships several other binaries which work in an analogous fashion that can be used to inspect restart files, e.g. `kw_list.x` and `kw_extract.x`

I hope this helps.

**Comment by dlmorenob** [comment]
Thank you very much, I will try and let you know. Thanks again. Btw, I used to work with the old Fortran code of the EnKF and I know Ert is the extended c version of it (I think?!).  Is there a working example that will show me how to configure the software for generic problems?

**Comment by joakim-hove** [comment]
> Is there a working example that will show me how to configure the software for generic problems?

For questions about ert as such - head over to: https://github.com/Ensembles/ert

**Comment by atgeirr** [comment]
This seems to be resolved, closing.
