### ISSUE TITLE
Problem with two-phase systems

### ISSUE THREAD

**Issue by Ruslan1541** [OPM/opm-simulators#5666]
Hello there!

I have a question about the running of this case: https://github.com/OPM/opm-tests/blob/master/spe1/SPE1CASE2_2P.DATA
When, I try to run this case, I face this problem: 
```
================ Starting main simulation loop ===============



---------------    Simulation step number 0    ---------------
      Current time (days)     0
      Current stepsize (days) 31
      Total time (days)       3650



Report step  0/120 at day 0/3650, date = 01-Jan-2015
Using Newton nonlinear solver.

Starting time step 0, stepsize 1 days, at day 0/31, date = 01-Jan-2015 
```
Can anybody know what the reason for this is?

**Comment by atgeirr** [comment]
What you posted looks like normal output. Does the output stop there, or did you just post part of it? Also, what is your version of OPM Flow?

**Comment by Ruslan1541** [comment]
The output of flow stops there, yeah
The version: flow 2024.10-pre

**Comment by Ruslan1541** [comment]
I want to say that I missed with the link to the test case, so I refreshed it and put a correct link.
Besides, I want to note that this problem occurred during the running of flow in Python. However, when I run this case in command line through keyword "flow", everything is correct and fine. So, I want to understand what a possible problem with the running of flow in python?

**Comment by atgeirr** [comment]
> So, I want to understand what a possible problem with the running of flow in python?

For this, I must yield to other people more knowledgeable about the python functionality.

**Comment by blattms** [comment]
Would you be willing to share the python script? maybe @hakonhagland has some clue.

**Comment by hakonhagland** [comment]
Hi @Ruslan1541. Unfortunately, only the blackoil simulator is currently implemented for the Python bindings, see: https://github.com/OPM/opm-simulators/issues/5105. Contributions are welcome. Further, we should consider providing a better error message when running unsupported cases with flow through the Python bindings and the [documentation](https://opm.github.io/opm-python-documentation/master/index.html) could mention that only blackoil simulation is implemented yet? Then, a user should be able to find the Python documentation easily. I could not find any links to the documentation [here](https://github.com/OPM/opm-simulators/blob/master/README.md) at least. What do you think @lisajulia, is it easy to find the documentation currently (assuming you do not know the [direct link](https://opm.github.io/opm-python-documentation/master/index.html))?

**Comment by atgeirr** [comment]
> I could not find any links to the documentation [here](https://github.com/OPM/opm-simulators/blob/master/README.md) at least.

There is a link on the OPM website: https://opm-project.org/?page_id=1454

However it is under the heading "OPM PYACTION AND UDQ/ACTIONX DOCUMENTATION", so you have to understand the connection. Maybe we should change the heading to "Python, PYACTION, UDQ and ACTIONX"?

**Comment by Ruslan1541** [comment]
@hakonhagland 
Thank you for your explanations!
