### ISSUE TITLE
Adding a CASENAME.PARAM when running flow in Python

### ISSUE THREAD

**Issue by Ruslan1541** [OPM/opm-simulators#5759]
Hello there!

If I run flow in Python, is it possible to add a CASENAME.PARAM file somewhere to change the simulation parameters?

**Comment by akva2** [comment]
This is not currently possible. I have added such support in https://github.com/OPM/opm-simulators/pull/5760

The constructor of the python simulator then takes an 'args' parameter which is a list of standard command line parameters. To use a parameter file you'd do something ala
```python
sim = BlackOilSimulator(filename='SPE1CASE1.DATA', args=['--parameter-file=CASENAME.PARAM'])
```
