### ISSUE TITLE
Jenkins placeholder

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#669]
@akva2: How can i trigger a build of master in this based on pr's in upstream modules? In particular I would like something like:

` jenkins build master opm-grid=216 please`

But I have no PR in opm-simulators to hang this on?

**Comment by akva2** [comment]
downstream module build triggers are not in place. it's not hard to do as such but would take a little more scripting (and time..).

**Comment by joakim-hove** [comment]
> downstream module build triggers are not in place

OK - I guess it is the man with $$ (@alfbr - do you hear me!) who calls the shots, but it would be a very convenient feature - specially when working 'way up stream'.

**Comment by akva2** [comment]
sigh. i had a left hand to work on this but somebody has broken opm-output. halting work until that is fixed.

**Comment by atgeirr** [comment]
> somebody has broken opm-output

I also experienced that today, turned out new ERT was needed.

**Comment by akva2** [comment]
nope, running with  master of ert. it tries to include a non-existent file https://github.com/OPM/opm-output/blob/master/opm/output/eclipse/Summary.cpp#L29

**Comment by akva2** [comment]
yarr, my bad. got lost in all the branches and origins. used master from my repo not upstream. sorry for the noise.

**Comment by akva2** [comment]
pull requests enabling downstream build triggers have been sent and i have started test builds in all modules.

**Comment by atgeirr** [comment]
This has been sufficiently covered by downstream Jenkins builds. Closing.
