### ISSUE TITLE
Simulator/output interaction - respect requested output directory

### ISSUE THREAD

**Issue by jokva** [OPM/opm-simulators#677]
Ok, so we've done some digging and discovered a few things from the patch fest yesterday.

https://github.com/OPM/opm-output/commit/81c0a795c214934fee4bcd3624a3a185310c34de#diff-671ffab73ee054de00ff6dd35ae144baL1488 This is the line that sparked the tests in opm-simulators breaking. The corresponding change to opm-simulator is here: https://github.com/OPM/opm-simulators/commit/58851e8c0291886188a6ee732e2b44e7c944f0a0#diff-ec72cb02ca6cd531a7da9977a448a982R395

The short summary is that where previously opm-output would largely ignore the output_dir_ default set by flow and instead set `.` unless specified by parameter group, it now inherits the directory from flow. This patch https://github.com/OPM/opm-simulators/commit/96d073a13e141485267ed08924a50990fc385883 fixes the immediate issue by using the same default directory for both (essentially matching how the tests used to behave), but we figured we need some discussion on how this is actually supposed to be have.

Should the default output dir from flow still be ./output? If so, the tests must be modified to actually take this assumption into account **or** use explicit path arguments.

**Comment by atgeirr** [comment]
The behaviour we used to have is that eclipse-type output would default to the current directory `.` while all other output (vtk, matlab, parameters used etc.) defaults to `output`. I did not very much like this, but accepted it as a compromise between conflicting needs:
 - those used to eclipse would expect their output to be in the same directory as the data file (typically the current directory)
 - all others would like output to not mess up their case files and be neatly placed in a separate dir

As it was, if the user actively chose to override this by specifying `output_dir=output_norne_testing_some_branch_for_example` then *all* output (including the eclipse output) would go to that directory, maintaining some sanity in terms of organizing the files (especially across multiple runs).

The visible clue to this behaviour (that confused some) would be that if you did not specify output_dir, the parameter system would report:
```
output_dir not found. Using default value 'output'.
```
at one point and then later
```
output_dir not found. Using default value '.'.
```
during the setup.

I still think this behaviour is quite reasonable, but now that we do not output vtk or matlab files by default the situation may have changed a bit.

**Comment by blattms** [comment]
Not sure whether that helps, but I just did a run with output_dir set and the following files ended up in it:
```
CASE.EGRID
CASE.INIT
CASE.PRT
CASE.RFT
CASE.SMSPEC
CASE.UNRST
CASE.UNSMRY
simulation.param
step_timing.txt
walltime.txt
```

**Comment by alfbr** [comment]
You are running the latest code, and you do not have the .CASE.DEBUG file there?

**Comment by atgeirr** [comment]
This is behaving correctly now, and has been for some time. Closing.
