### ISSUE TITLE
without setting output_dir, flow creates output directory failed.

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-simulators#682]
I run ``flow`` and ``flow_polymer`` failed if I don't specify the output_dir throw command line.
This error I never met before.
```
Program threw an exception: [opm/opm-simulators/opm/autodiff/FlowMain.hpp:335] Creating directories failed: "."
```

**Comment by atgeirr** [comment]
I do not get this error, possibly create_directories() behaves differently between platforms. Will try to make a small fix anyway.

**Comment by qilicun** [comment]
I checked the code in ``FlowMain.hpp``, originally ``output_dir`` is set to ``output`` by default, now it's ``.``, probably this is the reason? By the way, I update boost to 1.61.
