### ISSUE TITLE
run of flow simulator fails with error

### ISSUE THREAD

**Issue by sayfull** [OPM/opm-simulators#689]
Program threw an exception: vector::_M_range_check
[model.tar.gz](https://github.com/OPM/opm-simulators/files/270503/model.tar.gz)

**Comment by atgeirr** [comment]
I took a brief look and identified three things that prevent me from running it:
 - In WELSPECS, defaulting the group for each well does not work (I think it is discouraged also for Eclipse), change to 'G1' or some other dummy group name.
 - There is something wrong with RPTRST, I get a problem reading the BASIC=3 part, I do not know why (commented it out to get past it).
 - In general, Flow does not support two-phase runs completely at the moment, in particular multiple EQUIL regions does not work in two-phase runs. While this probably will be fixed eventually, we are not working on it right now. One workaround is to add a dummy third phase (along with simple dummy SGOF and PVDG tables).

**Comment by sayfull** [comment]
Thanks! But after correcting the model, I've got a bug (see files 1 and 2 in archive for stdout and stderr).
[model2.tar.gz](https://github.com/OPM/opm-simulators/files/271900/model2.tar.gz)
And why callstack contains "UnstructuredGrid" methods?

**Comment by pgdr** [comment]
Confirming that this segfaults at my desk as well.

    Iter   MB(Wat)    MB(Oil)    MB(Gas)     CNV(W)     CNV(O)     CNV(G)   W-FLUX(W)  W-FLUX(O)  W-FLUX(G)
       0  6.735e-09  4.612e-07  0.000e+00  8.359e-07  4.502e-12  0.000e+00  2.011e-07  1.032e-05  0.000e+00
    Segmentation fault (core dumped)

There are two warnings:

    -- Warning: In saturation table SATNUM = 1, Sogcr + Sgcr + Swco should be less than 1.
    -- Warning: In saturation table SATNUM = 2, Sogcr + Sgcr + Swco should be less than 1.

**Comment by sayfull** [comment]
Will You work under this bug? I have used dummy gas props, because model is 2 phase actually.

**Comment by atgeirr** [comment]
I do not have time to address this bug now, sorry! If you can fix it we would be very happy to include the contribution.

**Comment by andlaus** [comment]
I'm closing this now because it seems stale, re-open if it is still relevant.
