### ISSUE TITLE
NNCs might be represented twice.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#693]
@alfbr just reported that the MPI version aborts as there are NNCs represented in for Norne, which was not the case before merging #680.

I might be mistaking but to me it seems that connections between cells that are not neighbors by their cartesian index but might still share a facet in the grid representation of UG or CpGrid get added to nnc_. Unfortunately, this means that in the (non-)linear there might be one connection because of the face and another one because
of the entry in nnc_. To the very least this increases the runtime, see http://linuxbenchmarking.com/?open-porous-media-git for Norne on May 19. Depending on how the contributions are calculated it may also influence the results.

Or am I missing something?

**Comment by pgdr** [comment]
I'll take a look at it!

**Comment by atgeirr** [comment]
I think you may be right, investigating.

**Comment by atgeirr** [comment]
There is definitely a bug here. The geo_ object now stores all nncs of both "type A" and "type B", instead of just "type A" ("type B" are non-cartesian connections that are already represented in the grid, such as across faults). While this is correct for the output facilities, it is not correct for the simulator. A proper fix should probably separate these inside the DerivedGeology class.

I tried the following workaround: in BlackoilModelBase_impl.hpp line 173, replace geo.nnc() with eclState->getInputNNC(). It compiles, but does not run properly, need to further investigate.

**Comment by blattms** [comment]
I guess `DerivedGeology::exportNncStructure` writes them to `DerivedGeology::nnc_` even if they are already in the grid. Unfortunately, `HelperOps` takes them into account even if they are represented by the grid.

**Comment by pgdr** [comment]
There are three options that will fix this;

* Make NNC a map from _(a,b)_ to `trans`
* Test in `NNC.addNNC` whether an NNC already exists, if so, overwrite, ignore, add, min, max, what?
* test in `GeoProps.exportNncStructure` whether the NNC already exists, and act accordingly.

In these cases, we should consider whether NNCs are undirected (if so, have an NNC always with `cell1<cell2`) or whether a directed NNC makes more sense.

Ps., just saw atgeirrs comment.  We considered using `eclState->getInputNNC()` but for some reason decided against it.

**Comment by atgeirr** [comment]
The three options proposed will not fix this: the problem is not that nncs are repeated *in the nnc object itself* but that the when constructing the div operator etc. we'll consider the same connection both from the grid and from the nnc object.

**Comment by atgeirr** [comment]
The threshold pressures seems to be another place where this becomes conflicted. A simpler workaround seems to be the following: comment out line 203 of GeoProps.hpp (the call to exportNncStructure). I guess output is probably wrong with this workaround, but the simulator seems to run.

Can you try that @blattms? I'll propose a fix meanwhile.

**Comment by pgdr** [comment]
If I remember correctly, this was done purely to enable output writing of NNC.  We could add an additional `outputNnc` to `GeoProps` and export to that NNC object.  Then we use that for writing.

**Comment by atgeirr** [comment]
Fix proposed in #694. Please test!

**Comment by blattms** [comment]
Thanks for merging and fixing!
