### ISSUE TITLE
Wrong ordering of `SimulationDataContainer::saturation()` assumed in euclidianNormSquared

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#713]
According to @atgeirr:  All saturations of the first cell before the saturations of the next one
But [euclidianNormSquared](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1127-L1152) assumes the opposite (all staturations of the first phase come before the next one).
This will lead to wrong results [here](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1653), and [here](https://github.com/OPM/opm-simulators/blob/e861c495b8778fcf3b1e002c0a7eca2680c1c748/opm/autodiff/BlackoilModelBase_impl.hpp#L1659).

**Comment by atgeirr** [comment]
I agree, this is a bug. May partially explain weird adaptive timesteps some while back (before we changed the default mechanism).
