### ISSUE TITLE
Restarting a simulation does not work in parallel

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#715]
I envisioned to use the restart functionality for debugging my parallel runs. (I wanted to do a sequential run and then use these results to start a parallel run at an interesting point of time).

Unfortunately, this cannot work as `OPM::init_from_restart_file` assumes that the data found in the restart file has the exact size and indexing as the data members in the current simulation state. But that does not hold for parallel runs.

**Comment by blattms** [comment]
I would propose the same fix here as in #765:
Move the code in [SimulatorBase_impl.hpp lines 89-93](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/SimulatorBase_impl.hpp#L89-L93) to FlowMain.hpp between the calls to [`setupState()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/FlowMain.hpp#L147) and [`distributeData()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/FlowMain.hpp#L148).
Then `SimulatorBase::run()` will have the correct data from the beginning.

**Comment by alfbr** [comment]
Sounds good to me, please provide a PR unless anybody suggests a better approach.

**Comment by andlaus** [comment]
what's the status here?

**Comment by totto82** [comment]
This was fixed some time ago. Please reopen if it is still an issue.
