### ISSUE TITLE
Add a small test case without any wells.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#743]
There is one in opm-data. Not sure whether one can use that.

**Comment by andlaus** [comment]
does anybody want to do anything here in the near future? if no, this issue should be closed IMO.

**Comment by atgeirr** [comment]
> does anybody want to do anything here in the near future? if no, this issue should be closed IMO.

I think it should stay open, as it would be a very useful thing to have for debugging (or rather to avoid it...) even if no-one is currently about to do it.

**Comment by GitPaean** [comment]
This issue is closed with https://github.com/OPM/opm-data/pull/305 .
