### ISSUE TITLE
something from the ubuntu 16.04

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#757]
I just upgraded the system to ubuntu 16.04 by a fresh re-installation. 

I saw the following error, while I am not sure whether it is related to the wrong version of Eigen installed. I installed `libeigen3-dev` from the system. 

```
 61 /home/paean/devel/OPM/debug/opm-simulators/opm/autodiff/fastSparseOperations.hpp:198:51: error: cannot convert ‘const StorageIndex* {aka const int*}’ to ‘const Index* {aka const long int*}’ in initialization
 62          const Index* rhsOuter = rhs.outerIndexPtr();
 63                                                    ^
 64 /home/paean/devel/OPM/debug/opm-simulators/opm/autodiff/fastSparseOperations.hpp:199:51: error: cannot convert ‘const StorageIndex* {aka const int*}’ to ‘const Index* {aka const long int*}’ in initialization
 65          const Index* lhsOuter = lhs.outerIndexPtr();
 66                                                    ^
 67 /home/paean/devel/OPM/debug/opm-simulators/opm/autodiff/fastSparseOperations.hpp:208:51: error: cannot convert ‘const StorageIndex* {aka const int*}’ to ‘const Index* {aka const long int*}’ in initialization
 68          const Index* rhsInner = rhs.innerIndexPtr();
 69                                                    ^
 70 /home/paean/devel/OPM/debug/opm-simulators/opm/autodiff/fastSparseOperations.hpp:209:51: error: cannot convert ‘const StorageIndex* {aka const int*}’ to ‘const Index* {aka const long int*}’ in initialization
 71          const Index* lhsInner = lhs.innerIndexPtr();
```

**Comment by GitPaean** [comment]
I deleted the `libeigen3-dev` and opm will clone the one from `https://github.com/OPM/eigen3`. The latter one works pretty well. Did we did some change?

**Comment by bska** [comment]
> I deleted the libeigen3-dev and opm will clone the one from https://github.com/OPM/eigen3. The latter one works pretty well. Did we did some change

No, it's just that Someone decided to import a development version of Eigen (v3.3) into a long-term support version of Ubuntu.  As of right now the Eigen package that comes with the latest Ubuntu LTS is unusable with OPM and it is not OPM's fault.  See the discussion in #672, and in particular @akva2's [comment](https://github.com/OPM/opm-simulators/pull/672#issuecomment-215854679)

**Comment by GitPaean** [comment]
Yes. I realized it is not OPM's fault, while I am not clear about what happens to the `libeigen3` in the new ubuntu LTS.  Thanks for the information.
