### ISSUE TITLE
OutputWriter::writeInit cannot work correctly in parallel.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#765]
`SimulatorBase::run` starts of by writing the init file with the output writer, see [here](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/SimulatorBase_impl.hpp#L116). The eclipse writer in [BlackoilOutputWriter::writeInit](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/SimulatorFullyImplicitBlackoilOutput.cpp#L253) assumes that both the NNC and the vector of properties returned by the [`simProps()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/GeoProps.hpp#L242-L284) function contains correct information of the whole domain.  Unfortunately, as of now the vector with the properties will have the correct size (global size), but all  cells not represented on the current process will have transmissibility zero set for all global cells not represented, unconditionally. This is due to the `grid_` only representing the only local excerpt of the global grid. In addition each process will write to the same file which might cause additional problems.
Assuming that this information is only written once at the very beginning of a simulation, the easiest fix would be to move the writing into FlowMain.hpp before the call to [`distributeData()`](https://github.com/OPM/opm-simulators/blob/b387061b816d444514f0fceb90652ed9157e9ee8/opm/autodiff/FlowMain.hpp#L148). Can anyone confirm this assumption?

**Comment by jokva** [comment]
The `init` is just static data written before the simulation starts, so that should be fine.
