### ISSUE TITLE
Free gas rate, solution gas rate, voidage, WGPRF and friends

### ISSUE THREAD

**Issue by jokva** [OPM/opm-simulators#767]
Hi,

I'm beginning work on the second tier of Summary keyword support and came across `WGPRF`, `WGPRS`, `WOPRF`, in addition to `WVIR` and others. Quick glossary check shows:
- WGPRF - Free Gas Rate
- WGPRS - Solution Gas Rate
- WOPRF - Free oil rate
- WVIR - ~~Water~~ Well voidage rate

But I have no idea what either of these mean nor what makes them different from the rates supplied to opm-output by the simulator today. Double ignorance is better than no ignorance, as my mum used to say.

So I hoped someone could help me shed some light on this, and maybe point me to if/how we can compute these values based on what the simulator has at each and every time step. Can I derive this from the "regular" rates easily? Do I need to extend the data exchange?

**Comment by pgdr** [comment]
A minor comment; I think `WVIR` is short for _well_ voidage injection rate, and not Water.  Water is `WWVIR`.

**Comment by jokva** [comment]
Absolutely true.

**Comment by totto82** [comment]
My guess is that 
Free Gas Rate is the amount of gas in the gas phase at Reservoir condition.
Solution Gas Rate is the amount of gas in the oil phase at Reservoir condition. 
so WGPR = WGPRF + WGPRS 
Then Free oil rate is the amount of oil in the oil phase at Reservoir condition. 
It is possible to calculate this rates from the current data. 
Check for instance code 
https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/WellDensitySegmented.cpp#L112  
for calculation of rs/rv values. You will need the maximum rs and rv values.  fluid_.rsSat(pressure, ...)  Then:
WGPR = WGPRF + WOPRF * rs
WOPR = WOPRF + WGPRF * rv
You will need to solve this system of equations to get WOPRF and WGPRF
and then you can calculate WGPRS = WOPRF * rs etc. easily.

**Comment by andlaus** [comment]
this question seems to have been anwered.
