### ISSUE TITLE
Parallel Output relies on order of an unordered_map.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#772]
I experienced serious differences in the output of data of serial and parallel runs. It turns out that this even occurs for the initial data.
It turns out that when gathering data on one process the code in `PackUnPackSimulationDataContainer` holds a `state`, and `local_state` object of Type `SimulationDataContainer` and assumes that the keys are traversed in the same order when iterating over the `cellData()` members of both object. Apparently, this assumption does not hold and the `GASOILRATIO` and `SURFACEVOL` data get mixed up.

**Comment by blattms** [comment]
The easiest fix would be to replace the `unordered_map` with `map` in `SimulationDataContainer`.
Is there a compelling reason to use unordered_map here?

**Comment by blattms** [comment]
Alternatively, we could also send the key together with the data. But then we need to impose a limit on the length of the string used for the keys.

**Comment by blattms** [comment]
Just came up with an even better alternative:
The order of the iteration is governed by the hash, the comparison operator, and the insertion order. Our problem was that the latter was different. I guess we can assume that the insertion order for the local state is the same on each process. This means we can simply iterate over the key value pairs of the local state and use lookup with the key to insert the data in the correct spot of the global state.
I will cook up fix.

**Comment by dr-robertk** [comment]
May I raise the question again: why even unordered_map. An id should do the trick. That one would be very easy to communicate. The string comparison is really unnecessary at this point (SimDataCont).

**Comment by dr-robertk** [comment]
@blattms: The surface data exchange was not implemented, so why should it work?

**Comment by joakim-hove** [comment]
The `SimulationDataContainer` class was an attempt to make  a container class to hold and exchange data which should work well both for the simulator code and the output layer, that is also the reason it is located in opm-common.

To satisfy both output and simulators many compromises were, and probably the approach was  doomed from the outset due to the strong induced coupling. Anyway - the end result was that the output layer does not employ this datastructure at all, and constraints and requirements are only those induced by the simulator - not really my call but I guess moving it to simulators would be a natural step.

**Comment by dr-robertk** [comment]
Understandable. I think that is ok as long as the output knows what to output. opm-common still is a good place since this class is used by several other modules.

**Comment by jokva** [comment]
Is it?

**Comment by dr-robertk** [comment]
Unless we got rid of opm-core pretty much so ;-).

**Comment by blattms** [comment]
@dr-robertk Fact is that the output of RS was broken in parallel. That was because the sending side did send something else with stride 3 instead of 1. I guess the output of RS is supposed to work.

Concerning the matter map/unordered_map/id, etc. Please keep in mind that the current design is pretty flexible. You can simply register new cell data and it will get gathered automatically. I could imagine that it even gets written to file automatically, but I have not checked yet. Anyway, if it would be a wonderful way of outputting additional debug data (process id, etc.) and visualize it with ResInsight.

**Comment by blattms** [comment]
@GitPaean just found out the issue is apparent even for `WBHP WGPR WOPR WWPR` and my PR #773 does fix some of them but not all. It might be that there is really *NO* guarantee for unordered_map at all. In this case we either have to send the keys too or use a map. As I doubt that the performance difference for the lookup is critical I would prefer the latter. Or am I missing something @joakim-hove @jokva?

**Comment by jokva** [comment]
Well, output doesn't care about parallel in the sense that it assumes its caller will manager synchronisation and ordering. output is really a glorified key-value dumper.

**Comment by blattms** [comment]
@jokva That does not answer my question. Is there a reasonable reason against using a map in SimulationDataContainer?

I am pretty sure that the change unordered_map -> map is far less effort for me than sending the key for each entry and every time something is written. We should try to keep each others life simple.

**Comment by jokva** [comment]
SimulationDataContainer (really rolls off the tongue, doesn't it) is a key-value store. Ordering shouldn't matter honestly, but something may rely on it. That's a detail output doesn't deal with though, output never touches it.

**Comment by blattms** [comment]
I just realized that we are talking about well properties and these are not in the SimulationDataContainer, but in the WellState. So I guess this PR works as expected.

@jokva I know that this is not really writter anywhere, but due to the hashing the following should hold, right? If I have two unordered_maps, with the same values inserted in the same order then iterators should traverse the values in the same order.
On this assumption this PR is based.

**Comment by jokva** [comment]
They should, I suppose, but I don't think you have any guarantees.

**Comment by atgeirr** [comment]
I agree that switching to using std::map is the best solution. In the meantime, we can merge #773 as a workaround-that-helps-some-people. Do you want that @blattms?

I'll start work towards a PR for opm-common on the map.

**Comment by atgeirr** [comment]
@blattms can you test if OPM/opm-common#172 fixes any problems for you in the parallel case?

**Comment by atgeirr** [comment]
Reopened since we do not believe the linked PR is a complete solution.

**Comment by blattms** [comment]
@atgeirr Does this still need to be open?

**Comment by atgeirr** [comment]
I think this issue can be closed. If we have more issues with output in parallel they should not have anything to do with unordered map field ordering.
