### ISSUE TITLE
MINPV still not handled in DerivedGeology?

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-simulators#785]
while trying to wrap my head around the MINPV treatment, I just noticed the following:

- cells which exhibit a pore volume of less than MINPV, should get deactivated at grid creation time; at least that's what the documentation for `CpGrid::processEclipseFormat()` says.
- the modification of the NTG field in `GeoProps.hpp` loops over all active cells and modifies the NTG values if their pore volume is smaller than MINPV.

the problem is that the second part is a no-op if the grid creation works as advertised because there will not be any active cells which trigger the condition for point two. also note that, if it is a not no-op, the cells with exhibit a too small pore volume need to be deactivated to make it work somewhat correctly!?

 have I missed something?

**Comment by totto82** [comment]
Yes. 
The code checks the porv of the cell in the cell above in the Cartesian sense. Even though this cell does not exist in the cpGrid. It may exists in EclipseGrid with a pv.

**Comment by andlaus** [comment]
hm, you're right. this code is pretty convoluted and surprising.
