### ISSUE TITLE
MINPV treatment redux

### ISSUE THREAD

**Issue by andlaus** [OPM/opm-simulators#786]
Once again, I might have missed something, but I think I found another issue with the current MINPV treatment: it does not take ACTNUM into account. I suppose that if a cell is explicitly disabled in the deck, it should not influence the NTG value, but currently it (probably) does if its pore volume is non-zero and smaller than MINPV. (only cells which are are deactivated by virtue of their pore volume being too small should be influencing NTG, I guess.)

**Comment by totto82** [comment]
This time I think you are right. Usually porv=0 for all cells with ACTNUM=0. But this is not enforced. (The opposite is. i.e. if porv=0 then ACTNUM = 0). 

Do you have a case where this is a problem?

**Comment by andlaus** [comment]
> Do you have a case where this is a problem?

not really, I just wondered about it. Thanks for your fix and tests.
