### ISSUE TITLE
Regression test failure - possible cause found

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#793]
It looks like the ERT PR: https://github.com/Ensembles/ert/pull/1173 can be the cause of the  current regression test failure. We are looking into it and will provide a fix - or revert the PR quite fast.

**Comment by joakim-hove** [comment]
This PR: https://github.com/Ensembles/ert/pull/1184 in ert seems to solve the problem. I have rebuilt opm-simulatotors master, which is now green again. For various pull requests you can open/close them to force a rebuild.

The relative change in pore volumes calculated before and after https://github.com/Ensembles/ert/pull/1184 is on the order 10^{-16}. That such small changes can induce a relative change in well rates on the order of 10^{-5} might indicate some over sensitive floating point behavior - or the tolerances in the integration test might need to be adjusted/more fine grained.

**Comment by andlaus** [comment]
> That such small changes can induce a relative change in well rates on the order of 10^{-5} might indicate some over sensitive floating point behavior

Note that this has been a constant issue over the last few years, cf e.g.OPM/opm-material#144

**Comment by joakim-hove** [comment]
> Note that this has been a constant issue over the last few years, cf e.g.OPM/opm-material#144

Interesting; as is well known I am rabid proponent of testing, but we should be careful to not end up in a situation where flow - flow regression testing with strict tolerances becomes a straightjacket with floating point induced "randomness".
