### ISSUE TITLE
Assert failure in Eigen comma initializer

### ISSUE THREAD

**Issue by babrodtk** [OPM/opm-simulators#803]
With Eigen 3.2.9 (latest stable, eigen-eigen-dc6cfdf9bcec), the comma initializer object has an assertion failure (in debug) triggered by the following code:

``` diff
@@ -828,7 +828,12 @@ namespace detail {
         const V transi = subset(geo_.transmissibility(), ops_.internal_faces);
         const V trans_nnc = ops_.nnc_trans;
         V trans_all(transi.size() + trans_nnc.size());
-        trans_all << transi, trans_nnc;
+        if (trans_nnc.size() == 0) {
+            trans_all << transi;
+        }
+        else {
+            trans_all << transi, trans_nnc;
+        }
```

The assert is triggered in the destructor of `CommaInitializer`:

``` C++
inline ~CommaInitializer()
  {
    eigen_assert((m_row+m_currentBlockRows) == m_xpr.rows()
         && m_col == m_xpr.cols()
         && "Too few coefficients passed to comma initializer (operator<<)");
  }
```

Applying the workaround/quickfix suggested above solves the problem for me.

Compiler used: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609

**Comment by andlaus** [comment]
there should be a work-around for this in the current master? closing for now.

**Comment by atgeirr** [comment]
I am not sure if this patch actually made it into the code, did it @babrodtk?

**Comment by babrodtk** [comment]
I think it's still there in BlackoilModelBase_impl.hpp:851

Perhaps what you were thinking of @andlaus was the #1070 , which fixed compilation issues?

**Comment by atgeirr** [comment]
> I think it's still there in BlackoilModelBase_impl.hpp:851

Then I'll reopen this, as it should be fixed.

**Comment by andlaus** [comment]
> Perhaps what you were thinking of @andlaus was the #1070 , which fixed compilation issues?

yes. sorry for closing too early.

**Comment by blattms** [comment]
Eigen is not used anymore. Issue resolved.
