### ISSUE TITLE
the results of FIP maybe wrong in parallel. 

### ISSUE THREAD

**Issue by qilicun** [OPM/opm-simulators#807]
https://github.com/OPM/opm-simulators/pull/802 has been merged, but does not test in parallel, this issue is used to make a mark.

@blattms

**Comment by blattms** [comment]
Not sure what you mean with "does not test in parallel". Please clarify.

**Comment by blattms** [comment]
Are you perhaps talking about the [`FipTotals`](https://github.com/OPM/opm-simulators/blob/5f1bcb2a59fad727af1885916dff384171ef9bf4/opm/autodiff/SimulatorBase_impl.hpp##L685-L700)? These will be wrong as the sum over all pore volumes of the reservoir requires communication.

**Comment by qilicun** [comment]
@blattms 

>Not sure what you mean with "does not test in parallel".

I thought the FIP calculations might break the parallel runs.

> Please clarify. Are you perhaps talking about the FipTotals?

Yes, the results of sum over all pore volumes and for all different FIP regions could be wrong, there could be some ``mismatch`` as well, because I didn't test that in a parallel run.

**Comment by blattms** [comment]
I know where the sum over all pore volumes takes place but would you point to the computation for the specific fip regions, please. Are there global sums, too?

**Comment by qilicun** [comment]
>I know where the sum over all pore volumes takes place but would you point to the computation for the specific fip regions, please.

I not sure how the FIP regions will affect parallel runs, basically, FIP regions is assign a region number to each cell, and compute every region fluid-in-places numbers, which including pore volumes, pressure, hydrocarbon saturations.

>Are there global sums, too?

I think so.

**Comment by blattms** [comment]
Would you point me to the code computing the stuff for a region?

**Comment by qilicun** [comment]
Sure, you can check the codes starting with line.
https://github.com/OPM/opm-simulators/blob/master/opm/autodiff/BlackoilModelBase_impl.hpp#L2354

**Comment by atgeirr** [comment]
The PR revising the FIP stuff has been merged.
