### ISSUE TITLE
Sefault in computeFluidInPlace

### ISSUE THREAD

**Issue by ANerd** [OPM/opm-simulators#809]
In [`computeFluidInPlace`](https://github.com/OPM/opm-simulators/blob/983c7d995752587cc768304d03e288f98990b351/opm/autodiff/BlackoilModelBase_impl.hpp#L2302), a variable `s` is made with `ReservoirState::numPhases()` columns, but both oil and gas columns are accessed unconditionally [here](https://github.com/OPM/opm-simulators/blob/983c7d995752587cc768304d03e288f98990b351/opm/autodiff/BlackoilModelBase_impl.hpp#L2315).

For me this results in segfault in two-phase simulations.

**Comment by atgeirr** [comment]
A fix for this is being worked on in #808, but not yet complete.

**Comment by atgeirr** [comment]
@ANerd could you please check that the current master works for your case, since #808 has now been merged?

**Comment by ANerd** [comment]
No, this is still not working. `SolutionState state(np);` creates a list of only two saturations, but [here](https://github.com/OPM/opm-simulators/blob/4d2d004c43a30891b00e54fcc37525db3c57e6c9/opm/autodiff/BlackoilModelBase_impl.hpp#L2315) the gas saturation is accessed unconditionally.

**Comment by qilicun** [comment]
@ANerd 
Could you please check  if the PR https://github.com/OPM/opm-simulators/pull/813 solve this issue?

**Comment by atgeirr** [comment]
Merged #813.

**Comment by ANerd** [comment]
Now it's working, thanks!
