### ISSUE TITLE
writeTimeStep() is called twice at the end of each report step

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#823]
One is from `AdaptiveTimeStepping_impl.hpp`, line `231`, `outputWriter->writeTimeStep( substepTimer, state, well_state, substep);`, 

The other one is from `SimulatorBase_impl.hpp`, line `299`,  `output_writer_.writeTimeStep( timer, state, well_state );`. 

Basically, these two calls are outputting totally identical information. Is it something designed to be this way, or something happens to be this way, while no big harm?

Any opinion?

**Comment by blattms** [comment]
As output is slow (especially in parallel runs), we should prevent
this. Maybe with the following patch:

```
diff --git a/opm/core/simulator/AdaptiveTimeStepping_impl.hpp b/opm/core/simulator/AdaptiveTimeStepping_impl.hpp
index 56a11de..2b72ead 100644
--- a/opm/core/simulator/AdaptiveTimeStepping_impl.hpp
+++ b/opm/core/simulator/AdaptiveTimeStepping_impl.hpp
@@ -226,7 +226,7 @@ namespace Opm {
                 }
 
                 // write data if outputWriter was provided
-                if( outputWriter ) {
+                if( outputWriter && !substepTimer.done() ) {
                     bool substep = true;
                     const auto& physicalModel = solver.model();
                     outputWriter->writeTimeStep( substepTimer, state, well_state, physicalModel, substep);

```
