### ISSUE TITLE
The same well is specified both in WCONHIST and WCONINJH with the same period in schedule

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#826]
What will happen? Will the later specification just simply overwrite the previous one?

**Comment by bska** [comment]
I have no idea what currently happens (I haven't looked at the implementation in a long time), but this really **should** be undefined and we should terminate.  A single well should not be listed as being both an injector and a producer at the same time.

**Comment by GitPaean** [comment]
It exists in our model-2 file.

**Comment by bska** [comment]
> It exists in our model-2 file.

That does not mean that there is a defined behaviour.

**Comment by GitPaean** [comment]
I agree.

**Comment by andlaus** [comment]
@GitPaean: has this been resolved?

**Comment by GitPaean** [comment]
It is just something should not exist in a ECL deck while it happened unfortunately. I do not think it is an issue to me anymore.
