### ISSUE TITLE
Logging does not works as expected for parallel runs.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#830]
As the logger is not aware of parallelism (and most parts of the rest of the code are neither) there are several places where similar stuff is logged from multiple places. In most of the place we already output on the root process (rank 0), but there are still issue like:
- non-root processes create an additional *.PRT file in the current director when output_dir is set. If it is not set most probably multiple processes will still write to this file.
- some messages about events that only appear on non-root processes are never logged
- ZOLTAN logs to std::cout

**Comment by blattms** [comment]
See OPM/opm-output#86 for the first issue above.

**Comment by atgeirr** [comment]
> non-root processes create an additional *.PRT file in the current director when output_dir is set. If it is not set most probably multiple processes will still write to this file.

This we must fix!

> some messages about events that only appear on non-root processes are never logged

I think we must do some sort of reduction to have this work properly, agree?

> ZOLTAN logs to std::cout

That is a bit weird, but can be worked around: remember the rdbuf of cout (putting some ostringstream's rdbuf there instead) before calling Zoltan, then reset it after Zoltan returns.

**Comment by blattms** [comment]
> > some messages about events that only appear on non-root processes are never logged
>  I think we must do some sort of reduction to have this work properly, agree?
I think the only messages where this occurs is the switching of the well state. Additional synchronization points wherever this might happen (each nonlinear iteration) might be overkill. Maybe we can just leave it with multiple processes writing to one file until we can't stand the produced mess any longer. Switches should not take place to often.

**Comment by atgeirr** [comment]
> multiple processes writing to one file

I am not very knowledgeable about how this would work: since they would have different stream objects, is there any guarantee that a process appends to the end of the file if another process has written to it in the meantime?

**Comment by blattms** [comment]
> >    ZOLTAN logs to std::cout

> That is a bit weird, but can be worked around: remember the rdbuf of cout (putting some ostringstream's rdbuf there instead) before calling Zoltan, then reset it after Zoltan returns.

Oh that sounds really hacky. I just found out that there is non-verbose mode (I thought this was already activated, but it seems like 3 lines down the code I revert the setting). I guess we can live with fatal error in std::cout, right?

**Comment by atgeirr** [comment]
> we can live with fatal error in std::cout

I guess we can. Other than that, changing the rdbuf is not really hacky I think, sometimes it is the only way to deal with annoying behaviour in libraries we can or will not change.

**Comment by blattms** [comment]
> >    multiple processes writing to one file

> I am not very knowledgeable about how this would work: since they would have different stream objects, is there any guarantee that a process appends to the end of the file if another process has written to it in the meantime?

I checked the output really gets messup due to the wells switching ouput. On my system all the output from process 1 comes before the one from process 0 in a run with 2 processes. And some messages are swallowed. I will need to come up with a proper fix using communication.

**Comment by blattms** [comment]
Once OPM/opm-core#1077, and #842 get merged I think this issue should be fixed.
