### ISSUE TITLE
flow-solvent problem

### ISSUE THREAD

**Issue by hnqing369** [OPM/opm-simulators#831]
Simulation using 'flow-solvent' stopped with an error message:
Program threw an exception: Input vector must have full size.

(The same error happened with 'flow', but was recently solve.)

**Comment by blattms** [comment]
Could indeed be similar to what was fixed with #825.

**Comment by totto82** [comment]
@blattms Thanks. 
The modifications were never applied to the solvent model. I can take a look.

**Comment by atgeirr** [comment]
Should be fixed now, closing the issue. @hnqing369 please reopen if problem has not been solved!
