### ISSUE TITLE
Segfault in two-phase fluid-in-place calculation

### ISSUE THREAD

**Issue by ANerd** [OPM/opm-simulators#877]
When running two-phase oil-water case, I get a segfault [here](https://github.com/OPM/opm-simulators/blob/b2a64c2ddd59a002b698ad153305af12f7981f52/opm/autodiff/BlackoilModelBase_impl.hpp#L2419).

I don't know how it's supposed to work, but I guess something like [this](https://github.com/OPM/opm-simulators/blob/b2a64c2ddd59a002b698ad153305af12f7981f52/opm/autodiff/BlackoilModelBase_impl.hpp#L2391) is required.

**Comment by atgeirr** [comment]
This issue is important enough that we should not release without having fixed it.
