### ISSUE TITLE
symbol lookup error: flow_legacy

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#910]
I am receiving a symbol lookup error when trying to run a forward simulation on the Norne model or SPE1CASE1 with `flow_legacy`:
```
flow_legacy: symbol lookup error: flow_legacy: undefined symbol: _ZN3ERT11smspec_nodeC1ERKSsPKii 
```
Has someone experienced this or am I missing something? Please find my build logs here:  https://gist.github.com/anonymous/449cf1cbd7f7b880764afaf604f59aea

Thanks,
Rohith

**Comment by akva2** [comment]
On 11. nov. 2016 15:23, nairr wrote:
>
> I am receiving a symbol lookup error when trying to run a forward 
> simulation on the Norne model or SPE1CASE1 with flow_legacy: 
> flow_legacy: symbol lookup error: flow_legacy: undefined symbol: 
> _ZN3ERT11smspec_nodeC1ERKSsPKii . Has someone experienced this or am I 
> missing something? Please find my build logs here: 
> https://gist.github.com/anonymous/449cf1cbd7f7b880764afaf604f59aea
>

what binary are you running? if you are running the installed binary, in 
some random prefix you have to fiddle with LD_LIBRARY_PATH for those 
shared libraries, or it WILL pick those in the system libraries. which i 
suspect is what happening - you link to the build library, but on 
runtime it uses an older version.

arnem

**Comment by jokva** [comment]
smspec_node there looks to come from ert. Did you compile it with C++ enabled and a recent revision?

**Comment by akva2** [comment]
he gave the entire build log so you can confirm that yourself ;) everything built fine, it's runtime that breaks.

**Comment by jokva** [comment]
Right, gists don't play too nicely here and I didn't notice it reading the email.  My bad.

**Comment by joakim-hove** [comment]
But I thought RPATH should handle this - lest everything is installed?

**Comment by nairr** [comment]
my LD_LIBRARY_PATH was indeed set to an older build. It works now! Thanks
