### ISSUE TITLE
Is it intended that writeTimeStep passes zero size arrays to the output writer?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#928]
I am just debugging my modified parallel output for Norne and found out that oil/gas/fluid in place arrays have zero size when writing substeps. Is it intented to pass zero size arrays to the ouput writer?

**Comment by joakim-hove** [comment]
No - that is  bug, and will blow up. Should have exactly `nactive` elements, where `nactive` corresponds to the *total* number of active cells in the model.

**Comment by blattms** [comment]
I guess I have to do some digging then. The weired things that this happens only sometimes.

**Comment by andlaus** [comment]
this should have been fixed.
