### ISSUE TITLE
More than one .DEBUG files are created when run flow_mpi in parallel.

### ISSUE THREAD

**Issue by GitPaean** [OPM/opm-simulators#930]
With two mpi processes, two files `.NORNE_ATW2013.1.DEBUG  .NORNE_ATW2013.DEBUG` are created. The first one looks empty.  I am wondering if it is desired or some adjustment needs to be done there.

**Comment by GitPaean** [comment]
Answer given. It is a nice design. Closing the issue.

**Comment by blattms** [comment]
????
Are you saying that the .NORNE_ATW2013.1.DEBUG is still there after the successful run?

**Comment by GitPaean** [comment]
Nope. It was a crashed running. I have been using this feature for parallel debugging now, great feature.

**Comment by blattms** [comment]
Great that it is useful.
