### ISSUE TITLE
Weired issues when changin linear_solver_maxiter (adaptive timestepping).

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#955]
I have seen quite unexpected behaviour in the adaptive time stepping before (when I tried potentially better parallelization that made the time stepping break down). As it came to my attention that flow_ebos uses a different default for the maximum number of linear iterations I could not help experimenting a bit with it.

Norne
--------
Using flow_ebos with `linear_solver_maxiter` equal to either 75 or 150 the number of linear and nonlinear iterations, linearization, and the total runtime stays the same.

Using `flow_legacy` with `linear_solver_maxiter` equal to 150 the adaptive time stepping breaks down at step 150. This is totally unexpected! Any ideas?

Model 2
----------
For `flow_legacy` the the two runs are very similar

max | Time | Linearizations | Nonlin steps | lin steps |
------|--------|-------------------|------------------|------------|
150  | 8611 |              2332 |             1936 |   54204  |
  75  | 8866 |              2332 |             1936 |   54204  |

For `flow_ebos` the performance drops drastically if we allow less  linear steps

max | Time | Linearizations | Nonlin steps | lin steps |
------|--------|-------------------|------------------|------------|
150 | 5371| 2068 | 1724 | 46382 |
75   | 7254|2637 | 2085 | 51501|

I assume the nonlinear steps are not counted here if the nonlinear solver does not converge. Thus the number of linearizations is actually the total number of nonlinear steps including non-convergent runs. It seems like for the flow_ebos the quality of the linear solver is of much more importance. What makes me wonder is that the behavior differs for different models.

**Comment by alfbr** [comment]
The main difference in terms of linear solver is that the ebos based one preconditions the system with only cells (not wells). I assume this has more of an impact on model 2 since some of the wells there are longer and connect larger parts of the system.

**Comment by blattms** [comment]
I am closing this and in part apologize for any inconvenience.

I realized that for flow_legacy I used a version before the default maximum number of steps was changed. That explains the why there is no change in the number of linear iterations for Model 2 above ( as nothing changed in max_iter despite what the first column says).

I was also unable to reproduce the non-convergence behavior.
