### ISSUE TITLE
Only interleaved solvers approach seems to be available for flow_ebos

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#961]
I was trying to find out how to switch the solver approach for flow_ebos (default seems to be interleaved). Somehow I failed to see how one can switch to the CPR preconditioner or anything else.

**Comment by dr-robertk** [comment]
The created system matrix contains 3x3 blocks. CPR is only implemented for 1x1 blocks, i.e. scalars.
This is work yo do but was not considered urgent yet since Interleaved was the default option anyway.

**Comment by blattms** [comment]
One could and probably should setup the Matrix in the dune-istl way directly as a Dense 2x2 Matrix of BCRS-Matrices. left uppermost block would be the scalar pressure-pressure coupling. Thus one would get rid off the additional setup time.

Not sure wether ewoms allows such flexibility, though.

**Comment by dr-robertk** [comment]
Definitively a good idea. I would wait a bit until the issues with flow_ebos and MPI are resolved.

**Comment by andlaus** [comment]
> Not sure wether ewoms allows such flexibility, though.

Out of the box, I can state with confidence that it doesn't. It is not very complicated, though: as far as I can see, only the Linearizer class needs to be specialized. (i.e., the linearizeElement_() method must be adapted; it needs to make some black-oil specific assumptions and also some assumptions on the layout of the target matrix.)

**Comment by andlaus** [comment]
this issue still applies and it is still relevant as far as I can see.

**Comment by blattms** [comment]
Closing as resolved by refactoring
