### ISSUE TITLE
flow_ebos dosn't output EGRID and INIT

### ISSUE THREAD

**Issue by totto82** [OPM/opm-simulators#976]
With current updated master flow_ebos doesn't output EGRID and INIT files anymore. Is this only my problem?

**Comment by totto82** [comment]
I found 
#warning TODO
#if 0
                eclipse_writer_->writeInitial(geoprops_->simProps(grid),
                                              geoprops_->nonCartesianConnections());
#endif
in FlowMainEbos.hpp. 

@andlaus. I really need this to be fixed asap! It is not possible to compare results without results to compare.

**Comment by andlaus** [comment]
proper PR is in the making: essentially remove the `#if 0` and the `#warning`. I somehow forgot to revert this for f7910af7d70a69f0d381fa542d223bb2595c48e6.

**Comment by totto82** [comment]
Thanks.
