### ISSUE TITLE
Why do we check convergence in nonlinear solver like this?

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#983]
In [`Model::nonlinearIteration`](/OPM/opm-simulators/blob/67374531e3650a60ee9d84c415aace92a9f6387c/opm/autodiff/BlackoilModelBase_impl.hpp#L238-L324)` we proceed as follows:

1. Assemble jacobian system
2. Compute and check convergence: `report.converged = getConvergence()`
3. If not converged and iteration <= minIter, then solve jacobian and add the update.
4. Do not recompute convergence.

This method is called in a do-while loop until either the maximum iterations are reached or `report.convergence` is true and we have made minIter steps.

Shouldn't we recompute the convergence in Step 4? It seems like we are neglecting the last update as the convergence compute is always the one before the last update.

**Comment by andlaus** [comment]
> Shouldn't we recompute the convergence in Step 4? It seems like we are neglecting the last update as the convergence compute is always the one before the last update.

to calculate the convergence of the non-linear solver, the residual for the current solution is required. since computing that is elaborate (in fact, it often takes more time than the linear solve), this is delayed by one iteration where it can be "recycled" for the linear solver if necessary.

**Comment by totto82** [comment]
> If not converged and iteration <= minIter, then solve jacobian and add the update.

It is actually  iteration < minIter. And since the iteration counter is increased just before the check. It will never reassemble for the default case (i.e. miniter = 1).

**Comment by blattms** [comment]
Thanks
