### ISSUE TITLE
BlackoilModelEbos::convergenceReduction wrong in parallel.

### ISSUE THREAD

**Issue by blattms** [OPM/opm-simulators#986]
I think I have commented on this method before during some PR on the frankenstein branch. Either my memory looks like swiss cheese or this comment was overlooked.

Anyway the summations do not account for overlap/ghost cells which need to be switched of. Therefore I assume that all the sums are wrong for CpGrid as some values will be added twice.

Was there a special reason not to refactor (rip of the Eigen stuff) from BlackoilModelBase::convergenceReduction?

**Comment by andlaus** [comment]
thanks for bringing this up again. it is known that `flow_ebos` does not work in parallel yet, probably there are also plenty of other issues left. I'll have a look soon.

> Was there a special reason not to refactor (rip of the Eigen stuff) from BlackoilModelBase::convergenceReduction?

IIRC there was no "deep" reason, I just wanted to avoid to modify working code if possible. (and also I was not aware that this should/could be changed.)

**Comment by andlaus** [comment]
did #1111 fix that?

**Comment by blattms** [comment]
I cannot tell as there are still serious problems with SPE1 after the
first substep. Not sure how this is caused but weiredly the linear
solvers seem to converge as good in parallel as in a sequential run
only the nonlinear solver does not converge as it should.

**Comment by atgeirr** [comment]
> I cannot tell as there are still serious problems with SPE1 after the
> first substep. Not sure how this is caused but weiredly the linear
> solvers seem to converge as good in parallel as in a sequential run
> only the nonlinear solver does not converge as it should.

That does sound weird...! Could there be something wrong with the update step?

**Comment by blattms** [comment]
Fixed with the merge of #1139
